package-lock.json, packages/components/package.json, packages/components/src/Card/Card.css, packages/components/src/Card/colors.css
- 
- 
- 
- 
- Pushed CSS vars for Card up to root for better IE11 compatibility.
- 
---
=> Move card vars to root

packages/components/src/FormField/FormField.css, packages/components/src/FormField/FormField.css.d.ts, packages/components/src/FormField/FormField.tsx, packages/components/src/Select/Select.tsx, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
- Updated select to use form field
- Add icon on form field
- 
- 
- 
- 
- 
- 
---
=> Update select component to use form field

packages/components/src/FormField/FormField.tsx, packages/components/src/InputNumber/InputNumber.mdx, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputNumber/InputNumber.tsx, packages/components/src/InputNumber/index.ts
- Make form field return a number if type is number
- Make value return as number instead of string
- Input number component
- 
- 
- 
- 
- 
---
=> Create input number

packages/components/package-lock.json, packages/components/package.json, packages/components/packages/components/__mocks__/uuid.ts, packages/components/rollup.config.js, packages/components/src/FormField/FormField.test.tsx, packages/components/src/FormField/FormField.tsx, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputText/InputText.test.tsx, packages/components/src/InputTime/InputTime.mdx, packages/components/src/InputTime/InputTime.test.tsx, packages/components/src/InputTime/InputTime.tsx, packages/components/src/InputTime/InputTimeProps.tsx, packages/components/src/InputTime/InputTimeSafari.tsx, packages/components/src/InputTime/civilTimeConversions.tsx, packages/components/src/InputTime/time-input-polyfill.d.ts, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
- 
- 
- 
- 
- `InputTime` now works in Safari.
- 
---
=> Time for iBrowse

packages/components/src/FormField/FormField.css, packages/components/src/FormField/FormField.css.d.ts, packages/components/src/FormField/FormField.test.tsx, packages/components/src/FormField/FormField.tsx, packages/components/src/InputNumber/InputNumber.mdx, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputNumber/InputNumber.tsx, packages/components/src/InputText/InputText.tsx
- Reorder up form field component
- Adds in `onValidate` callbac for form field
- Adds in built-in validation for input number
- Built in validation for number min/max
- 
- 
- 
- 
- 
---
=> Give me a minimum amount of your maximum number

.vscode/settings.json, packages/components/package-lock.json, packages/components/package.json, packages/components/rollup.config.js
- 
- 
- 
- 
- Fixed an issue with the input time polyfill broke the latest release.
- 
---
=> Poly fix the polyfill

packages/components/src/Tabs/Tabs.css, packages/components/src/Tabs/Tabs.css.d.ts, packages/components/src/Tabs/Tabs.mdx, packages/components/src/Tabs/Tabs.tsx, packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
- Make tabs overflow like it should... but only if it should
- 
- 
- 
- 
- 
- 
---
=> Tabs overflowing with style

README.md
- Adds instructions on how to use plop.
- 
- 
- 
- 
- 
---
=> Add plop to readme

README.md, docs/proposals/InputDate.md
- 
- Update Readme to include repo structure.
- Add `InputDate` proposal.
- 
- 
- 
- 
---
=> Input proposal as well as Readme updates.

.github/pull_request_template.md, .github/semantic.yml
- Add `semantic-pull-requests` to enforce PR Titles in preparation for automatic version generation which would unlock continuous & automatic releases.
- 
- 
- 
- 
- 
---
=> build(base): Configure `semantic-pull-requests`.

packages/components/src/InputValidation/InputValidation.mdx
- 
- Improves the input validation example error message to be more friendly and less forceful, just like Jeff. 
- 
- 
- 
- 
---
=> docs: improve input validation example error message

.eslintrc.js, packages/eslint-config/.eslintrc.js
- 
- Pushed `jest/recommended` up so it is now provided by the base eslint config.
- Cleaned up the settings now that `"plugin:import/typescript"` is around.
- 
- 
- 
- 
---
=> chore: Promote a few eslint plugins.

.eslintrc.js, packages/eslint-config/.eslintrc.js, packages/eslint-config/README.md, packages/eslint-config/package-lock.json, packages/eslint-config/package.json
- 
- 
- 
- 
- Include eslint jest plugin properly
- 
---
=> fix: Properly include ESLint Jest plugin.

.eslintrc.js, packages/eslint-config/.eslintrc.js
- Enable `@typescript-eslint/no-non-null-assertion`
- Adjust rules around walking up directories pending further discussion on how to do this more broadly.
- 
- 
- 
- 
---
=> chore: Shared eslint improvements

doczrc.js, packages/components/src/Markdown/Markdown.test.tsx, packages/components/src/Markdown/Markdown.tsx, packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap, packages/components/src/Page/Page.css, packages/components/src/Page/Page.css.d.ts, packages/components/src/Page/Page.mdx, packages/components/src/Page/Page.test.tsx, packages/components/src/Page/Page.tsx, packages/components/src/Page/index.ts
- Updated markdown to support basic usage
- Created a page component that would extend to have more than a heading and intro
- 
- 
- 
- 
- 
---
=> feat: Create base page component

packages/components/README.md
- 
- Updated components package readme.
- 
- 
- 
- 
---
=> chore: update components package readme

packages/components/src/Banner/Banner.mdx, packages/components/src/Button/Button.mdx, packages/components/src/Card/Card.mdx, packages/components/src/Content/Content.mdx, packages/components/src/DescriptionList/DescriptionList.mdx, packages/components/src/Emphasis/Emphasis.mdx, packages/components/src/FeatureSwitch/FeatureSwitch.mdx, packages/components/src/FormField/FormField.mdx, packages/components/src/FormatTime/FormatTime.mdx, packages/components/src/Heading/Heading.mdx, packages/components/src/Icon/Icon.mdx, packages/components/src/InlineLabel/InlineLabel.mdx, packages/components/src/InputNumber/InputNumber.mdx, packages/components/src/InputText/InputText.mdx, packages/components/src/InputTime/InputTime.mdx, packages/components/src/InputValidation/InputValidation.mdx, packages/components/src/Markdown/Markdown.mdx, packages/components/src/Menu/Menu.mdx, packages/components/src/Modal/Modal.mdx, packages/components/src/Page/Page.mdx, packages/components/src/Select/Select.mdx, packages/components/src/Switch/Switch.mdx, packages/components/src/Table/Table.mdx, packages/components/src/Tabs/Tabs.mdx, packages/components/src/Text/Text.mdx, packages/components/src/Tooltip/Tooltip.mdx, packages/components/src/Typography/Typography.mdx, plop/templates/component/{{name}}.mdx
- Add import instructions to generator.
- Add import instructions to existing components.
- Unify component readme structure.
- 
- 
- 
- 
---
=> docs(components): Unify component Readme Structure

packages/components/src/Switch/Switch.mdx
- 
Changed variable names to be more intuitive 
- 
- 
- 
- 
---
=> docs: variable names for the switch component

packages/components/src/Button/Button.tsx
- 
- 
- 
- Remove some code that isn't being used, this didn't get caught by eslint but is known https://github.com/typescript-eslint/typescript-eslint/issues/1062
- 
- 
---
=> fix(components): clean up the button campground

packages/components/src/List/ListItem.css
- 
- 
- 
- 
- Icon styling can be overwritten and then doesn't look right, so add in addition styling to prevent that.
- 
---
=> fix(components): add styling to prevent overwriting

packages/components/src/FeatureSwitch/FeatureSwitch.mdx
- 
- 
- 
- 
The import should be for `FeatureSwitch`
- 
---
=> docs: Update import for feature switch

packages/components/package-lock.json, packages/components/src/Checkbox/Checkbox.css, packages/components/src/Checkbox/Checkbox.css.d.ts, packages/components/src/Checkbox/Checkbox.mdx, packages/components/src/Checkbox/Checkbox.test.tsx, packages/components/src/Checkbox/Checkbox.tsx, packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/components/src/Checkbox/index.ts
- Add a checkbox component
- 
- 
- 
- 
- 
---
=> feat(components): ☑️Create a checkbox

lerna.json, package.json
As a first step towards automating our Atlantis releases this moves us to generating release versions based on the PRs that have been merged since the last release.
- Now uses [Conventional Commits](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-commits) to auto calculate versions when creating releases. This is a first step to allow us to do auto deploying of Atlantis.
- 
- 
- 
- 
- 
- Run `npm run release-the-kraken`
- Note the prompt confirming you wish to make a release contains a generated version.
- Select `no` you do not wish to create a release as we're just checking that the version is generated here.
Notes for when we want to move publishing to CI.
- `https://github.com/lerna/lerna/issues/2022`
- …
=> feat(base): Move to  Conventional Commits for versioning.

.github/pull_request_template.md
It wasn't always clear why things were being done.
- Add `Motivations` section to PR Template.
- 
- 
- 
- 
- 
---
=> docs: add motivation section to PR Template

.vscode/settings.json, packages/components/src/FormField/FormField.tsx, packages/components/src/InputPassword/InputPassword.mdx, packages/components/src/InputPassword/InputPassword.test.tsx, packages/components/src/InputPassword/InputPassword.tsx, packages/components/src/InputPassword/index.ts
- InputPassword
- 
- 
- 
- 
- 
---
=> feat(components): Add InputPassword Component

packages/components/src/InputPassword/InputPassword.tsx
- 
- 
- 
- 
- Fix typing issue on InputPassword
- 
---
=> fix(components): Fix typing issue on InputPassword

.vscode/settings.json
- 
- 
- 
- 
- Peacock was getting a bit aggressive. This calms it down a bit. Still would be nice to have a cleaner override mechanism.
- 
---
=> chore: Calm down peacock. 🦚

packages/components/src/Button/Button.css, packages/components/src/Button/Button.tsx
- 
- 
- 
- 
- Fix height issue on multiline buttons.
- 
---
=> fix: Properly handle multiline buttons.

packages/components/src/Checkbox/Checkbox.tsx
- 
- 
- 
- 
Added disabled to the input for the checkbox component
- 
---
=> fix: disabled on checkbox component

.circleci/config.yml
- 
- 
- 
- 
- SSH keys are required for auto deploy
- 
---
=> fix: Add ssh keys

.circleci/config.yml, lerna.json
- 
- 
- 
- 
- Temporary fix for lerna's release loop.
- 
---
=> fix: Require approval before release

packages/components/src/Modal/Modal.tsx
https://getjobber.slack.com/archives/CHV3VNPDE/p1582664055005600
- 
- updated open and close animations of Modal to match sg-1
```
duration: 200ms
scale: 0.9 to/from 1
opacity: 0 to/from 1
easing: easeInOut
```
https://github.com/GetJobber/Jobber/blob/2ed8de7e2d2611cbc8adc419fdaf3a6cc26711a9/vendor/assets/sg-1/components-web-app.scss#L725-L773
- 
- 
- 
- 
- vid: https://slack-files.com/T02G3P55F-FUK9CSAPQ-e121280780
- live preview: https://deploy-preview-203--jobber-atlantis.netlify.com/components/modal
---
=> fix(components): replace spring animation in Modal

docs/proposals/Drawer/README.md
I wanted to propose a new Drawer component.
I added a proposal for the component.
=> docs(components): Drawer Component Proposal

doczrc.js, package-lock.json, package.json, src/gatsby-theme-docz/components/MainContainer/styles.js, src/gatsby-theme-docz/components/Playground/styles.js, src/gatsby-theme-docz/components/Props/styles.js
- 
- Nicer styling for the `Playground` component.
Before:
After:
- 
- 
- 
- 
---
=> chore: style the `Playground` component

doczrc.js
- 
- 
- 
- 
- Private components are once again hidden away safely.
- 
---
=> chore: Keep our privates private once again.

packages/components/src/Heading/Heading.mdx, packages/components/src/List/List.mdx
Fix typo
- 
- 
- 
- 
- 
- 
---
=> fix(components): fix typo in Heading documentation

packages/components/src/Icon/Icon.mdx
Every time someone creates a new icon, there's a question of "what are the guidelines to follow?"
Adding guidelines
Guidelines for icon structure
---
=> docs(design): include design guidelines for new icon creation

.github/semantic.yml, README.md, docs/proposals/Drawer/README.md
- Add `deps` scope to allowed semantic scopes.
- Few little organizational changes to the readme to better expose the table of contents.
- 
- 
- Applied `lint:fix` to markdown files.
- `npm run plop` was renamed to `npm run generate` the readme now reflects this. 
- 
---
=> chore: Cleanup Readme, Lint, add `deps` scope

packages/eslint-config/README.md
- `.eslintrc.js` starting snippet to readme.
- 
- 
- 
- 
- 
---
=> chore: Add `.eslintrc.js` snippet to readme.

docs/proposals/Avatar/README.md
We are going to need an Avatar component soon. This is a proposal on how to best create one.
---
=> docs(components): Avatar component proposal

docs/proposals/OptionList/README.md
=> chore: proposal v1

packages/components/src/Checkbox/Checkbox.mdx
Doing some disambiguation work on Switch, also in anticipation of RadioButton, cleaning up checkbox docs
Grammar
=> docs(components): grammar fixup on checkbox

packages/components/src/Avatar/Avatar.mdx
Noticed a typo while going through docs
fixed a typo
=> docs(components): Avatar typo fix on "calendar"

packages/components/src/Content/Content.mdx
I've found Content to be a confusing component, as it's an invisible component that "auto-magically" changes the appearance of any children - trying to update the docs to better explain what it is and when to use it.
Changed top description, added design guidelines
=> docs(components): update definition/add guidelines to content

packages/components/src/Card/Card.mdx
Want to make the "why" behind a card more apparent
Based on Jobber design team feedback, expanded upon card guidelines in foundational design terms.
=> docs(components): Update card docs with design usage guidelines

packages/components/src/ProgressBar/ProgressBar.mdx
WWR is using the progress bar, which made me think about progress bars
updated intro and added design & usage guidelines
=> docs(components): update docs for progress bar

packages/components/src/Content/Content.mdx
You should only have one h1 per page
- Bump Usage down to h2, and its children down to h3
=> docs(components): update content page hierarchy

packages/components/src/FeatureSwitch/FeatureSwitch.mdx
The docs on Feature Switch are okay, but should have more clarity around when and how to use it.
- Design & Usage Guidelines
- More detail in description
=> docs(components): Update docs for Feature Switch

packages/components/src/Page/Page.mdx
Page has been made more robust with Actions, and the docs should get some love too!
- Design & Usage guidelines
- Description of the Pattern
=> docs(components): Update Page docs

packages/components/src/DescriptionList/DescriptionList.mdx
Make it easier for designers to identify the right situation(s) to use DescriptionList relative to other collections of data.
- Design & Usage guidelines
=> docs(components): Update DescriptionList docs

packages/components/src/Emphasis/Emphasis.mdx
Add meaning to when to use Bold and Italic based on MDN semantic HTML docs.
- Usage notes for Bold, Italic and Highlight
=> docs(components): Better usage guidelines for Emphasis

packages/components/src/InlineLabel/InlineLabel.mdx
We have many available colours, knowing when to use them is important
- colour usage guidelines
=> docs(components): add guidelines to inlineLabel colour usage

packages/components/src/Table/Table.mdx
Flesh out the Table docs as we continue to work on the component.
- Design & Usage guidelines, disambiguation for other data collection types
=> docs(components): Update Table

packages/components/src/InputNumber/InputNumber.mdx
Better outline the use cases for number inputs.
- design & usage guidelines
=> docs(components): add usage notes to number input

packages/components/src/Icon/Icon.tsx, packages/components/src/Icon/index.ts
When the Icons were moved from components to design, they took some types with them. This PR brings back those types and re-exports them from components
Export `IconColorNames` and `IconNames` from `Icon`
- Export `IconColorNames` and `IconNames` from `Icon`
- 
- 
- 
- 
- 
---
=> fix(components): Icon export everything

packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/components/src/FormField/FormField.test.tsx, packages/components/src/FormField/FormField.tsx, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputPassword/InputPassword.test.tsx, packages/components/src/InputText/InputText.test.tsx, packages/components/src/InputTime/InputTime.test.tsx
We need to be able to call a function when we hit the enter key on Input Fields.
Adds an `onEnter` prop to FormFields that will all a call back for when the `Enter` key is hit.
- `onEnter` callback to FormFields
- 
- 
- 
- 
- 
---
=> feat(components): Adds an onEnter handler for Form Fields

packages/components/src/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap, packages/components/src/Button/Button.tsx, packages/components/src/Button/__snapshots__/Button.test.tsx.snap, packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/components/src/Icon/Icon.tsx, packages/components/src/Icon/__snapshots__/Icon.test.tsx.snap, packages/components/src/List/__snapshots__/List.test.tsx.snap, packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap, packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap, packages/components/src/Page/__snapshots__/Page.test.tsx.snap, packages/components/src/Select/__snapshots__/Select.test.tsx.snap, packages/components/src/Toast/Toast.css, packages/components/src/Toast/Toast.css.d.ts, packages/components/src/Toast/Toast.mdx, packages/components/src/Toast/Toast.test.tsx, packages/components/src/Toast/Toast.tsx, packages/components/src/Toast/__snapshots__/Toast.test.tsx.snap, packages/components/src/Toast/index.ts, packages/components/src/Toast/showToast.tsx, packages/design/src/elevations.css, tsconfig.base.json
We are moving towards a better way to display messages to the user. Toasts are the way of the future.
- Toast Component
- 
- 
- 
- 
- 
---
=> feat(components): Toast Component

packages/components/src/Button/Button.css.d.ts
- 
- 
- 
- 
- Adds in missing button type.
- 
---
=> fix(components): missing button css type

packages/components/src/Toast/Toast.css, packages/components/src/Toast/Toast.css.d.ts, packages/components/src/Toast/showToast.tsx
The `Toast` component needed some styling adjustments. 
Some css styling on the `Toast`
- 
- 
- 
- 
- Padding, Color, Z-index of the Toast
- 
---
=> fix(components): Style fixes for Toast

packages/components/src/InputFile/InputFile.mdx
- 
- `InputFile` now uses `FormatFile` in its docs example.
- 
- 
- 
- 
---
=> docs(components): Use FormatFile in the InputFile Docs.

packages/components/src/Divider/Divider.css, packages/components/src/Divider/Divider.css.d.ts, packages/components/src/Divider/Divider.mdx, packages/components/src/Divider/Divider.test.tsx, packages/components/src/Divider/Divider.tsx, packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap, packages/components/src/Divider/index.ts
We need a way to visually divide sections of content.
Adds a Divider component.
- Divider component
- 
- 
- 
- 
- 
---
=> feat(components): Divider component

docs/proposals/Text/Text_Mods.md
We need to make some modifications to the `Text` component. This is a proposal for how to most effectively make those changes.
- 
- 
- 
- 
- 
- 
---
=> docs(components): Update Text Proposal

packages/components/src/Banner/Banner.mdx
- Updated description of Banner component to differentiate from Toast
- Related components section to bottom of page
- 
- 
- 
- 
- 
---
=> docs(components): Update Banner.mdx

packages/components/src/Autocomplete/Autocomplete.mdx
-  Related components section to bottom of page
- 
- 
- 
- 
- 
---
=> docs(components): Update Autocomplete.mdx

packages/design/src/animation.mdx
- Docs for animation
- 
- 
- 
- 
- 
---
=> docs(components): Add animation page to docs

packages/components/src/Checkbox/Checkbox.css
Changed the color of checkbox border color to match new design changes
Changed color of checkbox border color to green
Look at the new checkbox, make sure the border is green for enabled but still grey when it is disabled
---
=> fix(components): Change Color of Checkbox Border to Green

packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/components/src/Form/Form.mdx, packages/components/src/FormField/FormField.test.tsx, packages/components/src/FormField/FormField.tsx, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputPassword/InputPassword.test.tsx, packages/components/src/InputText/InputText.test.tsx, packages/components/src/InputTime/InputTime.test.tsx, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Inline `FormFeild` ended up wrapped in a `div` which made it line break. This will wrap it in a span instead.
- 
- 
- 
- 
- `FormField` inline will no be inline.
- 
---
=> fix(components): Fixes the inline input

packages/components/src/FormatFile/FormatFile.css, packages/components/src/InputAvatar/InputAvatar.css, packages/components/src/InputAvatar/InputAvatar.css.d.ts, packages/components/src/InputAvatar/InputAvatar.mdx, packages/components/src/InputAvatar/InputAvatar.test.tsx, packages/components/src/InputAvatar/InputAvatar.tsx, packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap, packages/components/src/InputAvatar/index.ts, packages/components/src/InputFile/InputFile.css, packages/components/src/InputFile/InputFile.css.d.ts, packages/components/src/InputFile/InputFile.mdx, packages/components/src/InputFile/InputFile.test.tsx, packages/components/src/InputFile/InputFile.tsx, packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap, packages/components/src/InputFile/index.ts, packages/design/src/radii.css
- Adds InputAvatar Component
- Adds Button only mode for InputFile
- Adds Size and Variation options to InputFile
- 
- 
- 
- 
- 
---
=> feat(components): InputAvatar & Expand variation options for InputFile

packages/components/src/Heading/Heading.mdx
- addd related components section to header page
- 
- 
- 
- 
- 
---
=> docs(components): add related components section to header doc

packages/components/src/Checkbox/Checkbox.mdx
related components section to checkbox docs
- 
- 
- 
- 
- 
---
=> docs(components): add related components section to checkbox docs

packages/components/src/Form/Form.mdx, packages/components/src/Form/Form.test.tsx, packages/components/src/Form/Form.tsx, packages/components/src/Form/index.ts
A `Form` will sometimes need to be validated from outside of the `Form` component. This PR exposes a `validate` function that can be used to validate the `Form` from anywhere.
Adds a `validate` method to the `Form` component
- Adds a `validate` method to the `Form` component
- 
- 
- 
- 
- 
---
=> feat(components): Add `validate` function to Form

packages/components/src/Button/Button.css
I contributed by searching for issues related to hacktoberfest, and I found this. This afternoon I started analyzing the code and seeing what was causing this issue as well as working out a solution. 
With this pull request, it will always be the right solution for `this` issue ( #384 ).
Delete Button padding property on `.hasIconAndLabel` class name selector so the padding property active is from size based selector.
**Thankyou**
=> fix(components): update button padding on has icon and label button

.circleci/config.yml
CircleCI was setting the node versions to `15`. This wasn't so good. This PR will force the node version to `10`
- 
- 
- 
- 
- 
- 
---
=> chore: Forces node version on circle

.circleci/config.yml, packages/components/src/DescriptionList/DescriptionList.tsx, packages/components/src/DescriptionList/__snapshots__/DescriptionList.test.tsx.snap
This PR address issue #380 
Color update as per issue description
- 
- 
- 
- 
- 
- 
Please observe the detail text and confirm if color matches `--color-greyBlue--dark`
`rgb(66, 78, 86)`
---
=> fix(components): Updating DescriptionList details text color

packages/components/src/FormatFile/FormatFile.mdx
Related components section to FormatFile doc
- 
- 
- 
- 
- 
---
=> docs(components): add related components section to FormatFile

packages/components/src/DataDump/DataDump.mdx, packages/components/src/DataDump/DataDump.test.tsx, packages/components/src/DataDump/DataDump.tsx, packages/components/src/DataDump/__snapshots__/DataDump.test.tsx.snap, packages/components/src/DataDump/index.ts
- Adds `DataDump` Component.
- 
- 
- 
- 
- 
---
=> feat(components): Add DataDump Component

packages/components/src/Menu/Menu.css, packages/components/src/Menu/Menu.css.d.ts, packages/components/src/Menu/Menu.tsx
- 
- 
- 
- 
- Menu now opens to the left if it is on the right side of the screen so it doesn't overflow the browser window.
- 
If you make the playground really narrow it should get narrow enough to get the Menu on the right half of the screen.
---
=> fix(components): Menu properly positions on right side of screen.

docs/proposals/Drawer/README.md
This PR updates the old drawer proposal.
- 
- 
- 
- 
- 
- 
---
=> docs(components): Update drawer proposal

packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/components/src/Checkbox/Checkbox.css, packages/components/src/Checkbox/Checkbox.tsx, packages/components/src/Page/Page.tsx, packages/components/src/Page/__snapshots__/Page.test.tsx.snap, packages/components/src/Text/Text.mdx, packages/components/src/Text/Text.test.tsx, packages/components/src/Text/Text.tsx
The `Text` component needed an improvement that allowed it to have size and variations. This PR will add the `size` prop.
Adds a `size` prop on `Text` component. 
- `size` prop to the `Text` component
- 
- 
- `intro` from `variations` of `Text`
- 
- 
---
=> feat(components): Add size prop to Text

packages/components/src/ConfirmationModal/ConfirmationModal.mdx, packages/components/src/ConfirmationModal/ConfirmationModal.tsx, packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap, packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Sometimes `ConfirmationModal` wants to display more then just a string of text as the `message`. This PR allows `ConfirmationModal` to accept `Markdown` as the `message`
Allows `ConfirmationModal` to accept `Markdown` as a `message`
- `ConfirmationModal` accepts `Markdown` as a `message`
- 
- 
- 
- 
- 
---
=> feat(components): Add markdown to ConfirmationModal

packages/components/src/Table/Table.css, packages/design/src/borders.css
The `Table` was using `box-shadow` as borders due to the fact that `<table>` can not have a `border-radius` applied to it. While this looks fine when a `Table` is by its self. It looks a little bonkers when paired with something like a `Card`.
Change the `Table` borders from `box-shadow` to a `pseudo` element.
- 
- Change the `Table` borders from `box-shadow` to a `pseudo` element.
- 
- 
- 
- 
---
=> fix(components): Change `Table` borders from box-shadow to pseudo element

package-lock.json, packages/hooks/package-lock.json, packages/hooks/package.json, packages/hooks/src/index.ts, packages/hooks/src/useOnKeyDown/index.ts, packages/hooks/src/useOnKeyDown/useOnKeyDown.mdx, packages/hooks/src/useOnKeyDown/useOnKeyDown.test.tsx, packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
This PR adds a onKeyDown event hook. This will allow us to implement some UX niceties, for example automatically setting focus to a button when a user completes some input action.
This PR is almost entirely the work of @0length. This feature was built as a Hacktoberfest project. I've simply cleaned up his code and cleaned up the usage examples. All credit goes to him. The original PR description was:
```
This is refer to https://github.com/GetJobber/atlantis/pull/394#discussion_r509685744
Create new hook called `useOnKeyDown` to create on keydown event listener handler by specific one or multiple key in the same function.
**Thanks**
```
- Generic onKeyDown hook.
- Ensure that the mdx file examples function as expected.
--- …
=> feat(hooks): Add useOnKeyDown hook

packages/components/src/Table/Table.css
A bug fix went out that made the `Table` borders better. However it introduced a positioning bug in `Table`
Adjust the positioning and `pointer-events` on `Table` border
- 
- 
- 
- 
- Positioning on `Table`
- 
In `Table.mdx`.
```
import { Menu } from "@jobber/components/Menu";
```
```
<Playground>
<Table>
<Header>
<Cell>Ship</Cell>
<Cell>Class</Cell>
<Cell align="right">Menu</Cell>
</Header>
<Row>
<Cell>Nostromo</Cell>
<Cell>Towing Vehicle</Cell>
<Cell align="right">
<Menu
items={[
{
actions: [
{
label: "Edit",
icon: "edit",
onClick: () => {
alert("✏️");
}
}
]
}
]}
/>
</Cell>
</Row>
<Row>
<Cell>Rodger Young</Cell>
<Cell>Corvette Transport</Cell>
<Cell align="right">
<Menu
items={[
{
actions: [
{
label: "Edit",
icon: "edit",
onClick: () => {
alert("✏️");
}
}
]
}
]}
/>
</Cell>
</Row> …
```
=> fix(components): Fix the positioning of the Table

packages/components/src/Typography/css/FontSizes.css
The readability of the large text is not great, so adjusting the line height will help.
CSS change on large font size `line-height` to large
- Change line-height from `-tightest` to `-large`
---
=> fix(components): change line-height on large font size

.eslintrc.js, packages/docz-tools/package-lock.json, packages/docz-tools/package.json
When the latest PR was merged in, it broke the linting on master. This PR will fix it.
- 
- 
- 
- 
- 
- 
---
=> build: fixes linting on master

packages/components/src/Form/Form.mdx, packages/components/src/InputNumber/InputNumber.mdx, packages/components/src/InputPassword/InputPassword.mdx, packages/components/src/InputText/InputText.mdx, packages/components/src/InputValidation/InputValidation.mdx
We do not currently have very good documentation about `validations`. This PR Adds some documentation about validations
- Documentation about validation
- 
- 
- 
- 
- 
- 
---
=> docs: Add some documentation about validations

.github/pull_request_template.md, docs/CONTRIBUTING.md, docs/guides/pull-request-title-generator.mdx, packages/docz-tools/index.js, packages/docz-tools/package.json, packages/docz-tools/src/gatsby-theme-docz/components/Navigation/index.tsx, packages/docz-tools/src/gatsby-theme-docz/components/PullRequestGenerator/PullRequestGenerator.tsx, packages/docz-tools/src/gatsby-theme-docz/components/PullRequestGenerator/index.ts
Rumors were that people were getting confused about making a pull request title. @chris-at-jobber came up with an idea to create a tool that assists with this.
- PR Name generator page
- 
- 
- 
- 
- 
---
=> docs: Pull request name generator

packages/components/src/FormField/FormField.css, packages/components/src/FormField/FormField.css.d.ts, packages/components/src/FormField/FormField.tsx, packages/components/src/Select/Select.mdx, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Makes descenders on letters like `p`, `y`, `g`, and `q` visible.
- 
- 
- 
- 
- Makes descenders on letters like `p`, `y`, `g`, and `q` visible.
- 
---
=> fix(components): fixes the descenders on Select

packages/components/src/FormField/FormField.css, packages/components/src/Select/Select.mdx
Fixes the css for Select with miniLabel
- 
- 
- 
- 
- Fixes the css for Select with miniLabel
- 
---
=> fix(components): Fix the css for Select with miniLabel

packages/components/src/Autocomplete/Autocomplete.test.tsx, packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
There is a test in the `Autocomplete` component that was causing issues in circle CI. This PR changes the test from using a snapshot test, to looking for the invalid class name in the `container`
> Snapshots should only be used when the output is highly predictable.
Moves the `Autocomplete` test from a snapshot to a querySelector test.
- 
- Moves the `Autocomplete` test from a snapshot to a querySelector test.
- 
- 
- 
- 
---
=> fix(components): updates the flakey Autocomplete test to not use snapshot

packages/docz-tools/package-lock.json, packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.tsx
When we updated the theme, we broke the search functionality.
Moves the navigation items into their own component so that the number of hooks called is not changing all the time.
- 
- 
- 
- 
- Broken search functionality
- 
---
=> fix(docz-tools): Fixes the broken search

packages/components/rollup.config.js
In a former PR we moved the responsive breakpoints to the `@jobber/design` package. Turns out this broke everything. This PR brings it back.
Brings `responsiveBreakpoints` back to rollup config.
- Brings `responsiveBreakpoints` back to rollup config.
- 
- 
- 
- 
- 
---
=> feat(components): Include responsive breakpoints in Rollup

docs/README.md
=> fix: Update NPM requirement

packages/components/src/Toast/Toast.mdx
=> docs: update toast related components

docs/README.md
- Add some notes explaining handling packages in the monorepo.
- Add notes talking about cross dependancies.
- 
- 
- 
- 
- 
---
=> docs: Outline some notes for working in a MonoRepo

docs/guides/frontent-style.mdx
=> docs: Initial Pass on frontend style

packages/components/src/Icon/Icon.mdx
Got questions about icons, and the answers now live here.
- notes on icon color, and additional spacing notes
---
=> docs(components): update icon docs

packages/design/src/colors.css
the colors are currently breaking when using `rgba` with a `var`. This PR will revert the `rgba` with a `var` colors for the time being, until a better fix is worked on.
- 
- 
- 
- 
- 
- 
---
=> fix(design): temp fix the colors until a good fix is available

docs/guides/frontent-style.mdx
We leave a lot of comments about XOR vs unions! Let's write it down for people in our style guide.
Update frontend style guide.
- Section on XOR vs unions
---
=> docs: add XOR note

.circleci/config.yml, package-lock.json, package.json, packages/components/package.json, scripts/preventManualRelease.js
In Atlantis 🔱, we want to ensure that there are never any direct version bumps to any of the @jobber packages. The reason being is that if a version is manually bumped, lerna will have a struggle to try and figure out what the next proper version to release is.
- a new script to check for manual releases
- 
- 
- 
- 
- 
---
=> build: Prevent manual releases

packages/components/package-lock.json
CI is currently breaking on linting. This will hopefully fix it 🤞
- 
- 
- 
- 
- 
- 
---
=> chore: sync up the package-lock

package-lock.json, package.json, packages/components/src/Banner/Banner.tsx, packages/components/src/Form/Form.tsx, packages/components/src/InputEmail/InputEmail.tsx, packages/components/src/Page/Page.tsx, packages/docz-tools/src/gatsby-theme-docz/components/Navigation/useJobberMenu.tsx, packages/eslint-config/package-lock.json, packages/eslint-config/package.json, packages/hooks/src/useCollectionQuery/useCollectionQuery.ts, packages/hooks/src/useOnKeyDown/useOnKeyDown.ts, packages/hooks/src/usePasswordStrength/usePasswordStrength.ts
CircleCI was having some issues with prettier and formatting code. We were also having some issues identifying the root cause of this. As a solution I have decided to just upgrade prettier to the latest version. 
This will also help in keeping one of our packages more up to date.
Updates prettier to the latest version
- 
- prettier versioning
- 
- 
- 
- 
---
=> feat(eslint): Update prettier to latest

docs/content/product-vocabulary.mdx, docs/guides/frontent-style.mdx, docs/proposals/InputEmail/InputEmail.md, package.json, packages/components/src/Button/Button.mdx, packages/components/src/Disclosure/Disclosure.mdx, packages/components/src/Spinner/Spinner.mdx, packages/hooks/src/useResizeObserver.mdx
The command `npm run lint:markdown` was not actually getting all the markdown files. Unsure when this started happening. 
This PR will update the command to find all of the `md` and `mdx` files and properly lint them
- 
- 
- 
- 
- `npm run lint:markdown` command
- 
---
=> build: Fixes the markdown linter

docs/content/product-vocabulary.mdx
Added new guideline within actions section of Product Vocabulary for 'refresh' / 'reload'
- 
- 
- 
- 
- 
- 
---
=> docs(design): Add 'refresh' to product vocabulary

packages/components/src/Content/Paddings.css.d.ts, packages/components/src/Select/Select.css.d.ts
PR #706 was merged with the old css files. This brings them back to the new one
- 
- 
- 
- 
- 
- 
---
=> fix: Rerender select and padding css.d.ts

packages/components/src/Banner/Banner.test.tsx, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Fixes #695
In participation in Hacktoberfest, I contributed to issue #695 
Banner Close button aria-label was changed from "Close" to "Close this notification"
- 
- 
- 
- 
- 
- 
---
=> fix(components): Add a more distinct aria-label to Banner

packages/components/src/Table/Body.tsx, packages/components/src/Table/Table.mdx, packages/components/src/Table/Table.test.tsx, packages/components/src/Table/__snapshots__/Table.test.tsx.snap, packages/components/src/Table/index.ts
The Table component doesn't have a Body part to act as a `tbody` tag. This can make accessibility to not work properly. 
The [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody) says: "The `<tbody>`element, along with its cousins `<thead>` and `<tfoot>`, provide useful semantic information that can be used when rendering for either screen or printer as well as for accessibility purposes."
- Body component for Table
- 
- 
- 
- 
- 
Table component only has one single snapshot test, so basically the snapshot was updated.
---
=> feat(components): add Body component to Table components

packages/components/src/DatePicker/DatePicker.test.tsx
We're overwriting and making use of classnames internal to ReactDatePicker, this ensures no surprises happens.
- Wrote a test to ensure the classnames from ReactDatePicker that we're ~ab~ using still exists.
- 
- 
- 
- 
- 
- 
---
=> chore(components): Add test for datepicker to make sure custom css doesnt fail

packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/components/src/FormField/FormField.css, packages/components/src/FormField/FormField.css.d.ts, packages/components/src/FormField/FormFieldDescription.tsx, packages/components/src/FormField/FormFieldWrapper.tsx, packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap, packages/components/src/InputGroup/InputGroup.css, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap, packages/components/src/InputText/InputText.test.tsx, packages/components/src/InputTime/InputTime.test.tsx, packages/components/src/InputValidation/InputValidation.css, packages/components/src/InputValidation/InputValidation.css.d.ts, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Reverts GetJobber/atlantis#762
Missed an issue with `maxLength` reducing the size. Since it's the holiday, it's much safer to revert than fix it.
=> fix(components): Revert fix form field inconsistent spacing when used under Form and InputGroup JOB-37646

packages/components/src/RecurringSelect/RecurringSelect.mdx
Docs for RecurringSelect didn't get a lot of love in the review process as we wanted to expedite landing the component in Atlantis. Here is some love:
- Related components section
- Design and usage guidelines
- more a11y details
- rename some sections
- adjust hierarchy
---
=> docs(components): flesh out RecurringSelect docs

packages/components/src/Icon/Icon.mdx
The `signature` Icon exists in Atlantis, but you wouldn't know it from our docs!
- example of `signature`
---
=> docs(components): add signature to Icon examples

packages/components/src/InputText/InputText.tsx
Remove linting errors related to Prefix and Suffix 
Picked prefix and suffix types 
=> fix: InputText pick prefix and suffix

packages/hooks/package-lock.json
running `npm ci` removes the extra bits. Just a lil sync up!
- 
- 
- 
- a dependency from package lock after an npm ci
- 
- 
---
=> chore(deps): sync package-lock

packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
- Added a new state to determine wether an enter press is allowed while debouncing
- 
- 
- 
- 
- 
---
=> fix(components): Disable enter press on chip menu debounce

package-lock.json, packages/components/package-lock.json, packages/components/package.json, packages/components/src/Markdown/Markdown.tsx, packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
- 
- Bumped react-markdown to v6 which removes the `trim` subdependency
- Bumping to latest version breaks jest because of some ESM issue
- 
- 
- Fixes #894
- 
---
=> fix(deps): update markdown to v6.0.3

docs/content/formatting.mdx
Documentation of formatting rules we follow but haven't...well documented anywhere.
- 
- 
- 
- 
- 
- 
---
=> docs(design): Formatting guidelines

packages/components/src/Chips/InternalChipDismissible/hooks/useInView.ts, packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts, packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx, packages/components/src/Chips/InternalChipDismissible/hooks/useScrollToActive.tsx, packages/components/src/Modal/useFocusTrap.ts, packages/components/src/Tooltip/useTooltipPositioning.ts
=> chore(eslint) Fix no-null errors

packages/components/src/MultiSelect/MultiSelect.css, packages/components/src/MultiSelect/MultiSelect.css.d.ts, packages/components/src/MultiSelect/MultiSelect.mdx, packages/components/src/MultiSelect/MultiSelect.tsx
The MultiSelect component height was not matching the InputText component
added size property with `small` and `large` possible values
- 
- 
- 
- 
- 
---
=> feat(component) add size property to MultiSelect component

packages/components/src/MultiSelect/MultiSelect.css
The `MultiSelect` component didn't have` box-sizing` set to `border-box` so it was causing problems to match the design with another component (`InputText` for example) when used in other apps.
It was not noticed in the Atlantis page because the `Playground` component has it set to make all children components to inherit it.
- `box-sizing` css property set to `border-box` for the `MultiSelect` component container and all it's children components
- 
- 
- 
- 
- 
---
=> fix(design) Add box-sizing css to MultiSelect component

.circleci/config.yml, .gitignore, package-lock.json, package.json, packages/components/package.json, packages/components/rollup.config.js, packages/components/tsconfig.ci.json, packages/design/package.json, packages/formatters/package.json, packages/hooks/package.json
Wanted to improve our CI by adding a Typescript compile step to verify that we don't introduce a change that adds typescript issues
- Added typescript compile step for CircleCI. 
- Limitations: Due to tanstack errors the compile step will not be able to catch errors in `Datatable` until we update the typescript version so we can remove it from `tsconfig.ci.json`
To test locally install CircleCi locally https://circleci.com/docs/local-cli/ 
Revert 1f95edd4922777b63ce2003673e701954f6581cd
Run `circleci local execute --job local_typescript`
If you run into a docker issue follow the steps found here: https://github.com/CircleCI-Public/circleci-cli/issues/672#issuecomment-1235768553
To test the new compile command from the root folder run
`npm run lerna:compile-typescript`
---
[In Atlantis we …
=> JOB-58374 build: Add compile to circle ci

package-lock.json, packages/components/src/DataTable/Body.tsx, packages/components/src/DataTable/DataTable.css, packages/components/src/DataTable/DataTable.css.d.ts, packages/components/src/DataTable/DataTable.mdx, packages/components/src/DataTable/DataTable.test.tsx, packages/components/src/DataTable/DataTable.tsx, packages/components/src/DataTable/Pagination.tsx
- To improve UX when viewing a data table with no content
- Conditional rendering of text per designs
- The `Body` component used by the `DataTable`
- Run the Atlantis web app locally and navigate to the [empty state example](http://localhost:3333/components/data-table/#table-empty-state), validate the experience on mobile and desktop views.
---
=> feat(components): Add empty state behavior to DataTable component in Atlantis [JOB-58935]

packages/components/src/DatePicker/DatePicker.css
Updates the font size for the days of the week in the date picker
Only changed the font size
---
=> refactor(components): Update datepicker days of week to use `small` fontSize

packages/components/src/FormField/FormField.css
Match new style for InputText component because the typography has been updated
- adjusted Typography size of minilabel and placeholder of InputText component
---
=> refactor(components): Update FormField component typography

packages/components/src/Banner/Banner.css, packages/components/src/Banner/Banner.css.d.ts, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- Changed banner alignment
---
=> refactor(components): Adjust banner alignment

packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap, packages/components/src/Button/Button.css, packages/components/src/Button/Button.mdx, packages/components/src/Button/Button.tsx, packages/components/src/Button/__snapshots__/Button.test.tsx.snap, packages/components/src/ButtonDismiss/__snapshots__/ButtonDismiss.test.tsx.snap, packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap, packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap, packages/components/src/InputAvatar/__snapshots__/InputAvatar.test.tsx.snap, packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap, packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap, packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap, packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Match new style for Button component because the typography has been updated
Before:
After:
- updated casing, spacing and font-family of typography within the button
- snapshot tests that use button have been updated
- check Button component locally and compare with Figma
- can check casing by updating playground
---
=> refactor(components): Update typography for Button

packages/components/src/FormatFile/InternalThumbnail.css
Use our new typography token in InternalThumbnail
- 
- 
- 
- 
- 
- 
---
=> refactor(components): Use typography tokens for InternalThumbnail [JOB-60820]

packages/components/src/StatusLabel/StatusLabel.css
Adjust visuals of components with the new typefaces
Before:
After:
- offset of status indicator from 2 to 1 px
- view locally or on build
---
=> refactor(components): Update statuslabel indicator offset 

packages/components/src/Typography/css/Emphasis.css
Highlight placement was off with the new typefaces, and was using a fairly ✨ magic ✨ number to be positioned.
- Position of brushstroke from a percentage to the `bottom` value
- Brushstroke does not overlap with the text it is highlighting
Paste this snippet into the playground for Emphasis
```
<Heading level={1}>
Get paid <Emphasis variation="highlight">faster</Emphasis>
</Heading>
<Heading level={2}>
Get paid <Emphasis variation="highlight">faster</Emphasis>
</Heading>
<Heading level={3}>
Get paid <Emphasis variation="highlight">faster</Emphasis>
</Heading>
<Heading level={4}>
Get paid <Emphasis variation="highlight">faster</Emphasis>
</Heading>
<Heading level={5}>
Get paid <Emphasis variation="highlight">faster</Emphasis>
</Heading>
<Heading level={6}>
Get paid <Emphasis …
```
=> fix(components): Adjust placement of emphasis highlight [JOB-41951]

packages/components/src/InlineLabel/InlineLabel.css, packages/components/src/InlineLabel/InlineLabel.mdx, packages/components/src/InlineLabel/InlineLabel.test.tsx, packages/components/src/InlineLabel/InlineLabel.tsx
InlineLabel component has to be updated to match new typography
- padding on all three label sizes changed (now 6px x 10px for `base` & `large`; 10px x 14px for `larger`)
- casing removed and fontSize adjusted
- snapshot tests updated
Before:
After:
---
=> refactor(components): Update InlineLabel

docs/content/voice-and-tone.mdx
=> Docs: update voice and tone marketing link

packages/components/src/Button/Button.css
There should be no letter-spacing on the small buttons
Before:
After:
---
=> refactor(components): Remove letterSpacing-loose letter spacing from Buttons

packages/components/src/Checkbox/Checkbox.css, packages/components/src/RadioGroup/RadioGroup.css
Style issues where noticed with checkbox component while adding multiline label. 
- Checbox.css 
`margin-top: var(--space-smallest)`; within `.checkHolder`
-CheckBox
`align-items: flex-start;` in `.wrapper`
---
Before
After
=> refactor(components): Fix vertical spacing for Checkbox

packages/design/jobberStyle.js
Remove unwanted `console.log` from the build process.
- Remove unwanted `console.log` from the build process.
---
=> cleanup(design): Remove unwanted console log

packages/components/package-lock.json, packages/design/npm-shrinkwrap.json
Update `npm-shrinkwrap.json` from `packages/design` and `package-lock.json` from `packages/components`
- Update `npm-shrinkwrap.json` from `packages/design` and `package-lock.json` from `packages/components`
---
=> chore(components): Update package-lock.json and npm-shrinkwrap.json

doczrc.js, package-lock.json, packages/docz-tools/src/gatsby-theme-docz/components/Navigation/useJobberMenu.tsx
- 
- don't render stories link on docz sidebar
- 
- 
- 
- 
---
=> docs: Ignore stories.mdx on docz

packages/components/src/Card/Card.mdx, packages/components/src/Card/Card.tsx, packages/components/src/Card/CardHeader.tsx
Minor cleanup in Card component post customizable header changes in #1026 
cleanup with no change in functionality: 
- removed style className prop in CardHeader and replaced by direct import
- refactored rendering logic for title and header
- removed obsolete import in Card.mdx
- 
- 
- 
- 
- 
- 
[Add header title to Card](http://127.0.0.1:3333/components/card#card)
[Add custom header to Card](http://127.0.0.1:3333/components/card#header-with-custom-component)
---
=> refactor(components): Minor Cleanup in Card component post Customizable Header Change

.storybook/components/ExampleWithHooks/ExampleWithHooks.tsx, .storybook/components/ExampleWithHooks/index.ts, .storybook/main.ts
Help us render examples within Storybook's `<Canvas />` component. Pretty much make it work like Docz canvas and render function children
- Added `ExampleWithHooks` component
- Added `mdxUtils` so we can import it on `.stories.mdx` files
- 
- 
- 
- 
- 
---
=> docs: Add ExampleWithHooks component

.storybook/preview.js, packages/components/src/Chips/Chips.stories.mdx, packages/components/src/Countdown/Countdown.stories.mdx, packages/components/src/FormatFile/FormatFile.stories.mdx, packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.stories.mdx, packages/components/src/FormatTime/FormatTime.stories.mdx, packages/components/src/InputAvatar/InputAvatar.stories.mdx, packages/components/src/InputEmail/InputEmail.stories.mdx, packages/components/src/Table/Table.stories.mdx
- Created story files for 
- Chips
- Countdown
- FormatFile
- FormatRelativeDateTime
- FormatTime
- InputAvatar
- InputEmail
- Table
- 
- 
- 
- 
- 
---
=> docs(components): Docs migration bundle 3

doczrc.js, gatsby-config.js, gatsby-node.js, package-lock.json, package.json, packages/components/src/DatePicker/DatePicker.stories.mdx, packages/components/src/Gallery/Gallery.stories.mdx, packages/components/src/Heading/Heading.stories.mdx, packages/components/src/InputNumber/InputNumber.stories.mdx, packages/components/src/Markdown/Markdown.stories.mdx, packages/components/src/Popover/Popover.stories.mdx, packages/components/src/ProgressBar/ProgressBar.stories.mdx, packages/components/src/Toast/Toast.stories.mdx
Convert the first bundle of components to Storybook.
Storybook pages for:
- Markdown
- Gallery
- Heading
- DatePicker
- Toast
- InputNumber
- ProgressBar
- Popover
- 
- 
- 
- 
- 
---
=> docs(components): Convert bundle to Storybook

.storybook/main.ts, packages/design/src/Borders.stories.mdx, packages/design/src/Colors.stories.mdx, packages/design/src/Elevations.stories.mdx, packages/design/src/ResponsiveBreakpoint.stories.mdx, packages/docz-tools/src/components/index.ts
- Created Storybook files for:
- Colors
- Borders
- Elevation
- Breakpoints
- 
- 
- 
- 
- 
---
=> docs(design): Docs Migration Bundle 1

packages/components/src/Chips/Chips.stories.mdx, packages/components/src/Countdown/Countdown.stories.mdx
Follow up from https://github.com/GetJobber/atlantis/pull/1046 to make source code work again
- 
- Make use of `ExampleWithHooks` component
- 
- 
- 
- 
---
=> docs: Implement example with hooks

.storybook/main.ts
We noticed that the CSS for Gallery's lightbox is not loading in storybook. It was because of how webpack within storybookis handling them.
- 
- Separate how we handle css loaders for 3rd-party packages and Atlantis
- 
- 
- 
- 
---
=> docs: separate css loader for Atlantis and lib

packages/components/src/LightBox/LightBox.stories.mdx
Adds LightBox storybook page. The CSS for the library is working after #1074 so now we can have all components in Storybook.
- 
- 
- 
- 
- 
- 
---
=> docs(components): Add LightBox storybook page

packages/components/src/Countdown/Countdown.test.tsx, packages/components/src/Toast/Toast.test.tsx
This 2 tests fails when we upgrade to React 18. This should get it out of the way for us
- 
- ensure we await promises
- 
- 
- 
- 
---
=> chore: properly write waitFor tests

package-lock.json, package.json, packages/components/package-lock.json, packages/components/package.json
Reverts GetJobber/atlantis#1089
Since it's blocking atlantis from merging in updated components.
=> chore(components): Revert - Upgrade react router dom

package-lock.json, package.json, packages/components/package-lock.json
- 
- 
- 
- @reach/router, react-helmet-async, and @types/theme-ui are needed for docz and docz-tools
- 
- 
---
=> build(deps): Uninstall unused packages

package-lock.json, package.json, packages/components/package-lock.json
We need to bump lerna to latest to make it real easy to get to Node 18
- 
- Bumped Lerna to latest
- ✅  v4 breaking changes https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes-1
- ✅ v5 breaking changes https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes
- ✅ v6 https://github.com/lerna/lerna/blob/main/CHANGELOG.md#breaking-changes-1
- comes with a [lerna repair](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#new-lerna-repair-command)  <br/> ![image](https://user-images.githubusercontent.com/15986172/225018951-6f88b4c1-28ea-4fd7-a902-9b4200ba694b.png)
- 
- 
- 
- 
---
[JOB-63639]
[JOB-63639]: …
=> build(deps): Upgrade Lerna to v6

.eslintignore, packages/components/src/Autocomplete/Menu.tsx, packages/components/src/Banner/Banner.test.tsx, packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx, packages/components/src/DatePicker/DatePicker.test.tsx, packages/components/src/Drawer/Drawer.tsx, packages/components/src/FormField/FormFieldWrapper.tsx, packages/components/src/FormatFile/FormatFile.test.tsx, packages/components/src/Gallery/GalleryTypes.ts, packages/components/src/InputAvatar/InputAvatar.tsx, packages/components/src/LightBox/LightBox.test.tsx, packages/components/src/MultiSelect/MultiSelect.test.tsx, packages/components/src/Page/Page.test.tsx, packages/components/src/RecurringSelect/RecurringSelect.test.tsx, packages/components/src/Toast/Toast.test.tsx, packages/formatters/src/global.ts, packages/hooks/src/useCollectionQuery/mdxUtils.ts, packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
Preparing our codebase to upgrade ESlint. The fixes were made based on the outputs of #1118 
- Fixed some potential ESLint issues when we upgrade them
- Added the folder storybook-static to the `.eslintignore` file so the `npm run lint` doesn't get stuck
- 
- 
- 
- 
- 
- 
---
=> refactor: prepare for ESlint upgrade

package-lock.json, package.json, packages/components/package-lock.json, packages/components/package.json, packages/components/src/DataTable/DataTable.test.tsx, packages/design/package-lock.json, packages/design/package.json, packages/formatters/package-lock.json, packages/formatters/package.json, packages/hooks/package-lock.json, packages/hooks/package.json, tsconfig.base.json
In order to keep up with the times and, of course, allow us to upgrade to Node 18 with minimal issues around typescript, we need to upgrade to TS 4.9
- 
- Bumped to TS 4.9
- Bumped from ES5 to ES6 - which partially removes IE11 support
- Updated failing test
- 
- 
- 
- 
---
=> build: Upgrade Typescript to 4.9 [JOB-65415]

packages/components/src/Disclosure/Disclosure.tsx
As per this conversation : https://getjobber.slack.com/archives/C03BJHV3PMG/p1679937099895299, I updated the disclosure component to use `useResizeObserver` to change the size of the title of the `Disclosure` component  when on a smaller Breakpoint. 
Below Breakpoint :
Above Breakpoint: 
- 
- 
- 
- 
- 
- 
---
=> fix(components): update Disclosure component to use useResizeObserver on title

packages/components/src/InputFile/InputFile.test.tsx, packages/components/src/InputFile/InputFile.tsx
We need this to be able to use the upload expense receipt (following the same as the mobile side)
- `uploadUrl` is now a prop from `FileUpload` type following the same pattern as the mobile
- 
- 
- 
- 
- 
---
=> feat: Add uploadUrl to FileUpload

package-lock.json, package.json
- 
- 
- 
- 
- 
- Update trim package to mitigate https://github.com/advisories/GHSA-w5p7-h5w8-2hfq
---
=> chore: Change trim version to fix security vulnerability

package-lock.json, packages/components/package.json, packages/components/rollup.config.js, packages/components/src/Typography/css/Emphasis.css
To avoid deprecation warnings, `postcss-svg` needs to be removed during the Node 18 upgrade
- `Emphasis.css` now references the svg inline
- `postcss-svg` has been removed from `packages/components`
`npm i @jobber/components@4.3.1-pre.0+a91e717e` in JO
---
=> build(deps): Remove postcss-svg

packages/components/rollup.config.js
Prevent broken builds by preventing typescript error on rollup. Pretty much do what `tsc` would do if it's ran locally. But we use rollup typescript and it's off by default. This turns it on.
- Enable `noEmitOnError` on component typescript rollup
- 
- 
- 
- 
- 
---
=> fix: Enable noEmitOnError on component bootstrap

.vscode/extensions.json, .vscode/settings.json, docs/README.md
- More VSCode settings to make linting more consistent for contributers
- 
- 
- 
- 
- 
---
=> chore: Add vscode settings and extensions for linting

docs/README.md
The CircleCi badge broke:
Removed unnecessary API Status token within the mardown
---
=> docs: Fix CircleCi badge

package-lock.json, package.json, packages/hooks/package.json
This PR downgrades the `apollo/client` version to match jobber-mobile at `3.7.3`.  
We should test `hooks` in jobber-mobile and JO to be sure that in doing this version downgrade, `hooks` intended behaviour continues!
`@apollo/client` was downgraded from `3.7.10` to `3.7.3`
Places where Atlantis Hooks are being used in JO and jobber-mobile should be tested to make sure nothing is broken with hooks.
jobber-mobile PR here with pre-release installed: https://github.com/GetJobber/jobber-mobile/pull/7216
Android Bitrise Build here for testing: https://github.com/GetJobber/jobber-mobile/pull/7216#issuecomment-1527763167
Jobber online PR here with pre-release installed: https://github.com/GetJobber/Jobber/pull/35373
--- …
=> chore(hooks): Check if dropping hooks dev dependency version works [JOB-67899]

packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx, packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
Adds validation to InputPhoneNumber. It will remove the space, parenthesis and hyphen from the number and test if it's greater than 10 digits.
- Default validation to `InputPhoneNumber`
- 
- 
- 
- 
- 
---
=> feat(components): Add validations to InputPhoneNumber

packages/components/src/InputPhoneNumber/InputPhoneNumber.stories.mdx, packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx, packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
- 
- feat(components): Expose pattern prop to the InputPhoneNumber
- 
- 
- 
- 
- Verify that the `pattern` prop for `InputPhoneNumber` works
---
https://youtu.be/Fegs-XVKgnM
=> feat(components): Expose pattern prop in InputPhoneNumber

.github/CODEOWNERS
Because we need to know everything!
- codeowners file
- 
- 
- 
- 
- 
---
=> chore: Tag atlantis team on any PR

packages/components/src/InputPhoneNumber/InputPhoneNumber.test.tsx, packages/components/src/InputPhoneNumber/InputPhoneNumber.tsx
- The phone number validation would force an input even when the `required` prop was set to `false`.
- 
- 
- 
- 
- The phone number length is only validated when the input length is between 1-9.
- 
---
=> fix(components): fix phone number validation for when it's not required

packages/components/src/Banner/Banner.stories.mdx
Our design pattern no longer includes using banners for errors that can be solved by inline validation alone. Example updated.
- 
- 
- 
- 
- 
- 
---
=> docs: update banner from updated design guidelines

packages/components-native/src/Text/Text.test.tsx, packages/components-native/src/Text/Text.tsx, packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap, packages/components-native/src/Text/index.ts, packages/components-native/src/index.ts
Import `Text` to `components-native`
- `Text` RN component now exists
- test & snapshot files also added
---
=> feat(components-native): Import Text to components-native

packages/components-native/src/ActivityIndicator/ActivityIndicator.test.tsx, packages/components-native/src/ActivityIndicator/ActivityIndicator.tsx, packages/components-native/src/ActivityIndicator/index.ts, packages/components-native/src/index.ts
- `ActivityIndicator` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import ActivityIndicator to components-native

package-lock.json, packages/components-native/package.json, packages/components-native/src/Content/Content.test.tsx, packages/components-native/src/Content/Content.tsx, packages/components-native/src/Content/ContentHorizontal.style.ts, packages/components-native/src/Content/ContentSpaceAround.style.ts, packages/components-native/src/Content/ContentVertical.style.ts, packages/components-native/src/Content/index.ts, packages/components-native/src/index.ts
- `Content` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import Content to components-native

package-lock.json, packages/components-native/package.json, packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.style.ts, packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.test.tsx, packages/components-native/src/ErrorMessageWrapper/ErrorMessageWrapper.tsx, packages/components-native/src/ErrorMessageWrapper/context/ErrorMessageContext.tsx, packages/components-native/src/ErrorMessageWrapper/context/ErrorMessageProvider.tsx, packages/components-native/src/ErrorMessageWrapper/context/index.ts, packages/components-native/src/ErrorMessageWrapper/context/types.ts, packages/components-native/src/ErrorMessageWrapper/index.ts, packages/components-native/src/index.ts, tsconfig.base.json
- `ErrorMessageWrapper` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import ErrorMessageWrapper to components-native

package-lock.json, packages/components-native/jest.config.js, packages/components-native/jestNativeSetup.ts, packages/components-native/package.json, packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx, packages/components-native/src/AtlantisContext/AtlantisContext.tsx, packages/components-native/src/AtlantisContext/index.ts, packages/components-native/src/__mocks__/__mocks.ts, packages/components-native/src/index.ts
Import `AtlantisContext` to `components-native`
- `AtlantisContext` now exists
- setup `mocks` folder and global setup for native in `components-native`
---
=> feat(components-native): Import AtlantisContext

packages/components-native/src/Card/Card.style.ts, packages/components-native/src/Card/Card.test.tsx, packages/components-native/src/Card/Card.tsx, packages/components-native/src/Card/components/InternalCardHeader.style.ts, packages/components-native/src/Card/components/InternalCardHeader.test.tsx, packages/components-native/src/Card/components/InternalCardHeader.tsx, packages/components-native/src/Card/components/index.ts, packages/components-native/src/Card/index.ts, packages/components-native/src/index.ts
- `Content` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import Card to components-native

docs/components/Content/Content.stories.mdx, docs/components/Content/Mobile.stories.mdx
Just cleaning up some unused vars that we were importing.
- 
- 
- 
- Unused vars in stories files
- 
- 
---
=> docs(components): Cleanup unused vars in stories

docs/components/ActivityIndicator/ActivityIndicator.stories.mdx, docs/components/ActivityIndicator/Mobile.stories.mdx
Added storybook page for `ActivityIndicator`
- Added storybook page for `ActivityIndicator`
---
=> docs(components-native): Add ActivityIndicator storybook

packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
Skipping a flaky test that is causing failures. We will have to address this in the future but seeing CI fail every day because of this test creates a ton of noise that we should remove.
- 
- 
- 
- 
- 
- 
---
=> chore: Skip flaky Date test

.storybook/components/SBProvider/SBProvider.tsx, docs/components/ActionLabel/ActionLabel.stories.mdx, docs/components/ActionLabel/Mobile.stories.mdx, package-lock.json, package.json, packages/components-native/package.json
Adding the mobile`ActionLabel` docs and moving them to the new folder and pattern.
- Add `ActionLabel` mobile docs
- 
- 
- 
- 
- 
---
=> docs(components-native): Add Mobile ActionLabel docs

packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap, packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap, packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap, packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap, packages/design/src/colors.css
- To align the brand--highlight colour with marketing. See Slack [thread](https://getjobber.slack.com/archives/C03BJHV3PMG/p1684871664049589) for context.
- Changed colour code of brand--highlight from rgb(160, 215, 42) to rgb(132, 234, 0).
- 
- 
- 
- 
- 
- 
---
=> feat(design): change colour code for brand--highlight

packages/components-native/src/InputPressable/InputPressable.style.ts, packages/components-native/src/InputPressable/InputPressable.test.tsx, packages/components-native/src/InputPressable/InputPressable.tsx, packages/components-native/src/InputPressable/index.ts, packages/components-native/src/index.ts
- `InputPressable` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import InputPressable to components-native

packages/components-native/src/InputPressable/InputPressable.style.ts
- 
- use tokens instead of JobberStyle on InputPressable
- 
- 
- 
- 
---
=> fix: use tokens instead of JobberStyle on InputPressable

packages/components/src/InputNumber/InputNumber.tsx
- 
- enabled prefix and suffix on input number because... i think we just forgot
- 
- 
- 
- 
---
=> fix: enable prefix and suffix on InputNumber

packages/components-native/src/EmptyState/EmptyState.style.ts, packages/components-native/src/EmptyState/EmptyState.test.tsx, packages/components-native/src/EmptyState/EmptyState.tsx, packages/components-native/src/EmptyState/index.ts, packages/components-native/src/index.ts
- `EmptyState` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import EmptyState to components-native 

packages/design/src/ResponsiveBreakpoint.stories.mdx, packages/design/src/responsiveBreakpoints.css
We actually wanted the large to be `1024` and xl to `1440`
- 
- Large and XLarge breakpoint values
- 
- 
- 
- 
---
JOB-70199
=> fix(design)!: Adjust breakpoints BREAKING CHANGE

packages/components/src/Grid/Grid.css, packages/components/src/Page/Page.css
The math did not add up nicely with 16 on a big screens (we'd end up with a lot more half pixel column widths) so this aims to update them as design intended them to be designed!
- 
- changed Prid gap to 16 on medium-down and 24 on medium-up
- changed Page padding to be 16 on medium-down and 24 on medium-up
- 
- 
- 
- 
---
JOB-70200
=> fix(components): adjust grid and page spacing

packages/components-native/src/Switch/Switch.styles.ts, packages/components-native/src/Switch/Switch.test.tsx, packages/components-native/src/Switch/Switch.tsx, packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.test.tsx, packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.tsx, packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap, packages/components-native/src/Switch/components/BaseSwitch/index.ts, packages/components-native/src/Switch/index.ts, packages/components-native/src/index.ts
Import Switch to `components-native`
On Atlantis root:
```sh
npm pack -w @jobber/components-native
```
On jobber-mobile root (assuming you have them in the same folder): 
```sh
npm install ../atlantis/jobber-components-native-0.21.1.tgz
```
Then you can replace the usages in jobber-mobile: 
---
=> feat(components-native): Import Switch to components-native

packages/components/src/Checkbox/Checkbox.tsx, packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Makes `Checkbox` aware of the form state and updates the form state when the component is updated. It was breaking some tests in JO where teams wants the checkbox to be aware of the form state, but it's not updating it there.
I didn't wrap it in a `FormField` due to the styles applied to it, but the implementation is similar.
- `Controller` to the `Checkbox` component. Now `Checkbox` is aware of the form state and updates it.
- 
- 
- 
- 
- 
---
=> feat(components): Add Controller to Checkbox

packages/design/src/responsiveBreakpoints.css
We accidentally missed a few "px" units when updating the breakpoints.
- 
- 
- 
- 
- Add "px" units for a few custom breakpoints.
- 
---
=> fix(design): Fix breakpoints with missing "px" units

package-lock.json, packages/components-native/package.json, packages/components-native/src/InputSearch/InputSearch.style.ts, packages/components-native/src/InputSearch/InputSearch.test.tsx, packages/components-native/src/InputSearch/InputSearch.tsx, packages/components-native/src/InputSearch/components/FilterButton.tsx, packages/components-native/src/InputSearch/index.ts, packages/components-native/src/index.ts
-`InputSearch` component in components-native
- 
- 
- 
- 
- 
Branch to test it on jobber-mobile: https://github.com/GetJobber/jobber-mobile/compare/test-branch-inputsearch?expand=1
---
=> feat(components-native): Import InputSearch to components-native

packages/components-native/src/BottomSheet/index.ts
Exporting some components that we use outside of Atlantis in jobber-mobile that were not being exported by our `components-native` library.
- 
- `BottomSheet` now exports `BottomSheetRef`, `BottomSheetOptionsProps`, `BottomSheetOption`
- 
- 
- 
- 
---
=> fix(components-native): Export missing components from BottomSheet

packages/components-native/src/InputPassword/InputPassword.test.tsx, packages/components-native/src/InputPassword/InputPassword.tsx, packages/components-native/src/InputPassword/index.ts, packages/components-native/src/InputPassword/messages.ts, packages/components-native/src/index.ts
- `InputPassword` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import InputPassword to components-native

package-lock.json, packages/components-native/package.json, packages/components-native/src/Checkbox/Checkbox.style.ts, packages/components-native/src/Checkbox/Checkbox.test.tsx, packages/components-native/src/Checkbox/Checkbox.tsx, packages/components-native/src/Checkbox/CheckboxGroup.style.ts, packages/components-native/src/Checkbox/CheckboxGroup.test.tsx, packages/components-native/src/Checkbox/CheckboxGroup.tsx, packages/components-native/src/Checkbox/CheckboxGroupReducer.test.ts, packages/components-native/src/Checkbox/CheckboxGroupReducer.ts, packages/components-native/src/Checkbox/index.ts, packages/components-native/src/Checkbox/types.ts, packages/components-native/src/index.ts
I just didn't add the tests for `CheckboxGroup` because it requires `Form`, and it has not been imported yet.
- `Checkbox` component in components-native
- 
- 
- 
- 
- 
---
=> feat(components-native): Import Checkbox to components-native

packages/components/src/Glimmer/Glimmer.css, packages/components/src/Glimmer/Glimmer.css.d.ts, packages/components/src/Glimmer/Glimmer.stories.mdx, packages/components/src/Glimmer/Glimmer.test.tsx, packages/components/src/Glimmer/Glimmer.tsx, packages/components/src/Glimmer/style/Shape.css
- Supported `reverseTheme` prop to render the glimmer on a really dark background
- Added `Glimmer.Header`, `Glimmer.Text`, `Glimmer.Button` with default styling and a bit of semantic meaning
- Changed the default styling to adapt to the background color
- 
- 
- 
- 
---
=> feat: Extend Glimmer features

packages/components/src/Tabs/Tabs.css
=> fix(components): missing display flex prevented tabs to scroll

packages/components/src/InputValidation/InputValidation.css
- 
- Top aligned and resized icon which shows in multi-line input validation messages
Before:
After:
- 
- 
- 
- 
---
=> fix(components): Align and resize icon for multiline input validation messages

.github/workflows/codeql-analysis.yml
Adding custom CodeQL configuration to allow control over the directories, as we need to exclude the generator templates.
Reference: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning
- 
- 
- 
- 
- 
- 
---
=> build: Add CodeQL configuration

packages/components/src/InputEmail/InputEmail.stories.mdx
- 
- Added a missing period in overview statement of InputEmail
- 
- 
- 
- 
---
=> docs: Added missing period to overview sentence in InputEmail 

.github/workflows/pr-title-checker.yml, .github/workflows/trigger-qa-build.yml
A side effect of upgrading to GitHub Enterprise is that the default permissions of workflow actions became more restrictive (read-only by default, instead of read and write).
This is actually the more desirable setting anyways, so there will be a number of workflows (like these!) that now need editing to restore their permissions.
See https://github.com/GetJobber/Jobber/pull/36845
- 
- 
- 
- 
- 
- 
---
=> build: Update workflow permissions

package-lock.json, packages/components-native/package.json
`react-native-keyboard-aware-scroll-view` was installed as a dev dependency instead of an actual dependency of the package. Just moving from `devDependencies` to `dependencies`
- 
- 
- 
- 
- 
- 
---
=> fix(components-native): Install react-native-keyboard-aware-scroll-view as dependency

.storybook/components/StoryDetails/StoryDetails.css, .storybook/components/StoryDetails/StoryDetails.css.d.ts, .storybook/components/StoryDetails/StoryDetails.tsx, .storybook/components/StoryDetails/index.ts, .storybook/preview.tsx, docs/CONTRIBUTING.md, docs/components/ButtonGroup/ButtonGroup.stories.mdx, docs/components/ButtonGroup/Mobile.PrimaryAction.stories.tsx, docs/components/ButtonGroup/Mobile.SecondaryAction.stories.tsx, docs/components/ButtonGroup/Mobile.stories.tsx
Yup, that's right. More migration docs
- ButtonGroup documentation
- 
- 
- 
- 
- 
---
=> docs: add button group docs and mobile example

packages/design/src/index.ts
We need that to be able to use foundation tokens in our Jobber Online features and avoid jest failing due to importing internal modules from `@jobber/design` 
- Added `tokens` from `foundation` as a default export from `@jobber/design`
- 
- 
- 
- 
- 
---
=> fix(design): add export tokens from foundation index

.github/CODEOWNERS
Ping @chris-at-jobber and @fagnanm when new icons get added
- Code owners for icon folder
- 
- 
- 
- 
- 
---
=> build: ping designers on icon addition

.github/workflows/trigger-qa-build.yml
- 
- 
- 
- 
- Fixed syntax error that was causing pre-releases to fail
- 
---
=> build: Fix pre-release script

packages/components/src/Banner/Banner.css, packages/components/src/Banner/Banner.css.d.ts
The green link color on top of the banner background colors fails the WCAG 2 Contrast and Color Requirements. 
- I added a new css selector to target all links that are child elements of the banner component and make them the default text color.
Before
After 
- Add a link component inside of a banner and ensure that it is the expected text color
---
=> refactor(design): Make all links within a banner component the default text color

docs/components/Datepicker/Datepicker.stories.mdx, docs/components/Datepicker/Web.stories.tsx, docs/components/InputDate/InputDate.stories.mdx, packages/components/src/DatePicker/DatePicker.tsx, packages/components/src/RecurringSelect/RecurringSelect.stories.mdx
- 
- Updated DatePicker documentation to use our new format
- 
- 
- 
- 
---
=> docs(components):  Update DatePicker Docs

docs/components/StatusLabel/Mobile.stories.tsx, docs/components/StatusLabel/StatusLabel.stories.mdx, docs/components/StatusLabel/Web.stories.tsx
- 
- Updated `StatusLabel` docs to use our new format
- 
- 
- 
- 
---
=> docs(components): Updated StatusLabel docs

docs/components/EmptyState/EmptyState.stories.mdx, docs/components/EmptyState/Mobile.stories.tsx
Adding the docs for EmptyState, it's mobile only.
- 
- Added docs for EmptyState
- 
- 
- 
- 
---
=> docs(components): Update docs for EmptyState

docs/components/Emphasis/Emphasis.stories.mdx, docs/components/Emphasis/Web.stories.tsx, packages/design/src/Typography.stories.mdx
Updating Emphasis docs, it's web only.
- 
- Update Emphasis docs
- 
- 
- 
- 
---
=> docs(components): Update Emphasis docs

docs/components/AutoLink/AutoLink.stories.mdx, docs/components/AutoLink/Mobile.stories.tsx
- Added AutoLink docs
- 
- 
- 
- 
- 
---
=> docs(components-native): Added AutoLink docs

.storybook/manager.js
it was due to the storybook API not being there on refresh
- guard storybook API before destructuring
- 
- 
- 
- 
- 
On atlantis.getjobber.com, go to any code tab
Reload the browser
It fails
Try it on this branch
It don't fail no mo
---
=> docs: code sandbox not rendering on browser refresh

packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap, packages/components/src/InputNumber/InputNumber.test.tsx, packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap, packages/components/src/InputTime/InputTime.test.tsx, packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Some snapshot tests weren't updated in https://github.com/GetJobber/atlantis/pull/1467 which broke due to other changes on master that weren't present in the branch at the time of the tests running
- 
- 
- 
- 
- 
- 
---
=> fix(components): Fix snapshot tests that weren't updated.

docs/CONTRIBUTING.md, docs/README.md, docs/guides/create-basic-component.stories.mdx
Updating the docs where it was mentioning the generators. I added the new select choice the user will have when they use `npm run generate`.
- 
- Updating the docs where it was mentioning the generators. I added the new select choice the user will have when they use `npm run generate`.
- 
- 
- 
- 
---
=> docs(generators): Update docs for generators usage

packages/components/src/DataList/DataList.css, packages/components/src/DataList/DataList.css.d.ts, packages/components/src/DataList/DataList.stories.tsx, packages/components/src/DataList/DataList.tsx
In order for us to piecemeal this component, we need to create the initial shell for the DataList component.
- Initial component structure for DataList
- 
- 
- 
- 
- 
---
=> chore: create DataList shell component

packages/components/src/DataList/DataList.stories.tsx, packages/components/src/DataList/DataList.test.tsx, packages/components/src/DataList/DataList.tsx, packages/components/src/DataList/components/EmptyState/EmptyState.css, packages/components/src/DataList/components/EmptyState/EmptyState.css.d.ts, packages/components/src/DataList/components/EmptyState/EmptyState.test.tsx, packages/components/src/DataList/components/EmptyState/EmptyState.tsx, packages/components/src/DataList/components/EmptyState/index.ts
Added empty state for DataList.
Added temporary props for items and `filterApplied` to have differences between filtered message and the provided message
- Added `EmptyState` to `DataList`
- 
- 
- 
- 
- 
---
=> chore(components): JOB-75738 Added Empty State for DataList

packages/components/src/DataList/DataList.stories.tsx
=> chore(components-native): Remove datalist story

packages/components/src/DataList/DataList.css, packages/components/src/DataList/DataList.test.tsx, packages/components/src/DataList/DataList.utils.tsx, packages/components/src/DataList/__tests__/DataList.utils.test.tsx
We've added the basic structure for list layout and utils but it isn't tested so this PR adds the test.
- Test for DataList layout and utils
- Replaced how we style the headers since `b` has a different meaning than a text styled to be bolded
- 
- 
- 
- 
---
=> chore(components): add some data list test

packages/components/src/DataList/DataList.css, packages/components/src/DataList/DataList.css.d.ts, packages/components/src/DataList/DataList.stories.tsx, packages/components/src/DataList/DataList.test.tsx, packages/components/src/DataList/DataList.tsx, packages/components/src/DataList/DataList.types.ts, packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.css, packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.css.d.ts, packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.test.tsx, packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.tsx, packages/components/src/DataList/components/DataListTotalCount/index.ts, packages/components/src/DataList/storyUtils.ts
Adding the title and counter to DataList. They're both optional.
When it's loading, it will show the Glimmer instead of the results string.
- 
- Added title and counter to DataList
- 
- 
- 
- 
You can remove this line and then DataList will show up in Storybook:
https://github.com/GetJobber/atlantis/blob/c48f3d35e38846864f624b50c0e0481e2c19c737/packages/components/src/DataList/DataList.stories.tsx#L15
Use the controls to test the behavior.
---
=> chore(components): Add counter and title to DataList

packages/components-native/src/ContentOverlay/ContentOverlay.style.ts, packages/components-native/src/InputDate/InputDate.tsx
Bring the latest changes from `ContentOverlay`. The PR:
https://github.com/GetJobber/jobber-mobile/pull/7663
- 
- Bringing latest changes from jobber-mobile to Atlantis `ContentOverlay`
- 
- 
- 
- 
---
=> chore(components-native): Bring latest changes of Atlantis components from jobber-mobile

packages/components/src/DataList/DataList.stories.tsx, packages/components/src/DataList/DataList.test.tsx, packages/components/src/DataList/DataList.tsx, packages/components/src/DataList/DataList.types.ts, packages/components/src/DataList/DataList.utils.tsx, packages/components/src/DataList/__tests__/DataList.utils.test.tsx
We shouldn't use the index as a key for mapped children. This [react doc](https://react.dev/learn/rendering-lists#why-does-react-need-keys) goes into detail as to why.
Gist of it:
- Say you have 10 items
- If you insert an item between 4 and 5 you'd now have 11 items
- Since the 5th element is now the 6th and so on, it'll rerender the previous 5 to 10 elements since the index changed.
- Now imagine you have 1,000 and you inserted between 1 and 2
- Explicitly set and ID as per react's suggestion
- Added label as a required key
- Added tags as an optional key
- adjusted types accordingly
- 
- 
- 
- 
---
=> chore(components): better keys for data list items

packages/components/src/DataList/DataList.stories.tsx, packages/components/src/DataList/DataList.test.tsx, packages/components/src/DataList/DataList.tsx, packages/components/src/DataList/components/DataListLayoutInternal/DataListLayoutInternal.tsx, packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css, packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css.d.ts, packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx, packages/components/src/DataList/components/DataListLoadingState/index.ts
Adds the initial loading state to the DataList. You can test it by changing the loading to `true` in the story controls. It should also be shown when the list is initially loading.
- `DataListLoadingState` component to `DataList`
- 
- 
- 
- 
- 
---
=> chore(components): Add loading state to DataList

packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx, packages/components-native/src/AtlantisContext/AtlantisContext.tsx, packages/components-native/src/ButtonGroup/ButtonGroup.test.tsx, packages/components-native/src/Form/Form.test.tsx, packages/components-native/src/Form/components/FormErrorBanner/FormErrorBanner.test.tsx, packages/components-native/src/Form/context/AtlantisFormContext.test.tsx, packages/components-native/src/Form/context/AtlantisFormContext.tsx, packages/components-native/src/InputCurrency/InputCurrency.test.tsx, packages/components-native/src/InputDate/InputDate.test.tsx, packages/components-native/src/InputText/context/InputAccessoriesContext.ts, packages/components-native/src/InputTime/InputTime.test.tsx, packages/components-native/src/hooks/useAtlantisI18n/useAtlantisI18n.test.ts
Better naming on default context values. Before they're very generic and we didn't know to which context they were related, so now it's more clear.
- 
- Naming of default values contexts from `AtlantisContext`, `AtlantisFormContext` and `InputAccessoriesContext`.
- 
- 
- 
- 
---
=> refactor(components-native): Refactor default values in to match the related context

packages/hooks/src/useInView/useInView.stories.mdx
We have a hook to determine if an element is in view. This documents it and makes it useable for the masses
- Documentation for `useInView`
- 
- 
- 
- 
- 
---
JOB-78070
=> docs(hooks): create useInView documentation

packages/components/src/DataList/DataList.css, packages/components/src/DataList/DataList.css.d.ts, packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx, packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx, packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx, packages/components/src/DataList/components/DataListLayoutInternal/__tests__/DataListItems.test.tsx, packages/components/src/DataList/components/DataListTags/DataListTags.css
We've implemented a hover menu but there's 1 problem to hover menu's on DataList, you will have to tunnel your mouse from left to right to get to that hover menu. 
So instead of tunneling your way to the left, you can just right click anywhere on that item and get the same actions
- Context menu on the data list item
- Add active background when the context menu is triggered so you know which one has been right clicked
- 
- 
- 
- 
- 
---
=> feat(components): add context menu on data list

packages/components/src/Link/Link.tsx, packages/components/src/Link/index.ts
The Link component doesn't export the prop type. We should export the type so it can be used by our consumers. This Pull Request fixes that.
- `LinkProps` type to the exports of the Link components.
- 
- 
- 
- 
- 
---
=> fix(components): Expose Link component props

docs/components/Banner/Banner.stories.mdx
Change in design to global banners in mobile
- 
Changed notes on where the global banner should be positioned in mobile.
Added outage/maintenance messages under the Notice type.
- 
- 
- 
- 
- 
---
=> docs(components): global banner layout position update on mobile [JOB-79966]

packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx, packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.test.tsx, packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
These components didn't have tests yet, so I added them! I also restructured the tests of `DataListItemActions` to be more specific to that component and moved the general ones to `DataListActions`
- 
- 
- 
- 
- 
- 
---
=> chore: Add tests for DataListActions and DataListBulkActions

packages/design/src/ResponsiveBreakpoint.stories.mdx, packages/hooks/src/useBreakpoints/index.ts, packages/hooks/src/useBreakpoints/mockViewportWidth/index.ts, packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.test.ts, packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts, packages/hooks/src/useBreakpoints/useBreakpoints.stories.mdx, packages/hooks/src/useBreakpoints/useBreakpoints.test.ts, packages/hooks/src/useBreakpoints/useBreakpoints.ts, packages/hooks/src/useBreakpoints/useMediaQuery.ts
Make it easier for devs to use the same breakpoints as the CSS counterpart. Instead of having to add a listener to `window.resize` and matching it up with a random number, devs can just use this hook to check if they should render their component on our supported breakpoints.
- `useBreakpoints` hook that gives you the sizes that we support
- `mockViewportWidth` to easily test it on your own codebase
- 
- 
- 
- 
- 
---
=> feat(hooks): create breakpoints hook

packages/components/src/DataList/DataList.tsx, packages/components/src/DataList/DataList.types.ts, packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
In the event that saving a filter and applying it back is required, we need to be able to update the initial value of the search box to reflect that the data you're seeing is indeed programmatically filtered instead of user filtered
- Initial value for search
- Updating this value after mount would result in the search input being rerendered.
- 
- 
- 
- 
- 
---
=> fix(components): DataList search initial value

docs/README.md
I was working on the `design` package and had to ask in our team's private channel how to get the changes to reflect in components in my local environment. @darryltec told me how, so I should add that info here so that people who do not have direct access to the team can have the same knowledge.
- Steps to cross-link packages locally
---
=> docs: add local cross-package link steps to readme

docs/components/Combobox/Combobox.stories.mdx, docs/components/Combobox/Web.stories.tsx
MultiSelect is now a thing, we should inform people about it and how to use it.
Added descriptions about single VS multi select, and clarified a bit about onClose vs onSelect and how they work with single and multi
Fixed something erroneous with the accessibility description around keyboard navigation since you can't actually tab to the list
Give it a read!
---
=> docs(components): Update Docs for Combobox MultiSelect Variation

docs/components/DataList/DataList.stories.mdx
Improve tech documentation for DataList
- Explanation on each compound components
- 
- 
- 
- 
- 
---
=> docs(components):  improve data list docs

docs/components/Content/Content.stories.mdx, docs/components/Flex/Flex.stories.mdx, docs/components/Grid/Grid.stories.mdx
As we now have a more robust suite of layout tools (Content, Flex, and Grid) each with their own purposes, adding some docs to help engineers choose the right tool for the job at hand.
- "Related component" notes to Flex, Grid, and Content docs.
View the docs for each
---
=> docs(components): Add related component guidance to common layout tools

.gitignore, packages/components/package.json, packages/components/rollup.config.js, packages/components/tsconfig.json, packages/components/tsconfig.rollup.json
After we've enabled aliasing within TS, the tests are actually excluded from aliasing and throws an error. This PR mitigates that
- `tsconfig.rollup.json` for rollup to use when packing and not including tests
- rollup config to look for tsconfig.rollup instead of the base one
- 
- 
- 
- 
---
=> chore: ensure paths are aliased on test as well in components

packages/components/src/CalendarDatePicker/CalendarDatePicker.test.tsx
I test, you test, we all scream for tests. Depends on upgrading `@testing-library/user-event`
---
=> test(components): Additional keyboard tests for Calendar Date Picker

packages/components/src/Combobox/Combobox.test.tsx
This rewrites the test to follow the new API and assumes the old compound components are no more. It would be easier to review this via editor mode (press `.`) and look for the file there as the file has completely changed.
- 
- Combobox test to reflect the new API and tests more of the user interaction
- 
- 
- 
- 
---
=> chore(components): Update the Combobox test to follow the new API

packages/components/src/Combobox/Combobox.test.tsx
There was this small window of the heading prop changed to label and that broke the test in master 
- 
- 
- 
- 
- 
- 
---
=> chore(components): replace heading with label in comboobx test

packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx, packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
- If you have Name and Home world as sortable
- Home world is sorted to be descending
- Clicking Name clears all of the sorting instead of setting Name as sorted
- Ensure we only clear sorting when you've clicked the header that's on descending
- 
- 
- 
- 
- 
---
=> fix(components): Ensure DataList sorting gets cleared in a predictable manner

docs/components/DataList/Web.stories.tsx, packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx, packages/components/src/Combobox/hooks/useComboboxAccessibility.ts, packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx, packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx, packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
Use Combobox instead of Popover on DataList sorting. Also fixes the position of Combobox when it's on the right side of the screen. Before it was overflowing the screen, not it's being adjusted.
- 
- `DataListSort` now uses `Combobox` instead of `Popover`
- 
- 
- `Combobox` overflowing right side of the screen.
- 
---
=> fix(components): Refactor DataListSort to use Combobox

packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
Cleaning up `DataListSort`, mostly for that unwanted `console.log` (sorry for that 🤦 )
- 
- 
- 
- 
- 
- 
---
=> refactor(components): Cleanup on DataListSort

packages/design/src/responsiveBreakpoints.css, packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.test.ts, packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts, packages/hooks/src/useBreakpoints/useBreakpoints.ts
Related to https://github.com/GetJobber/atlantis/pull/1639 so to ensure breakpointsand mocking work, we need to update this
- 
- 
- 
- 
- 
- 
---
=> fix: breakpoints and viewport mock

packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css, packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css.d.ts, packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.tsx, packages/components/src/DataList/components/DataListSearch/DataListSearch.css, packages/components/src/DataList/components/DataListSearch/DataListSearch.css.d.ts, packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
There was an issue where we're drilling down via `nth-child` to add a margin between items but if your child was in a `display: contents` it fails as it doesn't skip that element anymore but also invalidates other CSS properties gets added to it. To mitigate that we need to make the gap bits more resilient by using gap.
- added 1 more div to gap those actions out
- 
- 
- 
- alignment issue with search
- 
---
=> fix(components): DataList filters gap

docs/components/Icon/Icon.stories.mdx, packages/design/assets/icons/tag.svg
Need a tag icon to represent the concept of a "tag" metadata element being applied to an object
- tag icon
View the tag icon in the docs, or pull it out in a prerelease if you really want to!
**Web story**
**Mobile story**
**Docs**
---
=> feat(design): add tag icon 

packages/components/src/DataList/__tests__/DataList.selectable.test.tsx
This tests keeps on flakin but we don't really need to test this part as the checkboxes not being checked is already testted so should be good to remove it.
- 
- 
- 
- Flakey test
- 
- 
---
=> chore(components): remove flakey test

packages/components/src/Chip/Chip.css, packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
Now that we have [updated our semantic values for hover and focus states](https://github.com/GetJobber/atlantis/pull/1545/files#diff-871bc930b14a9999af07646fdced777b0d6c0dfa5923cd62d5b895d31e66c0bb), components that were approximating those changes in advance should be be updated to use the new correct values.
- swapped in semantic tokens for base palette approximations
- also cleaned up some visual state conflicts where disabled + invalid did not look disabled
Chip: View out the ["Comparison" story](https://update-chip-and-datalist-wit.atlantis.pages.dev/?path=/story/components-selections-chip-web-comparisons--all)
DataList: View the ["Basic" story](https://update-chip-and-datalist-wit.atlantis.pages.dev/?path=/story/components-lists-and-tables-datalist-web--basic) and sort one of the …
=> refactor(components): Update Chip and DataList with semantic colors

packages/components-native/src/ProgressBar/ProgressBar.style.ts, packages/components-native/src/ProgressBar/ProgressBar.test.tsx, packages/components-native/src/ProgressBar/ProgressBar.tsx, packages/components-native/src/ProgressBar/ProgressBarStepped.tsx, packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap, packages/components-native/src/ProgressBar/types.ts
- There are projects coming up that anticipate to use the stepped progress bar in mobile; might as well do it at once 🙂
- Stepped variation of the progress bar.
- Animation was not added due to the note in `ProgressBarInner` that there's issues with Android.
- 
- 
- 
- 
- 
---
=> feat(components-native): Add stepped variation of progress bar for mobile

docs/components/DataList/Web.stories.tsx, packages/components/src/DataList/components/DataListTags/DataListTags.css, packages/components/src/DataList/components/DataListTags/DataListTags.tsx
Fixing the DataList tags overflow counter, it was not updating correctly when the number of tags changed; for example, if three tags were overflowing and it changed to 1 tag, and it didn't overflow, it would still show the +3 on the row.
I fixed it by resetting the `visibleIndex` state because I noticed that the previous state was copied to the new state on `handleIntersection`. This way, every time the items change, it will reset the visible items.
- 
- 
- 
- 
- 
- 
- I added a commit for, you can check out the commit `3167c2e101dfe4d8c52f817cfdf7c9d151753d0b`, and you will have two buttons to control the number of tags
---
=> fix(components): Fix DataList tags counter overflow

packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css, packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
We're seeing some strange behaviors of the Combobox list trying to use scrollbars even we don't need them (as per image below)
- 
- Update Combobox List styling to use `overflow: auto` rather than `overflow: scroll`
- 
- 
- 
- 
---
=> fix(components): update combobox list to use overflow: auto rather than scroll

packages/components/src/Switch/Switch.css
Allow Switch to be re-styled when a given class is present
- Enable Switch to be re-themed and create alternate styling for re-theme
- For both modes, set focus to be on `:focus-visible` to follow browser heuristics on when to show focus ring
Apply the `jobber-retheme` class to the Storybook iframe `body`
---
=> refactor(components): Update switch for retheme [JOB-84553]

packages/components/src/Button/Button.css, packages/components/src/RadioGroup/RadioGroup.css
Missed a style declaration in #1693 and #1690
- Secondary and tertiary buttons should look identical for now
- subtle-secondary button should not add a border on hover 
- Radio should show focus ring when tabbing, not when clicked with pointer/mouse
Add the `jobber-retheme` class to the body of the story iframe
---
=> fix(components): tertiary button border and radio focus state

packages/components/src/Banner/Banner.css, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/Banner.types.tsx, packages/components/src/Banner/components/BannerIcon/BannerIcon.css, packages/components/src/Banner/components/BannerIcon/BannerIcon.css.d.ts, packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx, packages/components/src/Banner/index.ts
Banners are being redesigned but it's in experiment so hide it behind a flag.
- 
- 
- 
- 
- 
- 
add this anywhere on preview.tsx as the class needs to exist before the component renders
```ts
setTimeout(() => {
document.body.classList.add("jobber-retheme");
}, 0);
```
---
=> chore: prep banner for retheme

packages/components/src/Button/Button.css, packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css, packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css, packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css, packages/components/src/DataList/components/DataListAction/DataListAction.css, packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css, packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css, packages/components/src/Drawer/Drawer.css, packages/components/src/Menu/Menu.css, packages/components/src/Tooltip/Tooltip.css
Get rethemed components more polished
- styling changes behind retheme flag
- Adjust Drawer styling for re-theme 
- increase specificity of selector for icon colors to ensure it's always one color
- Make small button slightly larger to match designs  
- reduce roundness of Combobox/DataList/Tooltip elements, which were prematurely rounded
Use the `.jobber-retheme` class on the story's iframe `body`
---
=> refactor(components): Spot fixes for rethemed components [JOB-85146]

packages/components/src/DataList/DataList.css, packages/components/src/DataList/components/DataListSearch/DataListSearch.css, packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx, packages/components/src/FormField/components/ClearAction.css
Making it easier for SPs to clear the search on DataList. 
I had to add a `max-width` to the input search container because it increased the width when the clear button was being shown. I set it to `base * 13` (208px) because it's closer to the current width that was being rendered (214px). I'm open to suggestions if you know a better solution.
- 
- 
- 
- 
- 
- 
---
=> feat(components): Add clearable to DataList Search

packages/components/src/LightBox/LightBox.css
Allow the appearance of Lightbox's toolbar to change when a new theme is applied
- When `.jobber-retheme` is set on the body, the toolbar is lighter
Add the `.jobber-retheme` class to the iframe body
---
=> refactor(components): update lightbox toolbar for retheme

packages/components/src/InputFile/InputFile.test.tsx, packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Testing now checks against the component instead of using a snapshot. 
---
=> chore: Updated testing for custom file types 

docs/content/product-vocabulary.stories.mdx
Added a line about using "appointments" to refer to scheduled events in a generalized manner.
- 
- 
- 
- 
- 
- 
---
=> docs(design): add use case for 'appointment' language in vocabulary guidelines

packages/hooks/src/useAssert/useAssert.tsx
Currently, we are checking the `process.env` directly, which is not available at Remix by default. This change adds the optional chaining to check if `process.env` is available.
- 
- 
- 
- 
- `useAssert` can be used in Remix
- 
---
=> fix(hooks): Guard useAssert to work with SSR

package-lock.json, packages/components/package.json, packages/components/src/AnimatedSwitcher/AnimatedSwitcher.tsx, packages/components/src/InputValidation/InputValidation.tsx
In order to take advantage of performance and bug fixes, we need to bump framer motion to latest.
- 
- framer motion from 6.x to 11.x
- 
- 
- 
- 
---
=> chore: upgrade framer motion to 11.0.3

packages/hooks/src/useBreakpoints/mockViewportWidth/mockViewportWidth.ts
Some packages, like framer-motion, supports the older match media function of add and remove event listener. That's all good, but we mock the match media when mocking the viewport width without the add and remove event listener. That would make other tests that include framer motion fail.
- support for deprecated add and remove event listener
- 
- 
- 
- 
- 
---
=> fix(hooks): support add and remove listener on mockViewportWidth

packages/components/src/Combobox/Combobox.test.tsx, packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx, packages/components/src/Combobox/hooks/useCombobox.ts, packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
There was no way of the Combobox clear search term while closing it
- 
- 
- 
- 
- When closing the Combobox it will clear the search term as well
- 
---
=> fix(components): clearing search term in Combobox after clicking on clear button 

.storybook/manager.js
Something happened internally that we finally noticed that the sidebar isn't using Jobber Pro. Now it does!
- Use jobber fonts when it's available
- 
- 
- 
- 
- 
---
=> docs: use jobber fonts on manager js

packages/components/src/DataList/DataList.test.tsx
Increasing the coverage of the DataListHeaderTile component. I added a test for the new sorting options, testing the `onSort` callback and the visibility of the options.
I used the same `Header` section of the `DataList.test.tsx` file.
- 
- Added tests for DataListHeaderTile
- 
- 
- 
- 
---
=> refactor(components): Increase coverage of DataListHeaderTile

docs/changelog/components-native.stories.mdx
Just noticed we don't have a changelog page for `@jobber/components-native`, so I'm adding it!
- 
- 
- 
- 
- 
- 
---
=> docs(components-native): Add components-native changelog page

docs/components/DataList/Web.stories.tsx, packages/components/src/DataList/components/DataListLayout/DataListLayout.tsx
`DataList` was not rerending if the `children` in the same layout changed because it was not being reregistered with the new `children`.
- 
- 
- 
- 
- DataList not rerendering when the `children` of the same layout changed.
- 
`git checkout 7098d47` and go to the `DataList` page and try to toggle the loading using the button on the top.
---
=> fix(components): Fix DataListLayout not rerendering

packages/design/src/icons/Icon.css
Some of our icons didn't use the semantic color. This PR changes that
- 
- Use semantic colors for our client icons
- 
- 
- 
- 
- Run `npm run -w @jobber/design bootstrap`
- Restart storybook.
- Check the person, clients, company, and property icons. Verify their fill color is `var(--color-client)`
- Update `/packages/design/src/colors.css#L73-L74` and change color-client to something else ex. `var(--color-pink)`
- Run `npm run -w @jobber/design bootstrap`
- Restart storybook
- Confirm the color of the icon changes
---
=> feat(design): JOB-91365 Update client icons using color-teal to use the client semantic color

packages/components/src/DataList/hooks/useMediaQuery.ts, packages/hooks/src/useBreakpoints/useMediaQuery.ts
Reverts GetJobber/atlantis#1797
=> fix(components): Revert Make useMediaQuery SSR Friendly

packages/components/src/List/index.ts
Exporting ListItemProps from List so it's easily accessed. Some consumers were reaching to `/dist/List/ListItem` to get access to this type. 
- 
- Exporting `ListItemProps` from `List`
- 
- 
- 
- 
---
=> refactor(components): Export ListItemProps from List

packages/components/src/InputTime/hooks/useTimePredict.ts
Wrapping the `navigator` in a `useEffect` so it won't break on SSR environments.
- 
- Internal change in InputTime's `useTimePredict` to make it work on SSR environments.
- 
- 
- 
- 
---
=> refactor(components): Guard InputTime's useTimePredict for SSR

packages/components/src/FormatTime/FormatTime.tsx
Adding a safe guard to make FormatTime work on SSR environments.
- 
- 
- 
- 
- Make FormatTime work on SSR environments
- 
---
=> fix(components): Make FormatTime work on SSR environments

docs/components/InputText/Mobile.stories.tsx, packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts, packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx, packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx, packages/components-native/src/InputText/InputText.tsx
A new pattern has emerged that we need to inject some form of toolbar inside the boundaries of an input
- Toolbar prop on input text and wrapper which only shows up on focus
- 
- 
- 
- 
- 
---
=> feat(components-native): add input toolbar

packages/components-native/src/InputText/InputText.test.tsx, packages/components-native/src/InputText/InputText.tsx
There are cases where a readonly prop is needed on an input. 
- `readonly` prop to input text native
- Please note that it is named readonly and not readOnly for consistency sake with web
- 
- 
- 
- 
- 
---
=> fix: allow readonly prop on input text native

.gitignore
When running `npm run pack` to create a local release of an Atlantis package it wouldn't be ignored by git so you would have to take extra time making sure not to accidentally commit it. This PR aims to address it
- 
- Added the output of `npm run pack` to the `.gitignore` file
- 
- 
- 
- 
Run `npm run pack @jobber/components @jobber/design @jobber/components-native @jobber/hooks @jobber/eslint-config @jobber/generators @jobber/formatters @jobber/stylelint-config @jobber/hooks` to create local versions of atlantis packages. Verify that the `.tgz` files created don't get listed when you run `git status`
---
=> chore: Update gitignore to ignore local runs of npm run pack

packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap, packages/components/src/Heading/Heading.tsx, packages/components/src/Modal/Modal.css, packages/components/src/Modal/Modal.tsx, packages/components/src/Typography/css/FontWeights.css
- 
- Updated Heading styling to match the new retheme styles
- 
- 
- 
- 
Import pre-release into Jobber Online. While in the retheme verify the Heading styling matches for each of the levels.
Open a modal and verify that the heading on the modal also matches.
You can use code from the Heading  story and Modal web story to quickly get all the components on the same view
Note: Modal should be an H2 with H2 stylings. See: https://github.com/GetJobber/atlantis/pull/1857#discussion_r1556071137
---
=> feat(components): Update Headings to match retheme design

packages/components/src/Button/Button.tsx
- Required to unblock Remix work for Home.
- 
- Added `type` functionality for submit action button.
- 
- 
- 
- 
---
=> fix(components): Allow type on submit action button

docs/components/Tabs/Web.stories.tsx
Tabs code tab was broken in the `WithTabChangeCallback` story:
Removed React. from const in Tabs story
check out `WithTabChangeCallback` story code tab
---
=> docs: Fix Tabs story code tab

docs/README.md, docs/changelog/breaking-changes.stories.mdx
Contractors using Atlantis were experiencing loosing styles when upgrading to `components/5.x.x`:
And I've had a few people reach out to me about how to update Atlantis package versions. We have a SO post however let's include it on our Introduction page so it's clear.
Info about upgrading versions:
http://localhost:6005/?path=/docs/introduction--page#installing-specific-versions
Breaking change update:
http://localhost:6005/?path=/docs/changelog-upcoming-breaking-changes--page#jobbercomponents4910
---
=> docs: Documentation updates

packages/components-native/src/Heading/Heading.tsx, packages/components-native/src/Heading/index.ts, packages/components-native/src/Text/Text.tsx, packages/components-native/src/Text/index.ts
There are situations where you need to use `Typography` to add custom styling to `Headings` and `Text` however without these exported the `maxFontScale` needs to be copied or else the default scaling in Typography is used which max not match these values.
- components-native: Export `HEADING_MAX_SCALED_FONT_SIZE` constant
- components-native: Export `TEXT_MAX_SCALED_FONT_SIZES` constant
- 
- 
- 
- 
- 
---
=> feat(components-native): Export typography max font scaling in components-native

.github/pull_request_template.md
Mention pre-releases in Testing section of Atlantis PR descriptions until we automate that step.
We want to encourage ourselves and external contributors to test Atlantis changes in external repos through pre-releases.
One sentence added to Testing section of PR descriptions.
You won't see this change until it's in `master`
---
=> chore: Update Testing Instructions in PR descriptions

packages/components/src/SideDrawer/SideDrawer.css
- 
- make scrollbar not appear when no scrolling is needed
- 
- 
- 
- 
Changes can be
---
=> fix: side drawer scroll overflow to auto

packages/components/src/Select/Select.css
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix(components): allow Select background to work in dark modes

packages/components/src/Link/Link.css, packages/components/src/Link/Link.css.d.ts, packages/components/src/Link/Link.tsx
- I noticed when migrating one of our team components to the new remix home, when I used the Link component it wasn't being styled properly. In jobber online we style our a tags but in the new home we can't rely on that anymore. 
- Added css styling to a tag 
- Css styling to a tag in link component
- 
- 
- 
- 
- 
Changes can be
---
=> fix: Add css to style href in link component

packages/components/src/FormatFile/FormatFile.test.tsx, packages/components/src/FormatFile/InternalThumbnailImage.tsx, packages/components/src/InputFile/InputFile.tsx
There's a case where we need to know if an image errored out while loading. It could be due to various different things. We just want to know when it failed to load so consumers can react (pun 100% intended) to it.
- `onImageLoadError` callback on file types
- 
- 
- 
- 
- 
Changes can be
---
=> feat: on error callback on image files in format file

docs/components/Banner/Web.stories.tsx, packages/components/src/Banner/Banner.test.tsx, packages/components/src/Banner/Banner.tsx
Our banner would automatically hide when dismissable was `true`. However with Remix this automatic state handling would cause a flicker on the banner. This PR allows developers to control the visibility of the banner when it is dismissed without using the Banner's internal state.
- Added ability to control the visibility of the `Banner` when the `controlledVisibilty` prop is provided
- 
- 
- 
- 
- 
Changes can be
---
=> feat(components): Allow Banner dismiss to be controlled

packages/components/src/Toast/Toast.test.tsx, packages/components/src/Toast/showToast.tsx, packages/components/src/index.tsx
During our SSR support updates we missed adding support for toasts. This PR fixes that by preventing references to `document` if it is undefined
- Added SSR support for toasts
- 
- 
- 
- 
- 
Verify Toasts work in the referenced PRs
Changes can be
---
=> feat(components): SSR support for toast

docs/README.md, package-lock.json, package.json, packages/components-native/package.json, packages/components/package.json, packages/hooks/package.json
I'm having trouble installing latest `master` in Jobber. it's yelling about React version dependency resolution. I suspect it's because we have `"react": "18.2.0"` which is quite specific and when it doesn't get exactly that, it can't resolve.
"18.2.0" -> "^18.2.0"
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix(components): Loosen React Dependency Version Requirement

docs/components/Box/Box.stories.mdx, docs/components/Card/Card.stories.mdx
Box is a relatively new component but has some overlap with Card, so clearing up when to use each is helpful.
It will also give Triton something a bit meatier to train on so it can be more robust in answering this question!
- "Related components" to Box and Card
- How we present the alpha state of Box
Read the docs in the build!
---
=> docs(components): update Box and Card component docs

.github/pull_request_template.md, .github/workflows/pr-title-checker.yml
The GH workflows were failing for some dependabot PRs due to title not conforming with the acceptable format.
Dependabot assigns PR scopes automatically based on the type of dependency it bumps. Out PR title checker accepted `deps` as a valid scope, however, `deps-dev` was missing. It's the scope dependabot assigns to devDependency packages.
- Added `deps-dev` to the `scopes` list in the `pr-title-check` CI job.
- Updated the GH template to list all acceptable scopes.
- 
- 
- 
- 
Changes can be
---
=> chore(deps): add deps-dev to PR title checker workflow

docs/README.md, package.json
- Change the npm version in prerequisites to 10, as well as in the `engines` block, since it's the [default version included with the required node@18.](https://nodejs.org/en/about/previous-releases#:~:text=ReleasesChangelogDocs-,v18.20.4,-Hydrogen)
Changes can be
---
=> chore(docx): Update required npm version to v10

packages/components-native/src/Text/Text.tsx, packages/components-native/src/Typography/Typography.style.ts, packages/components-native/src/Typography/Typography.tsx, packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix(components-native): Enhances support for italic to Typography and Text (JOB-101940)

.storybook/components/Playground/Playground.tsx
- 
- 
- 
- 
- Storybook Code tab broke with the new changes as a result of the `design` package rewrite. This PR fixes that
- 
- Verify Storybook Code Playground works
Changes can be
---
=> docs: Fix Storybook playground breaking with new design package

packages/components/src/index.tsx, packages/components/src/utils/meta/meta.json
- 
- 
- 
- 
- Fixed failing test on master relating to meta.json
- 
Changes can be
---
=> fix: Fix failing test on master relating meta.json

docs/components/Chip/Chip.stories.mdx
Chip had no usage docs! 
- Docs to Chip
Test locally or on Cloudflare build
---
=> docs(components): Create `Chip` docs

packages/hooks/src/useBreakpoints/useBreakpoints.test.ts
In some cases the `useBreakpoints` tests could flake when a PR is merged into master. This PR aims to resolve that issue
- 
- 
- 
- 
- Fixed cases where `useBreakpoints` tests could flake 
- 
`git revert f8fd9ee`
Run the tests for `useBreakpoints` verify that the tests don't fail
Changes can be
---
=> fix(components): Fix flakey spec in useBreakpoints

docs/components/Chips/Chips.stories.mdx, docs/components/Chips/Web.stories.tsx, packages/components/src/Chip/Chip.css, packages/components/src/Chip/Chip.test.tsx, packages/components/src/Chip/Chip.tsx, packages/components/src/Chip/Chip.types.d.ts, packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx, packages/components/src/Chips/ChipsTypes.tsx, packages/components/src/Chips/InternalChip.css, packages/components/src/Chips/InternalChip.tsx, packages/components/src/Chips/InternalChipButton.tsx, packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx, packages/components/src/Chips/InternalChipMultiSelect.tsx, packages/components/src/Chips/InternalChipSingleSelect.tsx, packages/components/src/Chips/tests/InternalChip.test.tsx, packages/components/src/Tooltip/Tooltip.tsx
a fresh, new take on: https://github.com/GetJobber/atlantis/pull/1694
merging/rebasing was a headache with how much has changed since that PR was made. given it consists of 2 commits, I decided cherry picking them onto a fresh branch was the way to go.
Please refer to the original linked PR for details.
- 
- 
- 
- 
- 
- 
Changes can be
---
=> feat(components): Separate Chip from Chips Again

docs/components/Chips/Chips.stories.mdx, docs/components/Chips/Web.stories.tsx, packages/components/src/Chip/Chip.css, packages/components/src/Chip/Chip.test.tsx, packages/components/src/Chip/Chip.tsx, packages/components/src/Chip/Chip.types.d.ts, packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx, packages/components/src/Chips/ChipsTypes.tsx, packages/components/src/Chips/InternalChip.css, packages/components/src/Chips/InternalChip.tsx, packages/components/src/Chips/InternalChipButton.tsx, packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissible.test.tsx, packages/components/src/Chips/InternalChipMultiSelect.tsx, packages/components/src/Chips/InternalChipSingleSelect.tsx, packages/components/src/Chips/tests/InternalChip.test.tsx, packages/components/src/Tooltip/Tooltip.tsx
Reverts GetJobber/atlantis#1995
=> revert: "feat(components): Separate Chip from Chips Again"

packages/components/src/Tooltip/Tooltip.css, packages/components/src/Tooltip/Tooltip.tsx
Based on feedback from the design team:
- reducing "visual weight" of Tooltip
- reducing noisiness of animations by
- removing scale transition
- adding a slight delay to only fire Tooltips on items the user truly rests on, not simply mouses over in passing
- size (padding) and fontweight of Tooltip
- animation of Tooltip
In Storybook:
- [Tooltip](https://tooltip-refinements.atlantis.pages.dev/?path=/story/components-overlays-tooltip-web--basic)
- [DataList row actions](https://tooltip-refinements.atlantis.pages.dev/?path=/story/components-lists-and-tables-datalist-web--basic)
- [Avatar with Tooltip](https://tooltip-refinements.atlantis.pages.dev/?path=/story/components-images-and-icons-avatar-web--with-tooltip)
Changes can be
[tested via …
=> refactor(components): Tooltip refinements [JOB-99926]

packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
Missed a custom item when adding elevation to the custom DataList action menus
- elevation attribute to DataListItemActions
- appearance of the item actions in dark mode - now lighter than the application background, and when hovering the row, the menu is no longer darker than the hovered surface the menu sits on
- 
Changes can be
---
=> feat(components): add elevation to DataList item actions

scripts/commentOnPrAfterPreRelease.js
This reverts commit b48903fc66482a41d80949b0e150f857a174c81c.
Accidentally pushed to master, not sure what happened but this reverts it
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix: Revert "Adding trouebleshooting link to the failure comment"

packages/components/src/Autocomplete/Autocomplete.tsx
- To allow users to easily clear their input.
- Added `clearable` prop to `Autocomplete` component.
- 
- 
- 
- 
- 
Changes can be
---
=> feat(components): Clearable Autocomplete

docs/components/DataList/DataList.stories.mdx, package-lock.json, package.json, packages/components/src/Disclosure/Disclosure.tsx
The Storybook package version in `package.json` was listed as fixed (7.6.7). This meant that we didn't allow any minor version updates, as well as patch version updates, which often include security vulnerabilities/patches. The latter is actually exactly the case, since version `7.6.7` had `ws@6.2.2` package listed as a dependency, which in turn has a known [high risk vulnerability](https://github.com/advisories/GHSA-3h5v-q93c-6h6q).
```
├─┬ storybook@7.6.7
│ └─┬ @storybook/cli@7.6.7
│   ├─┬ @storybook/core-server@7.6.7
│   │ └── ws@8.16.0
│   └─┬ puppeteer-core@2.1.1
│     └── ws@6.2.2
```
In regards to above, here's the console output of `npm list ws` AFTER updating Storybook
```
├─┬ storybook@7.6.20
│ └─┬ @storybook/cli@7.6.20
│   ├─┬ @storybook/core-server@7.6.20
│   │ └── ws@8.18.0
│ …
```
=> feat(deps): Update storybook to the latest patch version (7.6.20)

docs/components/Card/Card.stories.mdx
We should reflect the latest guidance for the Card component after the functional changes introduced in #2054 
- Guidance on use of clickable cards
- some verbiage related to mobile-specific behaviour that is no longer relevant
View the docs [in Cloudflare](https://update-card-docs.atlantis.pages.dev/?path=/docs/components-layouts-and-structure-card--docs) or locally
Changes can be
---
=> docs(components): Update `Card` docs

packages/components/src/DataList/index.ts
`onClick` prop of `<DataList.ItemActions>` expects an event handler with a parameter of type `DataListObject` (or a type that extends it), but this type is not exported from the package and as a result JO have multiple instances of `DataListObject` defined in the codebase. 
- export `DataListObject` from `DataList`'s index file.
- 
- 
- 
- 
- 
Changes can be
---
=> refactor(components): export `DataListObject` type

packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.pom.tsx, packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx, packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx, packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.pom.tsx, packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
missed some dependency updates in the `useCallback` for handlers
then, missed some mock updates in tests
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix(components): Fix Combobox Dependencies and Test Mocks

docs/components/Disclosure/Web.stories.tsx
- 
- 
- 
- 
- Fixed code tab in controlled disclosure
- 
Verify code tab works for the controlled disclosure story
Changes can be
---
=> docs: Fix disclosure code tab 

docs/README.md
Updated links to documentation
- 
- 
- 
- 
- links in README.md to storybook docs
- 
Changes can be
---
=> docs: Update links in README.md

packages/components-native/src/ProgressBar/ProgressBar.size.style.ts, packages/components-native/src/ProgressBar/ProgressBar.style.ts, packages/components-native/src/ProgressBar/ProgressBar.tsx, packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap, packages/components-native/src/ProgressBar/types.ts
- To allow for a smaller size as we do with the progress bar for web.
- Size prop on `ProgressBar`.
| Small | Base (default) |
| ----- | ----- |
| <img width="326" alt="image" src="https://github.com/user-attachments/assets/21657410-1d44-46bb-8f86-505f9bdf9a97"> | <img width="326" alt="image" src="https://github.com/user-attachments/assets/dc12737b-9165-4839-b3df-0492530bbffb"> |
- 
- 
- 
- 
- 
Changes can be
---
=> feat(components-native): Add size variation for progress bar

packages/site/src/components/CodeViewer.tsx, packages/site/src/layout/code-theme.css, packages/site/src/main.css
Make code sandbox "light mode" and introduce a thin abstraction layer so we can easily allow for swapping in light and dark modes
- 
- 
- 
- 
- 
- 
Changes can be
---
=> feat(docx): Update code sandbox styling

packages/design/src/tokens/dark.tokens.json, packages/design/src/tokens/darkElevated.tokens.json, packages/design/src/tokens/semanticColor.tokens.json, packages/design/src/tokens/workflow.tokens.json
This is an enabler so we can use semantic descriptions in docs
- 
- 
- 
- 
- 
- 
Changes can be
---
=> chore(design): Added descriptions to semantic tokens JSON files

docs/design/Borders.stories.mdx
- Added values for the border width for easy understanding
- 
- 
- 
- 
- 
Changes can be
---
=> docs(design): Adding values for the border

docs/components/Banner/Banner.stories.mdx
The "success" Banner uses the same example content as the "warning" Banner - this is confusing for consumers
- content in "Success" banner example
Take a look at [the docs](https://chris-at-jobber-patch-1.atlantis.pages.dev/?path=/docs/components-status-and-feedback-banner--docs)
---
=> docs(components): Update success Banner example

docs/components/ButtonDismiss/ButtonDismiss.stories.mdx
The ButtonDismiss docs were a bit sparse and kind of incorrect
- ButtonDismiss docs content
Read the docs!
---
=> docs(components): add more detail to buttondismiss

packages/site/src/layout/NavMenu.tsx, packages/site/src/pages/ComponentsChangelogPage.tsx, packages/site/src/pages/ComponentsNativeChangelogPage.tsx, packages/site/src/pages/DesignChangelogPage.tsx, packages/site/src/routes.tsx
New Changelog Disclosure in side nav with linked Changelogs for Components, Components Native and Design
Open the Changelog Disclosure and then click each changelog
Changes can be
---
=> docs: Add Changelogs to new docs site

docs/design/Colors.stories.mdx, packages/design/src/tokens/dark.tokens.json, packages/design/src/tokens/semanticColor.tokens.json
- UI components that use `surface--background` have poor contrast on some surfaces
- `color-surface--element` semantic token
- 
- 
- 
- 
Changes can be
---
=> refactor(design): Add --color-surface--element semantic token

packages/site/src/components/VisibleWhenFocused.module.css, packages/site/src/components/VisibleWhenFocused.tsx, packages/site/src/layout/Layout.tsx, packages/site/src/layout/NavMenu.tsx
Adds a button that allows users to skip to the main page content as demonstrated in this video:
https://github.com/user-attachments/assets/be0eea60-3f86-41b6-85ee-e6d2f70a3554
Tab/reverse tab around the page to ensure everything is working as expected
Changes can be
---
=> docs: Add option to skip to content [JOB-111012]

packages/design/README.md
The design package is called design, and while it ships something called foundation.css and has "foundational" elements to it, it's confusing that the README leads with the name "Foundation"
- h1 in README to match directory/package name
Run docs site locally, view in [the build](https://update-name-of-design-packag.atlantis.pages.dev/packages/design), or just go into the README in your IDE
---
=> chore(design): change name in README

docs/guides/customizing-components.stories.mdx
Break up customization docs for greater readability and (hopefully) clarity
- re-write the doc with an emphasis on reducing duplicate content and highlighting use cases for each method
Run site locally or in CF
---
=> docs: component customization

.circleci/config.yml, packages/generators/index.mjs, packages/generators/package.json
Continuing fixes in https://github.com/GetJobber/atlantis/pull/2335 for the generators package
- 
- build: Added way to bypass check manual release by committing `chore(release): Manual release...`
- build: Updated check manual release to not block remaining jobs for faster CI
- 
- 
- 
- 
Changes can be
---
=> chore: Re-add check manual release

package-lock.json, packages/components-native/package.json, packages/components/package.json, packages/formatters/package.json, packages/hooks/package.json
In the [rebuild](https://github.com/GetJobber/atlantis/pull/1965/files) of the design packages the design package was removed from the dependencies of components. While this is likely correct it should still be a peer Dependency so this PR adds that back
- 
- Make `@jobber/design` a peer dependency of `@jobber/components` and `@jobber/components-native`
- 
- 
- 
- 
Changes can be
---
=> build: Make Design peer depencency of components

packages/site/src/content/LightBox/LightBoxNotes.mdx
There was a note about testing implementations of Lightbox that was missing after it was updated. This PR adds the note that was missing
- Added docs related to testing lightbox
- 
- 
- 
- 
- 
Changes can be
---
=> docs: Added note about testing lightbox

packages/site/src/layout/TopNav.tsx
Based on the UX Foundations Slack channel conversation, we still want to keep minimal mode for the extension even though the top nav is responsive for small viewport already. There are some things that need to be hidden in minimal mode:
- Menu button
- Logo
- Search button
- Menu button, logo, and the search button are hidden in minimal mode
- Ask AI button is aligned right in desktop viewport in minimal mode (similar to how it sits currently in mobile viewport)
- In non-minimal mode, everything should behave the same as it currently does.
- 
- 
- 
- 
- 
- 
Changes can be
---
[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request …
=> fix(docx): Hide menu button, logo, and search in minimal mode

packages/components/src/Cluster/index.ts, packages/components/src/ContentBlock/index.ts, packages/components/src/Cover/index.ts, packages/components/src/ResponsiveSwitcher/index.ts, packages/components/src/SideKick/index.ts, packages/components/src/Stack/index.ts, packages/components/src/Tiles/index.ts
The component props for new layout components should be exported.
- Expose component props for `Cluster`, `ContentBlock`, `Cover`, `ResponsiveSwitcher`, `SideKick`, `Stack`, `Tiles`
- 
- 
- 
- 
- 
- Test you can `import { ClusterProps } from "@jobber/components/Cluster"` and vice versa
Changes can be
---
=> refactor(components): Export layout components props

packages/components/src/FormatFile/FormatFile.module.css, packages/components/src/InputFile/InputFile.module.css
When focused, FormatFile's focus indicator did not respect the rounded shape of the element.
- Radius of focus state follows the radius of the element being focused
Locally, Cloudflare, in-product via pre-release if needed
- Notes and Quotes can be testing surfaces in-product
Changes can be
---
=> fix(components): add radius to focus states of FormatFile

docs/components/RecurringSelect/RecurringSelect.stories.mdx, docs/components/RecurringSelect/Web.stories.tsx, packages/site/src/componentList.ts, packages/site/src/componentSections.ts
we've deprecated the component at the code level, our docs should reflect that too.
- 
moved the RecurringSelect components to be within a "Deprecated" sections of our docs site and storybook (old docs site)
RecurringSelect
- 
- 
- 
Changes can be
---
=> docs(components): Move RecurringSelect Docs to Deprecated Section

packages/components/src/InputFile/FileTypes.ts, packages/components/src/InputFile/InputFile.test.tsx
Looking to extend functionality for the secure documents upload. Success will be using it so SP's can send us their client/products & services, etc lists as CSV and XSLX formats only. 
Added `csv` and `xlsx` to the `FileType` enum
- 
- 
- 
- 
- 
Changes can be
---
=> feat(components): Update FileTypes enum

packages/components/src/DataList/index.ts
- 
- 
- 
- 
- export `DataListHeader` type along with its other types
- 
Changes can be
---
=> fix(components): export DataListHeader type

packages/components/src/Autocomplete/useAutocomplete.ts
we were importing hooks the incorrect way due to how our hooks package is configured, causing issues in certain projects. we should import the right way for now until we fix things.
- 
- 
- 
- 
- 
- 
Changes can be
---
=> fix(components): Import Hooks Correctly for Autocompletev2

packages/components/src/Modal/Modal.rebuilt.module.css
after a recent reorganization, I missed the zindex on the overlay, we need that to ensure proper layering.
- 
- 
- 
- 
brought back the zindex
- 
Changes can be
---
=> fix(components): Give Modal Rebuilt Proper Elevation
