GetJobber/atlantis

- packages/components/src/Tabs/Tabs.test.tsx
- packages/components/src/Tabs/Tabs.tsx
- packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
- 
- 
- 
- 
- `Tabs` component now properly accepts things other than strings.
- 
---
> tabs-should-accept-elements

- packages/components/package-lock.json
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
The PR ads a button type to the button component so it does submit all the time.
> Make-the-button-be-a-type-button

- packages/components/package-lock.json
- packages/components/src/InputTime/InputTime.test.tsx
- packages/components/src/InputTime/civilTimeConversions.tsx
Apparently typing in an input field is actually important. ;)
- 
- 
- 
- 
- Typing in the InputTime in chrome now allows you to input 2 digit times.
- 
---
> Fix the ol' input time on chrome.

- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InputText/InputText.test.tsx
- Adjust CSS for pixel perfect alignment of form fields and also match sg1
- Ad BG to textarea mini label to prevent this ⏬  from happening
it now looks like this ⏬ 
- 
- 
- 
- 
- 
- 
---
> Consistently consistent for field design from sg1 to atlantis

- packages/components/src/FormField/FormField.css
- Add `vertical-align: -moz-middle-with-baseline;` to fix firefox BS
- 
- 
- 
- 
- 
- 
---
> fix: firefix the firefox with align middle baseline

- packages/components/src/FormField/FormField.css
- 
- 
- 
- 
- Hide clear button on `InputTime` in chrome.
- 
---
> fix: Hide clear in chrome

- packages/components/src/FormField/FormField.css
- Better handle on the padding for small and large fields
- Reset z-index for fields to prevent unexpected outcome when importing to jobber
- 
- 
- 
- 
- 
- 
---
> fix: Adjust small and large form fields

- packages/components/src/Content/Content.mdx
- packages/components/src/Content/Content.test.tsx
- packages/components/src/Content/Content.tsx
- packages/components/src/Content/Paddings.css
- packages/components/src/Content/Paddings.css.d.ts
- packages/components/src/Content/Spacing.css
- packages/components/src/Content/Spacing.css.d.ts
- packages/components/src/Content/index.ts
✔️  Break up Content component on its own PR without default padding (This PR)
🚧  Use content component PR's on affected components like card and modal (Jobber online change)
🚧  Do the rest of the change on this PR #115 so once it's out, everything still looks the same. With some minor caveat that the tab would have a larger vertical spacing above it
- Adds in `Content` component that handles vertical spacing on components. [Click here to view](https://deploy-preview-116--jobber-atlantis.netlify.com/components/content)
---
> feat: Contentize the content. A.K.A add new content component

- packages/components/scripts/entryPoints.ts
- 
- 
- 
- 
- Entrypoints no longer need to be transpiled.
- 
---
> fix: Make entrypoints compatible with commonjs

- README.md
- package.json
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/DescriptionList/DescriptionList.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InlineLabel/InlineLabel.tsx
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputTime/InputTime.tsx
- packages/components/src/InputTime/InputTimeSafari.tsx
- packages/components/src/InputValidation/InputValidation.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Switch/Switch.tsx
- packages/components/src/Tabs/Tabs.tsx
- packages/eslint-config/.eslintrc.js
- packages/eslint-config/README.md
- packages/eslint-config/package-lock.json
- packages/eslint-config/package.json
- Improved import order specification.
- Improved prerelease flow.
- 
- 
- 
- Use `eslint-import-resolver-typescript` to resolve typescript code.
- 
---
> feat: Add eslint import resolver typescript

- packages/components/src/FeatureSwitch/FeatureSwitch.test.tsx
- packages/components/src/FeatureSwitch/FeatureSwitch.tsx
- packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
- Allow markdown on feature switch description
- 
- 
- 
- 
- 
---
> fix: Make feature switch description support markdown

- packages/eslint-config/.eslintrc.js
- 
- 
- 
- 
- `jest/no-jasmine-globals` should have been enabled here.
- 
---
> fix: enable `jest/no-jasmine-globals`

- packages/components/src/FormatTime/FormatTime.tsx
- Feed `FormatTime` the current year, month, and day to prevent leap seconds from messing with it
- 
- 
- 
- 
- 
- 
---
> fix: when the time leaps; the safari changes

- packages/components/src/FeatureSwitch/FeatureSwitch.css
- packages/components/src/FeatureSwitch/FeatureSwitch.mdx
- packages/components/src/FeatureSwitch/FeatureSwitch.tsx
- Use `useEffect` to catch when the component mounts so `saved` indicator doesn't show on mount
- Use `useEffect` to determine when should `saved` indicator show up
- 
- 
- 
- 
- 
- 
---
> fix(components): Make feature switch save indicator show up when `enabled` changes

- CONTRIBUTING.md
- doczrc.js
The contributing section works 👍 
Added the CONTRIBUTING.md to the doczrc.js so it can be recognized and give the file a proper route so it can be linked to. The contributing section was also added to the side nav
Run the repo locally and notice the contributing section actually links. 
---
> docs: link the contributing section correctly

- README.md
- packages/components/src/FormatTime/FormatTime.tsx
- a line to the read me specifying what version of npm is needed
- 
- 
- 
- Changed the way use24HourClock was used. It should more accurately hold its value now. 
- Had to manually add the locale to the "toLocaleTimeString" function
- 
---
> fix(components): The time formatter actually works for GB now and README changes

- packages/components/src/InputTime/InputTime.mdx
Meridiam (sic) was unclear about what it referred to. Period is not great either, but adding AM/PM helps.
---
> docs: Change meridiam to period (am/pm)

- packages/components/src/Select/Select.mdx
Natasha was inside of labels and that was making her not show up in example lists.
---
> docs: makes Natasha visible in lists -- patch release

- packages/components/src/Modal/Modal.test.tsx
- packages/components/src/Modal/Modal.tsx
- Modal: `title` is now an optional prop, and will now hide the Header if the title is not provided 
- 
- 
- 
- 
- 
---
> feat: modal title becomes optional and hides header if undefined

- packages/components/src/InputText/InputText.mdx
- Updated documentation to use age instead of value for the examples on the input text component.
- 
-  Updated documentation to use age instead of value for the examples on the input text component.
- 
- 
- 
- 
---
> docs: Updated input text example to use age and setAge

- packages/components/src/Modal/Modal.mdx
The `Modal` examples previously used generic variable names (`value`) for controlling the toggle state. Improved those and also made most show/hide calls more explicit to keep things explicit.
---
> docs: clarifies the variable names used in `Modal` examples

- packages/components/src/Card/Card.css
- 
- 
- 
- 
- Removed `overflow: auto;` from Card component so that the card can't scroll
- 
---
> fix(components): Don't allow Card component to scroll

- packages/components/src/Text/Text.mdx
- 
- 
- 
- 
- In the Text Component docs, the example at the bottom used `warning` variation but the component expects `warn`. Updated this to be correct and actually highlight in yellow now
- 
---
> docs: update variation on text component example to match component

- plop/templates/component/{{name}}.test.tsx
- plop/templates/component/{{name}}.tsx
- 
- 
- 
- 
- Adapt the plop template so that the sample test file passes CI.
- 
---
> fix: generated plop code now passes tests

- packages/components/package-lock.json
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/design/package-lock.json
- packages/eslint-config/package-lock.json
- packages/stylelint-config/package-lock.json
- Added a debounce import from lodash
- Changed `setOptions` to be wrapped in debounce.
- Debounced method for fetching results
- How setOption works
---
> feat(components): Adding debounce functionality for the Autocomplete component

- packages/components/src/Autocomplete/Autocomplete.tsx
- 
- 
- 
- 
- Loading autocomplete component in Jobber clobbers underscore.
Doing `import { debounce } from "lodash";` seems to always load all of lodash regardless of if you're only using part of it or not. Even though TypeScript seems to complain about `import debounce from "lodash/debounce" it seems to be the right way to load it to only get the functions you need.
Executing all of `lodash` was causing problems on production because a side-effect of loading `lodash` is that it will put itself on window as `_`. But we're already using `underscore` in Jobber, so this then clobbers the existing underscore instance.
Mostly this was fine until we hit some code that executes a function that existins in `underscore`, but doesn't exist in lodash.
- 
---
[In Atlantis we use Github's built in …
> fix(components): Changing the way we load `debounce` to avoid loading all of lodash.

- .github/semantic.yml
- packages/formatters/tsconfig.json
- 
- 
- 
- 
- Fix module export pattern for Formatters.
- 
---
> fix: Move `formatters` to CommonJS

- packages/components/src/Typography/css/Typography.css
- 
- 
- 
- 
- This is a fix to prevent fonts from being loaded twice 
https://jobber.atlassian.net/secure/RapidBoard.jspa?rapidView=55&modal=detail&selectedIssue=JOB-16638
- 
---
> fix: Stop font from being loaded twice

- packages/components/src/Tabs/Tabs.mdx
- packages/components/src/Tabs/Tabs.test.tsx
- packages/components/src/Tabs/Tabs.tsx
Allows tabs to have an `onClick` function when changing tabs.
- `onClick` prop to `InternalTab`
- Runs new `onClick` function along side the `activateTab` function
- Moves `activateTab` function from the `onClick` prop to its on prop on `InternalTab`
---
> feat(components): add onClick function to tabs

- doczrc.js
- packages/components/rollup.config.js
Allow CSS to be better inspected.
https://github.com/webpack-contrib/css-loader#object
https://github.com/webpack/loader-utils#interpolatename
- 
- 
- 
- 
- Classnames will be human readable when inspecting elements in Docz now.
- 
---
> fix: Show component class names when viewing docs.

- .vscode/settings.json
Modernize our `eslint` settings for current VSCode. 
See https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint for preference settings.
- 
- VSCode preference for running `eslint` has changed, so this updates us to what is currently standard.
- 
- 
- 
- 
---
> fix(eslint): update eslint setting in VSCode preferences to current standard

- packages/components/src/Button/Button.css
This zeros out the margin for the `Button` component so that Browser defaults (like Safari's) don't get used.
- 
- For more consistent support across browsers, we're explicitly zeroing out the margin on `Button`. Safari was adding some padding by default, but NO WAY Safari.
- 
- 
- 
- 
1. Load the Atlantis docs viewer for the `Button` component.
2. Using the browser tools, inspect the rendered value for the margin of the Buttons. Confirm it is zero.
3. Visually inspect the three loading buttons in the example to make sure they have no margin between them: `/components/button#loading`
Tested in:
---
> fix(components): buttons set zero margin explicitly

- lerna.json
- 
- 
- 
- 
- Publish commits do not need to trigger CI.
- 
https://circleci.com/docs/2.0/triggers/#skip-builds
https://github.com/lerna/lerna/tree/master/commands/version#--message-msg
---
> fix: Skip CI on Publish Commits

- packages/components/src/Button/Button.css
This sets the "ghost" and secondary buttons to have a white background color instead of being transparent. This should display more clearly under a variety of different backgrounds/conditions.
---
Examples of wrapping the button with a `<div>` that has a red background (see testing section below).
---
- 
- "cancel", "secondary" and "tertiary" types of buttons now have a white background (i.e. button fill) color.
- 
- 
- 
- 
View the Button component Docz page.
Wrap the following around each of the button examples to confirm expected behavior
`<div style={{"background-color": "red", padding: "10px"}}>`
---
> fix(components): set button bg color for tertiary buttons to white, not transparent

- .circleci/config.yml
- packages/components/CHANGELOG.md
- 
- Back to automatic releases now that the release loop is broken.
- 
- 
- 
- 
---
> chore: Back to automatic releases

- packages/components/src/Table/Table.mdx
- packages/components/src/Typography/Typography.mdx
- 
- 
- 
- 
- These Readmes had the wrong module name in them. Now they don't.
- 
---
> fix(components): Readme `import` Typos

- .circleci/config.yml
- lerna.json
- 
- 
- 
- 
- Circle reports skipped builds as failed. These changes allow us to avoid Circle's built in skipping mechanisms.
- 
The script logic is testable by making a little file containing the following, running it with commit messages.
```sh
if git log --max-count=1 --pretty=%s | grep -q "A COMMIT TO LOOK FOR"; then
echo "Skiping run on release commit."
else
echo "do release"
fi
```
Also, confirm that `echo $?` is `0` regardless.
https://discuss.circleci.com/t/status-badges-for-skipped-builds-show-as-failed/30182
---
> fix: CircleCI badge mis-reporting.

- packages/components/src/Tabs/Tabs.mdx
`a tabs` should just be `tabs`
Deleted `a `
n/a
n/a
n/a
n/a
n/a
n/a
Go to the docs
---
> fix(components): fix typo in Tabs documentation — Patch Release

- .github/pull_request_template.md
- docs/proposals/TEMPLATE.md
- Add `Responsive` section to the component proposal.
- Reordered the component proposal to bring accessibility and responsiveness earlier in the process.
- Clarified PR template.
- 
- 
- 
- 
---
> docs: Add responsive section 2 component proposal

- packages/components/src/FormatDate/FormatDate.mdx
- packages/components/src/FormatDate/FormatDate.test.tsx
- packages/components/src/FormatDate/FormatDate.tsx
- packages/components/src/FormatDate/index.ts
We need to format dates in Atlantis. Currently, only date format supported is:
MMM d, yyyy
ex. Feb 26, 2020
- FormatDate Component
- 
- 
- 
- 
- 
---
> feat(components): Add FormatDate component

- docs/getting-started-with-react/getGIF.ts
The Gif Gift example wouldn't return any search results due to mixed mode content.
- 
- 
- 
- 
- Fixed example in React Guide so that it now returns results on https schemes
- 
---
> docs: Remove scheme from search URL

- packages/components/src/List/ListItem.tsx
We currently mostly use numeric IDs for objects in the Jobber database. We do have some objects that have UUIDs. There's also external objects (like the ones from Stripe) that have unique string ids. I wanted to add support of string IDs to this component
- The `ListItem` id can now be a string or number. Previously it was only number.
- 
- 
- 
- 
- 
---
> feat(components): ListItem can have string as id

- packages/design/src/Elevations.mdx
After the docz upgrade, the `Design` > `Elevation` was no longer working. This was due to React Fragment shorthand not being available in the `.mdx` file.
- 
- Replaces fragment with `<React.Fragment>`
- 
- 
- 
- 
---
> chore: Upgrade docz - Elevation 

- packages/components/src/Select/Option.tsx
After the upgrade the props for the `Option` component were not showing due to the way that docz renders props.
- Changes the name of the component from `Option` to `SelectOption`
- Exports `SelectOption` as `Option`
- 
- 
- 
- 
- 
- 
---
> chore: Upgrade Docz - Allows the option props to render on the page

- src/gatsby-theme-docz/components/Header/index.js
- src/gatsby-theme-docz/components/Header/styles.js
- src/gatsby-theme-docz/components/HeaderButtons/index.js
- src/gatsby-theme-docz/components/HeaderButtons/styles.js
- src/gatsby-theme-docz/components/Sidebar/index.js
- src/gatsby-theme-docz/components/Sidebar/styles.js
Docz viewer currently has no way to view the menu on tablet/mobile.
This will add a mobile menu along with a button to toggle
Adds a button to toggle the mobile menu when on a tablet or mobile size screen.
- Mobile menu button
- So logic to the `HeaderButtons` component
- Moved `HeaderButtons` from `Header` to `Sidebar`
- 
- Header component markup
- Header component styling
- 
- 
---
> chore: Fixes the mobile menu on docz viewer

- package-lock.json
- packages/components/src/FormatEmail/FormatEmail.css
- packages/components/src/FormatEmail/FormatEmail.css.d.ts
- packages/components/src/FormatEmail/FormatEmail.mdx
- packages/components/src/FormatEmail/FormatEmail.test.tsx
- packages/components/src/FormatEmail/FormatEmail.tsx
- packages/components/src/FormatEmail/__snapshots__/FormatEmail.test.tsx.snap
- packages/components/src/FormatEmail/index.ts
We would like a way to make sure that we are formatting email addresses the same way throughout Jobber. `<FormatEmail />` will take an email address and return a formatted email address.
- Adds new FormatEmail component
- FormatEmail component
---
> feat(components): Adds FormatEmail component

- package-lock.json
- package.json
- packages/eslint-config/package-lock.json
- packages/eslint-config/package.json
We want to keep typescript up to date and take advantages of the new things available. 
- Update typescript to 3.8.3
- 
- 
- 
- 
- 
- 
---
> chore(deps): Update typescript to 3.8.3

- docs/proposals/BANNER_MODS.md
This proposes a few tweaks to the current props for the `<Banner>` component to support the new Manage Team vertical slice, and to become consistent with new work from Josh on site wide banners. (See https://www.figma.com/file/AZFSe2T7FID7d5DP52NTkX/Design-System-Contribution-%5B-Account-Banner-%5D?node-id=26%3A1)
- 
- 
- 
- 
- 
- 
---
> docs: propose new banner mods

- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/FeatureSwitch/FeatureSwitch.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InputText/InputText.tsx
- packages/components/src/InputTime/time-input-polyfill.d.ts
- packages/components/src/Tooltip/Tooltip.tsx
We recently updated typescript in Atlantis, however missed updating it in the components package. This PR updates typescript in components.
While updating typescript we found a few type bugs in components that caused `npm ci` to fail. These bugs have also been resolved in this PR to allow `npm ci` to finish running.
- Update typescript
- Update framer-motion
- Type declaration on InputText and FormField
---
> chore(deps): Update typescript in components

- packages/components/src/Tooltip/Tooltip.mdx
Make it easier to know when and why to use tooltips
There are design & usage guidelines now
There are design & usage guidelines now
tweaked intro copy
> docs(components): Add design and usage guidelines to tooltip

- packages/components/src/Switch/Switch.mdx
Improve Switch design docs, especially since Radio Button is likely on the near horizon and the usage guidelines provide some disambiguation.
Adding design guidelines, tweaking some others.
Design guidelines
Content around Controlled and Disabled variants
> docs(components): Update Switch design docs

- packages/components/src/ProgressBar/ProgressBar.css
- packages/components/src/ProgressBar/ProgressBar.test.tsx
- packages/components/src/ProgressBar/ProgressBar.tsx
- packages/components/src/ProgressBar/Sizes.css
- packages/components/src/ProgressBar/Sizes.css.d.ts
- packages/components/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
The progress bar was only one size that was too large when using it in smaller spaces. 
ProgressBar can have a small size, which is half the size of the default ProgressBar. 
- 
- 
- 
- 
- 
---
> feat(components): ProgressBar can have a size

- package-lock.json
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/index.ts
- packages/components/src/Page/Page.css
- packages/components/src/Page/Page.css.d.ts
- packages/components/src/Page/Page.mdx
- packages/components/src/Page/Page.test.tsx
- packages/components/src/Page/Page.tsx
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
- packages/formatters/package-lock.json
This adds primary and secondary action buttons and a menu as optional parts of the `<Page>` component. This will render them in the standard action button and action menu way. 
- This uses `ButtonProps` for flexibility and consistency across other places in the library.
- The CSS and markup are contained in the Page for now. In future work, we can bring it out into an ActionBar component.
- `<Page>` can now take a `primaryAction` (`ButtonProps` type), `secondaryAction`  (`ButtonProps` type) and an `actionMenu` prop (`SectionProps[]` type).
- 
- 
- 
- 
- 
---
> feat(components): add action buttons to Page component 

- packages/components/src/Checkbox/Checkbox.mdx
As we add more interface controls to Atlantis, it's increasingly important to distinguish proper usage between conceptually similar components.
Tweaked the docs - moved the initial disambiguation to the design & usage guidelines, used similar disambiguation as switch.
[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-reviews) - Go to ["Files changed"](https://github.com/GetJobber/atlantis/pull/254/files) and hit the "Review" button on the right to review or approve ❤️
> docs(components): update checkbox docs

- doczrc.js
- package.json
- packages/formatters/package-lock.json
- packages/formatters/package.json
When you are working in Atlantis and save a `css` file, we would like the types to generate. This used to happen, and then all of the sudden it didn't anymore. 
This PR makes that happen again!
It also contains an idea to build the types on `npm start`. The idea behind this is that you get your css types built when you start Atlantis.
- Adds prestart command to package.json
- 
- 
- 
- Builds css types on save
- 
- `npm start`, see that types are generated.
- add a new css class to a css file and save it. See that the type is added to the `.css.d.ts` file\\
---
> fix: Build css types on save

- package-lock.json
- package.json
- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/Button/Button.css
- packages/components/src/Button/Button.mdx
- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
In an SPA we need are able to do client side routing. We want to be able to use the `Button` component as a link for our router.
This PR adds a `to` prop that will allow the `Button` component be used as a `Link` component for `react-router`.
- `to` prop to Button
- Capability to use Button in client side routing
- 
- 
- 
- 
- 
---
> feat(components): Add routing Link to Button

- CONTRIBUTING.md
<!--
Atlantis uses Conventional Commits to track versions.
Pull request titles should follow the following format.
The "proposal template" link in our contribution guidelines redirects to the "home" page in Atlantis, instead of the template in Github.
- URL from atlantis internal to Github
> fix(generators): correct proposal template URL

- packages/components/src/Page/index.ts
We exported PageProps, but forgot to export PageProps from index.
- Export `PageProps` from index of `Page` component
- 
- 
- 
- 
- 
---
> fix(components): Export Page Props from index

- packages/components/src/Avatar/Avatar.tsx
- packages/components/src/Avatar/index.ts
When using an Avatar in Jobber, we require the Avatar props for typing
Exports the `AvatarProps` type from Avatar.
- Export `AvatarProps` type from Avatar.
- 
- 
- 
- 
- 
---
> feat(components): Export AvatarProps from avatar

- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/index.ts
I would like to use a `Menu` in Jobber, but first I need the `ActionProps` so that the types are not bonkers
- Export `ActionProps` from `Menu`
- Export `ActionProps` from `Menu`
- 
- 
- 
- 
- 
---
> feat(components): Export ActionProps from menu

- packages/components/src/Tooltip/Tooltip.mdx
Wanted to note the accessibility issue somewhere so we don't forget
- Added a `Deficiencies` > `Accessibility` section to Tooltip with a note.
- 
- 
- 
- 
- 
---
> docs(components): Added a note on an accessibility problem on the Tooltip component

- packages/components/src/Table/Cells/Cell.css
- packages/components/src/Table/Table.css
- packages/components/src/Table/Table.mdx
We should bake in common presentation elements to the `table` component so the teams implementing don't need to resolve styling every time
- Border to the tables
- Padding on cells
> feat(components): Adjust table styling

- packages/components/src/Card/Card.mdx
You should only have a single h1 per page
Bump usage down to h2, bump its' children down to h3
> docs(components): fix card page hierarchy

- packages/components/src/Heading/Heading.mdx
Move the guidelines for each heading inside of Design & Usage section
Swapped order of design & usage / props, moved individual headings under d&u
> docs(components): Update Heading docs

- packages/components/src/InputGroup/InputGroup.mdx
The description offers pretty solid directions on usage, just wanted to clean up some grammar.
Copy in description
> docs(components): tweak wording on inputGroup description

- packages/components/src/Page/Page.mdx
- packages/hooks/src/useResizeObserver.ts
UseResizeObserver isnt working in older browsers. This will polyfill it so that it works in older browsers
- 
- ResizeObserver to polyfilled version
- 
- 
- `useResiszeObserver` hook causing issues in older browsers
- 
---
> fix(hooks): Uses the polyfilled version of resizeObserver

- packages/components/package-lock.json
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.mdx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
- packages/components/src/FormatRelativeDateTime/index.ts
We needed a way to display date times in a relate manor. E.g. 4 minutes ago, 1 year ago
- FormatRelativeDateTime
-none
- none
- none
- none
- none
Use the new component
---
> feat(components): add FormatRelativeDateTime

- doczrc.js
- packages/components/src/Page/Page.css
- packages/components/src/Page/Page.test.tsx
- packages/components/src/Page/Page.tsx
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
- packages/hooks/src/useResizeObserver.mdx
- packages/hooks/src/useResizeObserver.ts
- src/gatsby-theme-docz/components/Playground/index.js
- src/gatsby-theme-docz/components/Playground/styles.js
- src/gatsby-theme-docz/components/Sidebar/styles.js
We wanted a better way to use `useResizeObserver` that would allow for some default comparisons, as well as allow the component to set its own breakpoints.
`useResizeObserver` will now return the breakpoint size as well as exact size of the component.
- Custom breakpoints to `useResizeObserver`
- 
- 
- 
- 
- 
---
> feat(hooks): useResizeObserver custom sizes

- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
Add React fragments to the `FormatRelativeDateTime` component
- 
- 
- 
- 
- Add React fragments to the `FormatRelativeDateTime` component
- 
---
> fix(components): Add fragments to FormatRelativeDateTime

- packages/components/src/InputText/InputText.mdx
- packages/components/src/InputText/InputText.tsx
- Need to set focus to InputText on demand.
- InputTextRef now provide access to `focus`
- Added sample code to playground.
---
> feat(components): expose focus method in InputText — (Minor) Feature Release

- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.mdx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
Spec did not want seconds when showing just the time. I missed that.
- none
- When showing just the time, now shows hours and minutes. No seconds. Eg. "9:45 AM"
- none
- none
- none
- none
Display a time less than day ago, but more than an hour ago.
---
> fix(components): removed seconds from time in FormatRelativeDateTime

- packages/design/src/icons/Icon.css
We want these variants of the invoice icon to have the same purple colour as the other invoice icons
`sendInvoice` and `paidInvoice` are now purple
- 
- 
- 
- 
- 
- 
---
> feat(design): Change system colour for sendInvoice and paidInvoice icons

- packages/components/src/Checkbox/Checkbox.mdx
- make more consistent with docs on Switch
- introduce clearer language around accessibility expectations for disabled elements
- more detail on `disabled` checkbox
> docs(components): Update disabled state docs on checkbox

- .gitignore
- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InputText/InputText.mdx
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputText/InputText.tsx
- packages/components/src/InputText/index.ts
We need to be able to have a textarea that would start as 1 line tall, and grow to a set amount, and then become scrollable if more room was needed beyond that set maximum. 
The current implementation almost allowed us to do this, however it wouldn't allow us to set a minimum number of rows.
Instead of just rows as a single number being passed into the InputText component, now we have the ability to pass in an associative array which has a min and max key, corresponding to the minimum and maximum number of rows that would like to be shown.
handleChange and calculateRows functions which actively monitor and calculates how many rows should be shown for a multiline text area **with** a set maximum and minimum number of rows.
The only change in existing functionality is the removal of the …
>   feat(components): InputText Automatic Resize

- packages/components/src/FormatDate/FormatDate.test.tsx
- packages/components/src/FormatDate/FormatDate.tsx
- packages/components/src/FormatDate/__snapshots__/FormatDate.test.tsx.snap
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.tsx
- packages/components/src/FormatTime/FormatTime.test.tsx
- packages/components/src/FormatTime/FormatTime.tsx
- packages/components/src/FormatTime/__snapshots__/FormatTime.test.tsx.snap
…Strings
- FormatDate now accepts `Date` objects  and ISO Strings
- FormatTime now accepts `Date` objects  and ISO Strings
- FormatRelativeDateTime now accepts `Date` objects  and ISO Strings
- 
- 
- 
- 
- 
---
> feat(components): Time and Date formatters now accept `Date` Objects and ISO Strings

- packages/components/src/FormField/FormField.css
…ight
CSS in main app was overriding this min-height, and therefore the multiline max and min row functionality was not working as expected. 
- 
- 
- 
- 
- Adds a min-height: auto to inputText with multiline
- 
---
> fix(components): prevent jobber from overriding min-height on InputText when it is a text area 

- packages/components/src/Button/Button.css
- packages/components/src/Button/Button.css.d.ts
- packages/components/src/Button/Button.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
Reduced left and right padding on icon button so that these buttons have a square shape rather than a slightly-wider-than-tall rectangular shape
- reduced left and right padding on `hasIcon` button that does not also have a label
> fix(components): update button padding on icon button

- packages/components/src/Toast/Toast.test.tsx
- packages/components/src/Toast/Toast.tsx
The `Toast` should default the variation prop, which means it should be optional. Success is also the most common type of `Toast` so that should be the default.
Makes the `variation` prop of toast optional and default to `success`
- 
- variation default is now `success`
- 
- 
- makes variation prop optional
- 
---
> fix(components): Make Toast variation optional

- packages/components/src/Autocomplete/Autocomplete.mdx
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
We forgot to remove the `heading` prop from one of the examples. This prop was scrapped during the dev process. We also forgot to disable browser autofill in the autocomplete component itself.
Browser autocomplete will be disabled in the autocomplete component.
Read the docs and make sure the browser autocomplete doesn't show up!
---
> fix(components): autocomplete: update documentation and disable browser autofill

- packages/components/src/Toast/Toast.mdx
- packages/components/src/Toast/Toast.test.tsx
- packages/components/src/Toast/Toast.tsx
Toast component was showing the wrong icon for the `info` variation. 
Makes Toast show the right icons
- 
- 
- 
- 
- Toast component shows the right icon for variations
- 
---
> fix(components): Toast show the right icon

- packages/components/src/RadioGroup/RadioGroup.test.tsx
- packages/components/src/RadioGroup/RadioGroup.tsx
- packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
When using multiple `RadioGroup` components on a page, there would be conflict if two of the `RadioOption` components had matching `value`s. 
This PR will add a `uuid` to the `id` of the `RadioOption` component.
Adds unique IDs to the `RadioOption` components.
- 
- 
- 
- 
- Add`uuid` to `RadioOption` ID.
- 
---
> fix(components): Adds unique ids to radio ids

- packages/components/src/RadioGroup/RadioGroup.css
- packages/components/src/RadioGroup/RadioGroup.css.d.ts
- packages/components/src/RadioGroup/RadioGroup.mdx
- packages/components/src/RadioGroup/RadioGroup.test.tsx
- packages/components/src/RadioGroup/RadioGroup.tsx
When using a `RadioGroup` component there may be options that you do not want the user to be able to select. This PR will allow for disabling `RadioOption`
Allows for disabling options in `RadioGroup`
- `disabled` prop to the `RadioOption` component
- adds focus styling to the `RadioOption` component
- 
- 
- 
- 
- 
---
> feat(components): Disable RadioOption component

- packages/components/src/Autocomplete/Menu.tsx
The visual hierarchy of the menu items of the autocomplete list is not clear, the idea is to make the description subdued to accomplish this.
- Added 'subdued' variation on the description text of menu items
---
> fix(components): autocomplete: use subdued text for description on menu items

- packages/components/src/Card/Card.css
The current card component has a minor visual issue with the accent. Because the accent and the standard card border are using the same border it creates a visual artifact where the accent angles into the standard border.
I tried exploring the below ideas:
The accent border angles into the side border (3x zoom image).
I'm using a `::before` pseudo selector to put the border on top of the card and have a clean straight line.
>  fix(components): fix a border issue on card accent

- packages/components/src/Autocomplete/Autocomplete.css
- packages/components/src/Autocomplete/Menu.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Autocomplete highlighting behaviour must be changed as highlighted option falls out of view when scrolling too far down or too far up
- When list item falls out of view on menu list, the list will scroll to keep that item in view
---
> feat(components): modify autocomplete to scroll list up and down

- packages/components/src/Form/Form.test.tsx
- packages/components/src/Form/Form.tsx
Allows the `<Form>` component to render as a `div` if no `onSubmit` was passed in.
- 
- Renders the `<Form>` component to as a `div` if no `onSubmit` was passed in.
- 
- 
- 
- 
---
> fix(components): Allow the form to not be a form but be a div instead

- packages/components/src/ConfirmationModal/ConfirmationModal.mdx
related components section to ConfirmationModal docs
- 
- 
- 
- 
- 
---
> docs(components): add related components section to ConfirmationModal

- packages/design/src/icons/Sizes.css
Small Icons were too small (14px)! Now they are just right! (16px)
- Small Icons now render as 16x16px (base-size) instead of 14x14px.
This needs to be visually tested in web and mobile, as this package is used by both.
---
> fix(design): embiggen the small Icons

- packages/components/src/Autocomplete/Autocomplete.mdx
- packages/components/src/Autocomplete/Autocomplete.test.tsx
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Autocomplete was incorrectly debouncing setOptions instead of getOptions
Adds a debounce to `getOptions` prop of the `AutoComplete` component
- debounce to `getOptions` prop of the `AutoComplete` component
- 
- 
- 
- debounce on getOptions
- 
---
> fix(components): Autocomplete debounce for getOptions

- packages/components/src/Autocomplete/Autocomplete.tsx
Solves issue https://github.com/GetJobber/atlantis/issues/379
Added options filtering to updateSearch function (not sure if it should also run on the initial array -- should it?)
Autocomplete.updateSearch
fixed typo in a comment
type in "Be" in filter at /components/autocomplete#section-headings of docz
> feat(components): Autocomplete now filters out headers with no options

- packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
- packages/components/src/Modal/Modal.test.tsx
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Improve component behaviour and contribute to hacktoberfest by providing a fix for https://github.com/GetJobber/atlantis/issues/385
- Fix focus on modal content on mount
- fixed React vulnerability by making conditional for `catchKeyboardEvent` hook part of the hook itself 
This follows the [Only Call Hooks on Top Level](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) rule as stated by the React docs.
- added unit test for checking focus on open modal
- manual test: open modal in playground (`yarn start` --> http://localhost:3333/components/modal) and press tab key
- Please don't forget to add "hacktoberfest" and / or "hacktoberfest-accepted" labels to this pull request to enable [verification](https://hacktoberfest.digitalocean.com/faq). Thank you :)
> fix(components): Make modal focus when opened

- packages/components/src/FormatDate/FormatDate.mdx
Add design guidelines to FormatDate
Making sure our design docs on components are up to date
- Added design & usage notes to clarify purpose of FormatDate and identify complementary components
> docs(components): update FormatDate design docs

- packages/components/src/Button/Button.mdx
Cleaning up the hierarchy of the button docs, which were created before our standard "design usage" section was introduced to the component generator template
Introduced a "design & usage" header, as well as a brief intro into the purpose of button types and levels
> docs(components): button docs hierarchy

- packages/components/src/InputPassword/InputPassword.mdx
Increase consistency across our components' design documentation.
- Design & Usage guidelines
> docs(components): add design docs to InputPassword

- packages/components/src/DescriptionList/DescriptionList.mdx
Moved and tweaked some text from design usage and guidelines to related components section
Added related components section to DescriptionList docs
- 
- 
- 
- 
- 
---
> docs(components): add related components section to DescriptionList

- packages/components/src/Button/Button.css
We discovered that if pulling Atlantis buttons with a URL (which render as `a` elements) into a product with existing styling for `a` elements, the hover and focus states may end up defined by the `a` element and not our `Button`.
Included specific `a` scope on :hover and :focus states.
> feat(components): guard against external anchor element styling

- packages/components/src/FeatureSwitch/FeatureSwitch.test.tsx
- packages/components/src/FeatureSwitch/FeatureSwitch.tsx
- packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
- Switch & description are now optional on FeatureSwitch.
- 
- 
- 
- 
- 
---
> feat(components): Make switch & description optional on FeatureSwitch

- packages/components/src/Autocomplete/Autocomplete.test.tsx
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
When the autocomplete is blurred with `!allowFreeForm` and does not match a result, the `onChange` was correctly being called with undefined, however the input value was not reflecting this change.
This left a confusing user experience as the data returned and the data showed was different.
Clears the `input` on `Autocomplete` if `!allowFreeForm` and input does not match a result on blur.
- 
- 
- 
- 
- Clears the `input` on `Autocomplete` if `!allowFreeForm` and input does not match a result on blur to that the data and visuals match
- 
- Navigation to `Autocomplete` page on preview.
- add `allowFreeForm={false}` to the first `Playground` example.
- type `Nos` into the input and see that there is one result.
- tab out, value in the input should be cleared
---
[In Atlantis we use Github's …
> fix(components): Sets AutoComplete to blank if no matches

- packages/components/src/InputAvatar/InputAvatar.test.tsx
- packages/components/src/InputAvatar/InputAvatar.tsx
- Add `onUploadComplete` to `InputAvatar` to allows callbacks to be provided for when the upload has completed.
- 
- 
- 
- 
- 
---
> feat(components): Add `onUploadComplete` to `InputAvatar`

- packages/components/src/Autocomplete/Autocomplete.test.tsx
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- Add `invalid` to `Autocomplete` to allow highlight field red to indicate an error.
- 
- 
- 
- 
- 
---
> feat(components): Add `invalid` to `Autocomplete`

- packages/components/src/Checkbox/Checkbox.css
- packages/components/src/RadioGroup/RadioGroup.css
- packages/components/src/RadioGroup/RadioGroup.css.d.ts
- packages/components/src/RadioGroup/RadioGroup.mdx
- packages/components/src/RadioGroup/RadioGroup.test.tsx
- packages/components/src/RadioGroup/RadioGroup.tsx
- packages/components/src/RadioGroup/RadioOption.tsx
- packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- packages/components/src/RadioGroup/index.ts
RadioGroup needs to be able to handle a description. The current use case does not allow that to be done very nicely. This PR adds a `label` and `description` prop to `RadioOption` that will allow for a nicer way to add labels and descriptions
- `label` prop to `RadioOption`
- `description` prop to `RadioOption`
- Additional styling to `RadioOption`
- 
- 
- 
- 
- 
---
> feat(components): Add label and description to RadioOption

- packages/components/src/Drawer/Drawer.css
This PR makes sure the content of the drawer fills the available horizontal space.
> fix(components): Make sure drawer content is full width

- packages/components/src/Drawer/Drawer.css
- packages/components/src/Drawer/DrawerGrid.module.css
This PR improved the appearance of the drawer on smaller screens by introducting a medium breakoint. It also fixes some layout issues with the drawerGrid component.
The drawer width is too large for screens between 640px and 1024px wide
Now the drawer is smaller for this screen size.
> feat(components): Reduce width of drawer for medium breakpoint

- docs/proposals/TEMPLATE.md
We noticed in the review process of component proposals that we couldn't figure out if a property was required or not. 
Added a `required` column to the prop table in the proposal template.
Added a `required` column to the prop table in the proposal template.
> feat: add required column to component proposal template

- packages/components/src/Banner/Banner.mdx
- packages/components/src/Banner/Banner.test.tsx
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- We do not want the banner reminding SP to setup 2FA phone number to be dismissible. Adding a prop to make non-dismissible banner available.
- dismissible prop in banner component.
- `dismissible` is true (default)
- `dismissible` is false
- Tested with playground in Atlantis.
---
> feat(components): Add dismissible prop to banner

- packages/components/src/InputNumber/InputNumber.mdx
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputNumber/InputNumber.tsx
- packages/components/src/InputNumber/index.ts
Allows focus and blur to be set on inputNumber
- InputNumberRef now provide access to focus and blur on InputNumber
- 
- 
- 
- 
- 
Added sample code to InputNumber playground
---
> feat(components): add inputNumberRef to inputNumber

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/Checkbox/Checkbox.css
- packages/components/src/Checkbox/Checkbox.mdx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/RadioGroup/RadioGroup.css
Our disabled states on similar UI controls are quite different!
- Uses the disabled "label" color, and same border/fills on the input itself
- Also created a stronger indicator of `selected` on radio options to distinguish a checked+disabled option from unchecked+disabled
This PR is a scoped-down version of what I initially set out to accomplish with [an earlier swing](https://github.com/GetJobber/atlantis/pull/434) that was just all kinds of problematic for the scope of problem this PR actually sets out to solve.
- changed colours on checkbox and radio
- Go to RadioGroup since there's a checkbox included there!
---
--- …
> fix(components): match colors on radio and checkbox labels and inputs

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/Heading/Heading.mdx
- packages/components/src/Heading/Heading.tsx
- packages/components/src/Typography/css/FontSizes.css
While working on [Page updates](https://github.com/GetJobber/atlantis/pull/422), I noticed that our line-heights on h1 (and h2) were quite large. This seems to be following the general principle of scaling the line-heights linearly with the font-size, however with large display typefaces you generally require _less_ line-height as you get into larger sizes, as the user 
a) is less likely to need to read 2+ lines of text
b) requires less space between those lines as the individual characters are larger and more distinguishable
After talking with @eddysims we decided I should do this work in a separate PR. This is that PR. Since I'm in here, I added an h6 to Atlantis because it feels like we should be accounting for a core semantic type element. Styling is based on Jobber's current …
> feat(components): adjust line-height on largest font sizes and add h6

- packages/components/src/RadioGroup/RadioGroup.css
At some point in the process of updating RadioGroup styling, the `[disabled]:checked` state got discarded 😞 . This fixes that and also adds the disabled state to the `.description` when a RadioOption is disabled.
- Use `grey` for the description and the border of the `[disabled]:checked` input. Use `grey--lighter` for the `[disabled]:checked` input fill.
---
> fix(components): account for checked disabled state on RadioGroup

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/ProgressBar/ProgressBar.css
- packages/components/src/ProgressBar/ProgressBar.css.d.ts
- packages/components/src/ProgressBar/ProgressBar.mdx
- packages/components/src/ProgressBar/ProgressBar.tsx
- packages/components/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
Making some improvements to progressBar that @jlelford noticed while working with Atlantis! Also sneaks in an accessibility improvement I've been wanting to make for some time, using `<progress>` instead of divs so that users of assistive tech can know what;s going on!
Also, it makes sense that on step 1 of N, you see your "currentStep" visualized!
- divs are now `<progress>`, and associated CSS changes
- this cuts out some JS calculations we were doing
- Step 1 is visualized as a step!
https://css-tricks.com/html5-progress-element/
---
> feat(components): convert `progressBar` to semantic HTML and count step 1

- packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.css
- packages/docx/src/ColorSwatches/ColorSwatches.css
Colors is one of the oldest sections of Atlantis, and since that time we've enabled our theme to use Atlantis. This PR puts some of our variables to use, and also makes some layout adjustments for ease of use.
Some layout changes, as well as some under-the-hood CSS changes.
- convert hard-coded values to variables
- increase font-size for variable name and values
- left-align variables names and values
- remove left/right spacing, borders, and radii from swatches
- increase vertical spacing
---
> docs(design): update color docs layouts

- packages/components/src/ProgressBar/ProgressBar.css
In switching `ProgressBar` to use the html `<progress>` element, we picked up a user-agent stylesheet `vertical-align` property that causes the `ProgressBar` to sit 0.2em lower than expected.
CSS change to reset `vertical-align` to its default value.
- baseline alignment issue with `ProgressBar`
---
> fix(components): reset vertical-align property on `ProgressBar`

- packages/components/src/Toast/Toast.css
Toast gets compacted quite a bit on small screens, even when there is sufficient room for it to breathe!
Allows the Toast to take up the full width of the screen, minus equivalent spacing on left, right and bottom (uses --space-large on all 3)
- Some CSS changes to allow Toast to expand
---
> fix(components): allow Toast to expand on small screens

- docs/guides/product-vocabulary.mdx
> docs: fix image path on product vocabulary

- packages/components/CHANGELOG.md
- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/Page/Page.tsx
Make subtitle and intro on Page optional
* From `readonly subtitle: string;` to `readonly subtitle?: string;`
* From `readonly intro: string;` to `readonly intro?: string;`
---
> fix(components): Make page subtitle and intro optional

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InputText/InputText.mdx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
This feature adds the ability to incorporate a spinner into the text input field. This would be used when a component is making a call to validate the contents of the field or doing some other long running task with the contents of the field.
The spinner component now is used in the form field generic component.
- a boolean `showSpinner` has been added to the form field component, however it will only work with text input components.
- 
- 
- 
- 
- 
The mdx has a section that includes the spinner. 
---
> feat(components): spinner loading state on input text

- ensureChangelogHeaders.js
Removed a dot from changelog fixed path.
- 
- 
- 
- 
- Changelog pathing
- 
---
> build: Fix changelog headers

- packages/components/src/Banner/Banner.mdx
https://jobber.atlassian.net/browse/JOB-27849
Added content guidelines for how to use banner types, and clarification of when to use banners (notably reducing the usage of success banners as we want to use toasts in lieu of them for feedback in both Jobber online and mobile when appropriate)
- 
- 
- 
- 
- 
- 
---
> docs(components): Add content guidelines to Banner

- packages/components/src/FormatDate/FormatDate.mdx
- packages/components/src/FormatDate/FormatDate.tsx
- packages/components/src/FormatDate/index.ts
We needed to export formatDate as a string so the resulting date can be passed as an attribute to other components.
Allowing the returned formatted date to be a string offers more flexibility on the places it can be used.
Exported the strFormateDate (the method used by FormatDate).
I'm now able to import `strFormatDate` and use it.
---
> fix(components): exports date formatting as a string

- packages/design/src/icons/Icon.css
- packages/design/src/icons/getIcon.ts
Backward compatibility of SG-1 to match `.company` Icon to teal.
- 
- 
- 
- 
- Change `.company` icon default to `teal`.
- 
Check the Icon Component page: https://deploy-preview-470--jobber-atlantis.netlify.app/components/icon
The Icon for company should be teal. 
---
> fix(design): Make company icon colour default to teal

- packages/design/src/icons/Icon.css.d.ts
Missing type files for the last PR (#470) released are breaking the build of Atlantis master. 
This add them back in. 
- 
- 
- 
- 
- Include missing type files required for build.
- 
---
> fix(design): add in CSS types missing from last build

- gatsby-node.js
- packages/docz-tools/gatsby-node.js
When using the `@jobber/docz-tools` package in another instance of `docz` there were some issues with the `gatsby-node` where if there was not a `js|jsx|ts|tsx` file in a specific directory, the `loaders.null()` would fail.
This PR moves that check from the `@jobber/docz-tools` package to the root of `🔱Atlantis`
Moves the null loader to the root of Atlantis
- 
- Moves the null loader to the root of Atlantis
- 
- 
- 
- 
---
> feat: moves the null loader to the root gatsby-node

- packages/docz-tools/src/gatsby-theme-docz/theme/styles.ts
We were seeing hard-to-read paragraphs in cases where `code` was used, as the padding and margins impacted the leading (line-height) of the text.
Removed vertical padding, increased font-size, and removed margin from `code`.
- n/a
- some js styling for `code` to prevent it from taking up additional space in a layout.
- n/a
- n/a
- bug with broken leading in paragraphs
---
> fix(docz-tools): update styling for code to prevent breaking paragraphs [29104]

- packages/components/src/Banner/Banner.css
When Banner content runs past 1 line, the actions container was flexing to full height, making the button taller than needed.
- CSS flex changes to align banner content to the top of the container.
- Button no longer expands taller than its' own content
Add a long string of text to a banner with an action
---
> fix(components): allow button to remain its' own height when Banner content gets long

- doczrc.js
- packages/docz-tools/README.md
- packages/docz-tools/src/gatsby-theme-docz/components/Layout/index.tsx
- packages/docz-tools/src/gatsby-theme-docz/components/Logo/index.tsx
- packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/index.tsx
- packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/styles.ts
Added theme configuration options so that when using `@jobber/docz-tools` in the Developer Center project, we can hide actions and update formatting so it doesn't cause overlap issues.
Overlapping seen with wrapper component and on a docs page.
Wrapper component seen on a non docs page.
Added theme configuration options so that the actions (GitHub link+logo & Edit Page) & logo can be conditionally hidden. As well the sidebar can be positioned relatively instead of fixed, which causes overlapping issues when wrapping with other components.
- added configuration options for the `@jobber/docz-tools` package to hide actions, logo and update sidebar relativeness
- added `isFixedHeight` theme configuration option which when set to false, sidebar will be relatively positioned and height will be …
> feat(docz-tools): added theme configuration options for hiding actions, logo and fixed sidebar 

- packages/components/src/DescriptionList/DescriptionList.tsx
- packages/components/src/DescriptionList/__snapshots__/DescriptionList.test.tsx.snap
Addresses a minor HTML discrepancy identified by the accessibility guild's audit
Uses correct order of term `dt` and description `dd` elements in the `DescriptionList` component
- Swapped order of dt and dd
- html presents in the expected sequence
- hit cmd+f5 to activate VoiceOver, using `control+option+rightArrow` to navigate the DescriptionList, content should read as expected
---
> fix(components): use correct html for DescriptionList 

- packages/components/src/Divider/Divider.tsx
- packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
While our `Divider` uses an HTML element (hr) that comes out of the box with semantic meaning, we actually used Divider for strictly decorative purposes, rather than the spec of:
> a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section
As we use Divider strictly for visual aid, it does not need to be announced to screen-readers or other assistive technology, and in doing so actually adds unhelpful noise to the experience.
- Divider now has a `role="none"` attribute so that assistive tech skips it
Use VoiceOver, ChromeVox, or another screen-reader and see that Divider is no longer announced to assistive tech.
--- …
> fix(components): allow screen-readers to skip Divider

- packages/design/src/Elevations.mdx
Did some shadows/elevation work with @rebecca-li and @jlapstra on mobile, and we got the basis of some good ground rules around shadows in place! Documenting them for future usage.
- More detail and design guidelines around shadows in our design system
- Clarified differences between current mobile and web implementations
---
> docs(components): enhance our elevation docs to reflect mobile work

- packages/components/src/Card/Card.css
- packages/components/src/Drawer/Drawer.css
- packages/components/src/FormField/FormField.css
- packages/components/src/FormatFile/FormatFile.css
- packages/components/src/InputFile/InputFile.css
- packages/components/src/List/List.css
- packages/components/src/List/SectionHeader.css
- packages/components/src/Modal/Modal.css
- packages/components/src/Table/Table.css
- packages/components/src/Tabs/Tabs.css
- packages/design/src/Borders.mdx
- packages/design/src/borders.css
Sean said this on a PR:
And I thought
Add docs for our Borders foundation elements
- docs for borders
- reference in that to Divider
---
> docs(design): Docs With Borders (write docs for Borders)

- packages/generators/templates/component/{{name}}.{{mdx}}
As we're tweaking the way we handle design system contributions for Atlantis, one of the changes will be to our component documentation templates.
Update the component documentation template
- Accessibility section to provide more clarity on a component's a11y requirements and outcomes
- Notes to provide future consumers of a component with any necessary context
- Usage guidelines are now required
- iframe for Figma embedding
- Interface stub until component is built (Playground would then fill this role)
- Content guidelines for both contributors and consumers to consider
- "Sample" component documentation (loud, volume, etc)
- "status" indicators as these have only provided confusion 
--- …
> docs(generators): Update component documentation template

- packages/components/src/Spinner/Spinner.mdx
@rebecca-li asked a good question about accessibility relating to loading states and I didn't have any of our own documentation on this to share 😭 
Added accessibility section to Spinner
- accessibility section to Spinner
---
> docs(components): Add accessibility notes to Spinner

- packages/components/src/Tooltip/Tooltip.mdx
[Popover](https://github.com/GetJobber/atlantis/pull/494) will take over some of the roles currently held by Tooltip, meaning we can get more concise in how we describe Tooltip.
Change guidelines for Tooltip
- Related components: Popover
- usage guidelines
---
> docs(components): update Tooltip to reflect Popover

- packages/docz-tools/README.md
- packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/index.tsx
In #487, I had requested/suggested there be options to hide the logo, actions and change some layout options. I have noticed that there is an issue with hiding the logo when `title` is `undefined`.
The page's title when using `title: undefined` in `doczrc.js`
Docz is expecting title to have a value to set page titles using a template. I am recommending a different configuration option which fixes this issue and has more flexibility as some may want a title but not a logo. I am considering this a fix - as it's not changing expected behaviour, it's simply accomplishing it differently than implemented before.
- Changed conditional logo display to use hasLogo instead of undefined title
- Add `hasLogo` to `doczrc.js`'s theme configuration object as follows:
```
// doczrc.js
export default { …
```
> fix(docz-tools): change configuration option for hiding logo to resolve undefined page titles 

- packages/components/src/Button/Button.css
- packages/design/src/animation.mdx
- packages/design/src/timings.css
@rebecca-li wrote some great guidelines on how to use animations in Atlantis, including guides on how to incorporate our timing variables. However, those were not actually reflected!
I did change the verbiage around the `timings` in documentation from `duration` to `timing` to get those to match, but the values themselves have been updated.
Change description of animation-duration variables to `timing` and update docs, change underlying timing values, add a new variable for Button as I think that's more of a one-off tied to a specific state of that component.
- changed timing variables to match Rebecca's guidelines
- changed Button loading animation from a global variable to one specific to Button
- updated docs to match names of concept and variables
- Go to animation docs, look at …
> feat(design): Update timing variables and docs

- packages/components/src/Popover/Popover.css
- packages/components/src/Popover/Popover.mdx
- packages/components/src/Popover/Popover.tsx
Gave the Popover docs a quick re-read after release, just some cleanups and design clarifications.
Also pulled in the border variable I'd introduced alongside the build of this component, which is available now!
- add a11y notes
- add related components
- use title-case when referencing component names
- flesh out design use cases
- use `color-border` design variable
---
> docs(components): Tweak some verbiage and order of the Popover docs

- docs/CONTRIBUTING.md
Clarify how contributors should request reviews in more places, so that it's easier for a new contributor to follow our workflow.
Add notes on review requests
- link to Github's review process docs
---
> docs: Add note on requesting review

- packages/components/src/InputValidation/InputValidation.css
- packages/components/src/InputValidation/InputValidation.test.tsx
- packages/components/src/InputValidation/InputValidation.tsx
While our error messages do print text elements to the DOM that _could_ be read by assistive technologies, the pattern is un-intuitive and more likely than not would be missed, leading to further errors when a user attempts to submit their form.
Users navigating a form will more likely than not be operating via the `tab` key, as this is a familiar pattern for moving between inputs in forms.
`p` elements are not tab-operable by default, and in addition we sometimes render these errors _above_ the input in the DOM; in either case, the user would need to `control+option+left/right arrow` to engage, and this action does not trigger the `onBlur` event of `tab`-ing, meaning the message will not be read out.
Solution follows the pattern recommended by the [W3C …
> fix(components): Allow input validation to be easily read by assistive tech

- docs/README.md
Our installation instructions are buried pretty deep in our IA - using Atlantis should be a key piece of info for contributors!
Added packages overview and links to installation
- Added packages overview and links to installation
---
> docs: add installation notes to Atlantis home

- packages/hooks/src/useResizeObserver.mdx
It's useful to be able to mock out the `useResizeObserver` hook, so that tests can be done with simulated browser attributes.
- Added a section for Jest testing to the useResizeObserver docs
---
> docs(hooks): Add Jest testing section to useResizeObserver docs 

- packages/design/src/Colors.mdx
- packages/design/src/colors.css
In adding semantic colors to Atlantis, we should help people know how to use them.
Content references [this Figma.](https://www.figma.com/file/PNo7p9G0OxygCOjgm4rpngav/Product-Colors?node-id=450%3A124)
While writing the docs, I had one of those "as you write it, you feel like the system is bad if you need to write too much" moments. As such, there are also some adjustments to the colors.css design package as well, to clarify the intent of the light and dark shades of the status colors and eliminate redundancy with extraneous "surface status" colors. 
- Added guidelines for how to use semantic colors
- Renamed some of the "Status" variables and removed the `surface--{status}` colors
Go to the colors page in Atlantis and take a look!
--- …
> docs(design): More detail on semantic color usage

- packages/components/src/RadioGroup/RadioGroup.css
We have semantic colors in Atlantis now, we should use them to get the full benefit!
- a bunch of CSS in Radio; mostly replacing descriptive CSS properties from that component to leverage the Atlantis system semantic properties
- Old component-specific properties where relevant
Go to the component page and test focus, disabled, etc
> feat(components): use semantic colors in Radio

- packages/components/src/Card/Card.css
- packages/components/src/Drawer/Drawer.css
- packages/components/src/Modal/Modal.css
We have semantic colors in Atlantis now, we should use them to get the full benefit!
I changed all three of these components in one PR as the changes are _extremely_ similar, and I think easier to review in this format.
- some CSS properties in each component; mostly replacing descriptive CSS properties from that component to leverage the Atlantis system semantic properties
- Old component-specific properties where relevant
Go to the component page and test focus, disabled, etc
---
> feat(components): Use semantic colors in card, modal and drawer

- packages/components/src/Switch/Switch.css
We have semantic colors in Atlantis now, we should use them to get the full benefit!
- a bunch of CSS in Switch; mostly replacing internal custom CSS properties from that component to leverage the Atlantis system properties
- Old component-specific properties where relevant
Go to the component page and test focus, disabled, etc
---
> feat(components): use semantic colors in Switch

- packages/components/src/Autocomplete/Autocomplete.css
- packages/components/src/Banner/notificationTypes.css
- packages/components/src/DescriptionList/DescriptionList.css
- packages/components/src/Disclosure/Disclosure.css
- packages/components/src/Divider/Divider.css
- packages/components/src/List/ListItem.css
- packages/components/src/List/SectionHeader.css
- packages/components/src/Menu/Menu.css
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Popover/Popover.css
- packages/components/src/ProgressBar/ProgressBar.css
- packages/components/src/Tabs/Tabs.css
- packages/components/src/Toast/Toast.css
- packages/components/src/Tooltip/Tooltip.css
To get the full value out of our new semantic color palette, we should use it as broadly as possible.
I know this is a whole pile of components, but they have very similar changes across the board and should be fairly easy to verify in QA.
Replaced base colors with semantic colors in...
- Autocomplete/Autocomplete.css
- Banner/notificationTypes.css
- DescriptionList/DescriptionList.css
- Disclosure/Disclosure.css
- Divider/Divider.css
- List/ListItem.css
- List/SectionHeader.css
- Menu/Menu.css
- Popover/Popover.css
- ProgressBar/ProgressBar.css
- Tabs/Tabs.css
- Toast/Toast.css
- Tooltip.css
Almost entirely "surface" and "border" colors, with a few "interactive" and "text" along the way.
- some component-specific CSS properties
- border-color values from Banner's "notificationTypes" as …
> feat(components): update remaining Atlantis components to use semantics

- packages/components/src/Button/Button.css
Locally, the fill color for Icons within Button was being correctly inherited per Button's style cascade:
However, on production this order is flipped:
- CSS for Button has been updated
- an `!important` declaration to the button's fill property so that it cascades with enough importance to over-ride the path-specific classnames we provide svg paths inside of `Icon`.
- Button icons should be the correct color 
You have to test this on Netlify's deploy preview, locally it's already fine and will continue to look as such.
---
> fix(components): add greater specificity to fill inheritance for icon buttons

- packages/docz-tools/src/gatsby-theme-docz/components/Logo/styles.ts
- packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
The "gold" styling we applied to make the text in "Atlantis" look like the 🔱 emoji isn't necessary, and doesn't make any sense when used outside of Atlantis.
Also, the initial `greyBlue-light` color we were setting on level 2 pageLabel did add more distinction between levels 1 and 2, but was harder to read (and failed WCAG AA). By leaving it as `greyBlue-lighter` we get better contrast, and the indentation/bullets still do enough heavy lifting on level-separation.
Adjusted text color of page labels and removed gold styling from title of the site.
---
> docs: remove the "gold" in sidenav and increase contrast of pageLabel

- packages/design/src/Radii.mdx
Got a question about our border radius today and realized we don't have docs on them 😓 
New raddi docs in Design!
- An MDX file for radii, including example table based off Borders
---
> docs(design): create radius docs

- packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
The "level 2" elements in the Atlantis navigation module do not handle long titles very well. This isn't an issue in Atlantis, but in other places we use this module (ie internal Jobber docs) it's problematic.
**Before**
**After**
Modified navigation CS to better reflow newlines in level 2 pagelabels.
- newlines in pageLabel re-flow to align with the other pageLabels, instead of wrapping
In the DOM or in code, change the labels of the sidenav elements and see that they wrap correctly
---
> docs: keep newlines of pageLabel aligned

- packages/components/src/Typography/Typography.test.tsx
- packages/components/src/Typography/Typography.tsx
In certain cases - it appears that the `maxLines` prop on `<Text/>` or `<Typography/>` was ignored.
See following from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp):
```
The -webkit-line-clamp CSS property allows limiting of the contents of a block container to the specified number of lines.
It only works in combination with the display property set to -webkit-box or -webkit-inline-box and the -webkit-box-orient property set to vertical.
```
The `-webkit-box-orient: "Vertical"` was missing, and has been added.
- Fixed the `maxLines` prop on Text & Typography to be slightly more consistent with popular browsers.
---
> fix: Text / Typography don't always respect maxLines [JOB-32400]

- package-lock.json
- package.json
- packages/hooks/package-lock.json
- packages/hooks/package.json
- packages/hooks/src/configure.test.ts
- packages/hooks/src/configure.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useCollectionQuery/__mocks__/index.ts
- packages/hooks/src/useCollectionQuery/__mocks__/mocks.tsx
- packages/hooks/src/useCollectionQuery/__mocks__/queries.ts
- packages/hooks/src/useCollectionQuery/__mocks__/utils.ts
- packages/hooks/src/useCollectionQuery/index.ts
- packages/hooks/src/useCollectionQuery/uniqueEdges.tsx
- packages/hooks/src/useCollectionQuery/uniqueNodes.tsx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.mdx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
- packages/hooks/src/useIsMounted/index.ts
- packages/hooks/src/useIsMounted/useIsMounted.mdx
- packages/hooks/src/useIsMounted/useIsMounted.test.tsx
- packages/hooks/src/useIsMounted/useIsMounted.ts
- packages/hooks/tsconfig.json
Both Jobber Online and Jobber Mobile use useCollectionQuery for 2WSMS. The version in Jobber Online, however did not have tests as it was implemented in Jobber Online during a big bug fix. It was always the intention to move useCollectionQuery to Atlantis, no time like now.
To make useCollectionQuery work, we needed to also move over useIsMounted.
Tests have been written.
Both hooks can now be updated from a shared component in Atlantis
The functionality should not change.
NA
NA
NA
NA
Tests should work. Integrations with Jobber Online and Mobile should be tested completely.
---
> feat(hooks): add useCollectionQuery and useIsMounted [JOB-32207]

- packages/components/src/RadioGroup/RadioGroup.tsx
- packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
Add role of "radiogroup" to the div that has that responsibility in the RadioGroup component so that assistive technology has a better idea of what that div is responsible for.
- role of `radiogroup` to the div with the classname "RadioGroup"
---
> fix(components): add "radiogroup" role to RadioGroup

- packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css
- packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css.d.ts
- packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.tsx
It's a Bad Time™ to use your keyboard to make your way through Atlantis, if you have to tab through all of the sidenav items. As a general accessibility practice, it's important to allow keyboard users to skip main navigation in favour of the main content.
This adds a skipnav link in keeping with [WebAIM guidance.](https://webaim.org/techniques/skipnav/)
Added a skipnav link to the Layout module.
- There's now a link that jumps the user to the main content of a page in Atlantis
- If you are on a less-than-wide screen, the link will also close the menu
- if you are on a wide+ screen, the link does not close the menu (because the menu should not ever close on wide screens)
- The `content` div in Layout now has an id of `mainContent` to act as a target for the skipnav link
Use the `tab` key …
> docs: Add skipnav to `Layout`

- lerna-debug.log
- packages/hooks/src/useCollectionQuery/test-utilities/mocks.tsx
- packages/hooks/src/useCollectionQuery/test-utilities/queries.ts
- packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
- We want to be able to use useCollectionQuery with search and a subscription, if someone is searching for something, we don't want new subscription data to come in and mess up those results. This fixes that problem. 
- Changed useCollectionQuery so that it does not pull in new data when a user is searching for content
- Specs were written to specifically test this situation.
---
> feat(hooks): Update useCollectionQuery to handle search terms [32867]

- packages/components/src/List/ListItem.css
- packages/design/src/Colors.mdx
- packages/design/src/colors.css
- packages/docx/src/ColorSwatches/ColorSwatch/ColorSwatch.css
Reflecting some more common surface and overlay patterns that I picked up on when rolling semantic colours out across Jobber. Also updates the docs to have color swatches associated with the usage guidelines, albeit in a rough fashion that could potentially be componentized in the future.
Some new colours! Some new swatches in the docs!
- color-surface--active extends the surface--hover pattern
- color-overlay--dimmed extends the overlay pattern, but for "dimming" temporarily-non-interactive (but not disabled) UI
- color-white now consumes an rgb value a la color-greyBlue for use in color-overlay
- components using surface--active now use them
- color docs have HTML-based color swatches
- split out accessibility in docs as its' own section, vs as a Banner
---
[In Atlantis we use Github's …
> feat(design): add active surface and dimmed overlay colors

- packages/components/src/Toast/Toast.css
- packages/components/src/Toast/Toast.mdx
- packages/design/src/Elevations.mdx
- packages/design/src/shadows.css
Toast is too subtle in part because it was built using the one and only shadow token we have in our design foundations! Also looks different in Figma as the Figma reflects the intended design @rebecca-li created, causing a conflict.
Add web shadow variations and apply them to Toast
- Shadow Low and Shadow High
- Toast shadow from Base to High
---
> feat(design): introduce web shadow variations, document and add to Toast

- packages/design/src/colors.css
While reviewing [a subsequent PR](https://github.com/GetJobber/atlantis/pull/580/files) I realized that the reason the `color-overlay--dimmed` value was not working was because I used an inconsistent hyphenation practice in the initial implementation.
This led to the color being interpreted as `rgba(0,0,0,0)` which is equivalent to... no color at all (transparent).
RGB token values now use naming consistent with other color values.
`--color-{colorName}--{modifier}`
- Hyphenation in `--color-overlay` and `--color-overlay--dimmed`
- `--color-overlay--dimmed` works!
You can merge this branch into the PR above, or change the color of some other element in Atlantis to use the `overlay--dimmed` color and inspect it to see that it's a 60% opacity of white.
---
[In Atlantis we use Github's built …
> fix(design): clean up --rgb tokens

- packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
Communiverse has run into an Apollo cache invalidation issue that is described [here](https://github.com/apollographql/apollo-client/issues/7491#issuecomment-767985363)
What we saw:
If you have a list, and use fetchMore to get a new page, and then call refetch it will refresh the first page of data only, and if that data has not changed, it will not remove the following pages, and the cached data will all be returned. However, if the first page is different than it was before, the following pages will be cleared out.
The result is that you can't actually "refetch" all data on your machine if the first page hasn't changed.
This is resolved in the Apollo 3.4.0 RC so we'd like to get onto that version once it's released. In the mean time we have this workaround for the issue
- NA
- Instead …
> fix(hooks): fix refreshing expected behaviour until apollo fix lands 

- packages/components/src/Form/Form.test.tsx
- packages/components/src/Form/Form.tsx
When forms were being submitted, they were not focusing on the invalid fields. This was causing users to have to scroll to find their invalid feidls.
Adds an `errorHandler` to the `Form` component that will focus on the first invalid field
- `errorHandler` to the `Form` component that will focus on the first invalid field
- 
- 
- 
- 
- 
---
> fix(components): Focus the first error on Form submission

- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/FormFieldTypes.ts
We want to support more options for autocomplete attribute
- added 4 new values: address-line1, address-line2, postal-code, cc-name
- changed `setAutocomplete` function
---
> feat(components): Add more values to autocomplete attribute

- packages/design/jobberStyle.js
- packages/design/src/colors.css
We currently do not properly parse values like rgb(var(--color-greyBlue--rgb)) and rgba(var(--color-greyBlue--rgb), 0.8) in colors.css
Update jobberStyle.js to support the above.
- Support rgb and rgba
- none
- none
- none
- JOB-34356 - Can not parse rgb in colors.css
- none
- Build foundation.js and confirm that values in colors.css like the above appear in foundation.js
---
> fix(design): Fix parsing of colors.css to support rgb and rgba [JOB-34356]

- packages/hooks/src/index.ts
Can't import `usePasswordStrength` as I had forgotten to export it from the base index file, it is still technically importable via `dist/usePasswordStrength`, however is not best, also is not how the markdown document says to import it.
- Exported the `usePasswordStrength`, so you don't have to import via `dist/usePasswordStrength`, similar to other hooks.
---
> fix(hooks): update exports to include usePasswordStrength 

- packages/design/src/Colors.mdx
- packages/design/src/colors.css
- packages/docz-tools/index.ts
- packages/docz-tools/src/components/ColorSwatches/ColorSwatches.module.css
- packages/docz-tools/src/components/ColorSwatches/ColorSwatches.module.css.d.ts
- packages/docz-tools/src/components/ColorSwatches/ColorSwatches.tsx
- packages/docz-tools/src/components/ColorSwatches/index.ts
@chriscarline did some work that redefines what our "reverse" surface is, so this is being reflected in our design system.
Further, the existence of a reverse surface implies the existence of reversed text, which makes sense.
Note: this is a scoped-down version of: https://github.com/GetJobber/atlantis/pull/595 in which I had also updated several components and Atlantis' layout. This PR is scoped to the colors themselves and the new docs.
Surface reverse is now based on `--color-blue`
- `--color-text--reverse` and `--color-text--reverse--secondary` added to color system and docs
- Improved swatch presentation for semantic values; readers of the docs can now copy the color swatch while reading the docs, rather than inspecting the DOM to copy and paste the values.
---
[In Atlantis we use …
> feat(design): Update surface reverse color

- docs/CONTRIBUTING.md
- packages/components/src/Button/Button.tsx
- packages/components/src/ButtonDismiss/ButtonDismiss.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/List/ListItem.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Tabs/Tabs.tsx
- packages/generators/templates/component/{{name}}.tsx
In some cases it is useful to have access to the mouse event when building more complex components that nest multiple components. In some cases it's needed to `event.stopPropagation()` or `event.preventDefault()`.
- Added `event` argument for all existing onClick events
- Use any of the components which have `onClick` events and log it when clicked!
---
> feat(components): Add `event` argument to onClick events

- packages/components/src/Button/Button.mdx
We added subtle button, this treats the "sandbox" examples more like the other variations, with the Primary/SecondaryTertiary stacked atop each other.
- Stacked the subtle buttons
---
> docs: consistency of displaying button variations

- packages/components/src/Modal/useFocusTrap.test.tsx
- packages/components/src/Modal/useFocusTrap.ts
Upon adding the modal to trap the focus (#634) I've added an `aria-hidden=true` on the body and `false` on the modal. I saw an example of that when dealing with tooltips and assumed that was one of the way to deal with hiding things behind the modal. Trapping still works tho.
So the `getByRole` (`findBy...`, `queryBy...`) [respects the `aria-hidden`](https://testing-library.com/docs/queries/byrole/#hidden), thus breaking all modal tests in Jobber Online from getting/finding the things inside the modal as it was aria-hidden through the body. It was just the test that was broken. UI wise, it all be working: trapping and screen readers.
Lesson: Confirm how aria-hidden works and pre-release test atlantis in jobber online (clicking around and running tests)
- 
- 
- 
- The use of aria-hidden …
> fix(components): remove aria-hidden prop on trap focus

- docs/content/product-vocabulary.mdx
Adding definitions of 'Subscription' 'Subscribe(d)' and 'Plan' under Product Vocabulary 'Concepts and Items'
To create rules around when and which subscription terms to use.
None
Definitions around 'Subscription' 'Subscribe(d)' and 'Plan'
None
None
None
None
None
Read through definitions and click on the link to Jobber's plan pricing
---
> docs(design): Adding subscription definitions to concepts and items in our product vocabulary 

- packages/components/src/Button/Button.tsx
- packages/components/src/ConfirmationModal/ConfirmationModal.mdx
- packages/components/src/ConfirmationModal/ConfirmationModal.tsx
- packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
Currently, the confirmation modal only accepts a primary “work” action, which breaks this pattern.
we have determined the pattern for this is to show a secondary destructive button, which triggers a confirmation modal with a primary destructive action
Adding actionType work | Destructive to the confirmation Button
Adding actionType work | Destructive to the confirmation Button
- 
- 
- 
- 
- 
- 
---
> feat(components): Add destructive  option for confirmation modal

- packages/components/src/Avatar/Avatar.css
- packages/components/src/Avatar/Avatar.css.d.ts
- packages/components/src/Avatar/Avatar.mdx
- packages/components/src/Avatar/Avatar.tsx
- Chip component requires a smaller avatar than what "base" provides
- Small size type to reduce the size of the avatar to 24x24 px
- Document when to use small
- 
- 
- 
- 
- 
---
> fix(components): Add small size to avatar

- packages/components/src/Avatar/Avatar.css
We allowed for Tooltip's children to be focused, which is good! However, some elements that Tooltip wraps do not have a designed focus state, so they end up with an unintentional-looking default ring.
This PR adds a defined focus state to Avatar.
Focus state on Avatar before:
After:
- set no outline, use our `shadow-focus`
- go to the Avatar docs page with the "use with Tooltip" section and focus the Avatar!
---
> fix(components): clean up focus state on Avatar

- docs/content/product-vocabulary.mdx
Had a discussion with designers where the example of using the inverse of create was a useful framing for when to use delete, vs remove.
- A few lines about delete and remove and their relation to create and add.
---
> docs: use inverse examples for remove and delete

- packages/docz-tools/src/gatsby-theme-docz/components/Layout/Layout.module.css
The skip to content link is still present at the top of the view, even when it is invisible, leading to accidental clicks and bad times. It should be completely hidden to users operating via mouse/trackpad.
Initially tried to fix this in part of a larger, [less-reviewable PR.](https://github.com/GetJobber/atlantis/pull/595)
Before:
https://user-images.githubusercontent.com/39704901/134788708-b4cfd0e8-6201-42bb-a7fc-007364bc97c6.mov
After:
https://user-images.githubusercontent.com/39704901/134788715-098cbb3f-f5a2-49ef-abef-0ec777de1211.mov
- negative top offset of skipnav in hidden state to push it out of the viewport
- You can no longer click the skipnav when you hover over the top of the viewport with your cursor.
Move your mouse cursor around the top ~32px of the viewport.
---
[In …
> fix: adjust skipnav offset in hidden state

- packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
- packages/docz-tools/src/gatsby-theme-docz/components/Sidebar/styles.ts
The initial design of the Atlantis sidenav was intended to match the Jobber web app's appearance. Since it has changed in product, we should change it here for a more consistent visual.
This will also be useful in other places that leverage the sidenav, such as our developer docs.
This PR is a more focused cut of an initial, much-too-broad change made in a [since-closed PR](https://github.com/GetJobber/atlantis/pull/595)
Color and type styling of the side navigation modules and search.
- sidenav now uses the equivalent of our `color-surface--reverse` [(color docs)](https://atlantis.getjobber.com/colors#surfaces)
-Before
- After
---
> feat: update sidenav to match Jobber appearance

- packages/components/src/Banner/Banner.mdx
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/index.ts
In order to integrate the Banner component, we need the banner type to be exported. 
- 
- 
No banner type is exported
Banner type is exported
- 
Banner type should be available to import 
---
> feat(components): export banner type

- docs/README.md
Clicking contribution guidelines link in the README goes to `404` when clicked via https://github.com/GetJobber/atlantis
It works fine when clicking from https://atlantis.getjobber.com/
Closes #693 
- 
- 
- 
- 
- README.md hyperlink to contributing guidelines goes to correct URL when clicked from github
- 
Verify that Gatsby still generates the proper url.
1. `npm run build && npm run serve` 
2. open in a browser: http://localhost:3333/
3. verify that clicking contribution guidelines still navigates to `http://localhost:3333/CONTRIBUTING.md`
Verify that the link works on GitHub (fork).
1. open in a browser: https://github.com/linhub15/atlantis
2. verify that clicking contribution guidelines navigates to https://github.com/linhub15/atlantis/blob/master/docs/CONTRIBUTING.md
---
[In Atlantis …
> chore: fix README hyperlink to CONTRIBUTING.md

- packages/components/src/Content/Paddings.css.d.ts
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Select/Select.css.d.ts
Closes #697 
This change is better for user experience and accessibility as users can start selecting menu items using tabs. Otherwise, the tab indexing was traveled along the whole page which is a very long process 
- Added auto-focus of the first item of Menu 
- Focuses the first item when menu is opened
1. Run the local dev environment and search for the Menu component
2. Click on the `More Actions` in the examples.
3. Verify that the first item of the Menu is focused.
4. Also verify that pressing tab should move to the next item.
---
> feat(components): Autofocus on first Menu item

- packages/components/src/Content/Paddings.css.d.ts
- packages/components/src/Select/Select.css.d.ts
Latest PR merge formatted some CSS declaration files which is causing issues with Lerna and releasing.
- Fixed css declaration files
- `Paddings.css.d.ts`
- `Select.css.d.ts`
---
> fix(components): Fix formatting of css declaration files to unbreak Lerna

- packages/components/src/Card/Card.css
Fixes #716
When using a clickable card, the `--color-border` css variable is overridden, which causes issues when using buttons or divider as a child component.
- Changed usage from `--color-border` to it's own variable `--card-border-color`
- `--card-border-color` still gets correctly updated to a transparent value as intended
- Card no longer overrides `--color-border` for children components
- To see reproduction of the issue, [see minimal reproduction](https://codesandbox.io/s/716-card-overriding-border-color-css-variable-repro-z36jt?file=/src/App.js)
- To see fixed version, pull down PR and import `Divider` component in the `Card` documentation page, and insert the divider in a clickable card  
--- …
> fix(components): Card no longer overrides border color variable

- packages/components/src/Banner/Banner.mdx
Realized documentation guidelines for Banner were not available around how much content is appropriate for this component.
- 
- 
- 
- 
- 
- 
---
> docs: Add content guidelines to Banner component 

- packages/components/src/InputValidation/InputValidation.mdx
Our pattern for validating Inputs is to render the error message below the inputs. See the [validation section for InputText](https://atlantis.getjobber.com/components/input-text/#validation-message).
We do this for consistency, but also to allow screen-reader users a better change to catch errors in the flow of navigating the form via the `tab` key.
However, most people looking for docs on InputValidation, go to [InputValidation](https://atlantis.getjobber.com/components/input-validation) where we show them this:
This is confusing for designers who then want to abstract the "error message goes above" pattern to other use cases:
> I'm wondering if there should be similar error text above a checkbox like we have for InputValidation
Moves the InputValidation component in the sandbox to …
> docs(components): Put InputValidation below the Input where it belongs

- packages/components/src/Menu/Menu.css
- packages/components/src/Menu/Menu.css.d.ts
- packages/components/src/Menu/Menu.tsx
In smaller layouts, it is ideal to update menu to take the full width of the container it's in so that it can span the entire screen, such as on smaller screens. Button's support this behaviour with a `fullWidth` prop, however, when used in custom activator it's ignored as the parent container doesn't grow to full width.
- Added conditional css class to make menu grow to full width when custom activator has `fullWidth` prop. 
```
<Menu
activator={<Button fullWidth label="My Fancy Menu" />}
items={[
{
actions: [
{
label: 'Edit',
icon: 'edit',
onClick: () => {
alert('✏️')
},
},
],
},
{
header: 'Send as...',
actions: [
{
label: 'Text Message',
icon: 'sms',
onClick: () => {
alert('📱')
},
},
{
label: 'Email',
icon: 'email',
onClick: () => {
alert('📨')
},
},
],
},
]}
/>
```
See the custom …
> feat(components): Menu component respects fullwidth on custom activator such as button

- packages/components/src/InputValidation/InputValidation.mdx
The use case for Input Validation should be limited to cases where an input does not provide validation out of the box. This isn't clear from the docs.
- Warning that directs readers to the docs for built-in input validation
---
> docs(components): add warning to InputValidation

- packages/components/src/Drawer/Drawer.test.tsx
- packages/components/src/Drawer/Drawer.tsx
Linting and testing was ❌  on master, this fixes that.
- 
- 
- 
- 
- Linting and tests on `Drawer`
- 
---
> refactor: Fix linting and tests on Drawer

- packages/components/src/FormField/FormField.css
Atlantis FormFields were initially built with some legacy styling that has since been updated. This introduces usage of the intended colors for disabled states in FormField and its' inheriting components.
- Uses an opacity of 0.6 on the entire input
- Value does not change color, but "dims" thanks to the use of opacity
- Uses our semantic color of `disabled` for the value when the input is disabled
- No longer using opacity value
- CSS changes to remove opacity and introduce usage of `color-disabled` for the FormField's `value` text elements.
- FormField with a value no longer uses a combination of opacity-changes and `blue` to create a "disabled" appearance, instead uses our specified semantic colors.
Add the following snippets into the sandboxes for each component. There are more …
> fix(components): use correct colors for disabled text

- packages/components/src/FormField/FormField.css
Similar to #776 , Atlantis inputs were designed with legacy styling in mind that we should be OK to move on from.
In particular, the lack of a focus "ring" and leveraging border-color in lieu led to issues where you could not clearly tell if you had focused an input with an error; this makes it harder to fix the error as it adds a bit of cognitive load.
Input in isolation
Input focused + invalid (note that you can't see the "focus" color because the border has taken the "error" color)
Input in a group (note that bottom border is also hidden by subsequent input)
Input in a modal
Input in isolation:
Input focused + invalid
Input in a group:
Input in a modal (showing that z-index usage is not creating any conflicts with other "elevated" elements)
- Focus shadow styling to FormField
- Focus …
> feat(components): Use focus shadow instead of focus border

- packages/design/src/Colors.mdx
Attempt to resolve some confusion around the appropriate usage of the `--color-focus` property.
- Made more explicit the intended usage of `--color-focus` in the `--shadow-focus` property, and not in isolation
---
> docs(design): Focus on focus

- packages/components/src/Banner/Banner.mdx
There are some questions about the preferred approach to using Banner within various layout types. This attempts to address those questions!
- Layout guidance to Banner design guidelines
---
> docs(components): include layout considerations in Banner guidelines

- packages/design/src/Spacing.mdx
We've never had any guidelines or examples of how to use Spacing. We should have that, so that designers can follow defined patterns and we're not just doing what seems good on a case-by-case basis.
- Adds usage guidelines to Spacing.
---
> docs(design): Write spacing guidelines

- packages/components/src/FormField/FormFieldAffix.tsx
- packages/components/src/InputText/InputText.mdx
Aligned with design team on the question of whether we want to...
- change all “clickable” icons to use subtle
- keep all “clickable” icons using work
- allow the clickable icons to have the ability to configure the button “type” (demonstrated in #767 )
- other (allow to choose either work/subtle ?)
**Answer:** we'll use subtle for all FieldAffix actions
- when FieldAffix has an onClick event, the rendered Button uses the `subtle` variation
- also brought in some usage guidance from the initial design proposal
---
> feat(components): Adjust formfield suffix actions to subtle

- packages/components/src/Toast/Toast.css
- packages/components/src/Toast/Toast.tsx
The Toast, while intended as a quick, non-critical message, is a bit too unobtrusive; admins are missing the success messages when they save changes, for example.
This is particularly problematic on larger/multiple monitor setups, which we know many of our admins are operating on.
- Toast now uses the `reverse` colors from the theme for high contrast against the main application surface
- Toast now has longer min and max durations, and a longer auto-calculated duration
---
> feat(components): update toast visuals and timing [JOB-27572]

- packages/components/src/DatePicker/DatePickerActivator.test.tsx
- The test being fixed initially will always pass since `fullWidth` will never add a class name but will add an HTML attribute on the activator.
---
> fix(components): Fix Activator Test

- packages/components/src/Toast/Toast.mdx
We should not be using toasts for error messages. There should be work to actively remove this functionality from Toast, but in lieu of having capacity for that, we should not make it a suggested usage.
- examples of Toast being used for an error message
---
> docs(components): remove error toast from examples

- packages/components/src/Banner/Banner.mdx
Sample warning banner was using an outdated use case that's better served by ConfirmationModal.
- update to related components
- Sample content in `warning` banner
---
> docs(components): update warning banner content for use case clarity

- packages/components/src/DatePicker/DatePicker.mdx
Got a question of "when should I actually use a datepicker on its own, vs in an InputDate format?"
- Just a bit more of a tangible example use case for datepicker as a standalone
---
> docs(components): add more detail to datepicker usage

- packages/components/src/Countdown/Countdown.test.tsx
- packages/components/src/Countdown/Countdown.tsx
- packages/components/src/Countdown/computeTimeUnit.test.tsx
- packages/components/src/Countdown/computeTimeUnit.tsx
- We want the countdown labels to be smarter by implementing smarter labeling of time units.
- When there is a singular time left (i.e 1 hour, 1 day, 1 second), we will show a singular unit instead of a pluralized unit
- before:
- after:
- Open up the Atlantis Playground > Countdown component > modify the time remaining 
---
> fix(components): Make countdown label smarter [JOB-39652]

- .circleci/config.yml
Investigating setting max heap memory on the Medium CI container (4GB) to see if it impacts what the memory consumption looks like.
In Node 10, as described [here](https://jobber.atlassian.net/wiki/spaces/JTW/pages/1311211576/TED+41+-+Node+Max+Memory), the maximum heap size is 1400 MB. In Node 12 and higher, it's dynamic for lower amounts of RAM (embedded devices), but once you get into 4GB territory, it maxes out once again - but at a new higher maximum of 2048.
This means that upgrading node from 10 to something higher on a Medium (4GB) will inherently give it a 600MB boost, in the absence of any other configuration changes.
For whatever reason, this additional memory makes the workflow step in question start to misbehave.
The solution? Use a special environment variable to REDUCE the …
> build: Decrease max old space size back to Node 10 value of 1400MB

- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
On button activator, the date picker flickers when you click it
On InputDate, the date picker closes permanently when you click/focus on the field again
It shouldn't be like that. It should just keep the date picker open when clicking the activator again
- 
- Added the `react-datepicker-ignore-onclickoutside` class name on our custom component
- Investigated how [react date picker](https://reactdatepicker.com/) works and that's how it determines if the calendar stays open or not
- 
- 
- 
- 
---
> fix(components): Prevent date picker from flickering / closing when click the activator again

- packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.tsx
- 
- 
- 
- 
- Resolves an issue where search lags by a keystroke.
- 
Search for `tab`.
---
> fix: Stop search results from lagging by one keystroke.

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
- packages/components/src/FormField/FormFieldDescription.tsx
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
- packages/components/src/InputGroup/InputGroup.css
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputTime/InputTime.test.tsx
- packages/components/src/InputValidation/InputValidation.css
- packages/components/src/InputValidation/InputValidation.css.d.ts
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
The `<Input* />` components aren't contained in a single tag. In some cases, those are okay but the input's also renders an error and now description below the field, thus opening those elements to be updated by anything that encapsulates it such as `<Form />` and `<InputGroup />`.
- 
- 
- 
- 
- 
---
> fix(components): Fix form field inconsistent spacing when used under Form and InputGroup JOB-37646

- packages/components/src/DatePicker/DatePicker.css
- packages/components/src/DatePicker/DatePicker.css.d.ts
- packages/components/src/DatePicker/DatePicker.tsx
- we are now importing the CSS module of react-datepicker into our component to unchoke our NEXTJS builds.
---
> chore(components): Make datepicker import css module instead of general css [JOB-38626]

- packages/components/src/DatePicker/DatePicker.css
- packages/components/src/DatePicker/DatePicker.css.d.ts
- packages/components/src/DatePicker/DatePicker.tsx
Release broke when #810 got introduced because the `bootstrap` (aka `npm ci`) removes `react-datepicker__month--selecting-range` from `.d.ts` but `npm start puts it back. When releasing, I believe it's only running `bootstrap` which leaves an uncommitted change which cancels out the release.
This PR ensures the `npm ci` and `npm start` doesn't clash
- 
- Read title
- But this time, it's importing `.module.css` as opposed to just `.css`
It still uses the `:global` instead of without it. Which fixes the nextjs bug. We think.
Before #810, it was only using `.css` to import so it will give you a result with no `:global`
- 
- 
- 
- 
---
> fix(components): Move import of ReactDatePicker CSS back to DatePicker.tsx

- packages/components/src/Divider/Divider.css
- packages/components/src/Divider/Divider.css.d.ts
- packages/components/src/Divider/Divider.mdx
- packages/components/src/Divider/Divider.test.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
- packages/design/src/Borders.mdx
- packages/design/src/borders.css
We recently expanded our suite of dividers on mobile and I'd like to keep Atlantis in sync for such a simple change.
- New `larger` and `largest` Dividers
- New value `border-thickest` that can be applied to the mobile divider (replacing current usage of `space-small`
- Opacity of `large` Divider to align with approach on mobile
- [Click here!](https://deploy-preview-799--jobber-atlantis.netlify.app/components/divider)
---
> feat(components): More dividers to align with mobile conventions

- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/InputDate/InputDate.tsx
Focusing on the selected date when the date picker opens was removed when we added the input date. This brings it back. This also makes the date picker refocus on the activator.
- Adds back the autofocus on selected date
- Refocus on activator 
- After selecting a date
- After hitting escape (only when the calendar itself is focused) 
- 
- 
- 
- 
- 
- When the date picker is opened
- When a date is selected
- It should move the focus to the selected date
- Hitting `esc` key should put the focus back to the activator
- Choosing another date should close the date picker and put the focus back to the activator
- When a date is NOT selected
- The focus should still be in the activator
- Choosing a date should close the date picker and put the focus back to the activator
- Tabbing to the date …
> fix: DatePicker smart focus [JOB-39118, JOB-38255]

- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/DatePicker/useFocusOnSelectedDate.test.tsx
- packages/components/src/DatePicker/useFocusOnSelectedDate.ts
Hook was introduced because the DatePicker test [here](https://github.com/GetJobber/atlantis/blob/master/packages/components/src/DatePicker/DatePicker.test.tsx#L114) was a false positive because initially the DatePicker library focuses on mount, so it would be the case that the test will always pass.
To fix this @darryltec suggested creating a separate hook that handles focusing on the date hence `useFocusOnSelectedDate`   
> fix(components): Move focus to hook

- package.json
- packages/components/package.json
- packages/components/src/DatePicker/DatePicker.css
- packages/components/src/DatePicker/DatePicker.css.d.ts
- packages/components/src/DatePicker/DatePicker.tsx
- packages/generators/templates/component/{{name}}.css.d.ts
- we are now importing the CSS module of react-datepicker CSS into our component to unchoke our NEXTJS builds. The postcss-import is the plugin that handles the importation of external CSS into our CSS modules which is only run during `npm run build` and `npm start` in our local dev.  In production, this is not the case hence why it fails.
- `package.json` has now been updated to not run `npm run build:CSS` in components since we are already pushing up the CSS types created from the gatsby/webpack `postcss-import` plugin.  This script is the reason why it is breaking because it keeps overwriting what we currently have committed in our branch.
- this `package.json` configuration `"build:cssTypes": "tcm src",` creates the CSS types but is missing the import CSS types because it does not run …
> chore(components): Update package json to accommodate the DatePicker import

- packages/components/src/Chips/InternalChipSingleSelect.tsx
- packages/components/src/Chips/tests/InternalChipSingleSelect.test.tsx
Since the single select chips are just an input radio behind the scenes, deselecting via space bar isn't really a default interaction for them. This make it support the ability to deselect a chip via a space bar press
Q: What about enter press?
A: Since radio's and checkboxes doesn't get selected on "enter" press, I didn't bother including it. You can, however, select both via a space bar so it seems natural to only support said key.
- Allow single select chips to be deselected on enter press
- Test that new interaction
- 
- 
- 
- 
- 
- You should be able to deselect a single select chip using the space bar
---
> fix: Allow space bar key deselect on single select chip

- .circleci/config.yml
While investigating parallel test runs @darryltec noticed that `npm ci` was being called over and over at each step after `install_dependencies`.  This was probably due to a mistake in implementation of the caching inside `config.yml`    
Decrease the total time of Atlantis builds:
Before: 11m 21s (without release step) and ~14m 45s (with release step)
After: ~8m 37s (without release step)
- Instead of using caching after `install_dependencies` we are persisting a workspace.  Caching works from branch to branch, but persisting a workspace works during a single pipeline instance.  This is why caching is still kept during `install_dependencies` since it could be the case that the cache will be hit on another branch that uses the same dependencies.  Commits …
> build: Speed Up CI Config Steps

- .circleci/config.yml
This PR is a follow up to https://github.com/GetJobber/atlantis/pull/837.
- There is another persist and some storing of artifacts that is slowing down the `build_docs` step. 
- Also, SSH pub key for `github_authentication` and a fingerprint are put into nice CI variables.
---
> build: Remove extra persist, use ssh variables

- .circleci/config.yml
Releases are failing now because of the SSH key variable added for this PR: https://github.com/GetJobber/atlantis/pull/840
More investigation is required into why it's failing.  So for now, it's best to unblock the release process until the solution can be finalized!!!
---
> build: Revert back ssh key to make release pass

- packages/docz-tools/gatsby-node.js
When working in Atlantis, the development mode was looking into the `dist` directory for hooks. This was causing developers to have to run an `npm run build` each time they saved their hook in order to see changes. This will change that to look in the `src` directory.
- 
- 
- 
- 
- Alias to `@jobber/hooks`
- 
---
> build: @jobber/hooks use the src dir instead of dist

- packages/components/src/Card/Card.tsx
- packages/components/src/Card/tests/Card.test.tsx
Card in Atlantis is not representative of desired output. It should use the `heading` color in the header, and because it had previously only been used in projects (Jobber) that had the desired color for `h3` elements set in global CSS, the production output was never an issue.
However as external applications are being built that leverage Atlantis, we should specify the heading color so that it does not inherit from whatever the external app's `body` color is set to.
- set `textColor` on Card's heading
---
> feat(components): add explicit "Heading" color to Card header

- packages/components/src/Button/Button.css
When a button label is large enough, the text wraps. For visual balance, this wrapping should be left-aligned when an icon is present. Additionally, when both an icon and a long text label is present, it should not squish the icon down into nothingness.
- Buttons with Icons and long text labels now have left-aligned text labels
- Buttons with Icons and long text labels do not shrink the Icon down
---
> feat(components): Left-align wrapping button labels when Icon is present 

- packages/components/src/FormatFile/FormatFile.css
- packages/components/src/LightBox/LightBox.css
- packages/components/src/Menu/Menu.css
- packages/components/src/Modal/Modal.css
- packages/design/src/colors.css
We'd like to replace our grey-blue overlay color as it very different than native mobile alert overlays which can be jarring particularly if they appear back-to-back. Also I can't remember what Josh said exactly, but the grey-blue looks off/dated.
- Overlay color set to default Material overlay values
- Added black as a base color to use as a base for the overlay color.
---
> feat(design): update overlay color to black

- packages/hooks/package-lock.json
- packages/hooks/package.json
Hooks is the only package that has @types/jest directly. This should already be handled by the root folder so it can be removed from hooks.
This got brought up when dependabot created a PR to bump one of its dependencies under hooks. See more context in https://github.com/GetJobber/atlantis/pull/674
- 
- 
- 
- Uninstall @types/jest under hooks
- 
- 
---
> build(deps): Uninstall @types/jest under hooks

- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/useTooltipPositioning.ts
- An issue was raised around tooltip arrows aren't aligning to the middle on both Atlantis and Jobber
- The Atlantis issue was pretty straightforward but, the Jobber issue was a mystery
- Updating tooltip to use `react-popper`'s `usePopper` instead of `@popperjs/core`'s `createPopper` is long overdue so that needed to be updated anyway
- We hoped that it fixes all the issues since it also removes the cruft that came with using `createPopper` and that it did!
- 
- replaced `createPopper` with `usePopper`
- 
- Transition out has been removed because it doesn't work well with `usePopper`. Lesser of the 2 ~evils~ things and whatnot
- 
- 
- it's on the activator instead of the tooltip because if the tooltip renders at the edge and there's no space, it will reposition itself but the arrow is …
> fix(components): Update tooltip to use react-popper

- packages/components/src/Popover/Popover.css
* Popover component was being displayed **under** some elements on Jobber online
* Additionally, the popover width was limited by the width of the element it was attached to
- 
* Replaced the component's previous z-index, `--elevation-base` with `--elevation-tooltip`
* Replace the component's previous width, `100%` with `max-content`
- 
- 
- 
- 
---
> fix(components): Update popover elevation and width

- packages/components/src/StatusLabel/StatusLabel.css
- packages/components/src/StatusLabel/StatusLabel.css.d.ts
- packages/components/src/StatusLabel/StatusLabel.mdx
- packages/components/src/StatusLabel/StatusLabel.test.tsx
- packages/components/src/StatusLabel/StatusLabel.tsx
- packages/components/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
- packages/components/src/StatusLabel/index.ts
With the introduction of the [StatusLabel component to the mobile app](https://atlantis-mobile.jobber.dev/?path=/docs/core-status-and-feedback-statuslabel--status-label) (internal Jobber access only) and some in-Jobber cleanup to remove a deprecated internal "StatusLabel" component, this seems a good time to carry out the plan to introduce component parity with mobile and add our desired StatusLabel to Atlantis for web.
The approach here is largely informed by the approach @dmcrorieGIT used in building our mobile component, with some adjustments for web.
- StatusLabel component, docs, and test suite
---
> feat(components): create statuslabel component

- packages/design/package-lock.json
- packages/design/package.json
- packages/design/rollup.config.js
- packages/design/src/icons/getIcon.ts
For some reason, rollup doesn't want to bring over the `.css.d.ts` file even tho we're referencing it. Could have something to do with the way those `typed-css-module` exports the type with the old-style imports `export = styles`.
Anyhoo, this makes rollup copy those files in the correct place. It now autocompletes again.
Prop table colors now shows the correct type
- Added a plugin called `rollup-plugin-copy` to copy the missing `.css.d.ts` files over to `dist` so it gets exported
- Make rollup use the `rollup-plugin-copy`
- Update icon sizing type to use the existing type file rather than hard coding it
- Updated `rollup-plugin-typescript2` to latest since it has issues/bug with async methods 
- https://github.com/ezolenko/rollup-plugin-typescript2/issues/105
- 
- 
- 
- 
Install the …
> fix(design): Add back missing icon colors types

- packages/components/src/Banner/Banner.test.tsx
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
Wrapping all of the children of `Banner` in `Text` has unintended consequences when I want to build my banner with more than just text (ie button and other sections)
Conditionally wrap the `children` of `Banner` in `Text` only if they are a `string`.
- If you used the `Banner` in the past with more than just a simple string, this will affect how your component renders now.
> feat(components): only wrap Banner children in Text if they are a simple string. 

- packages/components/src/RadioGroup/RadioGroup.css
Radio labels were inheriting font-size from the document body, making them larger than other input elements and `p` elements.
- Explicit font-size declaration on radio labels
- Radio labels will no longer rely on their parent site's `body` to determine font-size
---
> fix(components): set radio labels to base fontSize

- docs/content/product-vocabulary.mdx
We have a mix of x and × to indicate multiplication
- guide on proper use of multiply symbol ×
---
> docs: add multiplication notes to content guides

- packages/components/src/InputFile/InputFile.test.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
Allowing the component to handle PUT requests makes it more flexible. ActiveStorage creates pre-signed URLs that are to be used with PUT requests, so it is required for our work.
The `InputFile` component now allows PUT requests to be performed.
In your local Atlantis playground, you can go to the `InputFile` page and modify it so that its `getUploadParams` prop/ method returns the following in a promise:
```Javascript
{
url: "https://address_where_you_can_put.com",
fields: {
"Content-Type": "image/jpeg",
"OTHER-APPROPRIATE-HEADERS": "appropriate_header"
},
httpMethod: "PUT" 
}
```
example:
---
> feat(components): JOB-40406 Allow PUT requests in InputFile component

- packages/components/src/FormatFile/FormatFile.css
- packages/components/src/FormatFile/FormatFile.css.d.ts
- packages/components/src/FormatFile/FormatFile.mdx
- packages/components/src/FormatFile/FormatFile.test.tsx
- packages/components/src/FormatFile/FormatFile.tsx
- packages/components/src/FormatFile/FormatFileDeleteButton.tsx
- packages/components/src/FormatFile/InternalThumbnail.css
- packages/components/src/FormatFile/InternalThumbnail.css.d.ts
- packages/components/src/FormatFile/InternalThumbnail.tsx
- packages/components/src/FormatFile/__snapshots__/FormatFile.test.tsx.snap
We needed the ability to view format files as thumbnails
Added new props to allow format file to be displayed as a thumbnail
- we didn't add spacing to the component to allow for devs to set their own spacing
In playground with a format file, set display to "compact".
https://www.figma.com/file/b7LY6hVMwFOj5maidxPTMB/Design-System-Contribution-%5B-Thumbnail-%2B-Gallery-%5D?node-id=1420%3A19642
---
> JOB-40406 Modify FormField Altantis Component For Thumbnail Functionality

- packages/components/src/Chips/InternalChipAffix.tsx
- packages/components/src/Chips/InternalChipButton.tsx
- packages/components/src/Chips/tests/InternalChip.test.tsx
- packages/components/src/Chips/tests/InternalChipButton.test.tsx
- packages/components/src/Typography/css/TextColors.css
- packages/design/src/colors.css
We're updating our "base red" to be a bit less orange, and have a slightly higher contrast ratio on a white background. As a result, we can also move away from using `critical--onSurface` on white backgrounds, as that value is mainly intended to be used overtop `critical--surface`.
- updated rgb values of base red palette 
- updated components using `critical--onSurface` when not overlaid over red
- Base red [+ critical + destructive semantic values]
- Chip (when invalid)
- Button (destructive) 
- Text (error)
- InputValidation
- InputText (validation message)
- Card (accent = red)
- Icons (trash, userUnassigned, reminder, badInvoice)
- View color docs, Button, Chip, Text, InputValidation... basically the things from the screenshots above
--- …
> feat(design): update base red and usages of critical onSurface [JOB-48592]

- jest.config.js
- package-lock.json
- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/Markdown/Markdown.tsx
Update react markdown to latest so we can render it on storybook without it throwing 
```
Uncaught TypeError: Object(...).cwd is not a function
```
- 
- Updated react markdown to latest
- 
- 
- Storybook failing to render it
- 
- Ensure it still works like before
Running jest would throw this error
```  ● Test suite failed to run
Jest encountered an unexpected token
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
Here's what you can do:
• If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
• To have some of your "node_modules" files transformed, you can …
```
> chore(deps): Update react markdown to latest

- packages/components/src/FormatFile/FormatFile.tsx
- packages/components/src/FormatFile/__snapshots__/FormatFile.test.tsx.snap
We noticed a bug where clicking on a gallery thumbnail would trigger a form submission if the gallery was wrapped in a form
- Explicitly add `type="button"` to `DetailsContainer` of `FormatFile`, since `<button>` will default to a submit type
<details>
<summary>Change the first playground in Form.mdx to have a gallery</summary>
```
<Playground>
{() => {
const [{ isDirty, isValid }, setFormState] = useFormState();
const [first, setFirst] = useState("");
return (
<Form
onSubmit={() => alert("Submitted 🎉🎉🎉")}
onStateChange={setFormState}
>
<Content>
<InputText
placeholder="First Name"
name="firstName"
value={first}
onChange={setFirst}
validations={{
required: {
value: true,
message: "Tell us your name",
},
minLength: {
value: 3,
message: "Your name is to short.",
},
}}
/>
<InputText …
```
> fix(components): Clicking On FormatFile Triggers Form Submit

- packages/hooks/src/useCollectionQuery/mdxUtils.ts
- packages/hooks/src/useCollectionQuery/test-utilities/mocks.tsx
- packages/hooks/src/useCollectionQuery/test-utilities/queries.ts
- packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
- Comms Experience is attempting to reduce the load times of conversation queries. TotalCount is expensive, so if we remove totalCount from the query we should experience some wins.
- Make totalCount optional.
- If totalCount is not supplied, do not return it. 
- totalCount optionally returned
In both JO and JM:
- From JO: 
- app/javascript/jobber/chat/components/ChatDrawer/Chat/Chat.graphql.ts
- app/javascript/jobber/chat/components/ChatDrawer/NotificationList/NotificationList.graphql.ts
- remove reference to totalCount within NotificationListWrapper around line 113
- From JM: 
- src/features/SmsCommunication/views/Conversation/Conversation.graphql.ts
- src/features/SmsCommunication/views/ConversationList/ConversationList.graphql.ts
--- …
> feat(hooks): allow totalCount to be optional -- (Minor) Feature Release

- packages/components/src/FormatFile/FormatFile.css
Thumbnail component needs to have a border to match [figma](https://www.figma.com/file/b7LY6hVMwFOj5maidxPTMB/Design-System-Contribution-%5B-Thumbnail-%2B-Gallery-%5D?node-id=1420%3A19639) and so that they still look nice in the case of white backgrounds
- Add border on compact thumbnail component
---
> fix(components): add a border to thumbnail 

- packages/components/src/Chips/InternalChipDismissible/hooks/useInView.ts
- packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissible.ts
- packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
- packages/components/src/Chips/InternalChipDismissible/hooks/useScrollToActive.tsx
- packages/components/src/Modal/useFocusTrap.ts
- packages/components/src/Tooltip/useTooltipPositioning.ts
- packages/eslint-config/.eslintrc.js
- packages/eslint-config/package.json
There was a lot of discussion around the rule and we eventually decided to take it out. Because we're using tools and libraries that aren't as strict about `null` as this rule it means there's lots of cases where `null` is valid and necessary value to assign to a variable. An example of this is null fields in GraphQL. If a field is nullable and you want to test the null case your test data will necessarily have `null` in it. The rule meant that we were regularly adding exceptions or doing other type acrobatics to make the linter happy.
- 
- 
- 
- 
- 
- 
---
> chore(eslint) Removing `no-null` linter rule

- packages/components/src/Menu/Menu.tsx
If `Menu` is used in a form, the default HTML type of `button` being Submit causes the form to be accidentally submitted.
- specified type of "button" on the button used in Menu
- Menu can be used in forms without workarounds
---
> fix(components): update menu item button type

- packages/hooks/README.mdx
- The "useResizeObserver" link was broken.
- Start the URL with a /.
> docs: Fix broken link on /packages/hooks

- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/MultiSelect/DropDownMenu.css
- packages/components/src/MultiSelect/DropDownMenu.css.d.ts
- packages/components/src/MultiSelect/DropDownMenu.tsx
- packages/components/src/MultiSelect/MultiSelect.css
- packages/components/src/MultiSelect/MultiSelect.css.d.ts
- packages/components/src/MultiSelect/MultiSelect.mdx
- packages/components/src/MultiSelect/MultiSelect.test.tsx
- packages/components/src/MultiSelect/MultiSelect.tsx
- packages/components/src/MultiSelect/index.ts
- packages/components/src/MultiSelect/types.ts
- packages/components/src/MultiSelect/utils.ts
Add new MultiSelect component to have the ability to select multiple options in a list
MultiSelect Component with the following features:
- Options displayed as a list of checkboxes;
- Custom default Label, Custom All options selected Label;
- The MultiSelect trigger element contains a downward-pointing-arrow to hint that it can be expanded;
- Users are able to focus the MultiSelect trigger element by using the Tab key;
- Users should be able to display the options by using the Space or Enter/Return keys;
- Users should be able to navigate through the options by using Tab or ArrowDown/ArrowUp keys and check/uncheck them by using Space or Enter/Return keys;
- Users can press the Escape key, click out of the component or click the trigger again to close the menu;
- Features and behavior are …
> feat(components): MultiSelect component

- packages/components/src/DataTable/DataTable.tsx
- packages/components/src/DataTable/Header.tsx
- packages/components/src/DataTable/Pagination.tsx
- packages/components/src/DataTable/createTableSettings.ts
- packages/components/src/DataTable/types.ts
The height of the dropdown box was a little taller than we planned for:
- Adjust items per page dropdown height in the footer;
- Remove svg placeholder from headers;
> fix(component) Adjust dropdown height in DataTable compoment

- packages/components/src/DataTable/Body.tsx
- packages/components/src/DataTable/DataTable.mdx
- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/Footer.tsx
- packages/components/src/DataTable/Header.tsx
- packages/components/src/DataTable/test-utilities/mocks.ts
To be able to adjust the column width manually in order to emphasize column data
- Configurable column width options in column prop (`size, minSize, maxSize`)
- Add `size, minSize, maxSize` to a `column` object and test if this style is applied to the column element
---
> feat(components): Add configurable column width to DataTable

- packages/components/src/Tooltip/Tooltip.css
The tooltip arrow looked normal on white backgrounds. However, on non-white background it was possible to see white triangles on each side of it.
* Initialized the tooltip arrow background colour as transparent
* Set arrow background colour to `var(--color-informative--surface)` after the tooltip arrow is rotated
---
> fix(component) only add tooltip arrow background colour after rotation

- .circleci/config.yml
Updated the deploy key's fingerprint based on https://circleci.com/docs/add-ssh-key/#adding-ssh-keys-to-a-job
- fix(Build): SSH Key fingerprint not matching for release
> fix: Update ssh-key fingerprint for release

- .circleci/config.yml
Updated the deploy key's fingerprint based on https://circleci.com/docs/add-ssh-key/#adding-ssh-keys-to-a-job
The problem was that the deploy key didn't have permissions so a new one was needed
See #960 
- fix(Build): SSH Key fingerprint not matching for release
> fix: Update ssh-key fingerprint for release take 2

- .circleci/config.yml
Updated the deploy key's fingerprint based on https://circleci.com/docs/add-ssh-key/#adding-ssh-keys-to-a-job
The problem was that the deploy key didn't have permissions so a new one was needed
See #960 
- fix(Build): SSH Key fingerprint not matching for release
SEE: https://github.com/GetJobber/atlantis/pull/963
> fix: Update ssh-key fingerprint for release take 3

- packages/components/src/DataTable/DataTable.test.tsx
- packages/components/src/DataTable/index.ts
- packages/components/src/DataTable/test-utilities/helpers.ts
- packages/components/src/DataTable/test-utilities/index.ts
Add `mockContainerWidth` function to enable DataTable Footer to be tested.
As `DataTable` footer uses the `useResizeObserver` hook, when a developer tries to jest mock this hook from `jobber/hooks` package in an external project, it doesn't work because the reference isn't the same as the DataTable one.
- `mockContainerWidth` test utility helper function
- You can use the `mockContainerWidth` function in a jest test in an external project by copying the DataTable folder under dist and pasting inside the project node_modules jobber dist folder.
---
> feat(components): Add DataTable test helpers

- packages/components/src/RadioGroup/RadioGroup.css
Radio buttons were shrinking when it has long label text
added the css prop `flex-shrink: 0` to the container
> fix(components): Fix radio button shrinking when label is too long

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormField.tsx
- `FormField` was passing `autocomplete` as `autocomplete=“autocomplete-off”` when provided `false`, when it should be passing only `"off"`
- when `autocompleteSetting === false`, simply return `"off"`
---
> refactor(components): update autocomplete false value in FormField 

- packages/design/jobberStyle.js
Export Atlantis' CSS variables to a SCSS.
- The build phase of jobberStyles.js where to also generate a SCSS files with our colors to be consumed.
1. Open your cmd in the root of atlantis
2. `cd packages/design`
3. `npm run build`
You'll see that a `foundation.scss` file was generated along with other files.
---
> build(design): Export Atlantis CSS vars to SCSS

- packages/components/src/Typography/css/Typography.css
Modify the typography scale to account for new typeface
- Typography scale from `smaller` to `large` inclusive, have been bumped down by 2px.
- scale is now calculated relative to `--typography--fontSize-large` instead of `--base-unit`
- can compare typography size to the Figma; ex. Headings in the Figma match px size of new typography scale
---
> refactor(design): Adjust base typography scale

- package-lock.json
- Addresses [CVE-2022-41940](https://github.com/advisories/GHSA-r7qp-cfhv-p84w)
- Doesn't appeared the bot have spotted an issue however, it looks like we are using a vulnerable version (3.4.2)
- This PR bumps it to safety, to v3.6.1
- Bumping the required `engine.io` sub dependency and requirement to 3.6.1
- Addresses [CVE-2022-41940](https://github.com/advisories/GHSA-r7qp-cfhv-p84w)
- Pending CI, hosted CloudFlare page and Atlantis' behavior should continue to work without observable differences
> Bumping `engine.io` sub dependency version to 3.6.1

- package-lock.json
- Addresses [CVE-2022-37599](https://github.com/advisories/GHSA-hhq3-ff78-jv3g)
- Instead of individually managing all the PRs opened by Dependabot, I've decided to address it in one go
- This single PR should take care of [the 4 PRs dependabot have created](https://github.com/GetJobber/atlantis/pulls?q=is%3Apr+is%3Aopen+loader-utils)
- Bumping the required `loader-utils` to 1.4.2 will lift all sub-dependencies to use the same version as well
- Addresses [CVE-2022-37599](https://github.com/advisories/GHSA-hhq3-ff78-jv3g)
- Pending CI, hosted CloudFlare page and Atlantis' behavior should continue to work without observable differences
> Bumping `loader-utils` to v1.4.2

- packages/components/src/Typography/css/Typography.css
- packages/design/src/typography.css
To allow font tokens to be easily shared / used
- New typography tokens to design package
- typography tokens definitions from Typography component styles
- Test if all places using Typography still have the same styles using values from typography tokens.
---
> refactor: Move all Typography token variables to design package

- package-lock.json
- packages/docz-tools/package-lock.json
- packages/eslint-config/package-lock.json
- Addresses [CVE-2022-46175](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)
- Instead of individually managing all the PRs opened by Dependabot, I've decided to address it in one go
- Our sub-dependency `json5` is being used by other tools, so it was pulling in major version `1` and `2`
- This PR bumps both major versions to safety grounds, @ `2.2.3` and `1.0.2` respectively
- Addresses [CVE-2022-46175](https://github.com/advisories/GHSA-9c47-m6qq-7p4h)
- Pending CI, hosted CloudFlare page and Atlantis' behavior should continue to work without observable differences
> Bumping json5 dependency to 1.0.2 and 2.2.3 throughout Atlantis

- packages/components/src/Typography/Typography.mdx
- packages/design/src/Typography.mdx
Documentation for `Typography` needs to be updated to reflect new `base` font-size.
- Typography component is now exposed (with updated Playground displaying all sizes)
- added typography and line height token tables to the Typography Design page
- Updated wording in [Font Sizes](http://localhost:3333/typography#font-sizes) section of Typography component
---
> docs(design): Update Typography documentation to reflect new base font-size

- packages/components/src/Popover/Popover.css
- packages/docx/src/ColorSwatches/ColorSwatches.css
Prepping for updated font families and styling guidelines
- Nothing visual at this point
- updated casing of internal component
- updated CSS property for Popover font-size
- go to ColorSwatch docs and verify group titles are title-case instead of uppercase ("Interactive" in this example)
- go to Popover and verify text inside Popover uses `base` fontSize
---
> refactor(components): Update typography for Popover and ColorSwatches

- packages/design/src/typography.css
Work to adjust the Typography scale was originally done in [this PR](https://github.com/GetJobber/atlantis/pull/976), but was overwritten by changes to move the scale to a different file.  This PR is to correct that and re-add the new typography scale.
- Typography scale from smaller to large inclusive, have been bumped down by 2px
- scale is now calculated relative to `--typography--fontSize-large` instead of `--base-unit`
There is strange behaviour on loading within the two tables; for the purpose of getting this scale back into the feature branch, this will be addressed in a future PR
---
> refactor(design): Re-add typography scale

- packages/components/src/FormatFile/FormatFile.tsx
- packages/components/src/FormatFile/__snapshots__/FormatFile.test.tsx.snap
Match new style for FormatFile component because the typography has been updated
Updated `font-size` of the filename
Before:
After:
- `font-size` from `large` to `base` to match Figma
- updated snapshot tests
---
> refactor(components): Update FormatFile filename size

- packages/design/src/Typography.mdx
Just rounded the line height value to have a maximum of 3 decimals.
Rounded the value
---
> fix(docs): Round the decimals on line height

- packages/docz-tools/src/gatsby-theme-docz/components/Navigation/Navigation.module.css
Within each dropdown in the side nav, each component bullet was size `small` but new typography means they should be `base` instead
Before:
After:
- look at sidebar locally and inspect to be sure it's now `14px`
---
> refactor(components): Increase sidenav component list from small to base

- packages/components/src/Card/Card.tsx
- packages/components/src/Card/tests/Card.test.tsx
- packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
- packages/components/src/Drawer/Drawer.css
- packages/components/src/Drawer/Drawer.tsx
- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
- packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
- packages/components/src/Modal/Modal.tsx
- packages/components/src/Modal/__snapshots__/ModalSnapshots.test.tsx.snap
Update to match new designs with Jobber Pro and Inter
- Drawer, Modal, and Card now consume Heading level 3
- Padding on Drawer adjusted to match Figma
- Heading level 3 now uses Jobber Pro
- Go to Drawer, Modal and Card locally
- Can also checkout ConfirmationModal
---
> feat(components): Update drawer, modal and card headings

- packages/components/src/Switch/Switch.css
New Typography adjustment caused slightly off center vertical alignment of the label within Switch component
- `margin-top: var(--space-minuscule);` within `label` element
---
> refactor(components): Fix vertical spacing of label within Switch component

- packages/components/src/Banner/Banner.mdx
The validation link seems to be broken in production but works locally. So I think I'd have to change it further to work but IDK?
Anyway I thought I would push people to the more common validation page first regardless.
> Cleanup: Update validation link for banner

- packages/design/jobberStyle.js
Follow-up of #959 , now exporting the spacing variables to the `foundation.scss` file.
- Added the resolved spacing variables to the `foundation.scss` file
The Spacing tokens should be at the end of `foundation.scss`
---
> build(design): Export spacing tokens to SCSS

- packages/design/jobberStyle.js
Follow-up of #959 , now exporting the timing and elevation variables to the `foundation.scss` file.
- Added the resolved timing and elevation variables to the `foundation.scss` file
The timing and elevation tokens should in the file `foundation.scss`
---
> build(design): Export timing and elevation tokens

- packages/design/jobberStyle.js
Follow-up of #959, now exporting the `border` and `radius` variables to the `foundation.scss` file.
- Added the resolved `border` and `radius` variables to the `foundation.scss` file
The `border` and `radius` tokens should be in `foundation.scss`
---
> build(design): Export border and radius tokens to SCSS

- packages/design/jobberStyle.js
Follow-up of #959, now exporting the typography variables to the `foundation.scss` file.
- Added the resolved typography variables to the `foundation.scss` file
The typography tokens should be in the file `foundation.scss`
---
> build(design): Export Typography tokens

- packages/design/jobberStyle.js
Refactor the function that exports the design tokens to SCSS.
- Just clean up and refactor.
The exported tokens should be the same as `master`
---
> refactor(design): Cleanup function to export SCSS tokens

- packages/components/src/DataTable/SortIcon.css
CSS Selector was affecting other icons (truck, for example) and filling them with grey blue.
- SortIcon CSS selectors
---
> fix(components): Make CSS selector more specific on SortIcon to not affect other icons [JOB-61694]

- packages/components/src/ConfirmationModal/ConfirmationModal.tsx
- packages/components/src/ConfirmationModal/tests/__snapshots__/snapshot-ConfirmationModal.test.tsx.snap
In the [PR](https://github.com/GetJobber/atlantis/pull/969) that added additional functionality to the `ConfirmationModal` we assign the default `size` property to the `small` value. This led to only 2 sizes being available for the modal size: `small` and `large`. 
We want to ensure that if `size` property is not supplied, none of the styles for the size modal will be applied, meaning that it will be the default size.
Remove the default value for the `size` prop in the `ConfirmationModal` component.
n/a
The `small` size prop was a default value. Now, `size` doesn't have default value.
n/a
n/a
- 
n/a
- 
n/a
- 
Go to the Confirmation modal and open it. Should open the modal.
If you provide `small` or `large` size value - the size of the modal should change correspondingly.  
---
[In …
> fix(components): Remove default value for prop size in ConfirmationModal

- packages/components/src/InputAvatar/InputAvatar.test.tsx
Allow us to release and fix flakiness after
- 
- Temporarily skip InputAvatar flaky spec
- 
- 
- 
- 
---
> build: Temporarily skip InputAvatar flaky spec

- doczrc.js
- gatsby-config.js
- gatsby-node.js
For some reason, gatsby within docz doesn't want to ignore stories files so this makes sure it has the necessary pieces (more like disable) to work.
- 
- 
- 
- 
- 
- 
The `npm start` `npm run build` and `npm run storybook` should all build fine without stopping in an error
---
> docs: Make docz gatsby work with stories again

- packages/components/src/FormField/FormField.css
iOS safari text inputs have their own styling for disabled, this PR should override it to look like Atlantis and not iOS.
- Styling for disabled input
- 
- 
- 
- 
- 
- View on iPhone
- View on Desktop
- It should look exactly the same
---
> fix: Override iOS default styling for disabled input

- docs/content/product-vocabulary.mdx
@lorborb recently helped us get aligned on a direction to consistently present "timesheets" as "timesheets" and not "time sheets". This documents that decision for future questions about the "right" spelling.
- Timesheets guidance to our product vocabulary
Go to the [product vocabulary docs](https://add-timesheets-guidance-to-p.atlantis.pages.dev/content/product-vocabulary#timesheets) and make sure the timesheets section is there
---
> docs: add timesheets to product vocabulary

- docs/content/product-vocabulary.mdx
Timesheets was misspelled
'time sheets' to 'timesheets'
Spelling error
Check to see if 'timesheets' is spelled without a space
---
> docs: Update spelling of Timesheets

- packages/components/src/RadioGroup/RadioGroup.css
Style was updated for alignment around multiline children for the `RadioGroup` component. According to the [Contribution Guidelines](https://github.com/GetJobber/atlantis/blob/80ab88b320ffbb94af1dfd20c055ebd771c4bcaa/docs/CONTRIBUTING.md#bugfix), this is probably a BugFix, because the alignment is of the radio button when there are multiple children is broken. This _does_ affect the visual layout for the existing example in Docz that shows the component with user icons (this is shown in the before and after sections below).
We will do an audit of existing usage in Jobber to make sure this is working as intended and no consumers are affected.
- RadioGroup.css:
Added a top margin and updated alignment to be flex start instead of vertically centered. Used a `margin-top` of `smallest` for the …
> fix: JOB-62724 Update RadioGroup alignment

- packages/components/src/readme.stories.mdx
- packages/eslint-config/readme.stories.mdx
- packages/hooks/readme.stories.mdx
- packages/stylelint-config/readme.stories.mdx
Packages:
- Components
- Eslint Config
- Hooks
- Stylelint Config
Note: Docz Tools is not being added and Formatters doesn't contain any content
Updated the way these `README`'s get loaded in Storybook -> by loading from the original `README` instead of duplicating a file, **except** for these instances:
- _Hooks_: Decided to copy the `README` contents in the `stories.mdx` file because it contains a link to `useResizeObserver`.  I can't change that link directly in the original `README` right now, as it would change the link in docz hosted Atlantis web. 
- _Stylelint Config_: For an unknown reason, auto-formatting on save was not working when trying to pull contents directly from the original `README`. This was stopping the file from loading in Storybook so chose to just copy original …
> docs(components): Update Packages section

- .storybook/assets/css/preview.css
- packages/components/src/Button/Button.stories.mdx
The content guidelines for Button were deleted in the move to Storybook. In bringing them back, I also wanted to address feedback around Storybook's default table display which we use primarily for "Do/Don't" examples and highlighting token values. This is really hard to read!
- Storybook's tables how have even-width columns for the first two columns
- Storybook docs body content max-width has been reduced to 768px for shorter line lengths
- Button has content guidelines once again
View docs for Button, Product Vocabulary, Spacing, etc.
---
> docs: add table styling + bring back content guides for button

- packages/components/src/Card/CardHeader.tsx
It will throw a compile error on React 18 
- 
- Logic around determining the card header content
- Fix a bug where if you put `header={{ title: "Banana" }}` it won't show a card title until you add an action
- 
- 
- 
- 
---
> refactor: Fix typing issue on card header

- docs/guides/frontend-style.stories.mdx
Mitigate future issues like the SVG styling "leak" that @rodrigoeidelvein recently fixed
- rules around CSS selectors to frontend styleguide
---
> docs: add rule about targeting html elements [JOB-61707]

- packages/components/src/FormatFile/FormatFile.css
- alignment of the progress bar was off center in FormatFile
Before:
After:
- Applying `box-sizing: border-box;` to the progress bar fixes the issue
---
> fix(components): Fix progress bar alignment on FormatFile [JOB-63249]

- packages/components/src/LightBox/LightBox.stories.mdx
- packages/components/src/LightBox/LightBox.tsx
- packages/components/src/LightBox/__snapshots__/LightBoxSnapshots.test.tsx.snap
Don't show the navigation buttons when there is only one image in the Lightbox, avoids confusion to the user.
- 
- 
- 
- 
- 
- 
---
> feat(components): only show the navigation buttons on Lightbox when there is more than 1 image

- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
`forceUpdate` from popper was too forceful that it'll crash the whole page and throw an error around `flushSync` when you use dismissible chips. This PR should make it less forceful while still keeping the same functionality.
- 
- replaced `forceUpdate` to `update` in dismissible chips component
- The reason why we needed to update is to reposition the options when you've selected enough chips that it goes into multiple lines. This is so that it doesn't cover the other selected chips.
- 
- 
- 
- 
- Selecting many chips and going into multiple lines should reposition the options and not cover the selected chips.
---
> fix: use update instead of forceUpdate on popper

- packages/components/src/Toast/Toast.test.tsx
- packages/components/src/Toast/showToast.tsx
Get rid of the React warning below by replacing `ReactDOM.render` with `createRoot`.
- Replaced `ReactDOM.render` with `createRoot` on `showToast`
- Fixed tests by closing the toasts at the end of the tests.
- 
- 
- 
- 
- 
- 
---
> refactor(components): replace render with create root

- packages/components/src/Spinner/Spinner.css
We have timing values for animation and one of them matches our duration used in Spinner
- replaced raw value with equivalent Atlantis timing value
- Verify Spinner still spins at expected speed
---
> refactor(components): use Atlantis timing in Spinner

- packages/design/src/typography.css
Responsive behaviour within Heading components was broken.
- Custom media query value was reliant on in-project configuration outside of Atlantis to work
- Font sizes `extravagant`, `jumbo`, and `largest` are responsive outside of the Atlantis repository
**Before:**
**After:**
```
npm i @jobber/components@3.5.6-pre.0+03511639
npm i @jobber/design@0.29.4-pre.49+03511639
```
Or in Jobber, pull down `update-atlantis-headings-to-fix-responsiveness` for testing
---
> fix(design):  preserve responsive behaviour in larger fontSizes [JOB-64729]

- packages/components/src/Button/Button.stories.mdx
Our example buttons did not all follow their own content rules
- casing of sample button docs
View Buttons in storybook
---
> docs(components): update casing of sample buttons to follow guidelines

- packages/components/src/FormField/FormField.css
Because there's no defined lineheight on the fieldffix labels, but there is one on the `input` element, the fieldaffix labels are vulnerable to external stylesheets "leaking in" and causing unsightly inconsistencies when components using FormField are consumed by another project.
- Added a CSS custom prop to the input and used wherever line-height was already being defined, then added it on the fieldaffix where there was no definition. I'm also open to the idea of using `inherit` on the fieldaffix level, or other suggestions for a cleaner way to solve this! 🤷 
- FormField and assorted consumers will no longer have misaligned baselines when the application has a global stylesheet with a different default.
- Set a line-height on the body of the application and see that the FormField …
> fix(components): define and standardize lineheight in FormField

- packages/components/package-lock.json
- packages/components/package.json
- packages/components/src/Form/Form.test.tsx
- packages/components/src/Form/Form.tsx
- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/hooks/src/useFormState/useFormState.ts
`react-hook-form` can now be upgraded to latest because Atlantis is on R18
`react-hook-form` upgraded from `6.15.8` => `7.43.7`
- `errors` has been moved into `formState` object
---
> build(deps): Update react-hook-form to v7.43.7 [JOB-65458]

- jest.config.js
- package-lock.json
- package.json
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/FormatRelativeDateTime/FormatRelativeDateTime.test.tsx
- packages/components/src/Toast/Toast.test.tsx
- packages/design/package-lock.json
- packages/design/package.json
Jest needs to be bumped to `@latest` for our Node 18 upgrade.
- `jest-environment-jsdom`: `29.5.0`
- `jest`: `26.0.1` => `29.5.0`
- `@types/jest`: `26.0.0` => `29.5.0`
- Changed some tests to use `getByText` instead of `findByText`
[Timer Mocks](https://jestjs.io/docs/timer-mocks)
[Run Pending Timers](https://jestjs.io/docs/timer-mocks#run-pending-timers)
[Using Fake Timers](https://testing-library.com/docs/using-fake-timers/)
[From Jest v27 => v28 Upgrade Docs](https://jestjs.io/docs/28.x/upgrading-to-jest28) & [Changelog](https://github.com/facebook/jest/blob/main/CHANGELOG.md#2700)
[From Jest v28 => v29 Upgrade Docs](https://jestjs.io/docs/upgrading-to-jest29) &[ Changelog](https://github.com/facebook/jest/blob/main/CHANGELOG.md#2800)
--- …
> build(deps): Upgrade jest to v29.5.0

- lint-staged.config.js
- packages/components/rollup.config.js
- packages/components/src/DatePicker/DatePickerActivator.tsx
- packages/components/src/List/ListItem.tsx
Used to throw these warnings
Now it's not
- Fix warnings on date picker and list item
- Marked tanstack and react-dom/client as external
- Skip pre-commit hook on tests if nothing was found
- 
- 
- 
- 
- 
---
> fix(components): Fix Typescript warnings on components

- packages/components/src/Button/Button.tsx
Simplify reading the button prop type so developers can more easily read the type to understand what it is trying to achieve.
Removed unneeded inheritance in the sub types.
Removed unused destructive type
Separated type to give descriptive names
Paste this code into the button file. All the objects added to the workingButtons array should be valid 
All the buttons in the badButtons array should have a typescript error
The label or aria label should give some explanation.
Do this on master and in the branch. Behaviour should be mostly the same except for the last bad button preventing the `external` flag existing on with the `to` property.
```
const workingButtons: ButtonProps[] = [];
workingButtons.push({
label: "Button that doesn't do anything",
//should we make it so onClick, submit, …
```
> refactor(components): Remove redundant button prop types

- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
In order to improve accessibility on dismissible chips, we are changing the `ariaLabel` to use the chip `label` instead of the `value` to represent what the user is actually reading instead of the value of the chip that can be an ID.
- Changed dismissible chip to use `label` instead of `value`
- 
- 
- 
- 
- 
- 
---
> fix: Use chip label instead of value on aria-label [JOB-66426]

- packages/components/src/FormatFile/FormatFile.test.tsx
- packages/components/src/FormatFile/InternalThumbnail.css
- packages/components/src/FormatFile/InternalThumbnail.css.d.ts
- packages/components/src/FormatFile/InternalThumbnail.tsx
- packages/components/src/FormatFile/InternalThumbnailImage.css
- packages/components/src/FormatFile/InternalThumbnailImage.css.d.ts
- packages/components/src/FormatFile/InternalThumbnailImage.tsx
It's less than ideal to flash icon thumbnails when the image is loading. Especially if it's the big one.
https://user-images.githubusercontent.com/15986172/230926848-1dbb06ed-6cda-47c9-9429-9800b57bbb12.mp4
https://user-images.githubusercontent.com/15986172/230926887-c74b47b2-9c94-48b4-8405-0068cbee16fd.mp4
- Skeleton loader for image thumbnails
- 
- 
- 
- 
- 
- Open `FormatFile.stories.mdx`
- Do this changes which simulates slow image loading
```diff
diff --git a/packages/components/src/FormatFile/FormatFile.stories.mdx b/packages/components/src/FormatFile/FormatFile.stories.mdx
index bbbf7656..3fc10c3e 100644
--- a/packages/components/src/FormatFile/FormatFile.stories.mdx
+++ b/packages/components/src/FormatFile/FormatFile.stories.mdx
@@ -1,3 +1,4 @@
+import { useState } from "react"; …
```
> feat(components): Skeleton loader for image thumbnails

- packages/design/jobberStyle.js
- packages/design/src/foundation.css
- packages/design/src/opacity.css
To help setup a single source of truth for Design Tokens between jobber-mobile and web, opacity tokens now live in Atlantis
Added `opacity.css` to be included in the design build
Run `npm run build -w @jobber/design` in Atlantis to see the opacity tokens land in `packages/design/foundation.js`
pre-release: `npm i @jobber/components@4.7.1-tay.2+92c06a7b @jobber/design@0.32.1-tay.5+92c06a7b`
You can go to `jobber-mobile` and delete the opacity tokens from `mobile-foundation.ts`.  Test on the `Button` in Storybook to see opacity remains and is being pulled from `@jobber/design` & test in simulator
---
> feat(design): Add opacity tokens to Atlantis web

- packages/components/src/Autocomplete/Menu.tsx
Tests fails in our main repo because the children of the menu are not defined. Adding this guard `?` prevents the failure.
- Check if there are children before calling `scrollIntoView` on them.
---
> fix(components): Autocomplete Menu Test Bug

- .circleci/config.yml
Removing `upload_to_clodfare` step in CircleCI as we don't need it anymore. It was previously added because we did a workaround to build the docs first and then upload it cloudfare, but now that Cloudfare supports Node 18 without errors, we can go back to build and host it there directly.
- Removed `upload_to_cloudfare` step
- 
- 
- 
- 
- 
- 
---
> chore: Remove upload_to_cloudfare step

- .vscode/settings.json
Everyone using Atlantis in VSCode should be pointed at the same TS version
---
> chore: Update VSCode settings to use node_modules TS version

- packages/design/jobberStyle.js
- packages/design/src/getMobileFontSizes.js
Add ability to use Mobile specific design tokens (`typography-fontSize`) and have them bundle with @jobber/design
`typography--fontSize` tokens from mobile now build within mobile related foundation files
---
> feat(design): Move mobile fontSizes into design

- packages/components/src/Autocomplete/Autocomplete.css
There was an issue where the autocomplete options would appear behind the modal. Screenshot: 
Now it will appear in front of the modal so it can be selected. This is a quick fix so the component can be used. 
- 
- Go to anchor as test@example.com
- Go to an account 
- Go to update account
- Scroll down to the distribution channel component 
- Attempt to type in there, and you'll see it appear in front now.
> fix(components): calculate Z index for autocomplete 

- packages/design/src/icons/Icon.css
- packages/design/src/icons/Icon.css.d.ts
- packages/design/src/icons/getIcon.ts
The `archive` icon was made `--color-blue` to match with SG-1 icons ([see PR here](https://github.com/GetJobber/atlantis/pull/142)) however we've decided that `archive` in particular should be the base icon color instead.
`archive` no longer has specific styling
In Storybook, check that the `archive` icon has a fill of `--color-greyBlue` to match the majority of other icons
---
> refactor(design): Change archive icon to standard greyBlue

- packages/components/src/FormField/FormField.css
- packages/design/src/elevations.css
We're dealing with some z-index within the form field component. Sadly, the way z-index works, we have to contain it within the component itself since it is leaking outside of it and creating issues
https://user-images.githubusercontent.com/15986172/235973729-982444ac-a291-4be9-8440-9a6f0092d735.mp4
https://user-images.githubusercontent.com/15986172/235973995-519c5994-4192-4496-bfc7-e40d98d76107.mp4
- Go here https://codesandbox.io/s/placeholder-issue-zrdq7u?file=/src/App.js
- Scroll down
- To fix the issue, open package.json
- Update @jobber/component version to `4.11.1-fix-form-f.2`
Lemme start with z-index doesn't work the way you think it works.
- On the surface level, 2 is higher than 1 (makes sense)
- DOM structure-wise, the lower it is on the DOM, the higher it is on the Z-axis if …
> fix: Ensure form fields positioned children are contained

- packages/components/src/DescriptionList/DescriptionList.css
Currently DescriptionList component width for `key` is `60%` and width for `value` is `40%`. I believe it should be the opposite since usually the keyse are shorter than values
Updated `dd` element width from `40%` to `60%`
Updated `dt` element width from `60%` to `40%`
Before:
After:
> fix(components): fix the styling of DescriptionList component

- .github/pull_request_template.md
- .github/workflows/pr-title-checker.yml
Adds `components-native` as a valid scope for the PR titles
- 
- 
- 
- 
- 
- 
---
> chore: Add components-native to the allow PR titles

- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
The `Select` component what not opening the options if the user clicked on the label. With this fix, I created a class for the select, similar to what we do with textarea and changed the z-index of the input that was behind the label, making it impossible to trigger the select by clicking on the label.
- 
- Add a class specific for the select and changed its z-index
- 
- 
- 
- 
---
> fix(components): Fix Select component hit area

- package-lock.json
- packages/components-native/jest.config.js
- packages/components-native/package.json
- packages/components-native/src/Typography/Typography.test.tsx
- packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
Adding tests to `Typography` on components-native.
I had to install the same version of `react-native-gesture-handler` that we're using on jobber-mobile because they introduced a rule that doesn't make sense for us. 
https://github.com/software-mansion/react-native-gesture-handler/commit/ad626405d966b14966c14d45a0a0c141ed6251e6#diff-10cc5c6712f3dadbd9f8ff4fd42423bf6aa26d6678a909ea908971826e7b115bR403-R409
Now, `GestureDetector` needs to be wrapped on a `GestureHandlerRootView`, but it's already being declared in the root of the app, we don't need it on a simple `Typography` component. Anyways, just venting.
- 
- 
- 
- 
- 
- 
---
> refactor(components-native): Add tests to components-native's Typography

- packages/components-native/src/StatusLabel/StatusLabel.style.ts
- packages/components-native/src/StatusLabel/StatusLabel.test.tsx
- packages/components-native/src/StatusLabel/StatusLabel.tsx
- packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
- packages/components-native/src/StatusLabel/index.ts
- packages/components-native/src/index.ts
- `StatusLabel` component in components-native
- 
- 
- 
- 
- 
---
> feat(components-native): Import StatusLabel to components-native

- packages/components/src/Grid/Grid.tsx
Typescript complains if you try to give Grid only a single Grid.Cell child, but this is valid and should be supported.
Ran into a problem using Grid where I only needed one child element, but Typescript complained about it.
Updated the type of `children` for the `Grid` component
```
<Grid>
<Grid.Cell size={{xs: 12}} >Content!</Grid.Cell>
</Grid>
```
---
> fix(components): TECH-22 Fixing Grid prop type

- packages/components-native/src/TextList/TextList.style.ts
- packages/components-native/src/TextList/TextList.test.tsx
- packages/components-native/src/TextList/TextList.tsx
- packages/components-native/src/TextList/__snapshots__/TextList.test.tsx.snap
- packages/components-native/src/TextList/index.ts
- packages/components-native/src/index.ts
Migrate `TextList`. It was called `ListBulleted` in jobber-mobile.
- `TextList` component in components-native
- 
- 
- 
- 
- 
I created a branch to test this change on jobber-mobile: https://github.com/GetJobber/jobber-mobile/compare/test-branch-textlist?expand=1
As it's just being used by `Banner`, I changed the usage there to `TextList` and also created a example of each (`Banner` and `TextList`) in `ActivityFeed` so it's easier to test.
---
> feat(components-native): Import TextList (currently ListBulleted in JB) to components-native

- packages/design/src/colors.css
- scripts/commentOnPrAfterPreRelease.js
- Changed it so the github action splits the install command into Web and Mobile for the different component packages
- 
- 
- 
- 
- 
- 
---
> build: Split pre release install string based on Web or Mobile

- packages/components/src/FormatDate/FormatDate.test.tsx
- packages/components/src/FormatDate/FormatDate.tsx
This change is required for the Jobber Payments team to display the date using the `FormatDate` component without a year
- 
- `FormatDate` component now has a new optional `showYear` argument.
- 
- 
- 
- 
---
> feat(components): Update formatDate component with optional date

- packages/components-native/src/ButtonGroup/ButtonGroup.style.ts
- packages/components-native/src/ButtonGroup/ButtonGroup.test.tsx
- packages/components-native/src/ButtonGroup/ButtonGroup.tsx
- packages/components-native/src/ButtonGroup/ButtonGroupAction.tsx
- packages/components-native/src/ButtonGroup/components/SecondaryActionSheet/SecondaryActionSheet.tsx
- packages/components-native/src/ButtonGroup/components/SecondaryActionSheet/index.ts
- packages/components-native/src/ButtonGroup/index.ts
- packages/components-native/src/ButtonGroup/messages.ts
- packages/components-native/src/ButtonGroup/types.ts
- packages/components-native/src/ButtonGroup/utils.ts
- packages/components-native/src/index.ts
- feat(components-native): Added ButtonGroup component
- 
- 
- 
- 
- 
`npm run pack @jobber/components-native`
Replace `ButtonGroup` with the button group in `@jobber/components-native` verify it works as expected
---
> feat(components-native): Import ButtonGroup

- packages/components/src/InputText/InputText.tsx
`InputText` was not initially resizing if the user passed the `rows` prop with a `min` and `max` values because `rowRange.min` is passed to `FormField` and we just resized when the `onChange` was called.
Now, it will use `useLayoutEffect` to resize it on the first render too and it will handle the resizing if the input value is longer than the minimum row value.
- 
- `InputText` now resizes in the initial render if the consumer passes the `rows` prop
- 
- 
- 
- 
---
> fix(components): Fix initial resize of InputText when rows are passed in

- docs/CONTRIBUTING.md
- docs/README.md
Updated the link from relative to absolute so it would take you to Storybook, as Storybook page links and Github markdown links are not compatible with each other.
The docs on Github were breaking (blank screen) when following the storybook formatted relative link to the contribution guide.
Made the link absolute to point to the appropriate storybook documentation.
- 
- 
- 
- 
- 
- 
---
> docs: Fix contribution guide and pr title tool links on Github 

- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputNumber/InputNumber.tsx
If you define a custom validation function on InputNumber like this,
```
<InputNumber
placeholder="Custom validation function"
validations={{
validate: validationHandler,
}}
/>
```
The validation function won't run. This was because there's a validation function already defined internally for the component and it doesn't merge the user-defined function with the internal function.
- 
Added a function to merge the validation functions together.
I had to add the function because if I just spread the `validate` property like this,
```
validations={{
...props.validations,
validate: {
...props.validations?.validate,
getOverLimitMessage,
},
```
it fails in the cases where there's no `validate` value defined.
- 
- 
- 
- 
--- …
> fix(components): InputNumber doesn't run custom validations

- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
When you have a clickable row like this
and you try to click the menu (ellipsis), it'll fire both the click on the row and the click for the ellipsis. Clicking outside or a menu item fires the row click again because the menu is nested within the row.
This PR prevents that from happening and treats the menu as a standalone thing that gets no side effect
- 
- Stop event bubbling on menu click
- Implement refocus on activator
- 
- 
- 
- 
```diff
diff --git a/packages/components/src/Menu/Menu.stories.mdx b/packages/components/src/Menu/Menu.stories.mdx
index f50ad907..3b98401a 100644
--- a/packages/components/src/Menu/Menu.stories.mdx
+++ b/packages/components/src/Menu/Menu.stories.mdx
@@ -57,7 +57,11 @@ import { Menu } from "@jobber/components/Menu";
],
}}
>
-    {args => <Menu {...args} />} …
```
> fix(components): nesting menu on a clickable parent shouldn't trigger the parent click [JOB-72895]

- packages/components-native/src/InputText/InputText.tsx
- 
- 
- 
- 
- This PR fixes the duplication of text when dictating on an InputText.
This issue is related to this one from react native: https://github.com/facebook/react-native/issues/36521
- Removed the character U+FFFC on iOS on InputText's handleChangeText
- 
---
> fix(components-native): Workaround to make dictation work without duplicating the text

- .github/workflows/trigger-qa-build.yml
- Add force publish pre-release to `@jobber/components-native` on Github Actions
- 
- 
- 
- 
- 
---
> build(components-native): Add force publish to components-native on Github actions

- .storybook/manager.js
- packages/components/src/Link/Link.stories.mdx
`Link` component was not in a component folder & React imports were not combined
---
> docs: Move Link component to correct folder

- packages/components-native/src/Form/context/AtlantisFormContext.tsx
- packages/components-native/src/Form/context/types.ts
- packages/components-native/src/Form/hooks/useScreenInformation.ts
When migrating `Form`, I created the form context and ended up adding the `headerHeight` to it, but the same property was also added to `AtlantisContext` during the `Menu` migration, so now this value is being used only from `useAtlantisContext`
- 
- `useScreenInformation` now uses `headerHeight` value from `useAtlantisContext`
- 
- 
- 
- 
---
> refactor(components-native): Make useScreenInformation use headerHeight from Atlantis Context

- package-lock.json
- packages/components-native/package.json
- packages/components-native/src/AtlantisContext/AtlantisContext.tsx
- packages/components-native/src/InputCurrency/InputCurrency.test.tsx
- packages/components-native/src/__mocks__/__mocks.ts
We were just using one function from `react-native-localize`, and we actually can replace that function call with a native one from `Intl`.
- 
- The default `timezone` value from `AtlantisContext` is now using the timezone from the native `Intl`
- 
- 
- 
- 
---
> refactor(components-native): Remove react-native-localize dependency

- .storybook/components/Playground/Playground.css
- .storybook/components/Playground/Playground.test.tsx
- .storybook/components/Playground/Playground.tsx
- .storybook/components/Playground/PlaygroundWarning.tsx
There are a few limitations that would arise the more we enable the sandbox.
- New components won't work since the sandbox uses the production version of atlantis components
- The automatic imports isn't perfect and it will make mistakes eventually so we need to implement an escape hatch
- Override auto imports through parameters.code.imports
- Show extra warning when dealing with missing imports error
- This only shows up on dev/local
- 
- 
- 
- 
- 
---
JOB-73908
> docs: add extra warning on code sandbox when it errors out

- docs/components/IconButton/IconButton.stories.mdx
- docs/components/IconButton/Mobile.stories.tsx
What's that? Oh yeah, docs migration.
- IconButton docs baby!
- 
- 
- 
- 
- 
---
> docs: add IconButton docs

- .eslintignore
- .storybook/components/Playground/Playground.css
- .storybook/components/Playground/Playground.test.tsx
- .storybook/components/Playground/Playground.tsx
- .storybook/components/Playground/PlaygroundWarning.tsx
- .storybook/components/Playground/constants.ts
- .storybook/components/Playground/index.ts
- .storybook/components/Playground/types.ts
- docs/components/Button/Web.stories.tsx
Updated tests
Enable third party depedencies in Button's Web storybook
- Added the ability to use Third Party dependencies in the Storybook Playground
- 
- 
- 
- 
- 
- Verify `Button`'s web story correctly imports `react-router-dom`
---
> docs: Allow to PlayGround component to use third party dependencies

- docs/components/InputCurrency/InputCurrency.stories.mdx
- docs/components/InputCurrency/Mobile.stories.tsx
Need to add InputCurrency to the docs!
---
> docs(components): Add InputCurrency Docs

- .storybook/manager.js
- package-lock.json
- package.json
Because we want to know how much traffic we getting and where
- installed `react-ga4` package instead of @storybook/google-analytics since it doesn't support GA4.
- Tracked page visits through manager js
- Also included errors since that's what the @storybook/google-analytics does 
- 
- 
- 
- 
- 
- Install this [chrome extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)
- Ensure your browser extensions that blocks trackers are disabled
- Once done, click the google analytics extension to turn it on. It should have an ON badge
- It should start console logging the infos when viewing pages
Or just trust that it works
--- …
> docs: add Google Analytics tracking

- .storybook/components/Playground/Playground.css
- .storybook/components/Playground/Playground.test.tsx
- .storybook/components/Playground/Playground.tsx
- .storybook/components/Playground/utils.ts
- .storybook/preview.tsx
- docs/components/ActionLabel/Mobile.stories.tsx
- docs/components/Button/Mobile.stories.tsx
- docs/components/ButtonGroup/Mobile.PrimaryAction.stories.tsx
- docs/components/ButtonGroup/Mobile.SecondaryAction.stories.tsx
- docs/components/ButtonGroup/Mobile.stories.tsx
- docs/components/IconButton/Mobile.stories.tsx
- docs/components/Text/Mobile.stories.mdx
- docs/components/Text/Web.stories.mdx
- packages/components/src/Typography/Typography.stories.mdx
- Enable us to show the source code for mobile examples without rendering the preview. This allows consumers to grab the code for the component easily
- Support for playground to render the code snippet without playground ![image](https://github.com/GetJobber/atlantis/assets/15986172/a9e2f58c-495f-4634-a8cc-b74d475b4057)
- Glimmer loading for preview that's still loading ![image](https://github.com/GetJobber/atlantis/assets/15986172/197ea6e8-9503-42d8-9aa1-da0567fa704e)
- Render docs when a code tab shows up for docs ![image](https://github.com/GetJobber/atlantis/assets/15986172/7c655902-e116-44fe-b636-a746bf6bab10)
- Only happens when we do pull the trigger to turn Code tab ON for everything by default
-  Note, this closely follows storybook UX with canvas tab being clickable on docs
- …
> docs: allow code tab with no preview for mobile and other improvements

- .storybook/components/Playground/utils.ts
Noticed that Autocomplete Code is not loading and it was due to the prettier parser being set to babel instead of babel-ts. it didn't know what to do with `useState<State>()`
- 
- change prettier parser from babel to babel-ts
- 
- 
- 
- 
- Autocomplete Code tab should load
- Others should load as well
---
> docs: use babel-ts instead of babel as parser

- .storybook/components/Playground/Playground.test.tsx
- .storybook/components/Playground/Playground.tsx
- .storybook/manager.js
It's apparently not tracking page visits to the Code tab. This should fix that.
- Emit `STORY_CHANGED` on code tab navigation so GA can track them
- 
- 
- 
- 
- 
- Turn off all browser extensions that blocks tracking
- Install [this](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) and turn it on
- It should start logging on the console when GA is being triggered
- Going to code tab should trigger it
---
> docs: track code tab in GA

- docs/components/Disclosure/Mobile.stories.tsx
Having the `<Text>` component within the `args` was breaking to code output in the code tab.  I changed it back to a string.  It can be a Text within `header` in the template however I decided to just keep it simple with a string in `args`.
---
> docs(components): Fix Disclosure mobile example

- packages/components/rollup.config.js
- scripts/entryPoints.ts
Noticed that RecurringSelect isn't being released with the package.
- 
- components rollup to include index.tsx files
https://www.npmjs.com/package/@jobber/components?activeTab=code
https://codesandbox.io/s/recurringselect-atlantis-prod-h7fwd3?file=/Example.tsx
https://www.npmjs.com/package/@jobber/components/v/4.23.39-include-in.1?activeTab=code
https://codesandbox.io/s/recurrinselect-atlantis-this-pr-735zkz?file=/Example.tsx
- 
- 
- 
- 
---
> fix: include index.tsx on component packing

- docs/components/ActivityIndicator/ActivityIndicator.stories.mdx
- docs/components/Spinner/Spinner.stories.mdx
These two were merged around the same time - links were ready to update yet.
Spinner now references ActivityIndicator in Related components
Links to each component are updated
---
> docs(components): Update links for ActivityIndicator and Spinner

- docs/components/InputFile/Web.stories.tsx
Some code tab examples were broken for `InputFile` and the "Variations and Sizes" example didn't behave very nicely, it just hid the controls. 
- Improved the "Variations and Sizes" example allowing a default to handle the args.  Also stopped hiding the controls since the user can just turn them back on. 
- Code tab is working for all InputFile examples now. 
---
> docs(components): fix InputFile code examples

- packages/components/src/Autocomplete/Autocomplete.tsx
The `Autocomplete` component utilizes `InputText` behind the scenes to provide the primary input element that is rendered.
We've encountered a scenario where the following props need to be passed down to the underlying InputText element:
* `suffix` - To style the input with an icon suffix.
* `prefix` - To enable a clear action for the input.
* `inputRef` - A reference to the input element in the DOM so that focus can be activated programatically.
This PR exposes the props listed above on `Autocomplete` and forwards them to the `InputText` child. As the current `name` prop is also forwarded to the input, I opted to remove the explicit reference in favour of forwarding the prop via the spread operator.
- Add the `suffix`, `prefix` and `inputRef` props to the `Autocomplete` component.
The …
> feat(components): InputText Props for Autocomplete

- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
- packages/components/src/InputTime/InputTime.test.tsx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
The value that is provided to the `placeholder` prop is the value that we use for our label element. This value is not required and there are use cases where we aren't providing a placeholder value when using inputs such as when we want an [inline label](https://atlantis.getjobber.com/?path=/code/components-forms-and-inputs-inputvalidation-web--basic). 
Because we weren't conditionally rendering the label element in form filed wrapper only if a placeholder value was provided this element is still being created as an empty label when there is no placeholder value. See markup below with empty label:
This will cause accessibility concerns and is semantically messy.
I have added a small change to only add this label element when there is a placeholder value present.
---
[In Atlantis we use …
> fix(components): Only render the label element if a placeholder value has been provided

- docs/changelog/breaking-changes.stories.mdx
We have deprecated things but not really kept track of them somewhere. This PR adds a page for tracking these upcoming breaking changes
- 
- 
- 
- 
- 
- 
---
> docs: Added upcoming breaking changes to changelogs

- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/InputDate/InputDate.test.tsx
- packages/components/src/InputDate/InputDate.tsx
There's an undesirable flow with the InputDate where tabbing over the input opens the picker, then the tabs are trapped within it, and the only way to close it is to make a selection. This can be annoying if you didn't want to change the date and only wanted to tab past the InputDate.
N/A
Set the preventOpenOnFocus prop to true, making it so that you may interact with the input - perhaps editing the date text without opening the picker or even just tab past it. If you wish to open the picker you must tab onto the button and press enter, alternatively with the `InputDate` component specifically, **clicking** on the input will also launch the picker. This reduces friction for mouse users, allowing them to quick open and close the picker.
This `preventOpenOnFocus` behavior also applies to …
> fix(components): Prevent Open on DatePicker Focus

- docs/components/RadioGroup/Web.stories.tsx
Code tab was failing for RadioGroup's [Custom Radio](https://atlantis.getjobber.com/?path=/code/components-forms-and-inputs-radiogroup-web--custom-radio-option-content) example
- 
- proper import for chips in the Custom Radio Option example
- enabled args on Custom Radio Option example
- remove unnecessary code on the same example
- 
- 
- 
- 
- Code tab in custom radio option under radio group should render
---
> docs: fix custom radio option code tab

- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/InputDate/InputDate.test.tsx
When the InputDate, or DatePicker is used within another component that closes on ESC key press, when the DatePicker is open pressing ESC will close both the picker and the parent component. This is not what we want it to do in that scenario. It should only close the picker, and require another ESC if you want to close say the Modal.
N/A
N/A
N/A
N/A
While the date picker is open, pressing ESC will only close the picker. If there is some parent component that can also be closed on ESC, it will remain open.
N/A
Setup a component that listens to ESC presses for closing, such as a `Modal`, inside there add an `InputDate` or `DatePicker`. Activate the date picker so that the picker is open. Now press ESC and only the picker should close.
--- …
> fix(components): Prevent Closing Parent on DatePicker ESC

- docs/components/Popover/Popover.stories.mdx
As I was going though the Popover documentation I noticed a few broken links that hadn't been updated after the restructuring of the docs. This is just a small PR to fix those. 
- Broken links for the popover documentation.
---
> fix(components): Fix broken links for popover docs

- package-lock.json
- packages/components/package.json
- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.stories.tsx
- packages/components/src/DataList/DataList.utils.tsx
- packages/components/src/DataList/__tests__/DataList.utils.test.tsx
- packages/components/src/DataList/components/DataListTags/DataListTags.css
- packages/components/src/DataList/components/DataListTags/DataListTags.css.d.ts
- packages/components/src/DataList/components/DataListTags/DataListTags.test.tsx
- packages/components/src/DataList/components/DataListTags/DataListTags.tsx
- packages/components/src/DataList/components/DataListTags/index.ts
There's a pretty specific tags pattern in the list where it overflows and counts the ones that aren't visible/half-visible to convey that there are more tags.
This aims to add that pattern.
This is the logic behind it. Say you have 5 tags
- If only 3 are visible, it'll add a + 2 count
- If all 5 are visible, it won't add the + counter
- If 4 are visible and the last is half visible, it'll count that as not visible and add +1
- This is a designer-approved logic.
`IntersectionObserver` is also not available in Jest so a plugin needs to be added to mock it within the test.
- DataList Tag component
- Also test
- 
- 
- 
- 
- 
- Resize your screen to the point that the attributes column content doesn't fit
- It should start counting the labels that gets cut-off/not visible
---
[In Atlantis we …
> chore(components): add data list tags pattern

- docs/components/ActionItem/ActionItem.stories.mdx
- docs/components/ActionItem/Mobile.stories.tsx
- docs/components/ActionItemGroup/ActionItemGroup.stories.mdx
- docs/components/ActionItemGroup/Mobile.stories.tsx
`ActionItem` & `ActionItemGroup` don't have any Storybook docs
- docs pages & mobile examples added for both
---
> docs(components-native): Add ActionItem & ActionItemGroup documentation

- packages/components-native/src/AtlantisContext/AtlantisContext.test.tsx
- packages/components-native/src/AtlantisContext/AtlantisContext.tsx
Adds a new property to `AtlantisContext` called `setHeaderHeight` so it can be set dynamically in jobber-mobile.
I added this because currently we can't use `headerHeight` from `@react-navigation/elements` in the `AtlantisProvider` because the navigation/header is still not defined there.
This way, we can use `headerHeight` as a state in `AtlantisProvider` and update its value in `NavigationHeader`
Example: https://github.com/GetJobber/jobber-mobile/pull/7902/files
- New property in `AtlantisContext` called `setHeaderHeight`
- 
- 
- 
- 
- 
---
> refactor(components-native): Add setHeaderHeight to AtlantisContext

- docs/components/DataList/Web.stories.tsx
- package-lock.json
- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.css.d.ts
- packages/components/src/DataList/DataList.tsx
- packages/components/src/DataList/components/DataListFilters/DataListFilter.const.ts
- packages/components/src/DataList/components/DataListFilters/DataListFilters.css
- packages/components/src/DataList/components/DataListFilters/DataListFilters.css.d.ts
- packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
- packages/components/src/DataList/components/DataListFilters/DataListFilters.tsx
- packages/components/src/DataList/components/DataListFilters/index.ts
- packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
- packages/components/src/DataList/context/DataListContext/DataListContext.tsx
- packages/components/src/DataList/context/DataListContext/index.ts
- packages/hooks/package.json
- packages/hooks/src/useInView/index.ts
- packages/hooks/src/useInView/useInView.test.tsx
- packages/hooks/src/useInView/useInView.ts
Looking at a large set of data requires some form of filtering ability along with its microinteractions. This adds a place for the filters in DataList.
- An ability to pass in `DataList.Filters` to the DataList
- In the event that the amount of filters is bigger than the space we have, the filters would overflow with a fade indicator
- Added a context for DataList to reduce the amount of prop drilling we do which reduces the type issues we'd have in the future.
- Added a hook called `useInView` to check if an element is visible on the screen
- In the essence of time, opted to put the documentation for it on another PR.
- 
- 
- 
- 
- 
To test the overflow, set the story size to small mobile
--- …
> feat(components): implement ability to add a data list filters

- packages/components/src/DataList/DataList.tsx
- packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.css
- packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.css.d.ts
- packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.test.tsx
- packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.tsx
The filters stick to the top even without the column header. It doesn't have an indicator where the header stops so this adds a "border" on it when the filters are sticky when there's no column header.
- DataListStickyHeader to control and determine if the header is stuck
- 
- 
- 
- 
- 
- Set the storybook size to small mobile where the header columns disappear
- With the scroll being at the very top, it shouldn't have a border
- When scrolling down and the filter sticks, it should have a border at the bottom of the sticky filters
- When scrolling down and the column headers are visible, it should not add a thicker border at the bottom
---
> fix(components): add border on DataList header when scrolling without column headers

- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
A few minor adjustments and improvements to the search functionality of the combobox.
updated the way we are applying the gradient to the top and bottom of the list area when it has enough items to be scrollable. the previous way resulted in the `.search` div having a larger height than intended due to the pseudo elements, causing the centering of the X clear button to be off-center.
changed the markup around the clear button to be an actual semantic button. added a focused state here to make it easier to see when interacting with it via keyboard.
added a QoL/UX improvement to give the search input focus again after clearing it either with keyboard or clicks because I found it annoying to have to re-focus it after clearing
updated some class names to be a bit clearer
not a ton new to test …
> feat(components): Combobox Search

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/components/ComboboxContent/index.ts
Add ability to set selected option for the combobox component. We may want the ability to pass in an initially selected value for the selected option for a combobox.
Also a small refactor to update the option element to be an input type="radio" instead of a button because this is more semantically correct and it will be easier to implement multiselect moving forward.
Feel free to let me know if the prop name I chose isn't ideal.
- Added a prop called `preSelectedOption` to set the default selected value from the combobox options.
- Added a test to assure that the selected option is set as the preselected option on render when a value is passed to the new prop.
- Added a test to throw an error if the preselected option provided is not a valid option.
- Try passing in a non random value to …
> feat(components): Ability to set selected option for combobox

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
When there are no `options` loaded into Combobox, there should be a zero index state.  
- an optional prop called `contentNoun` that is meant to describe what the options are within Combobox (example `teammates`, `tax rates`, etc)
- established a variable for whether options exist or not
Zero index state will either return a default or customized string:
Default:
Setting "teammates" to `contentNoun`:
- in the Combobox `Web.stories.tsx` file, comment out the array of options and see the default zero index state message
- now add `contentNoun` to the `Combobox.Content` and pick a noun like "teammates" or "tax rates" and see the customized zero index state message appear
- make sure that search and filter still work as intended
--- …
> feat(components): Combobox zero index state

- docs/components/DataList/Web.stories.tsx
- packages/components/src/DataList/DataList.const.ts
- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.tsx
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListAction/DataListAction.css
- packages/components/src/DataList/components/DataListAction/DataListAction.css.d.ts
- packages/components/src/DataList/components/DataListAction/DataListAction.tsx
- packages/components/src/DataList/components/DataListAction/index.ts
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css.d.ts
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
- packages/components/src/DataList/components/DataListActionsMenu/index.ts
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.css.d.ts
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
- packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
- packages/components/src/DataList/components/DataListItemActions/index.ts
- packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
With a list of items, we need to add a way for the users to trigger actions on them. This allows the user to define what actions can a user do in a single list item.
- Allow consumers to implement actions
- Menu set up to allow us to show a context menu but not implement it yet
- Moving the actions with the layout on smaller screens.
- That's on a different ticket
- Right-click context menu
- Component signature for adding an action on each item
- 
- 
- 
- 
- 
- It should show the first 2 actions, but only if those 2 actions have an icon
- If none of the actions have icons, it shouldn't expose it
- All remaining actions that aren't exposed should show under the overflow more menu
- It should trap the focus when you open the overflow menu
- It should close the menu when you press escape …
> feat(components): Allow actions to be added on a single DataList item

- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
Short version is that accessibility guidelines for Combobox wants the trigger element to have a `role=combobox`
>The combobox role is set on input that controls another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the input.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role
here are a couple examples, one as a button
one as an input
so in our Combobox implementation this needs to go on our Trigger(s), but it needs to be on the literal `button` itself, not only something wrapping them.
for the `TriggerChip` that's fine since we're using a `button` but for `TriggerButton` that's using an Atlantis `Button` and thus we need to add an optional `role` prop to it which is where things got interesting
**Longer …
> feat(components): Add optional role to Button

- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css.d.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
Refactor to update the combobox options as li elements instead of radio inputs.
We made this decision due to accessibility concerns with the fact that when using a radio input when using the arrow keys to switch the selected value an option would be made without using spacebar or enter to confirm a selection and the combobox content would close automatically. This created a weird experience for the user.
---
> feat(components): Refactor options as li elements

- jest.web.config.js
- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListFilters/DataListFilters.test.tsx
- packages/components/src/DataList/components/DataListFilters/DataListFilters.tsx
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/index.ts
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
- packages/components/src/DataList/components/DataListLayoutInternal/DataListHeader.tsx
- packages/components/src/DataList/components/DataListSearch/DataListSearch.css
- packages/components/src/DataList/components/DataListSearch/DataListSearch.tsx
- packages/components/src/DataList/hooks/useMediaQueries.ts
- packages/components/src/DataList/hooks/useMediaQuery.ts
- packages/components/src/DataList/hooks/useResponsiveSizing.ts
- packages/components/src/DataList/hooks/useShowHeader.ts
- packages/components/tsconfig.json
We've recently implemented sorting and it is closely tied to the header showing up. Unfortunately, you can hide that header on any breakpoint which removes the sorting capability even if you have implemented it.
This PR moves the sorting capability to a button whenever the header disappears. That way the user have access to it at all times.
- Move the sorting capability to a button with the filters when the header is not shown
- Capability to import from `@jobber/components` instead of `../../../../../../../`
- Renamed `direction` to `order` since it is more common to hear "sort order" than "sort direction"
- 
- 
- 
- 
- Adjust story size to large mobile <br /> 
- Click this <br />
- That should swap between big enough that it's not a button, and small enough that it is a button
---
[In …
> feat(components): move sorting to a button when the header disappears

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/index.ts
We want the user who is implementing the combobox to be able to clear the selected value from outside of the component.
Added the a `useEffect` that will update the `setSelectedOption` value whenever the `selected prop is updated.
I also updated this prop so that it can be set to null. So if the selected value were to be updated and the null value was passed in this should trigger a rerender and clear the selected value for the combobox.
---
> feat(components): Ability to externally clear combobox selection

- docs/components/DataList/Web.stories.tsx
- packages/components/src/DataList/DataList.tsx
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListAction/DataListAction.css
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
- packages/components/src/DataList/components/DataListItemActions/DataListItemActionsOverflow.tsx
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.css
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.css.d.ts
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.test.tsx
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
- packages/components/src/DataList/components/DataListLayoutActions/index.ts
- packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
- packages/components/src/DataList/context/DataListContext/DataListContext.tsx
- packages/components/src/DataList/context/DataListLayoutContext/DataListLayoutContext.tsx
- packages/components/src/DataList/context/DataListLayoutContext/index.ts
By default, we have implemented the actions to be triggered by hover. However, we want the freedom to place those actions in any location in the layout. 
For example, we want it to be a hover menu on larger screens. But on smaller screens, we want it to be a part of the layout.
- Implement the idea of `DataList.LayoutActions` to be used only within `DataList.Layout` to inject it as part of the layout manually.
- This removes the hover menu whenever you use it on a layout.
- Sent the menu to the body
- 
- 
- 
- 
---
> feat(components): DataList Layout pluggable actions

- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/DataList.utils.tsx
- packages/components/src/DataList/__tests__/DataList.utils.test.tsx
- packages/components/src/DataList/components/DataListItem/DataListItem.tsx
- packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
- packages/components/src/DataList/components/DataListItem/index.ts
- packages/components/src/DataList/components/DataListItemActions/index.ts
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutActions.tsx
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/DataListLayoutContext.tsx
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/index.ts
- packages/components/src/DataList/components/DataListLayoutInternal/DataListItem.tsx
- packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx
- packages/components/src/DataList/context/DataListLayoutContext/DataListLayoutContext.tsx
With the addition of actions and state management around when it opens, it started reinitializing everything the moment you interact with the list. That's due to how we're tracking the state for the menu from the parent instead of for each list.
This PR changes that by introducing the state per each item so the parent doesn't change which stops each data list item from reinitializing (note: I didn't say rerender since it doesn't rerender the element in the DOM). 
Adding a console.log [here](https://github.com/GetJobber/atlantis/blob/462ba662b8856312e33ab613ba51c50864d1aa96/packages/components/src/DataList/components/DataListLayoutInternal/DataListItems.tsx#L37) shows you that wIthout these changes the list items get reinitialized on load more and interacting with it with a mouse
And more …
> fix(components): Improve performance on the list item creation

- docs/components/DataList/Web.stories.tsx
- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.css.d.ts
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.css
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
- packages/components/src/DataList/components/DataListItem/DataListItem.tsx
- packages/components/src/DataList/components/DataListItem/DataListItemInternal.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.test.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickableInternal.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/index.ts
- packages/components/src/DataList/components/DataListLayoutActions/DataListLayoutContext/DataListLayoutContext.tsx
- packages/hooks/src/useFocusTrap/useFocusTrap.ts
We need to allow a row click on the data list. There are 3 classification of an interactable item within DataList (and Jobber)
- normal onClick that is a button
- a link to another page (classic a href tag)
- a route to another page (SPA/PWA/etc)
This PR aims to support those 3.
On top of that, this also adjusts the tabbing experience within the list items.
Voice over accessibility. Is not in this PR. Right now, it is good enough but it could be improved. Infortunately, that involves more thinking around how we handle that so to not block this PR further, we can follow up on that task.
- Tabbing order
- Show actions on focus
- A pretty sweet hover interaction (except for firefox)
- Updated the focus trap hook to either focus on the parent if it's focusable or focus on the very first …
> feat(components): DataList row click and tabbing a11y

- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
- packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickable.test.tsx
- packages/components/src/DataList/components/DataListItem/components/DataListItemClickable/DataListItemClickableInternal.tsx
- packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
When the DataList items are clickable, it becomes a button. Unfortunately, you can also add a button inside it, like the layout actions, so it will fire both the item click and the menu/menu item click. 
So you'll have 2 problems
- HTML would throw an error around a button inside a button not allowed
- The item click fires with the menu click
This PR prevents that from happening.
- `stopPropagation` on places that need it to prevent event bubbling
- The wrapping button to a div with a role of button and acts like a button to avoid the button on button issue
- 
- 
- 
- 
---
> fix(components): nested button issue on DataList

- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
When using DataList in a jest test you get the following error
I tried adding `@jobber/components` and `@jobber/design` and subpaths to the transformIgnorePatterns and that did not resolve the issue
- 
- 
- 
- 
- Fixed using `DataList` in jest tests
- 
- Add DataList to a component and run the test in Jobber Online. Notice the error.
- Install the pre-release and verify that the jest test can run
---
> fix(components): Fixed using DataList in jest tests failing

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/ComboboxProvider.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
This PR adds the prop for the multi select functionality for the combobox component.
This is the first step for adding multi select functionality to the combobox. It will allow us to have a variable to hook off of in order to build the following multi select functionality.
> feat(components): Add multiselect prop to combobox

- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
When investigating some flakiness in some internal Jest tests, it was observed that _part_ of the problem was that a page using `Form` with a dismissible `Chips` component was having the Form submit simply by selecting a new item to add to the dismissable chips selection. I'm not sure why we weren't seeing this behaviour in a browser, but the [HTML spec](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type) does say that the default type for a `<button>` element is `submit`, and [jsdom matches that behaviour](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLButtonElement-impl.js#L52). It doesn't look like that was intentional though; this component is handling it's own activation logic (the `onClick={() => handleSelectOption(option)}` line below) …
> fix(components): Use button type in Dismissable Chip menu items

- .eslintrc.js
- package-lock.json
- package.json
We've always had this warning 
That was meant to catch people importing between packages via `../` their way in there. That's not good because this is a monorepo and relative paths does not exist after packaged up.
This PR turns that off and replaces it with a package that's made for monorepos and relative packages that throws this error now
- harder linter on reaching to another package through `../`
- 
- 
- 
- 
- 
---
> chore: enforce a better relative import

- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxList.css.d.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxList.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxList.tsx
While playing around with Combobox in the muliselect case, it felt a bit weird to have multiple selections, click one to unselect it and it would still have the same grey background. Sure the checkmark was gone, but overall it still felt like it was selected-ish because selected, focus, and hover all applied that background.
Thought I'd check out Polaris' implementation. Over there, they only apply the grey background on hover and focus which I like.
Ran this idea by Chris M, and he agreed it looked good.
This approach is great because it's so simple. No complicated logic where we only apply the selected class if it wasn't already selected or anything like that.
No more extra selected style!
Also, since that style is gone I've had to update the tests that were looking for the style. …
> feat(components): Adjust Combobox Selected Style

- packages/components/src/DataList/hooks/useMediaQuery.ts
When using DataList in a jest test environment, the test would immediately fail because `matchMedia` doesn't exist there. In turn, the consumers would have to mock `matchMedia` on their tests for not a lot of gain since breakpoint changes are already tested by DataList itself.
If the consumer does need to test a specific viewport–such as testing layouts of different screens–the can use the `mockViewportWidth` function from `@jobber/components/useBreakpoints`. Arguably, the layouts should be componentized and tested on their own, but if this happens, the consumer has a way.
- 
- guard matchMedia on one of DataList's internal hook
- 
- 
- 
- 
- use DataList in your project and run any test that uses DataList
- It will throw an error regarding `matchMedia` not existing
- This PR should let …
> chore: reduce the amount of mocking a consumer would have to do when using DataList

- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
In a case where we want only to use `<DataList.ItemActions onClick={handleActionClick} />`, DataList was still rendering the overlay with the menu of `DataListItemActions`. This PR fixes it.
- 
- 
- 
- 
- Avoid rendering `DataListItemActions` when there's no children
- 
---
> fix(components): Avoid rendering DataListItemActions when there's no children

- packages/hooks/src/useBreakpoints/useBreakpoints.stories.mdx
While implementing, I learnt about the option to use existing Breakpoint Sizes in my test which was not specified in Atlantic Docs. To make it easier for the next person, I've updated the docs to include it.
Added an example for the use of `BREAKPOINT_SIZES` in tests documentation
n/a
- Updated the documentation for `useBreakpoints` to added a test using existing sizes.
n/a
n/a
n/a
n/a
- Run Atlantis locally and visit documentation for `useBreakpoints`
---
> docs(hooks): Example for using breakpoints in tests

- docs/components/InlineLabel/InlineLabel.stories.mdx
The "Draft" example of the InlineLabel is broken , referencing a color variation (grey) that doesn't exist, so it's just a white rectangle. (This lead to confusion for a designer)
**Before:**
**After:**
While fixing that, updated the examples to be more in line with our semantic color standards and added
a reference to StatusLabel, which is better equipped to represent status.
- usage examples to reflect actual usage
- broken example ("draft")
View InlineLabel docs
---
> docs(components): update usage examples in InlineLabel docs

- packages/components-native/src/Button/Button.tsx
- packages/components-native/src/ButtonGroup/ButtonGroup.tsx
- packages/components-native/src/Form/components/FormSaveButton/FormSaveButton.tsx
As part of the e2e work, we need to modify the Button component to allow passing a testID so the contractors can select elements with language-agnostic unique identifiers. The way it works today, it's using the a11yLabel or label as id for testID and that doesn't work for us because when the app is running the Spanish version the e2e tests written will fail. 
I kept the previous implementation with the addition that now the testID prop will take precedence over the other two fallbacks. I also ended up modifying the ButtonGroup to achieve the same goal with the Form component. I know that we can have multiple ButtonGroup components in the same screen that could have the same testID with the current implementation, but it shouldn’t be a problem because they can always rely on xPath in these …
> feat(components-native): add testID property to Button and default testID values to ButtonGroup

- packages/components-native/src/ButtonGroup/ButtonGroup.tsx
By mistake, I ended up adding two testID prefix to the ButtonGroup to match the [Atlantis rule](https://jobber.atlassian.net/wiki/spaces/TEAMATL/pages/2476933462/How+should+we+declare+test+ID+s+in+Atlantis+components#Exposing-test-ID-as-a-prop) for that.
- removed prefix for testID on ButtonGroup
---
> fix(components-native): remove doubled testID prefix for GroupButton

- packages/hooks/src/useCollectionQuery/useCollectionQuery.test.tsx
- packages/hooks/src/useCollectionQuery/useCollectionQuery.ts
Fixing the error state of `useCollectionQuery`. Before, it was just doing a `console.error` when it failed on `fetchMore`. I added a state for the error and updated it when necessary.
I also added a test for this case.
- 
- 
- 
- 
- Fixed the error state of `useCollectionQuery` when it fails on `fetchMore`
- 
---
> fix(hooks): Fix useCollectionQuery error state when fetching more

- packages/components/src/Tooltip/Tooltip.css
In https://github.com/GetJobber/atlantis/pull/1593#issuecomment-1777767499 we uncovered that Tooltip is causing flickers on any activator with a hover state.
https://github.com/GetJobber/atlantis/assets/39704901/f650c880-ae80-4b5b-93fc-5e3208722fd6
- no more flicker at the edge of a Tooltip activator component
https://github.com/GetJobber/atlantis/assets/39704901/4efda7ee-9217-4b89-8ec4-37b38cb8a638
Hover around the edges of an element with a Tooltip
---
> fix(components): eliminate Tooltip/activator flicker

- packages/components-native/src/Select/Select.test.tsx
- packages/components-native/src/Select/Select.tsx
Some screens in the app has more than one select and we don’t have way to uniquely identify these components. So following the[ testID recommendations document](https://jobber.atlassian.net/wiki/spaces/TEAMATL/pages/2476933462/How+should+we+declare+test+ID+s+in+Atlantis+components#Exposing-test-ID-as-a-prop), I added a custom testID for the Select.
- new testID property to the Select component
You can pass a testID to any component in the app using this version and it should be present with the new pattern: ATL-{customId}-Select. If not present, should just be as it's.
---
> feat(components-native): add custom testID to Select component

- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.css.d.ts
- packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.css
- packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.css.d.ts
- packages/components/src/DataList/components/DataListBulkActions/DataListBulkActions.tsx
- packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.css
- packages/components/src/DataList/components/DataListLoadingState/DataListLoadingState.tsx
- packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
- packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.tsx
- packages/components/src/DataList/components/DataListTags/DataListTags.css
There are a few design tweaks we need to do to make the DataList UI more harmonious and polished
- 
- Ensure the height of each item is at a minimum of 56px so we reduce the amount of varying heights
- Remove focus on the clickable row to let the parent handle the styling of it
- Ensure bulk action doesn't change the height of the header
- More spacious loading glimmers
- Larger glimmers on wide screens
- Ensure tags doesn't wrap when there's more than 1 word inside a tag
- Ensure focus doesn't get clipped on filters and batch actiions
- 
- 
- 
- 
---
> fix(components): DataList UI updates

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/ComboboxProvider.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.tsx
- packages/components/src/Combobox/components/ComboboxOption/index.ts
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
- packages/components/src/Combobox/hooks/useComboboxValidation.ts
In an effort to simplify the API of Combobox and ensure JO gets a some buffer time before we pull the rug under it this PR is an intermediary state when we do remove the Triggers and Content components within Combobox.
I left the test as is as it is still technically testing what the internal ComboboxContent could do until the refactor comes.
- Added a Combobox.Option and ensure we only have either the Option or the Content being rendered
- Internalize the logic on building the options
- Deprecate Combobox.Content
- 
- 
- 
- 
---
> feat(components): Implement option and deprecate content

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
`heading` prop in `<Combobox>` needs to be optional for flexibility when using either a `Combobox.Activator` or the default `ComboboxTrigger`.
`heading` prop on `ComboboxProps` is now optional.
When a consumer of `Combobox` is using using a `Combobox.Activator` as the trigger, they will be able to set the label of the `Button` or `Chip` directly within that component.  This use case does not have a need for a `Combobox` `heading` so to avoid errors, `heading` needs to be optional.
When a consumer does not use a custom activator, `Combobox` will default to using `ComboboxTrigger` which is a Chip.  It is in this implementation, that a `heading` should be set.  We decided to set a default for this Chip heading (`Select`) and then the consumer can use the `heading` prop to change that as they …
> feat(components): Make Combobox heading prop optional

- packages/hooks/README.mdx
- packages/hooks/src/index.ts
- packages/hooks/src/useBool/index.ts
- packages/hooks/src/useBool/useBool.stories.mdx
- packages/hooks/src/useBool/useBool.test.ts
- packages/hooks/src/useBool/useBool.ts
Working on a different component (InputDate, DatePicker, and CalendarDatePicker) and using this hook in more than one place to track whether an element has focus or is selected.
`useBool` is a simple wrapper around `useState` for managing boolean values. It
provides a simple API for toggling the value, setting it to true, and setting it
to false.
```tsx
const [checked, on, off, toggle] = useBool(false);
return (
<>
<Checkbox checked={checked} onChange={toggle} />
<Button onClick={on} label={"On"} />
<Button onClick={off} label={"Off"} />
</>
);
```
Used branded typing so that hovering over the returned setters doesn show `() => void` but a helpful label:
> feat(hooks): Hook for managing boolean values

- packages/components/src/Chip/Chip.css
- packages/components/src/Chip/Chip.css.d.ts
- packages/components/src/Chip/Chip.tsx
While doing some tests on Safari, I noticed that the gradient on Chip was always showing up, even if the label was fully visible. To fix it, I added one pixel to the ref element that is being passed to the hook `useInView` to it can understand the size of the element to handle the intersections
- 
- 
- 
- 
- Fixed the gradient of Chip on Safari
- 
---
> fix(components): Fix Chip gradient on Safari

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
Atlantis has resets in the docs site that strip out styling on `input type="search"`, but all sites do not have this.
So, Combobox looks like this in Jobber:
Add styling to remove browser defaults
- New styling rules for search input
- new styling rules for dismiss button as the `cross` icon could be moved off-center by external styling
- Unwanted browser-provided styling that conflicted with our own
Pull pre-release into Jobber
---
> fix(components): remove useragent styling from Combobox search [JOB-82086]

- docs/components/DataList/DataList.stories.mdx
- docs/components/DataList/Web.stories.tsx
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListAction/DataListAction.test.tsx
- packages/components/src/DataList/components/DataListAction/DataListAction.tsx
- packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
- packages/components/src/DataList/components/DataListActions/DataListActions.tsx
- packages/components/src/DataList/components/DataListActionsMenu/DataListActionsMenu.tsx
- packages/components/src/DataList/components/DataListItem/DataListItem.test.tsx
- packages/components/src/DataList/components/DataListItem/DataListItem.tsx
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.test.tsx
- packages/components/src/DataList/components/DataListItemActions/DataListItemActions.tsx
- packages/components/src/DataList/hooks/useGetItemActions.ts
The DataList was initially built to have all of the actions or none of it. This enables a way to hide some actions when it's not valid. For example, you shouldn't have an archive action on an already archived item.
Since DataList actions gets built outside of the template, the `visible` prop needs to be function that has the item it's attached to as the parameter so the consumers can easily determine if it should should up based on the existing data.
- `visible` prop on DataList item actions
- 
- 
- 
- 
- 
---
> feat(components): Optional DataList action

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
The fade pseudo-elements were blocking the selection of the first and last options of Combobox, making them harder to select. This PR fixes it by adding the `pointer-events: none` on them.
- 
- 
- 
- 
- Make pseudo-elements avoid pointer events on Combobox
- 
---
> fix(components): Make pseudo-elements avoid pointer events on Combobox

- packages/components/src/DataList/hooks/useResponsiveSizing.ts
Upon further testing, we found out that the list items in the DataList weren't rendering. That was due to the fact that Safari on iOS16 and below prefers the `min-width` pattern instead of the new `width >=` pattern for media queries.
| Before | After |
|--|--|
| ![image](https://github.com/GetJobber/atlantis/assets/15986172/ac20a76b-d9a3-4884-ae96-2b969a7a93fb) | ![image](https://github.com/GetJobber/atlantis/assets/15986172/c3cd57f7-16b0-4bb9-bf4b-7eb2bb08781a) |
- 
- use `min-width: value` for media queries
- return true for xs always and forever since it is set to trigger at 0px
- 
- 
- 
- 
---
> fix(components): Ensure DataList renders the list item on safari

- packages/components/src/DataList/components/DataListTags/DataListTags.css
- packages/components/src/DataList/components/DataListTags/DataListTags.css.d.ts
- packages/components/src/DataList/components/DataListTags/DataListTags.tsx
When hovering the datalist row, the tag count's background gradient has a delay in receiving the new color value, so its' transition is not synced to the background of the row.
To resolve this, we'll get rid of the gradient background and apply a `mask-image` to the tags themselves.
- tag container is visually truncated by a mask on the container instead of an element with a gradient being positioned above it
- modified DOM structure of the tags + count to add a wrapper and allow the count to sit above the masked container
- tag count does not flicker when the Datalist row is hovered
- Hover on a clickable DataList with overflowing tags
---
> fix(components): resolve transition flicker on DataList "tag count" element

- package-lock.json
- packages/components/package.json
- packages/components/rollup.config.js
- packages/components/src/Autocomplete/Menu.tsx
- packages/hooks/package.json
- packages/hooks/src/useOnKeyDown/useOnKeyDown.ts
During the vite migration work we noticed that there was some errors coming from globals that weren't being set. After doing some digging into this we realized that this was related to an issue with the `@use-it/event-listener` dependency.
- The `@use-it/event-listener` dependency was unnecessary and causing issues. It's better to remove unnecessary dependencies.
- We have removed the `@use-it/event-listener` dependency and have updated the code to use the regular event handler attachment api. We also updated the uses to use a shared hook to reduce unnecessary code duplication.
---
> fix: remove @use-it/event-listener dependency and use regular event handler attachment api.

- docs/components/Glimmer/Glimmer.stories.mdx
Glimmer is stable
- warning from Glimmer
View docs
---
> docs: remove warning Banner from Glimmer

- packages/components/src/Chip/Chip.css
- packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.css
- packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css
- packages/components/src/DataList/components/DataListAction/DataListAction.css
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
Upon pulling the DataList and Combobox into Jobber, we found useragent styling on some of our custom-styled `button` and other HTML elements that was being masked by Storybook.
**Chip**
**Combobox**
**DataList**
It's possible there's a "systemic" fix to this like including a reset for HTML `button` elements in our Atlantis foundations stylesheet, but in service of solving the immediate problem this is my fix.
- Changed existing focus background and shadow styling to apply to `focus-visible` contexts for a smarter treatment of focus states: keyboard users always get the full focus treatment, pointer users receive what the browser heuristics determine is appropriate.
- Outline has been removed in contexts where we are already adding a focus style
- useragent styling is replaced with …
> fix(components): fix Chip, Combobox, and DataList focus states [JOB-82715]

- packages/components/src/DataList/components/DataListSearch/DataListSearch.css
you heard me
- 
- 
- 
- invalid comment
- 
- 
---
> chore(components): remove unnecessary comment

- docs/components/Checkbox/Mobile.stories.tsx
- docs/components/InputAvatar/Web.stories.tsx
- docs/components/InputDate/Mobile.stories.tsx
- docs/components/InputTime/Mobile.stories.tsx
- package-lock.json
- packages/components-native/src/Form/Form.tsx
- packages/components-native/src/InputText/InputText.tsx
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/Form/Form.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/eslint-config/.eslintrc.js
- packages/eslint-config/package.json
To keep up our lint related packages with bumps to typescript version (in jobber and jobber-mobile)
- Bumped the following packages
- @typescript-eslint/eslint-plugin `5.55.0` from to `6.10.0`
- @typescript-eslint/parser `5.55.0` from to `6.10.0`
- eslint-import-resolver-typescript `3.5.3` from to `3.6.1`
- eslint-plugin-import `2.27.5` from to `2.29.0`
- Fixed a bunch of new lint errors as a result of bumping `@typescript-eslint/reccomend`
- Most of this was related to `@typescript-eslint/no-explicit-any` becoming an error instead of a warning
- Avoided updating interfaces from `any` to `unknown` and chose to add ignore comments 
- The touched files it also auto fixed the warning level lint
--- …
> build(eslint): Upgrade eslint and tslint related packages [JOB-81741]

- packages/components/src/Chip/Chip.css
- packages/design/src/Animation.stories.mdx
Chip was calling an easing token that didn't exist, so the intended transition was not being applied.
Why was a token that doesn't exist being used? Probably because we had docs for it - despite a search of the codebase returning no matches for _any_ easing tokens.
- Transition state of Chip works as expected
- Documentation of tokens that don't seem to exist anywhere in Atlantis
Hover or focus Chip
---
> fix(components): fix Chip transition state

- docs/components/Select/Web.stories.tsx
- packages/components/src/FormField/FormField.tsx
We had an internal request to add support for onBlur and onFocus to our <Select /> component. Researching why that wasn't already the case turned up just an oversight and not a deliberate decision, so we've gone ahead and added support for those two callback to the `<select>` usage in FormField.
Added support for onBlur and onFocus callbacks for the <Select> Web component.
- support for onBlur and onFocus callbacks for the <Select> Web component.
- Storybook story for this functionality
- FormField - passed through onBlur and onFocus to child <select> component.
- FormField - handleFocus function now supports the HTMLSelectElement type as an argument
- FormField - handleFocus function now checks for `select` function being available because it is not present on HTMLSelectElement
- N/A
- …
> feat(components): Adding onBlur and onFocus support to Web <Select />

- packages/components-native/src/InputCurrency/InputCurrency.test.tsx
- packages/components-native/src/InputText/InputText.test.tsx
- packages/components-native/src/InputText/InputText.tsx
The InputText native component automatically trims whitespace from values.
Currently, the `onChangeText` callback is invoked when the input is blurred regardless of if the value actually changes. This can lead to additional renders, which cause further state-related issues down the line (i.e. when displaying contextual menus, etc.).
- The InputText `onChangeText` callback is no longer invoked on blur when the value does not change.
1. Use the native `InputText` in a react component.
i.e.
```tsx
import React from "react";
import { InputText } from "@jobber/components-native";
const MyComponent = () => {
const value = "Testing 🧪";
const onChangeText = (text: string) => {
console.log(`Text changed to: ${text}`);
}
return <InputText value={value} onChangeText={onChangeText} />;
};
```
2. Blur …
> fix(components-native): avoid InputText re-renders

- docs/components/InputTime/Web.stories.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputTime/InputTime.test.tsx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
The InputTime element was not showing the `Placeholder label` when the element was not focussed. SInce incorporating the new InputTime element for our reactified `Scherdule Card`, SPs have provided feedback regarding the InputTime element, stating that the field input seemed mandatory, which it was not. Hence there was a need to show the `Placeholder label` when not focussed.
- 
- Added `timeInputLabel` to FormField.css.d.ts
- Updated FormField.css to show `placeholder label` when there is no value in the time field element
- make FormFieldProps `readonly`
https://github.com/GetJobber/atlantis/assets/68708089/213aab1f-3d73-4b85-a5ac-925a4d49bc59
---
> feat(components): Add css changes to show the placeholder label to the form field [JOB-83555]

- packages/components/src/DataList/components/DataListItemActionsOverflow/DataListItemActionsOverflow.tsx
When working towards implementing `<DataList.LayoutActions />` on Jobber, we found out that if the list item have a URL to another page, it'll get triggered by tapping the more menu that came from `LayoutActions`. In order to prevent that, we should prevent default on the more menu click so it only opens the menu and not do a page navigation.
- Prevent default on layout actions more menu click
- 
- 
- 
- 
- 
change the action from `onClick` to `url`
```diff
diff --git a/docs/components/DataList/Web.stories.tsx b/docs/components/DataList/Web.stories.tsx
index ae76bc6f..1a28b11a 100644
--- a/docs/components/DataList/Web.stories.tsx
+++ b/docs/components/DataList/Web.stories.tsx
@@ -142,7 +142,7 @@ const Template: ComponentStory<typeof DataList> = args => {
placeholder="Search characters..." …
```
> fix(components): Prevent data list from navigating within the link when opening the menu

- packages/components-native/src/ContentOverlay/ContentOverlay.style.ts
- packages/components-native/src/ContentOverlay/ContentOverlay.tsx
We were told that long titles go edge to edge and it shouldn't be. Found out that there's no padding on it. This puts that padding in there.
- Padding horizontal on ContentOverlay title
- Allow title to wrap and get bigger than the set height
- If no dismiss, center align that text so when it wraps it looks center aligned
- 
- 
- 
- 
- 
---
> fix(components-native): add padding horizontal on content overlay title

- packages/components/src/DataList/components/DataListAction/DataListAction.css
- packages/components/src/DataList/components/DataListAction/DataListAction.tsx
The context menu of the DataList is heavily influenced by the mobile Menu - this aligns the two styles, and avoids alignment conflict when one item has an icon and the other does not.
**Before**
**After**
- The label comes before the icon in the DataList context menu now
---
> refactor(components): swap icon and label placement in DataList context menu

- packages/components/src/ProgressBar/ProgressBar.css
- Noticed that the stepped variation wasn't rendering when imported to JO.
- 
- 
- 
- 
- Fixed rendering of stepped variation of progress bar.
- 
---
> fix(components): Fix stepped variation of progress bar

- docs/CONTRIBUTING.md
- docs/components/InputPassword/InputPassword.stories.mdx
- packages/components/src/InputAvatar/InputAvatar.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputGroup/InputGroup.tsx
- packages/generators/templates/docs/{{name}}.stories.{{mdx}}
Back in March Rodrigo identified some bad links in our documentation. Today when I tried to bring that branch up to date with master so we could get it merged I broke the branch. 
So this PR is me replaying Rodrigo's work (and Chris' comment) from March against our mainline branch so we can get these links fixed! :)
- Fixed broken links in documentation + code
- Documentation Links
---
> docs(components): Fixing old links (and a bad rebase)

- packages/hooks/src/useBreakpoints/useBreakpoints.stories.mdx
Take out `localhost` from the `Design/Breakpoints` link in the `useBreakpoints` story
---
> docs(design): Fix broken link in useBreakpoints story

- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/ComboboxProvider.tsx
- packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.tsx
There are instances where the action would need to
- Only show up when there's a search term
- Base the label via the search term
- Know the search term on click
This PR enables all of that.
- Added a `visible` prop
- Exposes the search term on actions
| Empty search term | With search term |
|--|--|
| ![image](https://github.com/GetJobber/atlantis/assets/15986172/b488e12f-c5f0-4fd3-94a7-bb4cedfa3fed) | ![image](https://github.com/GetJobber/atlantis/assets/15986172/3c1e8a44-6059-4556-a2c8-32c675cb536b) |
- 
- 
- 
- 
- 
---
> feat(components): expose search term on combobox action

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
When scrolling to the top or bottom of a Combobox list the gradients used as a visual cue that the combo list can be inline scrolled doesn't disappear, which can be misleading and generally doesn't look good. 
- 
- 
- 
- 
---
> fix(components): remove gradient on scroll from top and bottom of Combobox [JOB-79443]

- packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
- packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.css
Combobox was using `surface--background` as proxy for our new hover color before that new hover color existed.
Now it just uses the new hover color!
- using `hover` color for hover and focus states instead of `surface--background` color
- useragent styling leaking into combobox clear-search action
View in Storybook
---
> fix(components): Clean up interactive state colors in combobox

- packages/components/src/DataList/DataList.css
When focused on the `Deselect all` header action, there is noticeable overlap between the focus ring and the adjacent elements.
**Before**
**After**
- standardized gaps across the header action layout elements
- no more overlap
View [DataList in Storybook](https://give-datalist-bulk-actions-s.atlantis.pages.dev/?path=/story/components-lists-and-tables-datalist-web--basic) with >=1 item selected, tab to Deselect All button
---
> fix(components): update spacing of DataList bulk header actions

- packages/components/src/DataList/components/DataListTags/DataListTags.css
After we changed the `gap` between tags to `space-smaller`, it had a little space to render the tags at the bottom that should not be showing up after it breaks into two lines. This PR reduces the space a little bit to render just the correct height that we need.
- 
- 
- 
- 
- A small part of the hidden tags on DataList was showing up.
- 
---
> fix(components): Fix DataList hidden tags sliver showing up

- docs/components/InputText/Web.stories.tsx
- docs/components/InputTime/Web.stories.tsx
- packages/components/src/FormField/FormField.test.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/FormFieldTypes.ts
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/components/ClearAction.css
- packages/components/src/FormField/components/ClearAction.css.d.ts
- packages/components/src/FormField/components/ClearAction.tsx
- packages/components/src/InputDate/InputDate.tsx
- packages/components/src/InputTime/InputTimeProps.tsx
Adding the clearable prop to inputs, except for `InputDate,` because I hit a blocker where `react-datepicker` requires the event when changing the input value for some reason, and I can't mimic it when setting the value directly to an empty string.
I tried to follow the same names and conventions we have on `@jobber/components` name.
- Added the `clearable` prop to inputs, except for `InputDate`.
- 
- 
- 
- 
- 
---
> feat(components): Add clearable prop to inputs

- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.tsx
Working theory: not surfacing the sort arrows until the user has clicked a sortable heading is a hard way for the user to learn that they need to click that heading. It’s also hard to tell which columns are in fact sortable. This is also inconsistent with DataTable, which surfaces sort permanently.
This PR shows the sort arrows permanently for any column that can be sorted on Datalist. It also adds a subtle rollover effect to the sorting arrows.
---
> fix(components): Always show sort icons on Datalist [JOB-82902]

- packages/components/src/Modal/Modal.css
This allows us to split off the styling of the modal when `jobber_retheme` class names exists on the body
- styling that only exists for `jobber_retheme`
- 
- 
- 
- 
- 
Add the `jobber-retheme` class name on the body within the preview iframe
---
> chore(components): prep modal for retheme

- packages/components/src/FormField/FormField.css
To allow for extending inputs within a consuming product, exposing commonly manipulated variables at `:root`.
- Vars are now exposed on root and can be overwritten with local CSS targeting the respective custom properties
- Ensure focus states, border-color change on invalid, etc are still working
- Manipulate the vars with custom CSS and observe they change
---
> refactor(components): expose input tokens on root [JOB-84547]

- packages/components/src/Card/Card.css
- packages/components/src/Card/Card.css.d.ts
Same as modal, retheme cards. This allows us to split off the styling of the modal when `jobber-retheme` class names exists on the body
- styling that only exists for `jobber-retheme`
- 
- 
- 
- 
- 
Add the `jobber-retheme` class name on the body within the preview iframe
---
> chore(components): prep card for retheme

- packages/components/src/Checkbox/Checkbox.css
- packages/design/src/radii.css
Allow checkbox to be re-styled when a given class is present
- Enable checkbox to be re-themed and create alternate styling for re-theme
Apply the `jobber-retheme` class to the Storybook iframe `body`
---
> refactor(components): update checkbox styling with re-theme flag [JOB-84551]

- packages/components/src/Button/Button.css
Allow Button to be re-styled when a given class is present
- Enable Button to be re-themed and create alternate styling for re-theme
- For both modes, set focus to be on `:focus-visible` to follow browser heuristics on when to show focus ring
Apply the `jobber-retheme` class to the Storybook iframe `body`
---
> refactor(components): update Button for retheme [JOB-84545]

- packages/components/src/Menu/Menu.css
- packages/components/src/Popover/Popover.css
To enable the menu and popover components to handle alternate styling base on a retheme classname.
- using gap instead of margin in both existing and retheme style to determine spacing between icon and label
- alternate styling available when `jobber-retheme` class is present on the body
- spacing and typographic styles change on Menu
- Popover has no arrow
Add `jobber-retheme` class to the "story" iframe in the DOM
---
> refactor(components): Update menu and popover for retheme [JOB-84566]

- packages/components/src/DataTable/Body.tsx
I am super tired of the console warnings telling me (correctly) that a `<div>` cannot be the child of a `<table>`. 
- Wrapped the  `DataTable` empty state in a `<tr>` and `<td>`. 
Check the data table empty state example and make sure there's no more console error. 
---
> fix(components): wrap DataTable empty state in valid DOM elements

- packages/components/src/DataTable/Header.tsx
Our team has a design debt ticket that led us to discover this.
In DataTable all of the table body cells (`tbody > tr > td`) have space-base for the cell padding on all sides. However, for table headers (`thead > tr > th`) we have an inline style that is overriding `padding-right`. This is in place to override to `0` if we are manually sorting the columns (to make room for the sorting control). However, if manual sorting is falsy our fallback is `padding-right: inherit` which I believe was meant to fallback on the default padding set on the th. 
Unfortunately that's not quite how inherit works. Inherit instead tells the cascade to fallback on the defined default in the **parent** element or the browser default if no parent default is found. So we end up with `padding-right: 0` either way. …
> fix(components): Fix th cell padding in DataTable

- packages/components/src/Button/Button.test.tsx
- packages/components/src/Button/Button.tsx
Currently the `to` prop in button only supports a new path while react-router-dom allows more customization. This PR updates the `to` prop to also adds the ability to use the other features. See: https://v5.reactrouter.com/web/api/Link
- Added ability to use the full `to` options provided by react-router in the button component
- 
- 
- 
- 
- 
- Verify Button `to` works when it is just a string
- Verify other options work [small code sandbox](https://codesandbox.io/p/sandbox/empty-water-vndrrr?file=%2FExample.tsx)
---
> feat(components): Add better typescript types for to prop on Button

- packages/components/src/InputFile/InputFile.tsx
Currently the useCallback hook is being called without any dependencies. This means that the hook will never know when there have been changes, and not update accordingly. 
This PR adds those missing depenedencies.
- This now has the correct dependencies.
To test this is working properly, try updating state in a component that uses InputFile before and after these changes and notice that state will not update correctly without these changes.
---
> fix(components): InputFile update the useCallback dependency array [85395]

- packages/components/src/InputFile/InputFile.test.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
feat(components): I want to be able to provide a list of acceptable MIME types such that I can restrict what the user should be able to upload.  
- Added another option for `allowedTypes` called `custom`. When this option is selected it will look at `acceptedMIMETypes` as the source of what MIME types the user can upload. 
- An additional prop called `acceptedMIMETypes`. This is prop expects a list of MIMETypes which will be passed down to the `useDropzone` hook. 
Here we are setting the MIME type as `image/heic`. For a list of MIME types we can refer to either the [MDN web docs])https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) or [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml)
This alerts the file selector that we are …
> feat: Add support for providing your own of acceptable file types to upload for InputFile

- packages/components/src/Card/Card.css
Didn't look good so needed to revert the border change back
Added spacing and borders back and made sure the accent colours don't appear
Import into rails app and borders should be back on cards with less space between header and content
---
> fix(components): Bring back card border and padding for retheme

- packages/components/src/Banner/Banner.css
- packages/components/src/Banner/Banner.css.d.ts
- packages/components/src/Banner/Banner.tsx
- packages/components/src/Banner/__snapshots__/Banner.test.tsx.snap
- packages/components/src/Banner/components/BannerIcon/BannerIcon.css
- packages/components/src/Banner/components/BannerIcon/BannerIcon.css.d.ts
- packages/components/src/Banner/components/BannerIcon/BannerIcon.tsx
Noticed the banner icons aren't aligned properly on the retheme styling
This fixes that
- align self center on the banner icon
- 
- 
- 
- 
- 
add this on preview.tsx
```
document.body.classList.add("jobber-retheme");
```
---
> fix: align center banner icon on retheme

- packages/components/src/DataTable/DataTable.css
When we change the roundness of the dataTable elements that are within it that don't follow that same roundness end up breaking outside the container.
Added overflow: hidden to hide elements that break outside the bounds. 
- 
Before
After
- 
- 
- 
- 
---
> fix(components): Hide anything overflowing the dataTable

- packages/components/src/DataList/components/DataListHeader/DataListHeader.tsx
The batch/bulk actions header isn't showing up on mobile when we would like it to
- 
- 
- 
- 
fix the header not showing when **all** selected. previously it would only show if you had more than zero selected, but less than **all** which is treated differently
now it will show even if you have all selected
**BEFORE**
**AFTOR**
you'll need a DataList with everything including a DataListHeader plus batch setup, and then view it on a small resolution screen
this might be a lot to set up, I've been testing it on the new Client index page via `npm run pack @jobber/components` in Atlantis to make the local package that has this version and then installing that in Jobber and trying it out
you should be able to use the generated preview version from this PR though, I think
medium/large screen …
> fix(components): Fix DataList Small Breakpoint DataListHeader Visibility

- packages/components/src/DataTable/Body.tsx
- packages/components/src/DataTable/DataTable.css
- packages/components/src/DataTable/DataTable.css.d.ts
My [previous PR](https://github.com/GetJobber/atlantis/pull/1698) introduced a bug where the empty state wouldn't span the full table width in `pinFirstColumn` due to positioning resets. 
- added a div container for width and an empty state cell class to override `pinFirstColumn` cell styles
**Before**
Janky
**After**
Beautiful
---
> fix(components): DataTable empty state should span full width with pinFirstColumn enabled [85639]

- packages/components/src/Menu/Menu.css
- packages/components/src/Toast/Toast.css
Some elements of Toast and Menu need a bit of love to work nicely in the retheme
- Menu body now has a shadow even on small screens (retheme and non-retheme)
- Toast dismiss button is now visible in retheme
To test the Toast changes, add the `.jobber-retheme` class to the body of the Storybook "story" iframe
---
> fix(components): Adapt toast and menu for retheme [JOB-86410]

- docs/components/InputFile/InputFile.stories.mdx
- packages/components/src/InputAvatar/InputAvatar.tsx
- packages/components/src/InputFile/InputFile.css
- packages/components/src/InputFile/InputFile.css.d.ts
- packages/components/src/InputFile/InputFile.test.tsx
- packages/components/src/InputFile/InputFile.tsx
I notice that it was possible for the input file to fail in two places. The first place is when the component requests for upload params and the second place. when the file is being uploaded. The lack of having an onError callbacks makes it difficult for the consumer of the component to know if something went wrong.
We also allowed the option to pass down a validator for the files to be rejected. When the file is rejected, the UI will update with a validation error message that was provided by the validator method. 
- Added an onUploadError callback which will be trigger when the component fails to fetch the upload params or when the upload process fails.
- Added error state to the component
- 
For testing the validator method I used the following function and assigned it to the validator …
> feat: Added Error State and onErrorCallback for InputFile

- package-lock.json
- packages/components/package.json
- packages/components/rollup.config.js
We've had reports that users building with Vue are seeing props typing issues with Atlantis components that generate acceptable prop values from css files.
The solution presented in this PR is a bit crude, but it does solve the issue in local testing with no changes to the core build process + local dev experience (the css.d.ts files are currently generated files and removing that step from the build process opened up a small can of worms). 
This PR will have a preview build generated from it so Vue consumers can verify that our local testing success can be replicated in other environments.
- Updated library build process to copy specific css.d.ts files to the `dist` folder
- Vue-based Atlantis consumers should no longer receive errors when attempting to use specific props on certain …
> fix(components): Attemping to fix typing issues for Vue-based Atlantis consumption

- docs/components/Combobox/Combobox.stories.mdx
- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css.d.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.tsx
- packages/components/src/Combobox/components/ComboboxOption/ComboboxOption.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
- packages/components/src/Combobox/hooks/useCombobox.ts
- packages/components/src/Combobox/hooks/useComboboxContent.ts
we have a known use case where we want to load data as it is searched for rather than having it all in the list up front. it's a tremendous amount of options where you simply wouldn't want to scroll thru them all, nor select them all
with that, we need to expose the ability for a consumer to hook into the search input's value as it changes, to receive that value and go grab whatever data makes sense for that. once they have the data, they can simply iterate over it as the new `Combobox.Option`s
this does present some notable differences from the current experience where we are able to make many more assumptions about the state and behavior of things, so some additional props were needed 
- onSearch prop, allowing consumer to receive the search term as it changes (debounced)
- a debounce …
> feat(components): onSearch Callback Prop for Combobox

- docs/components/Combobox/Web.stories.tsx
- docs/components/Combobox/storyUtils.ts
per some feedback on the initial `onSearch` PR, it would be preferable to have more realistic code as an example for how to implement a custom search with the `onSearch` prop talking to an api to fetch results based on the query
swapped out the scuffed code to use Apollo stuff to talk to a Richard and Mortimer character API
make a lil util file with the necessary code because if you have it in the webstory bad things happen, plus it's tidier this way
- 
- 
- 
- 
- 
- 
just play around with it! see that you have some options loaded initially
search for some characters not available in the initial set of data, see that it fetches them
undo the search term, get your initial options back!
I will say it's very hard to see the loading state now. I'm not sure this setup is actually ever setting …
> docs(components): Improve Combobox Custom Search Example

- docs/components/DataList/Web.stories.tsx
- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.tsx
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
Adding an `id` to the `li` of our sortable options means that mapping sorting logic from the backend to the `DataList` component will:
1. be more straightforward
2. avoid mapping against the label string (ex "Last Name (A-Z)") which is extremely brittle and if that string changes, good luck tracking down why sort is broken 😅 
`SortableOptions` type now has `id`:
```
export interface SortableOptions {
readonly id: string;
readonly label: string;
readonly order: "asc" | "desc";
}
```
Everyone gets an `id` 
NOTE: <s> Toggling on Last Activity will NOT return an `id` unless you on a small screen. </s> JUST KIDDING I did [this](https://github.com/GetJobber/atlantis/pull/1734/files#diff-9ee4883bf9251e8d0c7ebf791241f261dd3abfe95e9fd3eb337cdd4b7da70c47R106) so now toggling on Last Activity will …
> feat(components): Add data-value to sortable options

- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
`DataListSorting` type needs to have a Partial extend for `SortableOptions` in order to continue allowing for sorting with or without options (`id`, `label` & `order`)
Darryl and I have been working on implementing changes needed [here](https://github.com/GetJobber/Jobber/pull/42605)
---
> fix(components): Add SortableOptions Partial to DataListSorting

- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
Last Activity header was not sorting in the correct order
- added `setSorting` function to better handle sorting state updates; and share that function between `toggleSorting` as well as `handleSelectChange` (sorting on key only vs. sorting with options)
- updated the check for order being `undefined` in `toggleSorting`
- update variable names 
Update sorting state in the web stories to make sure that on load, Last activity header has desc sort indicated. Another click on the header returns no sorting state. Clicking a third time means the sorting state is asc.
```
const [sortingState, setSortingState] = useState<DataListSorting>({
key: "lastActivity",
order: "desc",
});
```
---
[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-reque …
> fix(components): Update handling of sorting state

- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/hooks/useCombobox.ts
there's an issue with new options being passed in not being recognized
added some dependencies to the `useCallback` array
made the filtered options re-calculate whenever the search term changes
- 
- 
- 
- 
options will now correctly update if you change them in some way other than with `onSearch`
- 
give the combobox new options but in a way that is not thru the `onSearch` prop and it will not have a splendid time
---
> fix(components): Ensure Combobox Updates on New Options

- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/index.ts
when implementing the new multi sorted header, I ran into the following
when I'm making my array of sorting objects, I don't have a nice type to refer to. I have to manually build out an object with  a `key` and optional `options` of type `SortableOptions`
and our linter yells at you for trying import from here to boot
so I'd like to make a type that encapsulates the expected type for the `sortable` that we can easily use on the implementation side!
- added a type
- exported the type from the index so it can be accessed without linting violations
- 
- 
- 
- 
- 
---
> fix(components): Extract and Export Sortable Type 

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.tsx
Noticed that when you set the loading to true, the spinner doesn't show up when an action is available. It's because it's being rendered under behind the actions 
This fixes it
- 
- from fixed to sticky so it stays the the bottom but keeps itself visible when scrolled
- 
- 
- 
- 
---
> fix: ensure loading spinner shows up on combobox when actions are there

- packages/components/src/DataList/DataList.const.ts
- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/DataList.tsx
- packages/components/src/DataList/__POM__/DataList.selectable.pom.tsx
- packages/components/src/DataList/components/DataListStickyHeader/DataListStickyHeader.tsx
To better support a single column `DataList` and remove unnecessary empty `<divs />` , we are conditionally rendering the presence of children within the `DataListStickyHeader`.
Example:
| Before | After |
| :----: | :----: |
|  <img width="597" alt="Screenshot 2024-02-12 at 4 48 19 PM" src="https://github.com/GetJobber/atlantis/assets/104797704/d4ccad28-50f3-4431-a09b-55447b1cb30d"> | <img width="605" alt="Screenshot 2024-02-12 at 4 45 49 PM" src="https://github.com/GetJobber/atlantis/assets/104797704/ea344d6f-81b9-4102-8512-683f3add3b43"> |
| Children              | Web | Web Mobile |
| :---------------- | :------: | :----: |
| Default                         |   <img width="731" alt="Screenshot 2024-02-12 at 4 19 49 PM" src="https://github.com/GetJobber/atlantis/assets/104797704/363b184 …
> feat(components): Conditionally render DataListStickyHeader based on presence of children

- packages/components-native/src/InputDate/InputDate.tsx
- packages/components-native/src/InputFieldWrapper/CommonInputStyles.style.ts
- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
- packages/components-native/src/InputPressable/InputPressable.style.ts
- packages/components-native/src/InputPressable/InputPressable.tsx
- packages/components-native/src/InputSearch/InputSearch.style.ts
- packages/components-native/src/InputText/InputText.style.ts
- packages/components-native/src/InputText/InputText.tsx
- packages/components-native/src/InputTime/InputTime.tsx
- packages/components-native/src/Select/Select.style.ts
- packages/components-native/src/Select/Select.tsx
Updating the base styling of `components-native`'s Input to match our new designs
- Added focused state to InputPressable
- Changed theming of Inputs to prepare for the retheme
- Added full borders around our Inputs
- Updated the size of the Inputs to match the new designs.
- Added padding to Inputs to match the new designs
- 
- 
- 
- 
- Use the Jobber Mobile builds [here](https://github.com/GetJobber/jobber-mobile/pull/8688) and verify the styling of Inputs matches the designs
---
> feat(components-native): JOB-88274 Prep inputs for retheme

- packages/components/src/DataList/DataList.css
- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/DataList.tsx
My initial implementation of conditionally rendering the `DataListStickyHeader` ([here](https://github.com/GetJobber/atlantis/pull/1755)) was not accounting for the sticky header having `headers` present.  
When a `DataList` has `headers` but not `Search` or `Filters`, we should still see the Sticky Header (containing `headers`)
However when I put that original PR into JO, certain `DataList` implementations were failing because they **have** headers but **not** Search or Filters.  And because the entire Sticky Header was being conditionally rendered, their `headers` disappeared, causing tests to fail.
With this change, if `headers`  || `Search` || `Filters` exist, then the `DataListStickyHeader` will render.  
If none of those components exist, the `DataListStickyHeader` will not render …
> feat(components): Render DataListStickyHeader when headers are present

- packages/components-native/src/ActionLabel/ActionLabel.test.tsx
- packages/components-native/src/ActionLabel/ActionLabel.tsx
WIth the retheme happening, don't need this anymore
- 
- 
- 
- Letter spacing on action label
- 
- 
---
> fix(components-native): remove action label letter spacing

- packages/components-native/src/StatusLabel/StatusLabel.style.ts
- packages/components-native/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
Avoid status label radius from being affected by tokens as it has to always be this shape regardless of tokens.
It's also set to 3 to follow what the web is doing https://github.com/GetJobber/atlantis/blob/5e1ab691f54f32589367e99fc60cd05b749f5df6/packages/components/src/StatusLabel/StatusLabel.css#L17
When retheme happens, the radius base token would be set to 8 and it would change the status label indicator to a circle which we don't want.
- 
- status label indicator from radius-base to hardcoded 3
- 
- 
- 
- 
---
> fix(components-native): hard code status label radius

- packages/components-native/src/Heading/Heading.tsx
- packages/components-native/src/Heading/__snapshots__/Heading.test.tsx.snap
To prep for retheme, `components-native` `Heading` needs to have updated styling
See [Figma](https://www.figma.com/file/ZJYCUJFHPxxzNDAKeZ9hhh/Mobile-Re-theme-Implementation?type=whiteboard&node-id=84%3A22552&t=Gp2MVGxLredCYkDr-1) showing before/after
`fontWeight` changes:
- `title` now has 800/`extraBold` 
- `subtitle` & `heading` now have 700/`base`
`fontFamily` changes:
- `subtitle` & `heading` now have `Inter`
Snapshot tests were also updated to reflect new values.
You can look at the Heading mobile story and inspect the new computed values
---
> feat(components-native): Update Heading styles

- packages/components-native/src/InputText/InputText.test.tsx
- packages/components-native/src/InputText/InputText.tsx
InputNumber was providing string values when text ended with a space.
InputText applies the transform before treating the form field value as a string.
Use InputNumber finish the number with a space like "13 " and see that InputNumber returns the number 13 instead of the string "13" **after blur**
---
> fix(components-native): Apply input transform in InputText before trim [OPS-20241]

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
A [bug ticket](https://jobber.atlassian.net/browse/OPS-20251) was reported whereby the client list is blank due to a tag filter, and the filter cannot be cleared because there are currently no client tags in your account, which prevents the clear button from appearing. 
We worked around this issue in https://github.com/GetJobber/Jobber/pull/43181 by clearing selections if there are no tags in the account. However, it seems that having the "clear" button always visible when there are "selections" provided would be valuable. This change ensures the header is alway shown in cases where there is an active selection, regardless of options being supplied. 
- ComboBoxHeader always appears when there are selections provided, to ensure the clear operation can always be accessed. 
This can be seen …
> fix(components): Always show clear when there are selected options in ComboBox

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentHeader/ComboboxContentHeader.css
Small buttons are larger in the new theme, causing misalignment between the header and button label in ComboboxContentHeader.
**Before**
**After**
- Text remains aligned in both old and new themes
Toggle the `.jobber-retheme` class on the Storybook iframe body.
---
> fix(components): keep ComboboxContentHeader label and action aligned across themes

- packages/components/src/Glimmer/Glimmer.tsx
This will hopefully improve accessibility but honestly the reason for this change is to make it easier to grab glimmers during testing. Rather than relying on glimmer test IDs.  We can use [getByRole](https://testing-library.com/docs/queries/byrole/#busy) to find the glimmers on the page. 
`getAllByRole('status', { busy: true })` will return a non empty array if there are glimmers on the page. Without this change the same line would work however it would be `getAllByRole('generic', { busy: true})` which doesn't feel as correct. 
https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html
>4. After a user activates a process, an icon symbolizing 'busy' appears on the screen. The screen reader announces "application busy".
Simply adding the status role to the glimmer component. 
--- …
> feat(components): Adds a role of status to the Glimmer component 

- packages/components/src/Card/Card.css
Object colours are coming back
Removes the override for the retheme that got rid of the accents. Makes them 6px instead of 8.
Accents were removed
Accents are back and slightly smaller
Apply `.jobber-retheme` to the body of the component in Storybook preview
---
> feat(components): Bring back card accent in retheme

- package-lock.json
- packages/components/__mocks__/uuid.ts
- packages/components/package.json
- packages/components/rollup.config.js
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
- packages/components/src/Chips/InternalChipSingleSelect.tsx
- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputNumber/InputNumber.test.tsx
- packages/components/src/InputPassword/__snapshots__/InputPassword.test.tsx.snap
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
- packages/components/src/RadioGroup/RadioGroup.test.tsx
- packages/components/src/RadioGroup/RadioGroup.tsx
- packages/components/src/RadioGroup/RadioOption.tsx
- packages/components/src/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
- packages/components/src/RecurringSelect/components/DayOfMonthSelect.tsx
- packages/components/src/RecurringSelect/components/WeeklySelect.tsx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
We have an upcoming need to support SSR, and our usage of uuid does not play well with that kind of rendering. We need the ids to match from server to client.
- Removed uuid usage in internal components. Should not affect external functionality.
- All form elements or anything previously using uuid, should render and operate as normal.
---
> fix(components): Removing uuid in web and replacing with useId

- packages/components/src/Modal/Modal.css
When using actions on a modal we allow the passing of icons into the buttons. Turns out our CSS for ordering of the actions also affects the children within the action (labels and icons). This causes whenever you add an icon to a button the right section of a modal the icon will also swap places with the label.
Made the global selector more specific so it doesn't touch every element within the left/right sides, just the first element (the buttons themselves)
Add an icon to a modal action and see what happens
---
> fix(components): Fix button label and icon alignment when inside a modal

- packages/components-native/src/Button/Button.style.ts
- packages/components-native/src/Button/Button.test.tsx
- packages/components-native/src/Button/Button.tsx
Updating our mobile Button `learning` variation color tokens for the retheme.
- Updated mobile Button color tokens from `information` to `interactive` for the `learning` variation
- Updated tests
Check out the mobile Button in Storybook and apply the `learning` variation type. All types should now use the interactive color.
---
> feat(components-native): Update Button learning variation style

- packages/components/src/Combobox/Combobox.test.tsx
I mocked out console error in one test but forgot that the scope would leak since it was on global scope 🤦‍♂️ 
I've fixed it with a [method from Kent C Dodds](https://github.com/jestjs/jest/pull/5267#issuecomment-356605468). This is to keep the console clean in tests with expected errors. 
Just drop a console error in a test following this one and make sure you see it. 
---
> fix(components): Fix an improper console mock in a test

- docs/README.md
- packages/components/package.json
We updated a CI configuration option which removed our public availability of our build success badge.
This PR removes that badge from our README, now that it doesn't work anymore.
- Removed CI Badge in README.md
- Removed reference to CircleCI in README, opting for generic `CI` instead.
- CI Badge in README.md
- CircleCI reference in README.md
- Badge is no longer present
- The Badge should no longer be present when running Storybook and viewing the landing page.
---
> fix(components): Removing Broken CI Badge

- packages/components/src/StatusIndicator/StatusIndicator.css
- packages/components/src/StatusLabel/StatusLabel.css
- packages/components/src/StatusLabel/StatusLabel.css.d.ts
- packages/components/src/StatusLabel/StatusLabel.tsx
- packages/components/src/StatusLabel/__snapshots__/StatusLabel.test.tsx.snap
- packages/components/src/Typography/css/TextColors.css
- packages/components/src/Typography/css/TextColors.css.d.ts
- StatusLabels look different, they have a background and rounded corners with matching coloured text
- StatusIndicator becomes a circle instead of a rounded square
- InputValidation (and any place use we use `Typography textColor="critical"`) gets a darker shade of red
- Moved a root variable to statusIndicator from statusLabel as it is no longer used in statusIndicator
Input validation text changes to using a darker red as Typography critical variant was updated
StatusLabel and inlineLabel (which was deprecated but not really because people still use it) now look pretty similar. We could continue that way, or potentially combine the two components and make the indicator a boolean. Will leave that decision to later.
Atlantis import can be tested in this Rails branch …
> feat(components): Restyle web statusLabel

- packages/components/src/DataList/DataList.utils.tsx
- packages/components/src/DataList/__tests__/DataList.utils.test.tsx
Subdued was a hold over from previous designs.
When datalist auto wraps data (either dates or text) in Text components it does not apply subdued anymore.
Look at datalist and see it is not using subdued text anymore.
---
Conversation about removing subdued from Datalist text
https://getjobber.slack.com/archives/C03BJHV3PMG/p1710366000231329
> fix(components): Remove subdued text from DataList

- package-lock.json
- package.json
- packages/components-native/package.json
- packages/components-native/src/Button/components/InternalButtonLoading/InternalButtonLoading.tsx
- packages/components-native/src/Disclosure/Disclosure.tsx
- packages/components-native/src/Disclosure/__snapshots__/Disclosure.test.tsx.snap
We want components-native to support reanimated@3
React Native Reanimated docs [Migrating from Reanimated 2.x to 3.x](https://docs.swmansion.com/react-native-reanimated/docs/guides/migration-from-2.x) have this to say
> Reanimated 3.x doesn't introduce any breaking changes between 2.x and 3.x in terms of the API. All the code you've written in Reanimated v2 API works in 3.x without any changes. However, Reanimated 3.x drops the Reanimated v1 API entirely.
I do not see us using Reanimated v1 API
Had to fix ts errors around deprecation of `createAnimatedComponent(FlatList)`
- reanimated peerDependancy bumped to include version 3
Could use some help here, is there still a way to launch storybook for native components?
components that use reanimated
- FormActionBar
- Button (loading state)
- …
> feat(components-native): Bump peerDependency for react-native-reanimated to also accept v3

- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
The clients index in Jobber supports directional sorting on names. Because we have two sorting options with the same id, but different direction, we see the following error in the browser console:
```
Warning: Encountered two children with the same key, `firstName`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
This error also floods the console when unit testing.
Construct element `key` based on both the option `id` and `order`
> fix(components): Use unique item key in DataListSortingOptions

- packages/components/src/Button/Button.tsx
We need to decouple the atlantis button from react router in order to support the Remix work and support SSR.
In order to do this we need to remove the to prop from our Atlantis button component.
Add deprecation warning to the Button `to` prop.
---
> refactor(components): Deprecate to prop for Button

- packages/components/src/DataList/hooks/useMediaQuery.ts
- packages/hooks/src/useBreakpoints/useMediaQuery.ts
Note that we originally merged this but reverted because we thought there might have been a last minute breaking change but we have assured that everything works as expected.
Our useMediaQuery implementation currently isn't SSR friendly because it makes use of DOM specific objects.
In order to prepare atlantis for the remix work we need to ensure that our library is compatible with server side rendering. With SSR the application will be rendered on the server and the server doesn't recognize the window and therefore our currently implementation won't work.
Update useMediaQuery to make use of useSyncExternalStore from the react library that enables this hook to be rendered on the server instead of just on the client via a guard.
--- …
> fix(components): Make useMediaQuery SSR Friendly

- .github/workflows/trigger-qa-build.yml
Our pre-release builds don't include the `stylelint-config` package.  In upgrading `stylelint` in [this PR](https://github.com/GetJobber/atlantis/pull/1819), it became apparent that we'd need this pre-release option.
`Force Publish Stylelint-config` added to the Trigger Pre-release Build workflow
1. Branch off of `TAYLOR/add-stylelint-config-to-prereleases` (this PR's branch)
2. Create a draft PR with a change to the `stylelint-config` `package.json`.  [Here](https://github.com/GetJobber/atlantis/pull/1822) is a branch where I upgraded 2 packages in the `package.json` to trigger the github-actions comment
3. Via github-actions, copy your draft PR branch & trigger a pre-release build with the `Force Publish Stylelint-config` desired workflow option
4. Check that a pre-release is commented …
> feat: Add stylelint-config to pre-release options

- .circleci/config.yml
- package-lock.json
- package.json
- packages/components/src/DatePicker/DatePicker.css
- packages/components/src/FormField/FormField.css
- packages/stylelint-config/package.json
- packages/stylelint-config/stylelint.config.js
`stylelint` needed to be upgraded since we were two major versions behind
Added two new rules to `stylelint-config/stylelint.config.js`, explained in [this comment](https://github.com/GetJobber/atlantis/pull/1819/files#r1534630455)
In main `package.json`:
- `"stylelint": "^14.2.0"` to `"stylelint": "^16.2.1"`
In `stylelint-config/package.json`:
- `"prettier": "^1.17.0"` to `"prettier": "^2.4.1"` which matches the version in our main `package.json`
- `"stylelint-config-css-modules": "^1.4.0"` to `"stylelint-config-css-modules": "^4.4.0"`
- `"stylelint-config-standard": "^18.3.0"` to `"stylelint-config-standard": "^36.0.0"`
- `"stylelint-declaration-block-no-ignored-properties": "^2.0.0"` to `"stylelint-declaration-block-no-ignored-properties": "^2.8.0"`
- `"stylelint-order": "^3.0.0"` to …
> build(stylelint): Upgrade stylelint from v14.2.0 to v16.2.1

- packages/components/src/InputPhoneNumber/InputMask.tsx
The bug occurs when a user translates the page with a browser extension and inputs a phone number.
fixed page crashing on phone number input, when the page is translated with a browser extension
BEFORE:
- use Chrome browser (I wasn't able to make Google Translate extension work in Firefox, but Firefox native translation feature doesn't crash the page)
- install [Google Translate browser extension](https://chromewebstore.google.com/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb), go to Extension Options and set your primary language to Spanish
- navigate to the InputPhoneNumber component on storybook
- click TRANSLATE THIS PAGE
- start typing your phone number
- when you type the last digit - the page should crash
AFTER:
the page doesn't crash
---
[In Atlantis we use Github's …
> fix(components): stop InputPhoneNumber crashing page when it's translated with a Google Translate browser extension  — Patch Release

- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.test.tsx
- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
- packages/components-native/src/InputText/InputText.tsx
Found out that there are scenarios where we need to keep the toobar shown even if you've focused out of the field. For example, an action that opens a bottom sheet could take away the focus from the input, which hides the toolbar and then closes the bottom sheet.
adding a prop to control wether the toolbar is always shown or only on focus (while-editing) fixes that problem.
- `toolbarVisibility` prop on components-native InputText that accepts the value of "always" or "while-editing"
- Those values are consistent with the clear prop language
- 
- 
- 
- 
- 
---
> feat(components-native): implement toolbar visibility

- packages/components/src/InlineLabel/InlineLabel.css
As part of the re-theme the statusLabel was updated in styling. This PR makes the inlineLabel the same height and styling as the statusLabel so they don't feel out of place when used on the same screen together.
- Adjusted the height by setting a consistent line height
- Cleaned up spacing on larger variants, less square, more rectangle, and a little rounder
Before
After
Stare at your screen for a long time and ponder "is this really just a 1.7px change?", the answer is yes.
Note, these all get rounder in the re-theme
---
> feat(components): Make inlineLabel sizing match statusLabel

- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
Our designers often use headings in their designs for the styles without intending for them to be that semantic heading. However, there's no way for devs to do this without custom CSS. So our codebase is filled with invalid HTML where we have heading structures like h1 > h4 > h4 > h2 > h4. This is an HTML violation and an accessibility violation. 
You can now cast a heading as an element different than the level you provided. So you can have a span styled like an `<h2>` or an `<h4>` that looks like an `<h1>`. This separates the intended styles from the semantic meaning of the element and allows devs to accomplish designs without disrupting document structure.
Try it out!
---
[In Atlantis we use Github's built in pull request reviews](https://help.github.com/en/articles/about-pull-request-r …
> feat(components): Heading can accept an element prop to override the numbered heading element

- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.style.ts
- packages/components-native/src/InputFieldWrapper/InputFieldWrapper.tsx
There was this issue after we added the toolbar
and now it's fixed
Hide whitespace to see what really changed
- 
- 
- 
- 
- prefix icon not being beside the input
- 
---
> fix(components-native): ensure prefix is beside the input

- packages/components/src/InputDate/InputDate.tsx
InputDate component was updated in [this PR](https://github.com/GetJobber/atlantis/pull/1817) to allow a value other than a date as the initial/empty value. I found scenarios in the schedule page where the empty value label wasn't rendered. This PR is a fix to cover those scenarios. 
https://github.com/GetJobber/atlantis/assets/35830155/89133d3b-a3a5-4471-bd95-7684420af8ed
Replaced the `showEmptyPlaceholder` state with a `isFocused` state which is set to `false` at the beginning and set to true when user focuses on the field. This creates a bette experience for the user as they don't need to delete the placeholder value. 
https://github.com/GetJobber/atlantis/assets/35830155/0eb534c7-5e28-4c44-8a1b-4a70daca801c …
> fix(components): Fix when InputDate's emptyValueLabel is updated

- docs/components/AnimatedSwitcher/Web.stories.tsx
- docs/components/Icon/Icon.stories.mdx
- packages/components-native/src/ActionItem/ActionItem.test.tsx
- packages/components-native/src/ActionItem/ActionItem.tsx
- packages/design/src/icons/Icon.css
- packages/design/src/icons/Icon.css.d.ts
- packages/design/src/icons/getIcon.ts
This work stems from updating `ActionItem` to align with retheme.  
As a side effect, Arrow icons are now more streamlined:
- Created `longArrowRight`:
For this, we are still using `backArrow.svg` and just simply rotating the icon via css.  I did this same thing to the `longArrowLeft`.
- The major change to `ActionItem`, is updating the `actionIcon` to be a 'long tail' arrow pointing right (where previously it was just `arrowRight`).  Any `ActionItem` without a set `actionIcon` prop will give you `longArrowRight` as a default
- Any existing implementation of `<Icon name="backArrow" />` (which is now called `longArrowLeft`) will not break, and will continue to display the long tailed arrow pointing left.
- using the pre-release you can find examples of `ActionItem` and `ActionItemGroup` …
> feat(design): Create longArrowRight and rename backArrow

- .storybook/components/SidebarLabel/SidebarLabel.tsx
- .storybook/components/SidebarLabel/alphaComponents.ts
We have determined that the mobile Menu component is not ready for prime time and needs work to handle various overflow cases. We've decided to mark it as _alpha_ until we can invest more time in it.
- Mark the mobile Menu component as alpha
Open storybook and you should see this little alpha tag:
> docs(components-native): Mark mobile Menu component as alpha

- .circleci/config.yml
We need to force a major version bump, and our manual check is preventing that.
Removed manual release check.
- Manual Release check
> build: removing manual release for now.

- .circleci/config.yml
- packages/components/package.json
- Darryl and I had to force a manual release of Atlantis to 5.0
- The manual release check was preventing that manual force push.
- We removed the manual release check in a previous PR, but now we're putting it back.
- Manual Release Check back in the CI chain.
This PR should not clear CI until the manual release check is complete.
---
> build: Moving Manual Release Check back

- packages/formatters/src/global.ts
Sometimes Atlantis is built in a Cloudflare environment. Our usage of the 'global' variable in formatters breaks there. We've fixed that in this PR.
Move 'global' to a proper variable (not a declaration) and provides a default value so it doesn't crash if attempting to access in a cloudflare environment.
- Formatters
> build(formatters): Fixing a build issue with formatters in a Cloudflare environment

- docs/components/Tooltip/Web.stories.tsx
- packages/components/src/Popover/Popover.css
- packages/components/src/Tooltip/Tooltip.css
- packages/components/src/Tooltip/Tooltip.css.d.ts
- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/Tooltip.types.ts
- packages/components/src/Tooltip/useTooltipPositioning.ts
There are instances where being able to influence the placement of a tooltip is desired such as on a navigation elements within the shell of a UI. By adding a `preferredPlacement` consumers are able to influence the placement depending on their contextual needs. By default it will use `top` like it always has.
- Adds ability to provide `preferredPlacement` to Tooltip component.
---
> feat(components): adds ability to provide "preferredPlacement" for Tooltip

- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
After shipping [this PR](https://github.com/GetJobber/atlantis/pull/1783), a few existing behaviours were made even more obvious. This PR is to fix those visual inconsistencies.
`padding-right` has been applied to all instances of `Select` (not just inline usages):
Before |  After
:---:|:---:
Before |  After
:---:|:---:
Before |  After
:---:|:---:
- test all possible
-  configurations of `Select` within Storybook
- test using the pre-release build [here](https://github.com/GetJobber/Jobber/pull/45446)
---
> fix(components): Select improvements

- docs/components/Chip/Web.stories.tsx
- packages/components/src/Chip/Chip.css
In initial development of Chip, we missed that only suffix should have the `surface` background. This leads to unexpected results when using in-product.
-  white (surface) background color from prefix, now only applied to suffix
See the Prefix story
---
> fix(components): remove Chip prefix background [JOB-92493]

- packages/components/src/Toast/showToast.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/index.tsx
We have some SSR related issues.
A recent update to Tooltip treated a Ref as a Boolean, so instead of flipping between true/false it was permanently true (which breaks in SSR environments)
In addition, it was noted that the Toast component when loaded via the ESM barrel file broke client-side functionality in certain framework environments. This is because the Toast component currently creates a React Root when the `showToast` function is imported, for compatibility in environments that aren't full SPAs. That createRoot call was conflicting with framework `hydrateRoot` calls and preventing all client-side interaction.
Some effort was taken to see if we could update the Toast component in a way that would support both island based loading and full SPA loading. Working solutions ran into …
> fix(components): SSR Fixes

- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/FormFieldTypes.ts
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputText/InputText.tsx
We want our input text to have autofocus as part of design requirements, for the chat drawer. The Native component supports the autofocus prop, but the HTML web version does not. This PR adds support for this prop for the web component.
- Added `autoFocus` to `InputText`
Added tests for `InputText` to assert that focus is given when the new prop is used.
> feat(components): Add autofocus support for InputText (JOB-94181)

- packages/components/src/Button/Button.css
The Atlantis button updates in the retheme looked OK for small buttons _with a label_, but were TOO SMALL when just an icon:
This is considerably smaller than the [Figma spec](https://www.figma.com/file/rIIhulZvcp9M82lNOCGv16/Product%2FOnline?type=design&node-id=14531%3A17&mode=design&t=ij64MZJIw7uMAvcE-1) calls for.
- Small buttons are now 32 by 32px when they only have an Icon, and are 32px high when they have a label
Set up a small button with an icon and no label in Storybook
---
> fix(components): update small button sizing

- packages/design/src/colors.css
The value for `taupe--light` did not match [Figma design specs](https://www.figma.com/file/HXWXusJPZLmaJNGlKEpiyhXW/branch/LKuwUrH3xAgzre1TKBsZ9x/Product%2FBase?type=design&node-id=18688%3A357&mode=design&t=KBZfoLVvsEX9cJad-1)
- rgb value of `taupe--light`
View color docs in the Cloudflare build
---
> refactor(design): update value of taupe--light

- packages/design/src/colors.css
We've established a usage pattern around `taupe--light` in the context of surfaces, now we can codify it in a meaningful way.
- A semantic value encapsulating usage of `taupe--light`. The naming convention has been reviewed by designers, and follows the existing `subtle` modifier pattern seen in `interactive` colors.
Locally, run `npm run bootstrap` and then apply the new value to a component. Verify that the component uses the correct underlying value.
---
> feat(design): add semantic value for subtle backgrounds

- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/FormFieldTypes.ts
- packages/components/src/FormField/FormFieldWrapper.tsx
currently, if you provide a `defaultValue` to an `InputText` and make that clearable, you cannot actually clear that value. it will always remain.
this was exposed via DataList's search, if you give that an `initialValue` it is passed into an `InputText` as a `defaultValue` which is where the real problem is
- 
- 
- 
- 
if you provide a `defaultValue` to an `InputText` along with `clearable` and it will work as intended
(sorta) fixed a type issue where we were only accepting "always" and "never" as values for `clearable` when there is code to deal with `while-editing` but there was no way to hit that code, at least if you listened to the types
- 
**DataList**
give the `DataList.Search` an `initialValue`, see that you can clear the value when pressing the X
**InputText**
give an …
> fix(components): Allow InputText Default Value to be Clearable

- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
On Safari, you can't resize a text area 😱
it only happens on multiline `InputText`s that **don't** have a toolbar prop.
this is because the toolbar will use margins to make sure its content doesn't cover the handle. however the non toolbar version will fill the entire area, and I guess Safari treats this different from other browsers 🤷 
- 
- 
- 
- 
made it so that the resize handle that is only present on multiline InputTexts is not obstructed and can be used on all browsers, especially Safari which was not having a great time
we put some padding around the entire textarea anyway, so I've just implemented that same amount of spacing but with margin on the container that would otherwise obstruct the resize handle. making sure to only do this for the multiline/textarea case because 
A) I …
> fix(components): Input Text Safari Resize Handle

- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentSearch/ComboboxContentSearch.css
Combobox was either not specifying a value and being over-ridden, or specifying a hard-coded color value in a few places.
This means that in a new theme or mode, we weren't seeing the expected outputs. 
- color and background-color declarations to ComboboxContentSearch
- overflow gradient value definitions
- Combobox search and overflow now respond to changes in theme 
- Modify the value of `--color-surface` and observe that Combobox responds appropriately
---
> fix(components): use semantic values in combobox

- packages/components/src/FormField/FormField.css
- packages/components/src/FormField/FormField.css.d.ts
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/hooks/useIsSafari.ts
the quick fix for the not being able to grab the resize handle has broader effects than I'd like. namely when you have content that is greater than the area, your scrollbar is not right aligned. the margin pushes it off a bit
**Before (Chrome)**
**Before (Firefox)**
I really tried to do this in a more elegant way, and got like 90% of the way there but more issues keep on popping up and I need to move on with my life, so here we are.
**After (Chrome, then Firefox)**
- 
- 
- 
- 
only going to apply the margin replacing padding approach on Safari where it is problematic. the others, firefox & chrome, have no need for the margins and it can make them look bad with certain scrollbar settings.
- 
**on Firefox, Chrome and Safari**
with a multiline InputText, try using the resize handle
try …
> fix(components): Reduce Scope of Safari Scrollbar Issue

- packages/components/src/Menu/Menu.tsx
- packages/components/src/Typography/Typography.test.tsx
- packages/components/src/Typography/css/TextCases.css
- packages/components/src/Typography/css/TextCases.css.d.ts
Because menu's subheading uses an `element={h6}` semantically, it was picking up styling from in-app CSS classes in Jobber that target `h6` making it uppercase. We still want it to be a semantic h6, so I added a `none` to `textCase` from `Typography` to give us the locked-down specificity we need for that to not happen.
- New textcase of `none` to Typography
Set a style of `h6 { text-transform: uppercase; }` (and other adjustments like font-weight, if you like) in the inspector stylesheet and observe that the casing of the Menu's subheader is preserved
---
> feat(components): add textCase=none to Typography

- .storybook/components/Playground/Playground.tsx
The Code Tab CSS was broken. So I fixed it.
Fixed the code tab CSS
- A new reference to our built css file in the Code Tab Sandbox Preview feature.
- Broken CSS is no longer Broken.
- Broken CSS
- Broken CSS
- Broken CSS
Run storybook.
Click on code tab.
Component should look cool and normal, not weird and unstyled.
---
> fix(components): Code Tab CSS Issue

- packages/components/src/FeatureSwitch/__snapshots__/FeatureSwitch.test.tsx.snap
- packages/components/src/Markdown/Markdown.test.tsx
- packages/components/src/Markdown/Markdown.tsx
- packages/components/src/Markdown/__snapshots__/Markdown.test.tsx.snap
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
The markdown component works well for handling markdown text, but our team has run into a use case where we need to know when a link was clicked. This PR extends the Markdown component to expose the underlying React Markdown's `component` prop. This way, we can use a custom component and attach whatever events we want.
Added an optional `components` prop to the Markdown component. This object is spread to the React Markdown component, ensuring that existing values can be overridden if desired.
Also added tests for this functionality.
> feat(components): Add support for link click listener for Markdown component (JOB-96041)

- packages/design/src/getMobileShadows.js
with the recent change of `radius-large` to go from 4 -> 16, the `shadow-base` in mobile feels very blown out, or not concentrated
4
16
changing the `shadow-base` `shadowRadius` to use the `radius-small` token which gets us the same appearance we had before
- 
- 
- 
- 
- 
- 
this needs to be done on mobile devices to see what it looks like, so I suppose just make your mobile setup use this version of `design` and then take a peek at the quick create menu items for the most easily accessible example
other places using `shadow-base` would also be affected so feel free to check those out if you'd like
---
> fix(design): Reduce Shadow Radius for MobileShadows

- packages/components/src/FormField/hooks/useActiveElement.ts
- packages/components/src/FormField/hooks/useFormFieldFocus.ts
- packages/components/src/Menu/Menu.css
- packages/components/src/Menu/Menu.css.d.ts
- packages/components/src/Menu/Menu.test.tsx
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
- packages/hooks/README.mdx
- packages/hooks/src/index.ts
- packages/hooks/src/useWindowDimensions/index.ts
- packages/hooks/src/useWindowDimensions/useWIndowDimensions.test.tsx
- packages/hooks/src/useWindowDimensions/useWindowDimensions.stories.mdx
- packages/hooks/src/useWindowDimensions/useWindowDimensions.ts
This reverts commit ad35140afe6ac6756cf5167e29d9f94ef4b68286.
I want to bring back those changes, but with a couple extra little fixes
- using `fixed` placement strategy to avoid absolute sometimes pushing content when incorrectly transformed/translated
- only apply extra y offset for small screen
for the y offset thing, the small UI achieved thru CSS used to also look at 640px as the breakpoint but it was updated in the CSS at some point however the JS part was not and that's how we got here. I think this might have been related to the issue I was seeing with the transform being incorrect after opening in the small screen state
- 
- 
- 
- 
pushing content
menu displacement way too much on medium screens. that code should only apply for the little bottom sheet like UX that we do thru CSS …
> fix(components): Portalled Menu Take 2

- packages/components/src/Menu/Menu.css
If you have a Menu inside a Modal, previously it would inherit that zIndex and show up fine
however now that we're portalling it out to the body, the zindex of the menu is lesser than the Modal and it gets hidden 😱 
- 
- 
- 
- 
no more of this Menu being hidden by Modal
vs now
- 
use a `Menu` inside of a `Modal`
see that when the Menu is opened, you can see and interact with those elements. they are not hidden/obstructed by the Modal.
---
> fix(components): Increase zIndex for Menu

- docs/components/InputPressable/InputPressable.stories.mdx
- packages/components-native/src/InputDate/InputDate.test.tsx
- packages/components-native/src/InputDate/InputDate.tsx
- packages/components-native/src/InputTime/InputTime.test.tsx
- packages/components-native/src/InputTime/InputTime.tsx
When an `InputDate` or `InputTime` was closed when an `InputText` was previously focused the `Form` would scroll to the `InputText` this created a jarring experience for users. This PR dismisses the keyboard when an `InputDate` or `InputTime` is focused
- 
- 
- 
- 
- Fixed: Other inputs remaining focused when an `InputDate` or `InputTime` were opened
- 
QA can be done in https://github.com/GetJobber/jobber-mobile/pull/9307
---
> fix(components-native): Dismiss keyboard on Date and Time Picker being opened

- packages/components/src/Menu/Menu.css
When fixing the zindex for Menus within Modals, I forgot to account for the small screen UI using different classes, and so the `menu` elevation was still being used placing it behind the Modal
also, the overlay from the Menu wasn't layered correctly on big screens. that was the Modal overlay being shown. we want the Menu overlay to be present to close just the Menu
- 
- 
- 
- 
- overlay when Menu used within a Modal
- menu on small screens when Menu used within a Modal
- 
Changes can be
---
> fix(components): Menu Small Screen zIndex Layering 

- packages/components/src/ConfirmationModal/ConfirmationModal.tsx
- packages/components/src/ConfirmationModal/tests/interaction-ConfirmationModal.test.tsx
- discovered a bug where we were calling `setState` _inside_ the react render cycle (in this case inside the reducer function)
- this bug manifested with an ugly console error in both the browser and in tests
```
console.error
Warning: Cannot update a component (`QuotesIndex`) while rendering a different component (`ForwardRef(ConfirmationModalInternal)`). To locate the bad setState() call inside `ForwardRef(ConfirmationModalInternal)`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
```
- moved calling of ConfirmationModal callbacks out of the reducer
- this removed a react error from the console
- this was a pure refactor to fix the bug
- added a regression test that would fail without this change
- here is what the error would look like in the test: …
> fix(components): fixes a bug where we call setState inside of the react render cycle

- docs/components/AnimatedSwitcher/Web.stories.tsx
- packages/components/src/AnimatedSwitcher/AnimatedSwitcher.tsx
When using `AnimatedSwitcher` if `initialChild` or `switchedTo` where wrapped in a fragment it would cause an error. This can be seen in [this](https://codesandbox.io/p/sandbox/laughing-wind-dmdlq3?file=%2FExample.tsx&utm_medium=sandpack) CodeSandbox example when switching the component.
The main way this would pop up was in `DataList` if a layout was wrapped in a fragment (see JO QA PR)
- 
- 
- 
- 
- fixed `AnimatedSwitcher` breaking when components wrapped in a fragment
- 
Run `git revert 5da59ced7c93080717f78ba0e1d7452721d7eb41` and verify the Animated Switcher doesn't break when the `initialChild` or `switchedTo` is wrapped by a fragment.
Verify that AnimatedSwitcher works when `initialChild` or `switchedTo` is not wrapped in a fragment
--- …
> fix(components): Animated switcher

- docs/components/Form/Form.stories.mdx
- packages/components-native/src/Form/types.ts
We had a bug during development about 2 months ago. It resulted when an error was handled during the `onSubmit` function of the form, preventing it from bubbling up. This didn't allow the form library to catch the error and trigger the `onSubmitError` function.
Added some description to the inline comment for form's `onSubmit` function and added some sentences to the form's story document page. 
n/a
Changes can be
---
> docs(components): Added more description about how Form onSubmit works with throwing errors. 

- .storybook/components/SidebarLabel/alphaComponents.ts
- docs/components/Box/Box.stories.mdx
- docs/components/Box/Web.stories.tsx
- docs/components/Flex/Web.stories.tsx
- packages/components/package.json
- packages/components/src/Box/Box.tsx
- packages/components/src/Box/Box.types.ts
- packages/components/src/Box/index.ts
- packages/components/src/Box/styles/Box.css
- packages/components/src/Box/styles/Box.css.d.ts
- packages/components/src/Box/styles/BoxBorder.css
- packages/components/src/Box/styles/BoxBorder.css.d.ts
- packages/components/src/Box/styles/BoxDimension.css
- packages/components/src/Box/styles/BoxDimension.css.d.ts
- packages/components/src/Box/styles/BoxGap.css
- packages/components/src/Box/styles/BoxGap.css.d.ts
- packages/components/src/Box/styles/BoxMargin.css
- packages/components/src/Box/styles/BoxMargin.css.d.ts
- packages/components/src/Box/styles/BoxPadding.css
- packages/components/src/Box/styles/BoxPadding.css.d.ts
- packages/components/src/Box/styles/BoxRadius.css
- packages/components/src/Box/styles/BoxRadius.css.d.ts
- packages/components/src/Box/utils/getBoxConfig.ts
- packages/components/src/Box/utils/getBoxDimension.ts
- packages/components/src/Box/utils/getBoxSpaces.ts
- packages/components/src/index.tsx
We've had a need for a generic layout component for a while. This component was rolled elsewhere, and we're moving it into Atlantis so everyone can benefit from its greatness.
The Box component is for all your wrapping component needs. You can put borders around your box, or padding, or margins, or border radiuses. You can set flex direction, gap size, all sorts of fun things.
There is basic documentation, but could be expanded with additional examples.
* Added the Box component
- The Box Component
The box component should render well in the provided storybook stories.
---
> feat(components): Box Component

- packages/components/src/Avatar/Avatar.css
- packages/components/src/Button/Button.css
- packages/components/src/Checkbox/Checkbox.css
- packages/components/src/Chip/Chip.css
- packages/components/src/Chips/InternalChip.css
- packages/components/src/FormField/FormField.css
- packages/components/src/InputFile/InputFile.css
- packages/components/src/RadioGroup/RadioGroup.css
- packages/components/src/Select/Select.css
- packages/components/src/Switch/Switch.css
- packages/design/src/colors.css
We need to be able to target the borders of interactive elements for theming, and for future improvements to accessibility of interactive elements.
Also want to be able to do this iteratively, so we can implement the "hook" before we use the "hook".
- 
- Underlying semantic value for borders of interactive elements
- Also made the text color in Avatar _non-semantic_ as there are computations being done in that component to determine whether the text should be light or dark based on background color.
- 
- 
- 
- 
Changes can be
---
> feat(components): update interactive borders and avatar [JOB-97530]

- packages/components/src/DatePicker/DatePicker.css
The wrapper for the `react-datepicker` used in Datepicker is hard-coded to #fff, meaning when you define a new `surface` color, the component doesn't respond and you get "show-through" between the cells
- Datepicker respondes to semantic updates
Override `--color-surface` token in inspector stylesheet
Changes can be
---
> fix(components): use semantic value for Datepicker background

- docs/components/Gallery/Web.stories.tsx
- packages/components/src/Gallery/Gallery.test.tsx
- packages/components/src/Gallery/Gallery.tsx
- packages/components/src/Gallery/GalleryTypes.ts
When using the gallery component, the thumbnail is the source image. It's all well and good until you pass in a large image that the browser needs to download. Furthermore, the user could be downloading a large image that they don't intend to view as they could've viewed it before and don't care about it.
This PR adds the ability to load a smaller thumbnail image on the gallery view so we keep the initial load small and thus speed up the wait that user would have to do
- allow files in gallery to pass in thumbnail urls
- 
- 
- 
- 
- 
Changes can be
---
> feat: allow thumbnails on gallery

- packages/components/src/Select/Select.css
In Windows, when the color theme changes, the select `option` elements were not picking up changes in theme. This has the potential to render the options unreadable:
- Added a more explicit selector to ensure the `option` elements pick up a semantically-themed background-color.
- 
- 
- Select is readable in other color modes (ie dark mode)
- 
Changes can be
---
> fix(components): make `Select` options readable in dark mode

- packages/components/src/Autocomplete/Autocomplete.css
To make a sectioned `Autocomplete` component look more similar to other Atlantis items such as `Menu` and `Combobox`
- Changed styling of section headings in `Autocomplete` component to use default border color for their seperator. 
- Fixed selector bug that was preventing section headings from getting appropriate spacing
Before:
After:
Changes can be
---
> fix(components): Adjust style of section headings in autocomplete

- docs/components/Page/Web.stories.tsx
- packages/components/src/Page/Page.css
- packages/components/src/Page/Page.css.d.ts
- packages/components/src/Page/Page.test.tsx
- packages/components/src/Page/Page.tsx
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
The Campaigns team requires a status label to be present beside the Heading within a page component. Designs can be found [here](https://www.figma.com/design/DjVmtJjQKATkgC5UxFAleU/Automated-Campaigns-v1?node-id=759-135655&t=KOm5iwuUkaZNYCb8-4). 
This could have been implemented without using the Page component, but we determined that it would be beneficial to allow a custom component to be appended to the end of the title. Then, other teams can take advantage of the change, and that the campaigns component using this implementation will maintain consistency with the design system over time (eg: in the case that the Page component style for the design system were to change).
- Updated the Page component to accept an optional ReactNode to display beside the title of the Page.
- Added a new …
> feat(components): Update Page component to accept a titleMetaData component [JOB-97759]

- packages/components/src/Icon/Icon.test.tsx
- packages/components/src/Icon/Icon.tsx
Allow a pass-through of a `testID` prop 
- new `testID` prop on `components` `Icon`
- tests for: using the `testID` prop & the situation where someone has used `name` as `data-testid` instead.
_Note:_ `name` was previously being used as a way to grab `data-testid` and there are two instances of that being used in jest tests in product. **_The same applies to `components-native` `Icon`_.** That's why I decided to use the OR operator and keep `name` as an option with `data-testid`.
In components where we have `suffix`, `prefix` or components like `Button` where we have `icon` as a prop:
```
interface ButtonFoundationProps {
...
readonly icon?: IconNames;
```
We're bringing in `IconNames` and teams are using _that_ to test that an `Icon` is being used in these components as prefixes, etc. …
> feat(components): Add testID prop to components Icon

- packages/components-native/src/Icon/Icon.test.tsx
- packages/components-native/src/Icon/Icon.tsx
Allow a pass-through of a testID prop
- new `testID` prop on `components-native` `Icon`
- tests for: using the `testID` prop & the situation where someone has used name as `data-testid` instead.
In `components-native` where we have `suffix`, `prefix` or components like `Button` where we have `icon` as a prop:
```
interface ButtonFoundationProps {
...
readonly icon?: IconNames;
```
We're bringing in `IconNames` and teams are using _that_ to test that an `Icon` is being used in these components as prefixes, etc.  So, only having `testID` here is not only more of a breaking change than I originally thought. I don't think we should expect consumers of `Button` to put a `testID` on a nested `Icon` that's being rendered as a prop.
Nothing fails in external mobile repo: …
> feat(components-native): Add testID prop to components-native Icon

- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/FormField/FormField.tsx
- packages/components/src/FormField/__snapshots__/FormField.test.tsx.snap
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/Select/__snapshots__/Select.test.tsx.snap
Eric found that React's built-in `useId` is not stable across renders when within a `StrictMode` tree (only affects local development). I confirmed this using his [branch](https://github.com/GetJobber/atlantis/compare/master...ec/rhf-stable-id-fix) for testing.
**Why is this a problem?**
Because we rely on `useId()` to generate a unique stable identifier when the parent component chooses not to pass a `name` prop to FormField. This id/name is passed to react-hook-form's controller and if it's not stable between renders, this breaks the form's validation logic.
**Why is this a _new_ problem?**
A recent [PR](https://github.com/GetJobber/atlantis/pull/1942/files) merged that updated `FormField` to use `useController` from `react-hook-form` instead of `<Controller>`. `useController` is more …
> fix(components): Update FormField to avoid useId StrictMode problem

- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css.d.ts
- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.tsx
- packages/components/src/DataTable/SortIcon.css
- packages/components/src/DataTable/SortIcon.css.d.ts
`DataList` and `DataTable`, despite having _almost_ identical interactions to sort columns, have their UI built styled differently. I'm not addressing the _built_ bit here, as there's some functionality to untangle, but I am making the interactions of the sort arrows work and feel the same.
- active sort arrow is `--color-interactive--subtle`
- inactive sort arrow is `--color-interactive--subtle` at 0.4 opacity
- inactive arrow **while hovered** is 0.6 opacity
This allows the user to observe
- arrows are hovered
- while the arrows are being clicked, the user can perceive the changing sort order
https://github.com/GetJobber/atlantis/assets/39704901/708bd99a-e5f4-4691-ba09-8dc864d14974
- CSS for both DataList and DataTable's sort arrows
- Sort arrow interactions are now consistent across …
> fix(components): make DataList and DataTable sorting interactions match

- packages/components/rollup.config.mjs
types were getting very confused when being consumed outside this project
specifically `Card` `Modal` and `ProgressBar`
types derived from styles in this way
`Card`
```
import colors from "./cardcolors.css";
readonly accent?: keyof typeof colors;
```
would not correctly find a type that had keys of actual color values. instead it would seemingly fallback to a definition that says any css import is a string, and therefore `keyof string` would give string prototype values like `match` or `indexOf`
Glimmer wasn't experiencing this problem and uses the same pattern of `keyof typeof size` so I went to see what was different. found the rollup config and noticed the file names in there for Card, Modal and ProgressBar didn't match their actual file names. maybe we updated them at one point and …
> fix(components): Fix Rollup Config File Names

- .storybook/assets/css/manager.css
Sidebar search was looking a little dim with the Storybook 7 upgrade
- gave the `search-field` `input` `border-color: var(--color-border);` so it would stand out more
You might have to restart storybook to see the change
---
> docs: Update border color of sidebar search

- docs/components/Chip/Web.stories.tsx
- packages/components/src/Chip/Chip.css
- packages/components/src/Chip/Chip.css.d.ts
- packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.test.tsx
- packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
`Chip.Suffix` should have an `onClick` so that a custom event can be triggered, separate from clicking the `Chip` itself
1. `onClick` optional prop to `Chip.Suffix`
If `<Chip.Suffix />` receives an `onClick`, the element becomes a `button`.  If no `onClick` is provided, the suffix remains a `span` element.  I decided on this solution to maintain a semantically correct element whether there's an `onClick` or not.
2. `testID` optional prop to `Chip.Suffix`
I think it's safe to assume that if any consumer of `Chip` wants to add a clickable suffix, they'll also want to test that interaction.
3. `ariaLabel` optional prop to `Chip.Suffix`
To provide as much flexibility as possible, we're passing an `ariaLabel` for clarity to screen readers. For example:
4. a new web story for `ClickableSuffix`, …
> feat(components): Add onClick to Chip Suffix

- docs/components/Drawer/Drawer.stories.mdx
- docs/components/Modal/Modal.stories.mdx
- docs/components/SideDrawer/SideDrawer.stories.mdx
Multiple questions around when to use Drawer vs SideDrawer
- Added or improved "Related components" sections in the docs for Drawer, SideDrawer, and also Modal 
Changes can be
---
> docs(components): Disambiguate Drawer and SideDrawer

- docs/components/FormatFile/Web.stories.tsx
- packages/components/src/FormatFile/FormatFile.css
- packages/components/src/FormatFile/FormatFile.css.d.ts
- packages/components/src/FormatFile/FormatFileDeleteButton.tsx
`FormatFile` has an issue when both `onClick` and `onDelete` are present, where you cannot click the delete Icon immediately after clicking the `FormatFile` component itself.  Instead, you'd have to remove focus from the `FormatFile` in order to click the delete Icon.
- a new `ExpandedwithDelete` story; good for testing this functionality but also, we should have a story with the `onDelete`
- added a `deleteButton` class so that we can raise the z-index of that element
When an `onClick` & an `onDelete` are both present, you cannot click the delete button immediately after triggering the `onClick` (volume up):
https://github.com/user-attachments/assets/abaded2d-d0df-4f8d-9c89-8f1e940e6f9b
When `onClick` & `onDelete` are both present, you can trigger the `onClick` and then trigger the …
> fix(components): Adjust z-index of clickable areas in FormatFile

- packages/components/src/InputFile/InputFile.css
- packages/components/src/InputFile/InputFile.css.d.ts
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
When `InputFile` is within a tall container and is stretched to fill the space, the dropzone content (`Button`, `hintText`) should be centered vertically and horizontally.
- new styles for `dropzoneContent`
Instead of the dropzone content sticking to the top of a tall `InputFile`, that content is now in the center. 
If the `InputFile` is set to `size="small"` (so only a button shows up), this is what we see:
Note that any `InputFile` not stretched within a tall container retains the same styling as before:
Pre-release showing prod example will be in separate PR tagged in slack msg
To see this in storybook, update the StatefulTemplate in `docs/components/InputFile/Web.stories.tsx` and see the screenshots above:
```
const StatefulTemplate: ComponentStory<typeof InputFile> = args => {
const …
```
> feat(components): Update positioning of dropzone content

- packages/components/src/FormatFile/FormatFile.css
Follow up to the `FormatFile` [change](https://github.com/GetJobber/atlantis/pull/1975) earlier today where I should have used a token instead of a number for the `deleteButton` z-index
```
.deleteButton {
z-index: 1;
}
```
becomes
```
.deleteButton {
z-index: var(--elevation-base);
}
```
Should behave as before:
- click on `FormatFile` and then immediately click on the delete button in [this story](http://localhost:6005/?path=/story/components-images-and-icons-formatfile-web--expanded-with-delete)
- you can tab/focus/select the delete button with no issue
---
> feat(components): Use token in FormatFile delete button

- packages/components/src/FormatFile/FormatFile.css
On mobile breakpoints if a `FormatFile` was in displaying in `compact` with an onDelete the delete icon would not display all the time. This would make deleting files hard if there was an `onClick` action on the `FormatFile`
- 
- 
- 
- 
- fix(components): Have the compact `FormatFile`s always display the delete button when on a mobile breakpoint
- 
- Verify compact formatFile doesn't display the delete button when the thumbnail isn't hovered on non-mobile breakpoints
- Verify the compact fomatFile will always display the delete button when on a mobile breakpoint
See mentioned PR for to test the pre-release in JO
Changes can be
--- …
> fix(components): Always show delete button on the FormatFile when on a small screen

- packages/components/src/Menu/Menu.tsx
- packages/components/src/Typography/css/TextColors.css
- packages/components/src/Typography/css/TextColors.css.d.ts
Because the menu items are not "secondary" to any other content, they should just use the default text color.
- Menu items use `text` color instead of `textSecondary`
- Also noticed that Typography doesn't have access to `destructive` so included that as well
Test in Storybook and via prerelease
Changes can be
---
> feat(components): use text color for menu items

- docs/components/Disclosure/Disclosure.stories.mdx
- docs/components/Disclosure/Web.stories.tsx
- packages/components/src/Disclosure/Disclosure.tsx
This PR provides a better documentation and example of the acceptable way to pass `title` to the `Disclosure` component in case it's not just a string, but a React Component
- Better description of the the `title` prop in the Storybook Docs.
- Better description of the the `title` in the <Disclosure> component prop interface.
- Storybook example to pass `span` instead of `h4`, since this component appears inside of `<summary`, hence the content should be of ["phrasing content"](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#phrasing_content) type, which was added to the docs.
- Change the typing for the `title` prop to be `ReactElement` and `ReactElement[]` instead of `ReactNode` and `ReactNode[]`, since type `string` IS a `ReactNode`.
- 
- 
- 
- 
- Verify that the …
> fix(components):  Update description of title prop in Disclosure component

- .storybook/assets/css/preview.css
- .storybook/components/ColorSwatches/ColorSwatches.module.css
- .storybook/components/ColorSwatches/ColorSwatches.module.css.d.ts
- .storybook/components/ColorSwatches/ColorSwatches.tsx
- docs/design/Colors.stories.mdx
Base color palette was rendering extremely incorrectly
- Presentation of color swatches 
- Use of automagic "pull all the colors" component because it wasn't playing nice with our new token tooling
- Base palette renders again
View color docs locally or on Cloudflare build
---
> docs(design): update swatches and fix broken base colors

- docs/components/Page/Web.stories.tsx
- packages/components/src/Page/Page.css
- packages/components/src/Page/Page.test.tsx
- packages/components/src/Page/Page.tsx
I needed a popover on a button, but the button was a page primary action. 
- 
- added `ref` to div wrapping primary and secondary action buttons
- modified storybook to show example of change
- added test to make sure the `ref` prop is not passed into the button component
- 
- 
- 
- 
- Open `Page` "With Actions" storybook
- Click the primary and secondary actions to see the Popover 
Changes can be
---
> fix(components): Add ref prop to primary and secondary actions on Page component

- packages/components-native/src/Glimmer/Glimmer.style.ts
- packages/components-native/src/Glimmer/Glimmer.tsx
Because the Glimmer was using a `surface--background` token, it was actually quite difficult to parse when used overtop `surface--background` or other `surface--` variants.
In addition, it was inconsistent with the web Glimmer, which uses a neutral value.
- semantic color tokens to rgb value so the Glimmer works better overlaid across assorted surfaces
- mobile Glimmer works better across various surface types
Changes can be
---
> fix(components): match Glimmer mobile styles to web

- packages/components-native/src/Text/Text.test.tsx
- packages/components-native/src/Text/Text.tsx
- packages/components-native/src/Text/__snapshots__/Text.test.tsx.snap
- packages/components-native/src/Typography/Typography.style.ts
- packages/components-native/src/Typography/Typography.test.tsx
- packages/components-native/src/Typography/Typography.tsx
- packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
This PR adds the ability to add underlining to the Text component for the native-components.
**Android**
**iOS**
The underline styles here (dashed, etc) are not implemented yet on the Android side. For this reason Android defaults to the basic underline style regardless of what value is passed in. For iOS, the proper dashed style should be displayed.
- Added `underline` prop to `TextProps` with options `"solid"` or `"dashed"`
- Added `underline` prop to `TypographyProps` with options `"solid"`, `"double"`, `"dotted"`, or `"dashed"` (I covered more than what is exposed from Text, because this is an internal component; if the reviewer thinks this is unnecessary, I can change it to support only the solid/dashed cases that we need)
- Added underline styles to `typographyTokens`
To test …
> feat(components-native): Add underline support to Text/Typography components for mobile (JOB-104505)

- docs/components/InputFile/InputFile.stories.mdx
- docs/components/InputFile/Web.stories.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/components/src/InputFile/__snapshots__/InputFile.test.tsx.snap
The purpose behind adding `supportText` is to communicate to a user, the permitted file types and max file size when uploading files via `InputFile` dropzone.  This can help in avoiding upload errors that need to be rectified after a failed upload.
1. `supportText` prop, which is a string. Why a string?
- Although the motivation behind adding this prop is to display file types and size limit for files, I feel that keeping this as customizable as possible, allows for flexibility moving forward
- Allowing for a string also makes localization easier on the consumer side
[Figma](https://www.figma.com/design/rIIhulZvcp9M82lNOCGv16/branch/FRyCZpCX92n6dzD6alwyKj/Product%2FOnline?m=auto&node-id=13630-0&t=JI0ecH7XrhDzgHw6-1)
Why not dynamically use `allowedTypes` here?  
Thinking about instances …
> feat(components): Add description prop to InputFile

- packages/components/src/DataList/DataList.css
On touch screen devices that were wider than our `--medium-screens-and-up` the DataList checkbox wouldn't be displayed because the user wouldn't be able to hover over the row, this PR works to fix that.
- 
- 
- 
- 
- components: Display DataList checkboxes on touch screen devices that are medium screen sized and up.
- 
Can be tested in storybook here: https://5607bc22.atlantis.pages.dev/iframe?args=&id=components-lists-and-tables-datalist-web--basic&viewMode=story
Can also be tested in JO, see the PR mentioning this one.
To test enable responsive mode in your browser inspector (this is wider screen with touch simulation enabled):
Verify:
-  When on the medium-screens-and-up size the check box appears when touch simulation is enabled
- Verify the checkboxes do not appear on the …
> fix(components): Display Datalist checkbox based on device type instead of breakpoint

- docs/design/Colors.stories.mdx
It was confusing that we had a semantic color that wasn't documented!
- `--color-surface--background--subtle` is now documented in Colors
Check the docs! Locally or in Cloudflare
Changes can be
---
> docs(design): add subtle background usage to color docs

- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.css
- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.css
The focus state for DataList headers looked a little unfinished with no radius
- DataList interactive headers now have a small radius in their focused state
- Sortable headers on right-aligned columns now align properly to their columns' contents
You can test in [Cloudflare](https://add-radius-to-datalist-heade.atlantis.pages.dev/?path=/story/components-lists-and-tables-datalist-web--basic) or locally by tabbing through the interface and observing the slightly rounded corners.
Changes can be
---
> feat(components): small improvement to focus state of DataList headers

- .storybook/theme.ts
The controls section in stories didn't have Dark Mode applied and it made it difficult to read the props, etc.
- adjusted tokens in `theme.ts` so the controls section can be viewed in Dark Mode
Look at any story, and make sure the controls section (with the props) responds to the sun/moon theme toggle in the top nav
Changes can be
---
> docs: Dark Mode applied in Storybook controls

- docs/components/Chip/Chip.stories.mdx
- packages/components/src/Chip/Chip.tsx
- packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.test.tsx
- packages/components/src/Chip/components/ChipPrefix/Chip.Prefix.tsx
It would be nice to be able to add like a logo or a custom image to the prefix
Chip.Prefix now accepts anything, but if you provide either an Avatar or an Icon you get the fallback behavior
Changes can be
---
> feat(components): update Chip.Prefix to accept more than Icon and Avatar

- packages/components/src/DataList/components/DataListOverflowFade/DataListOverflowFade.css
Reverting some css changes from[ this PR](https://github.com/GetJobber/atlantis/pull/1915/files#diff-2e47ed917e3fb0e72f31e95ba28e39e9147a9fefa74908b54edf8bff1731e937) (specifically from DataListOverflowFade.css)
https://github.com/user-attachments/assets/43357125-e880-4a04-958d-9b12f8cf72fa
Why I'm also bringing back ` --overflow-fade--negative-offset`:
https://github.com/user-attachments/assets/08481855-c4a7-4551-ace1-e57a9340adf2
Changes can be
---
> fix(components): Fix DataListOverflowFade spacing

- scripts/commentOnPrAfterPreRelease.js
This reverts commit 74e21e336603602b4b7fcb3839a3ef0557671dcc.
Added a link to our documentation on troubleshooting pre-release failures when a pre-release fails
- 
- 
- 
- 
- 
- 
See failed build below, verify the link goes to our troubleshooting guide
Changes can be
---
> docs: Adding trouebleshooting link to the failure comment

- packages/components-native/src/Typography/Typography.style.ts
- packages/components-native/src/Typography/Typography.test.tsx
- packages/components-native/src/Typography/Typography.tsx
- packages/components-native/src/Typography/__snapshots__/Typography.test.tsx.snap
All of the semantic colors should be available for Typography on mobile
Adds missing semantic colors to Typography.style.ts. Also reorganizes the colors to make it easier to find the color you need in the future and makes deprecated colors clear.
Missing semantic colors for mobile typography
Re-organizes the colors
Groups various colors to be deprecated in the near future
No colors were removed
N/A
N/A
Open up storybook via the pre-release branch and locally tp play around with new colors/existing colors to ensure they all work
Changes can be
---
> refactor(components): Add semantic colors to typography on mobile [97200]

- docs/components/InputFile/InputFile.stories.mdx
- docs/components/InputFile/Web.stories.tsx
- packages/components/src/InputFile/FileTypes.ts
- packages/components/src/InputFile/InputFile.test.tsx
- packages/components/src/InputFile/InputFile.tsx
If consumers are setting `allowedTypes` on `InputFile` to be `string[]`, it's possible they might end up with an array like this (where the last string is for DOCX files):
```
allowedTypes={[
"image/jpeg",
"image/png",
"image/heic",
"application/pdf",
"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
]}
```
When a user then tries to upload a non-allowed file type, they'd see this behemoth validation error:
and that is **not** what we want to see.  Let's clean up the validation errors that surface when a non-allowed file type tries to be uploaded.  
_**Also,**_ then consumers can then implement `allowedTypes` like this:
```
allowedTypes={["JPEG", "PNG", "HEIC", "PDF", "DOCX"]}
```
Existing implementations that use the long strings within `allowedTypes`, will still …
> feat(components): Create FileTypes enum for InputFile and use in validation error

- .storybook/components/Playground/Playground.tsx
- 
- Fixed regex to use negative lookahead instead of negative lookbehind, since the latter doesn't seem to be supported by the Cloudflare JS engine.
- Improve existing regex to select words that start with capital letter (to match React components, and not HTML tags), which would remove at least one loop.
- 
- 
- 
- 
- Check the `code` tab (e.g. in `DataList` "Clear All Filters" story.
- Make sure it's rendered, since it's currently broken on `master`:
- Verify that there are no unused/weird imports, such as 
```
import { T } from "@jobber/components/T";
import { SelectedFilters } from "@jobber/components/SelectedFilters";
```
Changes can be
---
[In Atlantis we use Github's built in …
> fix(docx): Fix regex in Playground for the code tab to work correctly

- .storybook/components/PullRequestGenerator/PullRequestGenerator.tsx
As I showed [here](https://getjobber.slack.com/archives/C03BKPST4KC/p1728432648402599) there was a bug in the PR title generator where the selected scope would not show up as having been selected. Also, the list of scope values did not match the accepted list of scopes so it was possible that the title generator gave you an invalid title.
- Change the value on the scope selector from type to scope
- Updates to the list of options for scopes so that only valid scopes can be selected
A couple of new scope values
- 
- 
- 
Only valid scopes can be selected and they now show up in the scope selector
- 
Play around with the [PR Title Generator](http://localhost:6005/?path=/docs/guides-pull-request-title-generator--docs) to verify things are looking good.
Changes can be
[tested via …
> fix(docx): Fix bug in PR title generator 

- packages/components-native/src/ContentOverlay/ContentOverlay.style.ts
- packages/components-native/src/ContentOverlay/ContentOverlay.tsx
Based on design review feedback in [this JM PR](https://github.com/GetJobber/jobber-mobile/pull/9716#discussion_r1803809106) it seems that design wants the `Heading` of the `ContentOverlay` to be start aligned whether or not the dismiss button is present. 
- 
- `Header` without a dismiss button is now start aligned instead of being center aligned
| Before | After |
| -------| ----- |
| <img width="320" alt="image" src="https://github.com/user-attachments/assets/233cd564-ec3a-45fe-800c-e8dcd6a5fae7"> | <img width="320" alt="image" src="https://github.com/user-attachments/assets/b07be005-fefb-493b-9ab3-dd2fbf499406"> |
- 
- 
- 
- 
Changes can be
---
[In Atlantis we use Github's built in …
> fix(components-native): ContentOverlay Heading alignment should not change with presence of dismiss button

- packages/components/src/Grid/GridCell/GridCell.tsx
- 
- 
- 
- 
- Fixed regression where GridCell could not longer have no children which was used to create spacer cells for adding empty space to the start of a grid. [The change that caused this](https://github.com/GetJobber/atlantis/pull/2074/files#diff-0119fc0182d00d596c0314e898f3a6dea1dc55487b4ab5119195578390f0fc4eR22) removed the PropsWithChildren which used to allow no children to be passed with `<Grid.Cell size={...} />` which is no longer allowed
- 
Changes can be
---
> fix(components): Fixed issue where GridCell could no longer have no children

- docs/components/Combobox/Combobox.stories.mdx
- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/ComboboxProvider.tsx
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
- packages/components/src/Combobox/constants.ts
- packages/components/src/Combobox/hooks/useCombobox.ts
- packages/components/src/Combobox/hooks/useComboboxActivatorAccessibility.ts
- packages/components/src/Combobox/hooks/useComboboxValidation.ts
- packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
- packages/components/src/Combobox/index.ts
Some designs call for even further customization beyond a Chip or Button.
To enable this, we are going to open up the Activator even further to allow more customization.
Combobox Activator can accept custom markup. No longer limited to only Chip and Button.
**toggleOpen & handleOpen**
regardless of if we want to expose the API through render props or not, calling `setOpen` directly can be risky. `setOpen(true)` is fine. `setOpen(false)` is not since we want to make sure to do all the cleanup and invoke all the callbacks in addition to closing the combobox. 
to that end, I've created an equivalent wrapper for `setOpen(true)`: `handleOpen`. if we ever want to add callbacks for `onOpen` then it will be easy to add it to one place over all the places we were using `setOpen(true)`. right now …
> feat(components): Allow Fully Custom Combobox Activator

- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
- packages/components/src/DataList/components/DataListHeaderTile/DataListSortingArrows.tsx
Sorting icon in `DataList` was missing some accessibility tags, which would be helpful for screen reading devices.
Moreover, having those properties would allow us to select those elements in UI tests.
- `aria-label`
- `aria-sort`
- 
- 
- 
- DataList sorting not receiving aria attributes. 
- 
Changes can be
---
> fix(components): JOB-104988 Add accessibility attributes (also helps with testing)

- docs/components/Combobox/Combobox.stories.mdx
- docs/components/Combobox/Web.stories.tsx
- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/ComboboxProvider.tsx
- packages/components/src/Combobox/components/ComboboxAction/ComboboxAction.pom.tsx
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.test.tsx
- packages/components/src/Combobox/components/ComboboxActivator/ComboboxActivator.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.test.tsx
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContentList/ComboboxContentList.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.test.tsx
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
- packages/components/src/Combobox/hooks/useCombobox.ts
- packages/components/src/Combobox/hooks/useMakeComboboxHandlers.ts
- packages/components/src/DataList/components/DataListFilters/components/DataListSort/DataListSort.test.tsx
Combobox doesn't allow you to actually interact with the Activator again once the combobox is open. Maybe some day it will, but that day is not today.
With that, the `toggleOpen` method is a bit misleading. in practice it is a one way toggle that can only ever toggle from closed -> open.
the `toggleOpen` method has a dead code path that only exists in theory. functionally, you have no way to interact with the activator while the combobox is open. we will close it when you click outside the combobox, when you press ESC, when you interact with an Action that has the default close on click, or when you make a selection in single select mode.
the only way you can interact with it would be through DOM manipulation which is not realistic.
it's similar to how we handle the overlay
```
{open && ( …
```
> refactor(components): Replace ToggleOpen with HandleOpen

- docs/components/InlineLabel/InlineLabel.stories.mdx
- docs/components/StatusLabel/StatusLabel.stories.mdx
When we did Summit the design team landed on a path where there would be no more InlineLabel, only the re-designed StatusLabel. Accordingly, we deprecated the component in the design system.
Over time, though, designers kept using InlineLabel and had some pretty legitimate use cases for not using StatusLabel. We’ve even aligned internally on usage guidance/disambiguation, so this adds that guidance to help designers choose the "right" *Label and removes references that suggest the InlineLabel should go away.
- Better disambiguation comments to both Inline- and StatusLabel "Related components" sections
- Scrapped references that InlineLabel should not be used
Read the docs! 
Changes can be …
> docs(components): better disambiguate InlineLabel and StatusLabel [JOB-108048]

- packages/design/src/iconStyles/iconColors.ts
- packages/design/src/iconStyles/iconStyles.web.ts
The task icon was defaulting to color-navy which caused it to not look good in dark mode. This updates the task icon to use color-task to accommodate for both light and dark modes.
- 
- `task` icon now defaults to `color-task`
- 
- 
- 
- 
Changes can be
---
> fix(design): Updating the task icon to use task-color [JOB-98804]

- docs/components/List/List.stories.mdx
- docs/components/List/Web.stories.tsx
- packages/components/src/List/List.test.tsx
- packages/components/src/List/List.tsx
- packages/components/src/List/ListItem.module.css
- packages/components/src/List/ListItem.module.css.d.ts
- packages/components/src/List/ListItem.tsx
- packages/components/src/List/__snapshots__/List.test.tsx.snap
- packages/components/src/List/index.ts
The List component is rarely used because it can currently only be used to render list items in a very particular format. If consumers were able to specify how the items are rendered it could be used in many more places. This PR adds that flexibility.
The `content` prop in `ListItemProps` is now optional
Before these changes `ListItem` was used to render the items passed into `List`. This PR adds a `customRenderItem` prop to `List` that will take precedence over `ListItem`. If no `customRenderItem` is provided the behaviour with using `ListItem` should be unchanged.
For existing `List` implementations there should be no change to functionality
- 
- 
- 
- 
Some before and after photos from testing things using the pre-release:
Before:
After:
Before:
After:
Before:
After:
Christain Ellinger …
> feat(components): Improve list composability [JOB-107035]

- packages/site/src/layout/NavMenu.tsx
- packages/site/src/layout/SearchBox.module.css
- packages/site/src/layout/SearchBox.tsx
Searching the new docs site should be smooth and consumer grade! This cleans up some UI cruft and makes the search feel more intuitive.
- No search icon or clearable on the search input
- Modal would overflow the screen, forcing scroll - also limited results per viewport with a "base" width modal
- Results headings too similar in weight to section headings (Design + Components)
- Could not predictably fire the Search modal via keyboard
https://github.com/user-attachments/assets/cf322dd0-9bfc-40ce-87e7-ad9abe3ebca3
- Search icon on the search input, and it's clearable
- Modal cannot overflow the screen
- Modal is wider, allowing for more results per query
- Better hierarchy within search results (more spacing, emphasis on content over headings)
- Can predictably fire the search modal using …
> feat(docx): Improve search experience in new docs site

- packages/design/src/styles/dark.mode.suffixStyles.css
We wanted to move away from using `::-webkit-scrollbar` as a CSS selector as it is considered non-standard (https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar).
Unfortunately the change does not work on Safari, so the previous code remains for that case only. Safari's current behaviour seems to be on initial page load, the scrollbar is light but turns dark on subsequent page loads and this behaviour is unaffected by this change.
- Updated the CSS selector for the dark mode of the scrollbar for supported browsers
Turn on dark mode and check out the scrollbar 👀 
Changes can be
Removed -- don't believe their lies
--- …
> fix(design): Updated CSS selectors for dark scrollbar colour [JOB-108461]

- packages/components/src/DataList/DataList.utils.tsx
- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
The video of the issue can be found here: https://jobber.atlassian.net/browse/JOB-108034
Basically, navigating to Home from Requests tab (where DataList -> DataListHeaderTile is instantiated) caused Requests nav link item to refocus, making it appear as if this is still an active link.
While investigating the issue, I noticed that the `useRefocusOnActivator` hook was called twice, once in `DataListSortingOptions` (to move focus back onto the column header after the sorting option was selected with an assistive technology/keyboard) and in `DataListHeaderTile` (where I believe it should NOT be called). So this PR removes calling this hook in `DataListHeaderTile`.
- 
- 
- 
- 
- `visible` prop from `DataListHeaderTile`
- `useRefocusOnActivator` hook call in `DataListHeaderTile`
- 
- 
Changes …
> fix(components): Remove unnecessary useRefocusOnActivator from DataListHeaderTile

- packages/design/src/tokens/border.tokens.json
We don't want to use spacing for things that aren't spacing (ie dimensions like height and width). This should extend to border thickness as well.
(Noted by @Beccaneer in a [related PR for Divider](https://github.com/GetJobber/atlantis/pull/2110#issuecomment-2471155109))
- Border-width tokens now resolve to a pixel value instead of a spacing token which _then_ resolves to a pixel value.
- NOTE: underlying values are not changed
- `border` = 1px
- `border-thick` = 2px
- `border-thicker` = 4px
- `border-thickest` = 8px 
On the Cloudflare build (or locally, once you've run `npm run bootstrap && npm start`), you can go to a component that references the border tokens (ie Card) and inspect the CSS custom prop, then follow the custom prop to its' definition and see that it no longer resolves to …
> refactor(design): Decouple border width tokens from spacing

- packages/site/src/componentList.ts
- packages/site/src/layout/SearchBox.tsx
- packages/site/src/pages/HomePage.tsx
It's common for less-universal components (ie not Button) to be known by different names. This makes it easier to find some of those components in our system, which is especially useful for newer consumers and contributors to adopt our nomenclature.
Inspiration from [component.gallery](https://component.gallery/)
**Before**
"Looks like Atlantis doesn't have a `pill` component, guess I have to design one myself!"
**After**
"Ah I see one of these might be what I'm looking for"
Additionally, search should be case-insensitive, so you can search "button" and see Button.
**Before**
**After**
- 
- 
- 
- 
- 
- 
Search for some of the terms in the "Additional Results" fields for each component
Search in upper and lower case
Changes can be
[tested via …
> feat(docx): add disambiguation to a few components' Search

- docs/components/SegmentedControl/Web.stories.tsx
- packages/components/src/SegmentedControl/SegmentedControl.module.css
- packages/components/src/SegmentedControl/SegmentedControl.module.css.d.ts
- packages/components/src/SegmentedControl/SegmentedControl.tsx
- packages/components/src/SegmentedControl/SegmentedControlBase.tsx
Some current implementations of similar components within product have varying heights. We can match our `Button` component and offer 2 sizes, `base` & `small`
- `size` prop that is set on the parent
- added a `Sizes` story to show what `base` and `small` look like
- the default `SegmentedControl` is now `40px` in height to match other components like `Button`, where the `base` is also `40px`
- now the `small` variation is `32px` in height
Check out the Sizes story.
I'll also share video, to show that a long label (although not recommended) will still give the same spacing, etc between `base` & `small`
https://github.com/user-attachments/assets/e611eee1-15f8-4151-86f5-ea8fbea49d4d
--- …
> feat(components): Add size prop to SegmentedControl

- packages/components/src/DataList/components/DataListSearch/DataListSearch.module.css
Credit to Zak as I copied most of this PR description from [his PR](https://github.com/GetJobber/atlantis/pull/1918) but since this is a different solution I decided to put up a separate PR to avoid any confusion based on the comments on the other one
Right now there's an issue on below medium screens where you can scroll horizontally because of some extra unintended width
- 
- Small CSS changes
- 
- 
Even though we're setting a `width: 0` on this parent element
the nested FormField elements still have a width
these are causing the layout to have horizontal scrolling
with that `width: 0` we're clearly trying to make them take up no space, and have them be functionally invisible. This is achieved in this PR by setting overflow to hidden for small screen sizes unless the search is expanded. …
> fix(components): Fix DataList Sticky Header Scrolling  [JOB-96126]

- packages/components/src/Divider/Divider.module.css
- packages/components/src/Divider/Divider.module.css.d.ts
- packages/components/src/Divider/Divider.test.tsx
- packages/components/src/Divider/Divider.tsx
- packages/components/src/Divider/DividerDirections.module.css
- packages/components/src/Divider/DividerDirections.module.css.d.ts
- packages/components/src/Divider/DividerSizes.module.css
- packages/components/src/Divider/DividerSizes.module.css.d.ts
- packages/components/src/Divider/__snapshots__/Divider.test.tsx.snap
Updating `Divider` in `@jobber/components` as part of our continued effort to increase prop consistency between equivalent web and mobile components.
Now `Divider` props are exactly the same in mobile and web versions
A new `testID` prop exists on the `div`.  A test for that prop was also added in `Divider.test.tsx`
In following a similar pattern to other components in Atlantis, I decided to dynamically reference the size and direction props to ensure the component is tightly coupled to the available size/direction options.  This means a few new files were created - `DividerSizes.module.css` and `DividerDirections.module.css`. This also DRYs up a bit of the logic in `Divider.tsx`
Testing the pre-release in product is linked below.
UI/UX wise, everything remains the same as it was before. …
> feat(components): Add testID to Divider and dynamically reference size and direction props

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/Countdown/Countdown.props.json
- packages/site/src/content/Countdown/index.tsx
- packages/site/src/content/index.ts
Adding `Countdown` to the new docs site
Added the `Countdown` component to the new docs site.
You should see a `Countdown` option after clicking on Components.
---
> docs(components): Adding Countdown to Docs

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/Heading/Heading.props.json
- packages/site/src/content/Heading/index.tsx
- packages/site/src/content/index.ts
Adding `Heading` to the new docs site
Added the `Heading` component to the new docs site.
**NOTE** HeadingLevel is a type and doesn't come through on the props table like we'd expect - I see the same thing is happening with `IconNames` in `AnimatedSwitcher` and `Button` so I assume we're ok to move ahead for now. I've noted in the Figma that it would be nice to get more functionality in this area in the future
You should see a `Heading` option after clicking on Components.
---
> docs(components): Adding Heading to Docs

- packages/site/src/content/AnimatedPresence/index.tsx
- packages/site/src/content/AnimatedSwitcher/index.tsx
- packages/site/src/content/Autocomplete/index.tsx
- packages/site/src/content/Button/index.tsx
- packages/site/src/content/ButtonDismiss/index.tsx
- packages/site/src/content/Checkbox/index.tsx
- packages/site/src/content/Chip/index.tsx
- packages/site/src/content/Countdown/index.tsx
- packages/site/src/content/Disclosure/index.tsx
- packages/site/src/content/StatusLabel/index.tsx
- packages/site/src/content/Switch/index.tsx
- packages/site/src/layout/ComponentView.tsx
We are not using the Description field because it conflicts/duplicates the existing descriptions in most Stories.mdx files
- individual descriptions, as well as the rendering of the subtle in the ComponentView
View component pages
---
> docs: Remove description from component indexes and page [JOB-110417]

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/Autocomplete/Autocomplete.props.json
- packages/site/src/content/DataList/DataList.props.json
- packages/site/src/content/DataList/index.tsx
- packages/site/src/content/index.ts
DataList needed to be added to docs
DataList is in docs
The image for DataList is larger than the others, so this has introduced a display bug:
We probably just need to set a max height on the image (or scale-down the DataList image). Or maybe another solution? A fancier CSS solution?
The base implementation is very barebones. This is the PR where I decided I need to do something about the Code Tab + How it pulls from the rendered component. So I'm going to work on that a bit, and we can determine later how we want the base example to be displayed/rendered.
Run the new docs site, DataList should be visible in three places:
Changes can be
--- …
> feat(components): DataList to Docs

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/FormatDate/FormatDate.props.json
- packages/site/src/content/FormatDate/index.tsx
- packages/site/src/content/index.ts
Added the FormateDate component to the new docs site.
You should see a 'FormateDate' option after clicking on Components.
Changes can be
---
> docs(components): Adding FormateDate to New Docs Site [JOB-110497]

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/StatusIndicator/StatusIndicator.props.json
- packages/site/src/content/StatusIndicator/index.tsx
- packages/site/src/content/index.ts
Added the StatusIndicator component to the new docs site.
You should see a 'StatusIndicator' option after clicking on Components.
Changes can be
---
> docs(components): Adding StatusIndicator to New Docs Site [JOB-110402]

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/Autocomplete/Autocomplete.props.json
- packages/site/src/content/FormatEmail/FormatEmail.props.json
- packages/site/src/content/FormatEmail/index.tsx
- packages/site/src/content/index.ts
Added the FormatEmail component to the new docs site.
You should see an 'FormatEmail' option after clicking on Components.
Changes can be
---
> docs(components): Adding FormatEmail to New Docs Site [JOB-110499]

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/InputDate/InputDate.props.json
- packages/site/src/content/InputDate/index.tsx
- packages/site/src/content/index.ts
Added the InputDate component to the new docs site.
You should see an 'InputDate' option after clicking on Components.
Changes can be
---
> docs(components): Adding InputDate to New Docs Site [JOB-110588]

- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/components/AtlantisPreviewEditorProvider.tsx
- packages/site/src/content/ConfirmationModal/ConfirmationModal.props.json
- packages/site/src/content/ConfirmationModal/index.tsx
- packages/site/src/content/index.ts
Adding `ConfirmationModal` to the new docs site
Added the `ConfirmationModal` component to the new docs site.
You should see a `ConfirmationModal` option after clicking on Components.
---
> docs(components): Add ConfirmationModal to New Docs Site

- packages/site/src/components/BodyBlock.tsx
- packages/site/src/components/ContentCard.tsx
- packages/site/src/components/ContentCardWrapper.tsx
- packages/site/src/pages/ComponentsPage.tsx
Address some visual tightness caused by spacing visually dense cards in close proximity to each other
- Increased spacing between cards (referenced some other docs sites that I like to land on a more generous 32px)
- Applied low elevation to use a subtle shadow instead of border
- reduced prominence of section heading in BodyBlock
View Components list page, or the Search modal
---
> docs: give components more room to breathe [JOB-110749]

- packages/site/src/componentList.ts
Fixing a small typo in RecurringSelect card
Before:
After:
---
> docs: Fix RecurringSelect typo

- docs/components/Tabs/Web.stories.tsx
- packages/components/src/Tabs/Tabs.test.tsx
- packages/components/src/Tabs/Tabs.tsx
Adding a controlled option to the `Tabs` component
In this PR, the `Tabs` component checks if the `activeTab` prop is provided. If it is, the component uses this prop to determine which tab is active. This means the parent component can control the active tab by updating the `activeTab` prop. If the `activeTab` prop is not provided, the `Tabs` component falls back to managing its own state internally using the `internalActiveTab` state variable.
- new optional prop `activeTab` to allow `Tabs` to be controlled
- new test for controlled version
- storybook example for controlled version
Changes can be
--- …
> feat(components): Add controlled option to Tabs

- packages/site/src/components/ContentCard.tsx
- packages/site/src/components/ToggleThemeButton.tsx
Felt like I could make the collection thumbnails less glaring until we have a better solution (ie mode-responsive images)
- gently darken thumbnail backgrounds and used a darker moon icon
Throw the new docs site in dark mode
---
> docs: tweaks to dark mode experience

- packages/site/src/components/HeaderBlock.tsx
The "subtitle" on the collection pages didn't match the Figma
- div in `HeaderBlock` to use `header`
- weight of subtitle to `semiBold`
View Home, Components, Design in the new site
---
> docs: improve collection page styling and semantics

- packages/site/src/components/ContentCardWrapper.tsx
- packages/site/src/components/ToggleThemeButton.tsx
The theme switcher button and the swatches of cards were getting a bit lost in dark mode
we have the concept of elevation lightening surfaces in dark mode for just such an occasion!
- Elevation applied to the cards and button makes them lighter in dark mode. No change to light mode other than the shadow on the Button wrapper
Check out the Search or collection pages
---
> docs: elevate cardcontentwrapper and theme button for dark mode

- packages/components/src/Tabs/Tabs.test.tsx
- packages/components/src/Tabs/Tabs.tsx
- packages/components/src/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/components/src/Tabs/hooks/useArrowKeyNavigation.ts
In the `Tabs` component, keyboard navigation can be improved when navigating between tabs and to children within individual tabs.  Currently the only way to navigate between tabs is with the tab key and hitting enter to view the focused tab's children. 
Here is a demo of what we should now expect for navigation between tabs:
https://github.com/user-attachments/assets/cc5d24b4-47a9-48ac-936c-7d62c98b6325
In the Tabs component users can:
- tab key will enter or exit the Tabs component
- use arrow keys to navigate between tabs
- while focused on a Tab, if the children of that tab have focusable items, hitting tab will move focus to the child element
- while focused on the content of children in a Tab, shift-tabbing “upwards” out of the content will return focus to the active Tab selector
If …
> feat(components): Add arrow key navigation to Tabs

- packages/site/src/layout/Layout.tsx
We pushed a change recently that removed the design sections from the routing table (erroneously)
This change puts them back in! :)
Removed a line preventing `inNav` items from being added to the routing table.
We also added a manual routing table entry used to allow the components to keep rendering.
Everything should be as it was before this change, but with the design content pages working properly.
---
> fix(components): Docs Site not rendering Design items properly

- packages/site/src/layout/NavMenu.module.css
The arrow on the nav disclosure items was invisible because of the blend mode being applied
- disclosure arrow visible in dark mode
Run the new docs site in dark mode
---
> fix: nav disclosure section dark mode [JOB-111816]

- packages/site/src/designList.ts
- packages/site/src/maps/designContent.tsx
- packages/site/src/routes.tsx
The Design section in the side nav was not utilizing `AnimatedPresenceDisclosure`, so this PR makes that change.
- Design in the side nav is now a disclosure!
- updated the URL from `responsive-breakpoints` to just `breakpoints`. This matches the current url from Storybook (which doesn't have "responsive" in it). I also removed the word responsive from the side nav item. We only have "Breakpoints" in the content cards also. Now everything matches! Less words! Horray!
All Design content loads as it should from Home/Search/Disclosure
Changes can be
---
> docs: Refactor Design item in side nav to use AnimatedPresenceDisclosure

- packages/site/src/pages/HomePage.tsx
We recently updated urls to not all have `/content` preceding other collections like `/design`, etc
This actually broke the `Get Started` button on Home. This PR just removes `/content` to make it work again.
- Get Started button is no longer broken
Click Get Started on Home and make sure you see the welcome/introduction page.
---
> docs: Fix broken url for Get Started button on Home

- packages/site/src/components/ComponentLinks.tsx
- packages/site/src/layout/ComponentView.tsx
- packages/site/src/layout/Layout.tsx
- packages/site/src/layout/NavMenu.module.css
- packages/site/src/layout/PageWrapper.tsx
To get the docs site looking the way it was mocked up and address early feedback, we're structuring the component detail pages a little differently.
- Pull the side rail out of the Grid on the components view
- remove the Grid on the Components view
- reduce max-width of the content for readability
View a component detail page!
Also view a collection page because it uses _some_ of the same components.
---
> docs: Update site layout structure [JOB-111448]

- packages/site/src/layout/Layout.tsx
Removing a blue focus outline on Layout when focused
Hit tab in side nav to engage "Skip to Content" button, select it and see that when focus moves to the content, there is no blue line.
---
> docs: Remove blue border around Layout on focus

- packages/site/src/components/PageBlock.tsx
- packages/site/src/pages/ComponentsPage.tsx
- packages/site/src/pages/HomePage.tsx
On the Home Page, we want sections just like on the Components Page.
1. New prop on `PageBlock` called `showSegmentedControl`. We want to categorize Home but there are not enough items to warrant a `SegmentedControl`. This way, other pages can use the organization of sections but without `SegmentedControl` if needed
2. `sections` have been added to all current items in `HomePage.tsx`
Make sure the Home Page is in categories. No `SegmentedControl`.
Also make sure the Components page still has categories and there is a `SegmentedControl` for further display options.
Changes can be
--- …
> docs: Home Page categorization on New Docs Site

- packages/site/.eslintrc.cjs
- packages/site/src/components/ContentLoader.tsx
- packages/site/src/layout/Layout.tsx
- packages/site/src/layout/SearchBox.tsx
- packages/site/src/main.css
- packages/site/src/maps/index.ts
- packages/site/src/maps/packagesContent.tsx
- packages/site/src/packagesList.ts
- packages/site/src/pages/ContentView.tsx
- packages/site/src/pages/HomePage.tsx
- packages/site/src/pages/PackagesPage.tsx
- packages/site/src/routes.tsx
- packages/site/vite.config.ts
- Packages section added to new docs site, with landing page, sidenav bar items, home item, and search functionality
- fixed the min height for the main content area to be 100% of viewport height
- fixed bug where empty search result was coming up when there were some search results
- check out the side nav, make sure package pages are working as expected
- In the packages - hook page, test out some links (I set up a redirect for those)
- Test out search, make sure packages show up. Make sure if you search for something that doesn't return any component or design results that the empty search state does not appear
Changes can be
--- …
> docs(docx): Adding Packages Section to New Docs Site [JOB-111818]

- packages/site/src/components/AnchorLinks.tsx
- packages/site/src/components/ComponentLinks.tsx
- packages/site/src/components/ContentLoader.tsx
- packages/site/src/layout/BaseView.tsx
- packages/site/src/layout/ComponentView.tsx
- packages/site/src/layout/ContentView.tsx
- packages/site/src/pages/ContentView.tsx
- Adds a `BaseView` component that contains the styles that are shared between `ComponentView` and `ContentView`
- Related to this the page layout on content pages should now be consistent with component pages
- Content pages now have a siderail with anchor tags to jump to parts of the page
- If the siderail has many links (like on changelog pages) the siderail has a scrollbar independent of the main content scrollbar
- Some other cleanup and refactoring
- Click around content and component pages and compare the two. The layouts should be matching
- The content pages should now have anchor links in the siderail. That being said as [Taylor recently pointed out](https://getjobber.slack.com/archives/C081WMPQLUV/p1734460480376659) there are issues with many of the anchor links in the site. So …
> docs: Add siderail for content pages and improve layouts [Job 111086]

- packages/site/src/layout/NavMenu.module.css
When the NavMenu was fully collapsed and there was no need for scrolling, a empty scrollbar was visible (especially on light mode).
We need to hide the scrollbar until it's necessary because a large disclosure is open, etc.
When there are not enough items in the NavMenu to warrant a scrollbar, make sure you don't see one.
Open Components and you should see a scrollbar appear and it works.
Changes can be
---
> docs: Hide NavMenu scrollbar when it's not needed

- packages/site/index.html
Adds the Jobber font via the CDN. Included in this was allowing the local version of the docs site to access the CDN with [this PR](https://github.com/GetJobber/terraform-edge-services-app/pull/23).
If you have a better 👁️  for fonts than me you can just navigate around and look. I was able to clearly show that Jobber Pro is being used in Firefox. I had trouble with this in Chrome but I verified by explicitly setting the font family to "Jobber Pro" on some text to verify that didn't change the appearance of the text at all.
Changes can be
---
> docs: Add Jobber Pro font [JOB-111466]

- packages/site/src/layout/AnimatedPresenceDisclosure.tsx
- packages/site/src/layout/NavMenu.module.css
- packages/site/src/layout/NavMenu.tsx
When navigating through the New Docs site, we want to indicate where the user is, by highlighting the current page in the side nav.
Quick Demo:
https://github.com/user-attachments/assets/3bc7bff6-e06b-4efc-8c63-1b27ed09c3a4
1. New `selected` prop in `AnimatedPresenceDisclosure`
The `selected` prop is passed to each child element to determine if it matches the current URL path. This allows us to apply styles indicating the item is selected in the side nav.
2. `selectedRef` in `NavMenu`.
This allows us to perform actions on selected link like scrolling the item into view in the side nav.
We use `isSelected` to determine if the current URL matches `to` and if it does, the link is considered selected. Then, `selectedRef` is assigned to `ref` of the `Link` component.
See how the side nav …
> docs: Make current page apparent in side nav

- packages/site/src/components/AnchorLinks.tsx
- packages/site/src/components/ComponentLinks.tsx
- packages/site/src/layout/ContentView.tsx
- packages/site/src/layout/Layout.tsx
When viewing the site locally, the following errors were in the console:
`ComponentLinks` which is using `AnchorLinks` had a `key` prop - however we should be avoiding calling a prop `key` to avoid confusion with React's `key` attribute.  That is why I renamed the prop to `id`.
`Layout` needed keys so I've added those to the previously empty fragments. The `React.Fragment` is grouping the dynamic routes under the Switch and adding keys makes React happy (we're aligning more with React's preference for list rendering).
All side rail links should work as expected.
All component pages and sections render as expected.
---
> docs: Add id to AnchorLinks and Add keys to Switch in Layout

- docs/guides/customizing-components.stories.mdx
- packages/components/src/Popover/Popover.test.tsx
- packages/components/src/Popover/Popover.tsx
We've been thinking about incorporating `UNSAFE_` classnames to our components, as an escape hatch. We recently had a request for a style override in `Popover` and thought this would be a great place to start.
Moving forward, our pattern for setting `UNSAFE_` props will be as follows:
- each component has `UNSAFE_className` & `UNSAFE_style` so consumers have flexibility to style inline or use a css module.
- each component will have a container _type_ for the wrapping container
- wherever possible, each component will also have _types_ for subcomponents (`dismissButtonContainer` & `arrow`)
- **_names for these sub types should be carefully considered_**; subcomponents may be other Atlantis components that will eventually have their own classnames.
```
readonly UNSAFE_className?: { …
```
> feat(components): Add UNSAFE_className and UNSAFE_style to Popover

- packages/site/src/layout/NavMenu.module.css
- packages/site/src/layout/NavMenu.tsx
Refining some details to make the docs site search button feel _more Jobber._
- Transition and cursor on hover
- Icon and text color and weight to look more like an "input"
- Radius on keyboard-trigger indicator
Run docs site locally and interact with the Search feature
---
> docs: refine UI for search button

- packages/site/baseDesignList.mjs
- packages/site/tests/site.components.e2e.ts
- basic e2e tests for design pages
- heading text test for the home page
- Pull the branch and run `npm run e2e` 
- Note that my local environment does not load the Icon page, and so these tests break for me. The Icon page seems to load fine in prod though 🤔 
Changes can be
---
> docs(docx): Adding Design e2e tests [JOB-111581]

- packages/site/vite.config.ts
1. We noticed an issue in our production build where the component names were garbled.
This is happening because currently the MDX files are being parsed through Vite via an external source.
I imagine when we move the MDX files into the project, we will not longer have disable minification of the prod code to prevent the garbled component names.
1. Fixing an issue with how our component names render in prod
1. Running `npm run build` locally will generate the prod build, which if you run, will see the proper component names.
Changes can be
---
> fix(components): Garbled Component Names in Prod Site Build Canvas

- packages/site/index.html
- packages/site/src/components/HeaderBlock.tsx
- packages/site/src/main.css
After a recent change to our index file, Jobber Pro was no longer being pulled in from the CDN.
Also, the h1s on our collection pages were set up using Typography to achieve a "white" version, but using the wrong weight of Jobber Pro. This is a great use case for the AtlantisThemeContextProvider.
- Jobber Pro is back
- Collection and detail pages h1s have consistent font-weights
Run docs site locally/Cloudflare
- check collection page (ie Home, Components)
- check detail page (ie Button)
If you can't visually parse the difference between Jobber Pro and Poppins, remove Poppins from the fallback stack in your inspector and observe no change to the rendered font.
---
> docs: fix h1s across the docs site [JOB-113010]

- packages/site/src/preview/useAtlantisPreviewSkeleton.tsx
1. Reported issue where Heading + Typography were not rendering the Jobber Pro font (and instead Poppins or Inter).
Added the font properly to the AtlantisPreview build.
Viewing the Heading component now looks proper, and you can modify the Typography code (fontFamily='display') to render the Jobber Pro font.
If you want to show it on/off, you can remove the line added to the PR to disable/renable the font (in Chrome).
NOTE: This bug did not appear in Firefox, so swapping will have no effect there.
Changes can be
---
> fix(docx): Jobber Pro not rendering properly within Heading + Typography coded examples.

- packages/site/src/components/VisibleWhenFocused.module.css
- packages/site/src/layout/NavMenu.module.css
When we recently introduced some updates to the sidenav + 404page + DOM, we accidentally introduced some additional scrollbars where we didn't want them.
This PR removes the scrollbars (and ensures the nav is the correct width).
Before the changes: 
After the changes:
Removed the double scrollbars (the width of the skip nav combined with the padding on the inner nav elements was causing an overflow).
When visiting the link below you should not see a horizontal scrollbar, and only a single vertical scrollbar.
Changes can be
---
> fix(docx): Fixing the double scroll bars on the Docs Site

- docs/guides/documentation-style.stories.mdx
- packages/site/src/components/PropsList.tsx
- packages/site/src/guidesList.ts
- packages/site/src/layout/BaseView.tsx
- packages/site/src/main.css
- packages/site/src/maps/guidesContent.tsx
- packages/site/src/routes.tsx
While our primary consumers are working on larger monitors, we should consider that they don't always have the docs site running at full width.
- Siderail hides on smaller viewports
- this could be a bit controversial, but I think it's better to maximize usable docs space over quick navigation. Similar behaviour can be observed in other docs sites like [this one](https://polaris.shopify.com/components/actions/button).
- siderail and nav are narrower on smaller-than-large viewports
- Non-component "detail" pages have padding on the left and right when the "main" page region gets narrower than 768 px (future work: Make all "detail" pages use the Page component)
- Props Table reflows a bit earlier
Run docs site locally/CF
--- …
> docs: Make the site work better at the sub-1024px range

- packages/site/src/components/CategoryCardSection.tsx
- packages/site/src/components/ToggleThemeButton.tsx
On smaller breakpoints, the `CategoryCardSection` that holds the headings would overlap the Dark Mode toggle on the bottom right of the page.
At first I adjusted `CategoryCardSection` but really, it should probably be the `ToggleThemeButton` that is adjusted to have a higher zIndex.
Changes can be
---
> docs: Update zIndex on ToggleThemeButton

- packages/site/src/maps/designContent.tsx
- packages/site/src/pages/GettingStartedPage.tsx
- packages/site/src/pages/HomePage.tsx
- packages/site/src/pages/WelcomeGuidePage.tsx
- packages/site/src/routes.tsx
Clicking on the `Get Started` Button on the Home page, also opened up the Design side nav item.
https://github.com/user-attachments/assets/0a833771-d9b6-4ee5-b611-b40022b9e62f
https://github.com/user-attachments/assets/d6268b41-c31f-4c08-b81d-301004084b03
Changes can be
---
> docs: Add a new route for Welcome Guide

- packages/site/src/layout/NavMenu.module.css
- packages/site/src/layout/NavMenu.tsx
Safari sidenav items were misaligned and not interacting as expected in [Safari 17.1 and older.](https://caniuse.com/css-nesting)
- Moved some nested selectors out of the "nested" CSS pattern and into standalone selectors for backwards compatibility. It might be worth doing this globally, or ensuring that our CSS compiles into backwards-compatible CSS automatically, but this PR just fixes the most egregious examples I found.
- Search, sidenav link and disclosure items look as expected
Run locally or in CF in Safari
---
> fix(docx): style sidenav correctly in Safari

- packages/site/src/preview/AtlantisPreviewViewer.tsx
Initially, I set the height of the iframes to have a min-height simply to avoid the internal scrolling area that was occuring, not intending to fix the components themselves not being visible, however this also seems to have fixed the components not being visible as well. 🎉 ?
- add min-height to the iframes themselves
- without the min-height, they seemed to just be collapsing in on themselves
- Components now render in Safari
Run locally in Safari/Chrome/FF
---
> fix(docx): get component iframes rendering correctly

- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.test.tsx
- packages/components/src/DataList/components/DataListTotalCount/DataListTotalCount.tsx
This fixes the `DataListTotalCount` results pluralization 
- When there is a singular result we will show `(1 result)`
- before:
- after:
- Hardcode the `totalCount` to 0,1,2 [here](https://github.com/GetJobber/atlantis/blob/eb21f8c427dd5d427275eb3856d9a2c4bd017019/docs/components/DataList/Web.stories.tsx#L77)
Changes can be
---
> fix(components): DataListTotalCount results pluralization

- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.module.css
We are already adding a box shadow data list sorting options when focused so we don't need an additional outline. As you can see the current behaviour is quite busy:
Makes the outline on focused sorting options transparent
Here is a video of the new behaviour when tested via the pre-release
https://github.com/user-attachments/assets/3433ca33-39f1-4029-bad4-b0920f82f887
Changes can be
---
> fix(components): Add transparent outline for DataList sort options 

- packages/components/src/DataList/components/DataListHeaderTile/components/DataListSortingOptions.module.css
- packages/components/src/SegmentedControl/SegmentedControl.module.css
On old versions of Safari (before 18) the labels on SegmentedControl were displaying far off of where they belonged. 
This was only observed in our new docs site but could also present itself in other implementations. The reason that this was only impacting old versions of Safari is that in 18 they fixed the bug: 
> Fixed overlapping elements with flex box when height: 100% is applied on nested content.
As far as I can tell the height of 100% on the label container was providing no benefits so removing it should allow the labels to display as expected in all versions of Safari as well as other browsers.
The height of 100% from the label container for SegmentedControl labels
- 
- 
Ensure that SegmentedControl continues to behave the same and as expected on browsers other than Safari. If …
> fix(components): Fix label issue with SegmentedControl on older versions of Safari [113267]

- docs/components/InputText/InputText.stories.mdx
- docs/components/InputText/Web.stories.tsx
- packages/components/src/FormField/FormFieldTypes.ts
- packages/components/src/FormField/hooks/useFormFieldWrapperStyles.ts
- packages/components/src/InputText/InputText.rebuilt.tsx
- packages/components/src/InputText/InputText.test.tsx
- packages/components/src/InputText/InputText.tsx
- packages/components/src/InputText/InputText.types.ts
- packages/components/src/InputText/__snapshots__/InputText.test.tsx.snap
- packages/components/src/InputText/index.ts
- packages/components/src/InputText/index.tsx
- packages/components/src/InputText/useInputTextActions.ts
- packages/components/src/InputText/useInputTextFormField.ts
- packages/components/src/InputText/useTextAreaResize.ts
Reverts GetJobber/atlantis#2315
Re-adds the InputText rebuild with fixes for the InputProps types
<strike>I decided to have the have the export of `InputTextProps` be the legacy versions of the props because that is the type most people will be using. I chose not to call it `InputTextLegacyProps` due to no one using the version 2 of InputText at the moment and since it is still "experimental". The rebuild version of the props can be accessed with `InputTextRebuiltProps`</strike>
I decided to not export `InputTextProps` and instead export `InputTextLegacyProps` for the existing usages and `InputTextRebuiltProps`. The reason for this is once we migrate completely from the legacy version we can export `InputTextRebuiltProps` as `InputTextProps`
> revert: "revert: "feat(components): add input text rebuild EARLY Iterations"

- docs/components/DataList/Web.stories.tsx
- docs/components/DataList/storyUtils.ts
- packages/hooks/src/useCollectionQuery/mdxUtils.ts
There were a bunch of console errors when trying to check the docs for `useCollectionQuery` hook, since the star wars API link specified no longer worked.
- 
- Changed the graphQL API link to the one 
- 
- 
- 
- 
1. Navigate to https://atlantis.getjobber.com/hooks/useCollectionQuery
2. Observe CORS error in the console (and network tab) and no returned results in the UI (no list of Star Wars planets)
3. Pull the branch locally or open a preview website
4. Notice the graph request is now successful (200 OK) as well as now you can see the list of planets in the UI.
4.1. CORS error is no longer present in Chrome console.
Changes can be
--- …
> fix(docx): use a correct link for star wars graphQL API (useCollectionQuery hook)

- docs/patterns/interaction.stories.mdx
- packages/components/src/Menu/Menu.module.css
Make Menu hover feel more cohesive with the rest of Atlantis
Make our interaction guide more reflective of how we build hover states
- Menu hover to `ease-out`
- Updated guide content
Locally or via prerelease
Test Menu
Read the docs!
---
> refactor(components): update menu hover state animation curve and transition state guidance

- docs/components/InputPressable/Mobile.stories.tsx
- packages/components-native/src/InputPressable/InputPressable.tsx
`InputPressable` uses `InputFieldWrapper` internally, which accepts a `suffix` prop. While `InputFieldWrapper`'s `suffix` accepts `icon`, `label` and `onPress`, `InputPressable` was missing `onPress` from type definitions. Passing that property still worked, but TS was throwing an error due to missing prop.
- `onPress` prop as a part of `suffix` type in `InputPressable`.
- 
- 
- 
- 
- 
Changes can be
---
> fix(components-native): Add missing onPress prop type to InputPressable suffix (it's already accepted)

- docs/components/Gallery/Web.stories.tsx
- packages/components/src/Gallery/Gallery.test.tsx
- packages/components/src/Gallery/Gallery.tsx
- packages/components/src/Gallery/GalleryTypes.ts
- packages/components/src/Gallery/index.ts
Currently our `InputFile` returns a list of `FileUpload` objects but those objects can't be plugged directly into the Gallery component. This is because Gallery expects files to be of type `File` whose src field is of type `string` instead of `FileUpload` which has a src of type `() => Promise<string>`
- 
The file type that Gallery accepts now allows for a src field of either `string` or `() => Promise<string>` so users can now plug the files that come from InputFile directly into Gallery
- 
- 
- 
- 
The Max Files storybook example now uses files whose src value is `() => Promise<string>`. You can also test existing instances of Gallery using the pre-release version to ensure that its functionality hasn't been modified
Changes can be
[tested via …
> feat(components): Allow Gallery to take a promise source [JOB-113953]

- packages/components/src/Popover/Popover.tsx
A user of Atlantis [pointed out](https://getjobber.slack.com/archives/C03BJHV3PMG/p1738701498519799) that when they use Popover inside a container that has overflow: hidden their popover is cut off. This is because the popover is not inside a portal.
A portal wrapping Popover
- 
- 
- 
- 
Verify that a couple of other portals are behaving as expected and have not been modified. You can grab the pre-release and test out [the endpoint](http://localhost.test:3000/business_health) where the problem was reported. Kyle said I would need a feature flag turned on to view this but I didn't end up needing to. Mentioning in case the reviewer runs into an error on that endpoint.
Changes can be
--- …
> fix(components): Put Popover inside a portal 

- packages/components/src/LightBox/LightBox.module.css
when you view a small image with the new Lightbox changes, it gets stretched out and doesn't look excellent
rather than stretching the image, lets let it be as big as it is and then it doesn't look so bad for small images
- 
we were using `object-fit: contain`
>[contain](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#contain)
>The replaced content is scaled to maintain its [aspect ratio](https://developer.mozilla.org/en-US/docs/Glossary/Aspect_ratio) while fitting within the element's content box. The entire object is made to fill the box, while preserving its aspect ratio, so the object will be ["letterboxed"](https://en.wikipedia.org/wiki/Letterboxing_(filming)) or ["pillarboxed"](https://en.wikipedia.org/wiki/Pillarbox) if its aspect ratio does not match the aspect ratio …
> fix(components): Prevent Stretching Small Images in Lightbox

- docs/components/Checkbox/Web.stories.tsx
- packages/components/src/Checkbox/Checkbox.rebuilt.test.tsx
- packages/components/src/Checkbox/Checkbox.rebuilt.tsx
- packages/components/src/Checkbox/Checkbox.test.tsx
- packages/components/src/Checkbox/Checkbox.tsx
- packages/components/src/Checkbox/Checkbox.types.ts
- packages/components/src/Checkbox/index.ts
- packages/components/src/Checkbox/index.tsx
We want to have a version of Checkbox that isn't coupled with RHF internally. The hidden connection that generates its own names isn't desirable when we want to use a Checkbox with RHF on a form. Additionally, we would like to be less tied to a single form library.
We can't just remove the coupling in our existing component because too much relies on that, and so to offer a de-coupled version we're going to offer a v2 that doesn't include the same setup.
unlike some of the other v2 inputs we've made recently I've opted to not add `ref` as a prop. I can't think of a compelling reason you'd need access to the ref. I haven't heard of anyone requesting it in all the time Checkbox has existed. not strictly opposed to it though, just don't see a reason currently.
A "rebuilt" Checkbox that has …
> feat(components): Checkbox v2

- packages/components/src/LightBox/LightBox.module.css
Follow-up on lightbox component, fixes a bug where the styling of the scrollbar wasn't getting correctly applied in the Safari browser.
> fix(components): Fix scrollbar styling bug in Lightbox component for Safari 

- packages/components/src/DataList/DataList.types.ts
- packages/components/src/DataList/DataList.utils.tsx
- packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
- packages/components/src/DataList/components/DataListActions/DataListActions.tsx
SCE wants to introduce a persistent `DataList.ItemAction` for our review dashboard client attributions. [See original PR.](https://jobber.atlassian.net/browse/JOB-114615)
- Until the `DataList.ItemAction` UI becomes completely customizable/composable by JO facing teams, this prop allows us to force a single action item to render un-nested (no longer hidden behind the `more` icon)
- Please see the video below for usage of the prop.
https://github.com/user-attachments/assets/04dd4887-0020-45f2-ad08-8b81047a7704
_You can follow the steps in the video above or follow along below_
1. Deploy storybook locally
2. Verify DataList remains unbroken
3. Open `docs/components/DataList/Web.stories.tsx` and set one of the item actions to `alwaysVisible={true}`, delete the other item actions
4. Navigate …
> feat: Allow DataList.ItemAction to avoid nesting

- packages/components/src/Menu/Menu.module.css
- packages/components/src/Menu/Menu.module.css.d.ts
- packages/components/src/Menu/Menu.tsx
- packages/components/src/Menu/__snapshots__/Menu.test.tsx.snap
- packages/components/src/Page/__snapshots__/Page.test.tsx.snap
Gui pointed out [here](https://getjobber.slack.com/archives/C03BJHV3PMG/p1739480113250269) that a `Chip` could not be used as an activator for a `Menu`. The reason Chip doesn't work is:
- Chip is essentially a Button wrapped in a Toolbar which leads to code like this:
```
<span class="Tooltip-module__shadowActivator--G4n8v"></span>
<button class="Chip-module__chip--Ob7Ns Chip-module__base--Gz7fH" tabindex="0" role="button" type="button" aria-description="description">
```
- Before these changes we were adding a shadow ref as a sibling to the activator and then using `shadowRef.current?.nextElementSibling` to access the activator
- When a button was used as an activator this would work since the button would be the sibling of the shadow ref. Unfortunately, this was broken for a Chip since …
> fix(components): Allow Chip to be used as an activator in Menu 

- docs/components/Button/Mobile.stories.tsx
- docs/components/Text/Text.stories.mdx
- packages/components-native/src/Button/Button.tsx
- packages/components-native/src/Text/Text.tsx
- packages/components/src/Popover/Popover.tsx
- packages/site/src/content/Button/Button.props-mobile.json
- packages/site/src/content/Button/ButtonNotes.mdx
- packages/site/src/content/Popover/Popover.props.json
- packages/site/src/content/Popover/PopoverNotes.mdx
- packages/site/src/content/Text/Text.props-mobile.json
- packages/site/src/content/Text/TextNotes.mdx
- packages/site/src/content/Text/index.tsx
Recently we added `UNSAFE_` props to mobile `Text` & `Button`.  
`UNSAFE_` was going to be used by a team and was somewhat time sensitive, so I committed to updating docs as a fast follow, to get the feature out the door.
- New `Text` Implement tab with `UNSAFE_` info
- `UNSAFE_` info to the pre-existing `Button` Implement tab
Make sure you see `UNSAFE_` info in the Implement tab for `Button` & `Text`.
Changes can be
---
> docs: Add UNSAFE documentation to mobile Button and Text

- packages/components/src/DataList/components/DataListActions/DataListActions.test.tsx
- packages/components/src/DataList/components/DataListActions/DataListActions.tsx
I merged a typo with my branch last week that prevents the persistent ItemActions from rendering correctly. For shame.
- Fix spelling so that the DataList.ItemAction properly renders
- Open `docs/components/DataList/Web.stories.tsx` and set one of the item actions to alwaysVisible={true}, delete the other item actions
- Navigate to your local story book and verify you no longer see the 'more' icon and instead see your item actions label on hover of the row.
---
> fix(components): There was a typo in the DataList.ItemAction logic

- packages/site/src/components/TritonConversation.tsx
Documentation links from Triton were doing full page navigation, causing Triton chat to lose the questions and answers state in context.
- 
- 
- 
- Triton documentation link now uses `Link` from `react-router-dom` instead of Atlantis `Link`
- 
Changes can be
---
> fix(docx): Stop Triton Link from doing full page navigation

- .circleci/config.yml
- packages/components/src/Menu/Menu.tsx
Linting failures can be teadius because warnings are also reported. This PR aims to fix this by using [--quite](https://eslint.org/docs/latest/use/command-line-interface#--quiet)
-  Only report errors in Circle CI to make taking issues when linting fails easier 
Check the eslint failures in circle CI for https://github.com/GetJobber/atlantis/pull/2401/commits/15e1d77a0f9df52b5d79f7e39149b84bcc2f971c and verify that only the errors are reported in the list of failed tests
Changes can be
---
> build: Update circle to only report errors when linting javascript

- docs/components/Chip/Comparison.stories.tsx
- packages/components/src/Chip/Chip.module.css
- packages/components/src/Chip/Chip.tsx
the hover/focus states of the truncation gradient did not look great. this is because you cannot simply apply a `transition` to a `linear-gradient` `background`.
the goal of this PR is to make that look better than the current state.
rather than trying to transition between the same element having 2 different gradient colors, what we're doing is instead having 2 distinct elements with a different gradient color for each of them. one will have `opacity: 1` by default, this will be the same color as the resting Chip variant background color.
the other will be `opacity: 0` by default and will have the hover/focus background color as its gradient.
as we hover, we will swap the opacity of these two gradients that are in the exact same position. since opacity IS a value that responds to …
> fix(components): Fix Chip Truncation Gradient

- docs/components/Autocomplete/Web.stories.tsx
- packages/site/src/content/Autocomplete/AutocompleteExamples.tsx
- packages/site/src/content/Autocomplete/AutocompleteNotes.mdx
Our documentation for `customRenderMenu` includes a custom menu and a footer button. The footer should not scroll. We want to provide an implementation for this use case and make sure scroll into view with keyboard navigation still works.
- Storybook implementation to make sticky footer and keyboard navigation work
- Updates to implementation notes to explain this usage
- 
- 
- 
- 
- 
- 
Changes can be
---
> docs: AutoComplete customRenderMenu sticky footer implementation

- packages/site/src/components/TritonConversation.tsx
With the new SideDrawer title, the welcome heading was identical in weight to the drawer title.
- Better visual and semantic hierarchy for the Triton drawer when you first interact with it.
Run locally or on CF
---
> docs: use h3 instead of h2 for Triton welcome message

- packages/components/src/FormField/FormFieldAffix.tsx
- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/index.ts
- packages/components/src/utils/meta/meta.json
As we work on composability we want to export the internal building blocks of our components to allow consumers to leverage them when composing our components. This PR exports some of the internals
- 
- 
- 
- 
- Export internal of `FormFieldWrapper` for consumers to use if neede3d
- 
Changes can be
---
> fix(components): Export form field internal components.

- packages/site/src/components/TritonSideDrawer.tsx
- packages/site/src/providers/TritonProvider.tsx
- packages/site/src/utils/useTritonApi.ts
Developers and Designers can use the Triton SideDrawer, so we should offer both personalities.
- A `SegmentedControl` is now in the Triton SideDrawer to toggle back and forth between personalities
- an `ActivePersonalities` type for `developer` and `designer` (mirrors the Triton API)
- `TritonProvider` manages the value of `ActivePersonalities` in it's context state, when the `SegmentedControl` is toggled, the context's `setPersonality` is called, updating the personality
- In `useTritonApi.ts` in the `response` update the url: `http://localhost:8788/${endpoint}`
- start the `atlantis-ai` server
- in atlantis, cd into `packages/site` and run `npm run dev`
- enter the Triton API key in the SideDrawer and ask a question with `developer` selected and then `designer` selected
- go to the …
> docs: Add personality SegmentedControl to Triton SideDrawer

- docs/components/InputText/Web.stories.tsx
The Code tab in `InputText` story was broken - we needed to add `extraImports`
Changes can be
---
> docs: Add FormFieldLabel to extraImports in InputText example

- packages/components/src/SegmentedControl/SegmentedControlProvider.test.tsx
- packages/components/src/SegmentedControl/SegmentedControlProvider.tsx
The controlled variation of `SegmentedControl` calls `onSelectValue` during rendering, which is usually a `setState` call. There should not be side effects during render phase.
This was first discovered as part of this [PR](https://github.com/GetJobber/atlantis/pull/2423) where `onSelectValue` (which is a `setPersonality` setState call in its parent) is called during render phase. This is the error:
`Cannot update a component (TritonProvider) while rendering a different component (SegmentedControlProvider).`
- 
- Wrapped onSelectValue call in SegmentedControlProvider in `useEffect` to make sure it only gets called after initial render
- 
- 
- 
- 
Changes can be
---
[In Atlantis we use …
> fix(components): fix controlled SegmentedControl render state update

- packages/components/src/SegmentedControl/SegmentedControlProvider.test.tsx
- packages/components/src/SegmentedControl/SegmentedControlProvider.tsx
The `useEffect` was unnecessary. In a controlled component pattern, the parent is the
source of truth  and the child should only notify of actual user interactions,
not try to sync or manage state with the parent.
This change:
- Removes the `useEffect` that was calling `onSelectValue` on mount
- Maintains proper parent-child relationship where parent is all-knowing
- Prevents unwanted navigation when the component loads
Changes can be
---
> fix(components): remove unnecessary useEffect in SegmentedControlProvider

- packages/components/src/Typography/Typography.test.tsx
- packages/components/src/Typography/Typography.tsx
- packages/site/src/content/Typography/Typography.props.json
- packages/site/src/content/Typography/TypographyNotes.mdx
As we add `UNSAFE_` props to move and more components, it's important and helpful to get `UNSAFE_` into atom components first. Updating `Typography` will help unlock maximum customization in components like `Text`, `Disclosure`, etc.
- `UNSAFE_className` and `UNSAFE_style` on `Typography`. I decided to make these props a keyed object, even though we just have one element here.  This is for a few reasons:
1. Consistency - the mobile `Typography` component has a `textStyle` key; now `UNSAFE_` is 1:1 in mobile and web
2. Future-proofing - if we ever need to add more targetable elements in the future, we don't need to change the API structure
- Updated the Implement tab to include `UNSAFE_` info
- tests
Add this to `docs/components/Typography/Web.stories.tsx` to see that you can override via …
> feat(components): Add UNSAFE_ props to Typography

- packages/site/src/main.css
Before we had more sensible line-lengths/width restrictions in the docs site, center-aligning and capping the width of tables was a practical approach to making sure they never got too wide, and had less of a "river" effect when used in sequence.
However, since we've tightened up our document layouts, the tables can fairly safely run full-width and have a less jarring jump in content alignment.
- Table layout (before/afters):
Run docs site locally (design and content pages, as well as patterns, have a decent set of tables)
---
> docs: make docs tables more predictable

- packages/site/src/layout/NavMenu.module.css
- packages/site/src/layout/TopNav.tsx
- packages/site/src/main.css
With some of the recent changes to the doc site (notably top nav), the balance is a little off.
- Padding of topnav and alignment of items in the side nav and side rail
Run site locally.
Changes can be
---
> docs: adjust layout of doc site chrome

- packages/components/src/Disclosure/Disclosure.test.tsx
- packages/components/src/Disclosure/Disclosure.tsx
- packages/site/src/content/Disclosure/Disclosure.props.json
- packages/site/src/content/Disclosure/DisclosureNotes.mdx
- packages/site/src/content/Disclosure/index.tsx
`Disclosure` is a high priority component for composability so we've decided to add `UNSAFE_` props.
- `UNSAFE_className` & `UNSAFE_style` props for each element of the `Disclosure` (including `Typography` and `Icon` being surfaced)
- Tests for both `UNSAFE_` prop type
- Implement Tab for `Disclosure`, outlining how to use `UNSAFE_` props 
You can add this to `docs/components/Disclosure/Web.stories.tsx` and see how we can successfully target `Disclosure` elements including the `Icon` and `Text`
```
export const UNSAFECustomization = BasicTemplate.bind({});
UNSAFECustomization.args = {
title: "Customized Disclosure",
UNSAFE_style: {
container: {
border: "3px solid var(--color-purple)",
borderRadius: "var(--radius-base)",
},
summary: {
background: "var(--color-yellow--lighter)",
padding: …
```
> feat(components): Add UNSAFE_ props to Disclosure

- package-lock.json
- packages/components/package.json
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.module.css
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/hooks/useComboboxAccessibility.ts
Since PopperJS is EOL we are aiming to replace it with Floating UI. This is the first PR to remove PopperJS from our repo.
Decisions:
- I updated the keyboard dismiss logic to take advantage of Floating UI's [useDismiss](https://floating-ui.com/docs/useDismiss) functionality
- 
- Changed Combobox content to be rendered with Floating UI instead of PopperJS
- 
- 
- 
- 
Open up combox box stories
- Verify the following with both mouse navigation and keyboard navigation
- On the non-keep open on click story verify that selecting the Combobox action closes the combobox
- On the keep open on click story verify that selecting the action keeps the combobox open
- Verify on single select, selecting an option closes the combobox
- Verify on multi select, selecting an option does not close the …
> refactor(components): Replace popperjs with floating-ui in combobox

- docs/components/Card/Web.stories.tsx
- packages/components/src/Card/Card.tsx
- packages/components/src/Card/tests/Card.test.tsx
- packages/components/src/Card/types.ts
- packages/components/src/utils/meta/meta.json
- packages/site/src/content/Card/Card.props.json
- packages/site/src/content/Card/CardNotes.mdx
- packages/site/src/content/Card/index.tsx
Enhance the Card component's flexibility and usability by implementing a compound component pattern, which allows for better composition and more intuitive usage of Card subcomponents.
- Added comprehensive documentation for Card component usage and customization
- Added `CardHeader` and `CardBody` sub-components for better composition
- Added detailed documentation for `url`, `external`, and `onClick` props
- Added `CompoundComponent` story to showcase the `Card` component with header and body structure
- Added comprehensive tests for compound components scenarios
- Simplified prop destructuring and enhanced rendering logic in Card component
- Renamed header and body components for consistency
- Refactored `Card` component to support three distinct card types: LinkCard, ClickableCard, …
> refactor(components): Make Card component composable

- docs/components/Page/Web.stories.tsx
- packages/components/src/Page/Page.test.tsx
- packages/components/src/Page/Page.tsx
- packages/site/src/content/Page/Page.props.json
New Pages are in need of actions that are not primary actions.
- Introduced a new `SecondaryActionOnly` story to showcase the Page component with only a secondary action.
- Updated documentation to reflect changes in the secondary action behavior.
- Updated the Page component to display the secondary action button even when no primary action is provided.
- Enhanced tests to verify rendering and functionality of the secondary action button independently.
Changes can be
---
> feat(components): Add secondary action support to Page component even without primary action

- packages/components/src/Text/Text.test.tsx
- packages/components/src/Text/Text.tsx
- packages/site/src/content/InputFile/InputFile.props.json
- packages/site/src/content/Text/Text.props.json
- packages/site/src/content/Text/TextNotes.mdx
- packages/site/src/content/Typography/TypographyNotes.mdx
We are currently making our way through atom components, adding `UNSAFE_` props in these small building blocks so it is easier to surface in larger components later on.
- `UNSAFE_` props in web `Text` (just surfacing via `Typography`)
- tests for `UNSAFE_` props
- new section in the `Text` `Implement` tab explaining how to use the props
- update in `Text` props file
- update in `InputFile` props file (comment below talking about it)
- some markup was changed in `TypographyNotes` while I'm in the area
Update existing Storybook example and look at the Basic story:
```
Basic.args = {
children:
'"640K is more memory than anyone will ever need on a computer" - Not Bill Gates',
UNSAFE_style: {
textStyle: {
color: "red",
fontSize: "20px",
},
},
};
```
Changes can be
[tested via …
> feat(components): Add UNSAFE props to Text

- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
- packages/site/src/content/Heading/Heading.props.json
- packages/site/src/content/Heading/HeadingNotes.mdx
- packages/site/src/content/Heading/index.tsx
Adding UNSAFE props to atom components to allow more customizations
- Added `UNSAFE_className` and `UNSAFE_style` props to `Heading` (which just get forwarded to `Typography`
- Tests for UNSAFE props
- Notes in the Implementations tab with UNSAFE props use explanation
- `Heading` props file update
- 
- 
- 
- 
- 
Add this to the existing story and make sure it renders as expected
```
<Heading
level={1}
UNSAFE_style={{ textStyle: { color: "var(--color-red" } }}
>
Custom Heading
</Heading>
```
Changes can be
---
> feat(components): Add UNSAFE props to Heading

- packages/components/src/Banner/Banner.tsx
- packages/site/src/content/Banner/Banner.props.json
Banner has some prop descriptions that are missing or outdated 
Missing: **type** description
_Probably the most commonly needed prop_
Outdated: **icon** description
_There's always an icon now, you can just override it as an option_
Outdated: **primaryAction** description
_primaryAction defaults to a subtle Button now and there's no more conditional switching based on Banner type_
- Descriptions of some Banner props
Review the Banner docs in Storybook and the docs site
---
> docs: clean up Banner prop docs

- docs/design/Spacing.stories.mdx
- packages/components/src/Box/styles/BoxGap.module.css
- packages/components/src/Box/styles/BoxGap.module.css.d.ts
- packages/design/src/tokens/space.tokens.json
- packages/site/src/content/Box/Box.props.json
In Atlantis alone, we work around the lack of a space in between `small` and `base` in several places:
Adding small (8) and smaller (4):
Subtracting smaller (4) from base (16):
In addition, the Jobber web and mobile codebases (either directly or through calcs) get to this number a few dozen times between them.
As a note: I would prefer to _add_ the token here and then fast-follow with the in-Atlantis replacements of the calcs for ease of testing/reviewing, but if you, reviewer, would prefer I do all of that in one shot I can!
[Figma](https://www.figma.com/design/HXWXusJPZLmaJNGlKEpiyhXW/branch/1LPdYn25btQCAiEdg23IUE/Product%2FBase?m=auto&node-id=13731-0&t=IVHs08XV7u2iIYHI-1)
- Updated the outdated spacing patterns imagery with embedded Figmas for "live" updates
- New spacing token: …
> feat(design): add slim spacing token and add to docs

- packages/site/src/content/InputCurrency/index.tsx
noticed on prod that the storybook link for InputCurrency is for `localhost:6006.....` which of course doesn't work on prod, nor localhost unless you're running it on that port which I am not.
- 
- 
- 
- 
the link now correctly links to the actual storybook for InputCurrency on prod
- 
check the prerelease, click the link see that it works :)
Changes can be
---
> fix(docx): Fix InputCurrency Storybook Link

- docs/components/Glimmer/Glimmer.stories.mdx
- docs/components/Glimmer/Web.stories.tsx
- packages/components/src/Glimmer/Glimmer.module.css
Ricardo raises a valid point: the existing Glimmer does not use semantic tokens (fairly, as it relies on opacities in a way that our color tokens do not handle), so Glimmer looks like this in dark mode:
The dark "track" is barely noticeable, and the white "glimmer" is jarringly bright.
This update checks for Atlantis' dark mode and adjusts the CSS values accordingly:
https://github.com/user-attachments/assets/37b3bf46-dcab-4446-8290-fd70815a2410
- comparison stories to make it easier to QA visual updates to Glimmer
- update Glimmer styling to check for dark theme
- Glimmer is now appropriately visible in dark mode
Storybook is _likely_ sufficient, but you can pull in pre-release to verify in Jobber.
Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workf …
> fix(components): make Glimmer respond to dark mode

- packages/components/src/FormField/FormField.module.css
A small bug was noticed when using autofill in Chrome on our Input fields, in dark mode. The input text stayed black when it should be white.
- `-webkit-text-fill-color: var(--field--value-color);` to target the -webkit-autofill pseudo-class to maintain consistent text colour when switching between light/dark modes
_Note:_ the overlap with the text & placeholder when hovering over the autofill option happened before, it is just more noticeable now in dark mode that the text is white. 
```
const AutofillTemplate: ComponentStory<typeof InputText> = args => {
return <InputText {...args} />;
};
export const Autofill = AutofillTemplate.bind({});
Autofill.args = {
name: "firstname",
placeholder: "First name",
autoComplete: "given-name",
};
```
Changes can be
[tested via …
> fix(components): Update text color on autofill in FormField

- packages/components/src/DataList/components/DataListHeaderTile/DataListHeaderTile.tsx
When `DataListHeaderTile` is sortable, the header is then turned into a html `button`. 
An html `button` will act as `type=submit` when wrapped inside a form.
Therefore, if a `<form>` contains a `DataList` with sortable headers, attempting to sort the `DataList` columns will cause a form submit and therefore, page reload.
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/submit#using_submit_buttons
```
<Tag
...
{...(isSortable ? { type: "button" } : {})}
>
```
When `isSortable` is true: spreads { type: "button" } onto the element
When `isSortable` is false: add nothing
I could have also done `type={isSortable ? "button" : undefined}`.  This would then mean we're setting `type={undefined}` on a div element - not semantically correct.
Put the following code into …
> fix(components): Assign type button to DataListHeaderTile when column is sortable

- docs/components/Chips/Web.stories.tsx
- docs/components/Chips/utils/storyUtils.ts
- packages/components/src/Chips/ChipsTypes.tsx
- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissible.tsx
- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleInput.tsx
- packages/components/src/Chips/InternalChipDismissible/InternalChipDismissibleTypes.ts
- packages/components/src/Chips/InternalChipDismissible/__tests__/InternalChipDismissibleInput.test.tsx
- packages/components/src/Chips/InternalChipDismissible/hooks/__tests__/useInternalChipDismissibleInput.test.tsx
- packages/components/src/Chips/InternalChipDismissible/hooks/useInternalChipDismissibleInput.tsx
- packages/site/src/content/Chips/Chips.props.json
The motivation was to achieve the A/C of this ticket, essentially allowing Chips to be used as an email selection input that has similar functionality to GMail. I'll admit, I don't feel fantastic about these changes as they add more complexity to already quite complex component. I had a conversation with though and we agreed that it made sense to add these additions to Chips for now and then look into building a new component, potentially using autocomplete, to achieve this functionality in the future without relying on Chips. In the meantime though I tried really hard to keep the new logic as simple as possible and add new testing coverage/improve the tests that were existing before.
Adds two new props:
- `onlyShowMenuOnSearch`: If this is `false` (the default) when you click on the …
> feat(components): Add ability to only open Chips menu on search [JOB-119726]

- packages/components/src/FormField/FormFieldTypes.ts
the `Clearable` type was not coming through in non-Atlantis projects using Atlantis. this is because there was a bad path to it that makes sense in Atlantis, but wouldn't be valid when the separate packages (hooks, components etc) are bundled and used.
we need to reference it in the correct way
credit goes to Jacob for figuring this out!
updated `Clearable` path/source to work when we bundle Atlantis
- 
- 
- 
- 
- 
- 
use this pre-release build in another project. see that when using the `clearable` prop on components like `InputTime` `InputText` `Autocomplete` and more, that your IDE and the types correctly inform you what is available and what is invalid eg. `clearable={false}` is not OK
Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigg …
> fix(components): Fix Type Definition Linking for Clearable

- packages/components/src/InputTime/InputTime.types.ts
- packages/components/src/InputTime/index.tsx
- packages/site/src/content/InputTime/InputTime.props.json
we removed the functionality of `defaultValue` on `InputTime` v2 - since it's meant to be a controlled component. however the types are not correctly reflecting that, I believe it's because we had defined `version?: 1 | 2` and so it could meet that criteria of the "old" set of props and not exclude it like we'd like
re-jigged the types a bit to properly tell TS that if you do `version={2}` there is no `defaultValue` prop
- 
- 
- 
- 
- 
- 
`<InputTime version={2} defaultValue={new Date()} .../>` should NOT do anything with the provided date, and TS should tell you that's invalid.
`<InputTime version={1} defaultValue={new Date()} ... />` should continue to work
`<InputTime defaultValue={new Date()} ... />` should continue to work
anything referencing `InputTimeProps` should continue to …
> fix(components): Properly Exclude DefaultValue from InputTimev2 Props

- docs/components/Select/Web.stories.tsx
- packages/components/src/Select/Select.rebuilt.tsx
- packages/components/src/Select/Select.types.ts
- packages/site/src/content/Select/Select.props.json
It turns out `maxLength` is not only used on `input` and `textarea`, but also fed into `useFormFieldWrapperStyles` to determine the width of the input. This PR adds the prop back to `SelectLegacy` that originally had it.
- 
- Added `maxLength` to `SelectLegacyProps` and `SelectRebuiltProps`
- 
- 
- 
- 
Changes can be
---
> feat(components): Add maxLength prop to both Select versions

- packages/components/src/FormField/FormFieldWrapper.tsx
- packages/components/src/FormField/components/ClearAction.tsx
- packages/components/src/Select/Select.rebuilt.tsx
- packages/components/src/Select/hooks/useSelectActions.ts
For some inputs, they are not clearable (e.g. `Select`). However even if `clearable` is set to "never", `onClear` handler is still a required prop on `FormFieldWrapper`, making us create `handleClear` function that will never be used.
- 
- `onClear` prop of `FormFieldWrapper` is now optional
- `onClick` prop of `ClearAction` now has a `?` conditional check.
- Removed empty `handleClear` function in Select rebuilt 
- 
- 
- 
- 
- Test in legacy InputText's clearable story, where `onClear` handler comes from `useAtlantisFormFieldActions`. Confirm value is still being cleared.
- In Select rebuilt, `onClear` is not being passed into `FormFieldWrapper`. Confirm no typescript error.
Changes can be
[tested via Pre-release](https://github.com/GetJobber/atlantis/actions/workflows/trigger-qa-build.ym …
> feat(components): make onClear optional on FormFieldWrapper

- packages/site/src/guidesList.ts
When using search for layouts and clicking the layouts guide it leads to a 404. This PR fixes that.
- 
- 
- 
- 
- Fixed link to Layouts guide when using search
- 
Changes can be
- On [atlantis](https://atlantis.getjobber.com/) search for layouts and click the guides to page layouts. Notice that it 404s. This also happens from https://atlantis.getjobber.com/guides
- On the preview site. Search for layouts and click the page layouts guide. Observe it redirects correctly. Confirm that layouts page loads when you click Page Layouts on the [guides page](https://mike-fix-layouts-link.atlantis.pages.dev/guides) …
> docs: fix link to layouts guide provided by the search

- docs/guides/figma-101.mdx
- docs/guides/figma-overview.mdx
- packages/site/src/guidesList.ts
- packages/site/src/maps/guidesContent.tsx
- packages/site/src/routes.tsx
There's some good Figma onboarding pieces scattered around internal wikis that would be helpful for new Jobber designers to have consolidated access to. Would like to link this on the Home page once it lands.
- Guide to our Figma library setup and general Jobber-specific approaches to file setup and structure
- Note: Figmas are not publicly viewable and are also have no real "trade secret" content - IMO this is secure enough. If the team feels strongly otherwise, I can leave the content in internal wikis, or we could look at some of the ideas around conditional authentication like we have in place on Triton. FWIW we already have embedded Figmas in our icon guidance docs and some patterns docs.
- Run locally/in CF
- When not logged in to Figma, you should not see the Figma files previewed …
> docs: add guide to Figma libraries

- packages/components/src/Combobox/Combobox.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/components/ComboboxTrigger/ComboboxTrigger.tsx
- packages/site/src/content/Combobox/Combobox.props.json
Recently we added `ref` to `Chip` so that if you are using a Combobox to make a selection that is required on a form, specifically Zod + RHF though a similar effect could be achieved other ways, we'd have a ref to register with the form to scroll to and focus.
The only way to provide a ref would be thru a custom activator, which is not ideal if all you want is the default activator with a ref. Having to rebuild the activator just to access that isn't great.
So, to allow for the default to have a ref we're adding a `defaultActivatorRef` prop. The intent of the name is to communicate that it is ONLY going to work if you are using the default activator since the way COmbobox works is that if you want to override the default you provide `Combobox.Activator`, if you want the default you do not …
> feat(components): Add Default Activator Ref to Combobox

- packages/components/src/Button/Button.tsx
- packages/components/src/Button/__snapshots__/Button.test.tsx.snap
- packages/components/src/Link/Link.tsx
Add security attributes to external links to prevent potential security vulnerabilities when using `target="_blank"`. This follows web security best practices by preventing the new page from accessing the `window.opener` property and hiding the referrer information.
- Added `rel="noopener noreferrer"` to external links in the `Link` component when `external` prop is true
1. Go to the `Basic` Link story
2. Inspect & verify that the rendered anchor tag includes both `target="_blank"` and `rel="noopener noreferrer"`
3. Click the link and ensure it still opens in a new tab as expected
Changes can be
--- …
> feat(components): Add noopener and noreferrer attributes to Link

- packages/components/src/Text/Text.tsx
- packages/site/src/content/InputFile/InputFile.props.json
- packages/site/src/content/Text/Text.props.json
Allow users of the `Text` component to specify which HTML element they want to render, providing the same flexibility as the `Typography` component. This enables more semantic markup while maintaining consistent text styling.
- Added `element` prop to `Text` component that accepts all HTML elements supported by `Typography` (h1-h6, p, b, em, dd, dt, strong, span)
- Default value is "p" to maintain existing behavior
- Type is derived from `Typography` component to ensure consistency
Use `Text` component with different element values:
2. Verify that each renders with the correct HTML tag while maintaining Text component styling
3. Verify that existing Text component usage without the element prop continues to render as a paragraph
Changes can be
[tested via …
> feat(components): Add element prop to Text

- packages/components-native/src/Content/Content.test.tsx
- packages/components-native/src/Content/Content.tsx
- packages/components-native/src/TextList/__snapshots__/TextList.test.tsx.snap
- packages/site/src/content/Content/Content.props-mobile.json
- packages/site/src/content/Content/ContentNotes.mdx
- packages/site/src/content/Content/index.tsx
This PR adds `UNSAFE_style` customization capabilities to the mobile `Content` component. The main driver for this was to allow consumers the ability to set different spacing on the outer edges of `Content`.
- Added `ContentUnsafeStyle` interface with support for:
- `container`: Customizes the main wrapper View
- `childWrapper`: Customizes each child's wrapper View
- Added tests for `UNSAFE_style` functionality
- Added documentation in ContentNotes.mdx
- re-generated `Content.props-mobile.json`
You can put the following in `docs/components/Content/Mobile.stories.tsx`:
```
export const WithCustomStyles = BasicTemplate.bind({});
WithCustomStyles.args = {
direction: "vertical",
spacing: "none",
UNSAFE_style: {
container: {
backgroundColor: tokens["color-surface--background"],
padding: …
```
> feat(components-native): Add UNSAFE_style to Content

- docs/components/Modal/Web.stories.tsx
- packages/components/src/Modal/ModalSizes.module.css
There was an issue where sometimes the `modal.module.css` and `modalsizes.module.css` could be imported in different order causing the styling to not cascade consistently. This PR fixes that. This issue also caused the `Modal.Provider` method of using a modal to not respect the size prop.
- 
- 
- 
- 
- fix(components): Fix Modal.Rebuilt not respecting size prop consistently
- fix(components): Fix modal sometimes not respecting the size prop
- 
- Verify the size prop is respected in the storybook example [here](https://b8334687.atlantis.pages.dev/storybook/?path=/story/components-overlays-modal-web--modal-with-provider-example)
Changes can be
--- …
> fix(components): Fix modal size not being respected in all cases

- packages/components/src/Card/cardcolors.module.css
- packages/components/src/Card/cardcolors.module.css.d.ts
`Card` allowed `invoiceColor`, `requestColor`, `jobColor` & `quoteColor` as an `accent`. Now we need to add `clientColor` to round out all objects.
- `clientColor` is now available as a `Card` `accent`
Select `clientColor` from the `accent` dropdown and see the change.
Changes can be
---
> feat(components): Add clientColor to Card accent

- packages/design/src/tokens/dark.tokens.json
- packages/design/src/tokens/workflow.tokens.json
- packages/site/src/content/Box/Box.props.json
- packages/site/src/content/Typography/Typography.props.json
When trying to assign `clientColor` to a `Card` in product, it wasn't appearing as the same taupe color that was displaying in Storybook. It was showing up as just grey. See this PR for the `Card` update https://github.com/GetJobber/atlantis/pull/2537
Looking through colors I noticed that `client` didn't have the same tokens as other objects. This PR fixes the `clientColor` issue in product.
- `client-` tokens for `surface` & `onSurface` in `dark.tokens.json` and `workflow.tokens.json`
Can put this in `docs/design/Colors.stories.mdx` to see the colors:
```
<Swatch
colors={[
"--color-client",
"--color-client--surface",
"--color-client--onSurface",
]}
/>
```
Changes can be
---
[In Atlantis …
> feat(design): Add surface and onSurface colors for color-client

- packages/components-native/src/Chip/Chip.test.tsx
- packages/components-native/src/Chip/Chip.tsx
- packages/components-native/src/FormatFile/components/ProgressBar/ProgressBar.style.tsx
- packages/components-native/src/ProgressBar/ProgressBar.tsx
- packages/components-native/src/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
- packages/components-native/src/Switch/components/BaseSwitch/BaseSwitch.tsx
- packages/components-native/src/Switch/components/BaseSwitch/__snapshots__/BaseSwitch.test.tsx.snap
Standardize visual language of native components with web, leveraging the new token created in #2227 and implemented in web components in #2230 
- Background color in
- Chip
- ProgressBar
- FormatFile internal ProgressBar
- Switch
In Storybook and run prerelease in mobile project (Android + iOS to test Switch)
Changes can be
---
> refactor(components-native): use interactive--background token in mobile components

- docs/components/Tiles/Web.stories.tsx
- packages/components/src/Tiles/Tiles.module.css
- packages/components/src/Tiles/Tiles.tsx
- packages/components/src/Tiles/types.ts
- packages/site/src/content/Tiles/Tiles.mdx
- packages/site/src/content/Tiles/Tiles.props.json
Fixed tiles having a default min size but forcing it to be required
Tiles had 2 issues that I wanted to address.
1. Tiles had a default `minSize` in the component but still required it while using it. This marks the `minSize` as optional to match the implementation.
2. Updated Tiles to support vertical alignment of tiles
- Support vertical alignment of Tiles
- Fixed tiles requiring the `minSize` prop even though the implementation had a default value set
- 
Changes can be
---
> feat(components): Update tiles to support alignment prop.

- packages/components/src/Banner/Banner.module.css
- packages/components/src/Button/Button.module.css
- packages/components/src/FormField/FormField.module.css
- packages/components/src/InlineLabel/InlineLabel.module.css
- packages/components/src/MultiSelect/MultiSelect.module.css
- packages/components/src/SegmentedControl/SegmentedControl.module.css
Since we've introduced a token for `slim` to meet needs that were being worked around repeatedly, let's clean up the old workarounds.
The most common was subtracting `smaller` (4) from `base` (16), but also found some multiplications. I checked for division like `large` (24) / `2`, but did not find anything 
- No visual changes
- Replacing calcs with the `--space-slim` token
- Banner
- Button
- FormField
- InlineLabel
- MultiSelect
- SegmentedControl
Testing in Storybook should be sufficient - expect no visual diff
Changes can be
---
> refactor(components): replace calcs to 12 with slim in web

- packages/components/src/FormField/FormField.module.css
- packages/components/src/FormField/FormField.module.css.d.ts
- packages/components/src/InputDate/InputDate.rebuilt.tsx
- packages/components/src/InputDate/InputDate.tsx
This fixes a few bugs where input fields show a focus ring (or in some cases their "invalid" border treatment) when they are disabled.
The Bugs:
https://github.com/user-attachments/assets/bea8dde1-9f22-4a70-86c6-887ac23425ea
https://github.com/user-attachments/assets/9ee2ec90-8300-4d73-bef1-a762b5c7b77a
The Fixes:
https://github.com/user-attachments/assets/a94cdebe-185c-435a-b122-d221a185ab4b
- Modify CSS to exclude focus ring on disabled fields 
- Modify CSS to exclude invalid border on disabled fields
To reproduce the bug, visit the current Atlantis site:
1. View the [Atlantis InputTime "invalid" story with disabled set to true](https://atlantis.getjobber.com/storybook/?path=/story/components-forms-and-inputs-inputtime-web--invalid&args=disabled:!true). 
2. Click on the field. 
3. …
> fix(components): stop showing focus ring on disabled and invalid components

- docs/components/Select/Web.stories.tsx
- packages/components/src/Select/Select.rebuilt.tsx
- packages/components/src/Select/Select.types.ts
We want to allow the error to be passed through to the `SelectRebuilt` component.
1. The error is now passed through to the SelectRebuilt component.
You should be able to add an 'error' prop to the `SelectRebuilt` component and see the error displayed
"Version comparison" story's Toggle Error verifies `error` prop is being passed through
Changes can be
---
> fix(components): Allowing error passthrough on <Select version={2} />

- packages/components/src/FormField/FormField.module.css
InputTime should not show interaction when disabled. 
This fixes a case where a blank disabled InputTime would show interaction when clicked on.
Bug:
https://github.com/user-attachments/assets/6b7e4168-002d-4547-9930-b867b398b23a
No regressions:
When the disabled field has a value, it should also continue to not show interaction when clicked on.
https://github.com/user-attachments/assets/f0309504-761b-4ba3-b0f2-a75d58dd48c8
Modifies the FormField CSS to include a few more cases of handling focus on InputTime.
- InputTime no longer responds to focus to animate minilabel when disabled.
1. Navigate to https://atlantis.getjobber.com/storybook/?path=/story/components-forms-and-inputs-inputtime-web--uncontrolled
2. Set a placeholder value on the field and set it to disabled.
3. Click within the …
> fix(components): stop minilabel from responding on empty disabled InputTime

- packages/components/src/FormField/FormField.module.css
- packages/components/src/FormField/FormField.module.css.d.ts
- packages/components/src/FormField/FormFieldAffix.tsx
[This bug](https://jobber.atlassian.net/browse/JOB-119173) was reported where the calendar from the date picker is overlapping with the save bar. 
Looking into it I can't determine the need for this z-index. I asked [here](https://getjobber.slack.com/archives/C03BKPST4KC/p1747244072043699) and Chris who was a reviewer on the original PR thinks it was to make sure that the icons are always above the input content (value/placeholder). I've done some testing though and it doesn't seem necessary for that. It's worth noting that only suffixes can have actions, so we only need to test this behaviour for suffixes and not prefixes.
The z-index for affix icons with actions has been removed.
To do some initial testing I added the following to one of the stories for form field:
```
suffix: {
icon: …
```
> fix(components): Remove z-index from affix icons with actions [JOB-119173 ]

- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/components/DataListHeader/DataListHeader.test.tsx
- packages/components/src/DataList/components/DataListHeader/DataListHeader.tsx
- packages/components/src/DataList/components/DataListHeader/DataListHeaderCheckbox.test.tsx
- packages/components/src/DataList/components/DataListHeader/DataListHeaderCheckbox.tsx
we had 2 somewhat related issues with DataList headers, both happening in the situation where your DataList has an `onSelect` and `selected` props implemented but NO `onSelectAll`
**the first issue**
because we aren't rendering the checkbox to select all, everything shifts to the left - causing misalignment in all your columns with the header. this is very hard, or awkward to solve at the consumer level because you don't have access to the checkbox. the best you can do is some not great workaround checking for `!item.id` in the `DataList.Layout` to give the header the exact amount of spacing as the Checkbox would occupy
**second issue**
on mobile/small screens, the headers would show up if you have a selection
this isn't desirable because the headers don't make any sense due to the …
> fix(components): DataList Header Fixes

- packages/components/src/FormatFile/FormatFile.module.css
- packages/components/src/FormatFile/FormatFile.module.css.d.ts
- packages/components/src/FormatFile/FormatFile.tsx
- packages/site/src/content/FormatFile/FormatFile.props.json
The delete button on a thumbnail in FormatFile is
- too big on the base size (covers way too much surface area) and arguably doesn't need to be as large as it is in the large size thumbnail either
- too close to the edge on the large size (focus state has a just-off overlap with the border)
- the radius of the button looks awkward against the corner of the thumbnail
- delete button was not visible on larger touch devices like an iPad
Base
Focus state does overlap but I think it's an acceptable trade-off for the reduction in image covered
Large
Touch emulator with a large viewport
Mouse with a small viewport
- Delete button is always `small`
- On base size thumbnail, custom styling is applied to reduce size further
- No changes to Expanded state
- Added a shadow to give button slightly …
> fix(components): Clean up size and placement of FormatFile delete button

- packages/components/src/InputTime/InputTime.rebuilt.tsx
- packages/components/src/InputTime/InputTime.tsx
clearable while-editing does not work in InputTime. This is caused by missing `wrapperRef` prop into `FormFieldWrapper`, which results in the focus event listeners not getting registered in `useFormFieldFocus`. clearable while-editing relies on the focus state to show/hide the clear icon button
- 
- Pass `wrapperRef` into `FormFieldWrapper` in `InputTime.rebuilt`
- 
- 
- InputTime v2 can now be cleared while-editing
- 
- In one of the existing stories, set `clearable="while-editing"`
- Confirm that clear icon button is visible while editing.
Changes can be
---
> fix(components): Fix InputTime v2 clearable while-editing 

- packages/components-native/src/Checkbox/Checkbox.style.ts
- packages/components-native/src/Checkbox/Checkbox.tsx
Assistive text on Checkbox does not match intended designs
**Actual**
**Design**
- Mobile checkbox now matches designs
**Short text**
**Wrapping text**
Can test locally, limited usage in the app
Changes can be
---
> fix(components-native): fix placement of assistive text on Checkbox [JOB-125934]

- packages/components/src/InputFile/FileTypes.ts
- packages/components/src/InputFile/InputFile.test.tsx
Looking to extend functionality for webp to be allowed in input file. Without this change the "images" input type doesn't include `webp` and providing a custom list of file types also doesn't support `webp`.
Added `webp` to the `FileType` enum
- 
- 
- 
- 
- 
Changes can be
---
> feat(components): Add webp to FileTypes enum (input file can accept webp in list of custom file types)

- packages/components-native/src/Select/Select.tsx
When no label is provided to Select, there's still an element rendered that occupies space
- wrapped the Text for the label in a conditional so it only show up when present
- Select now looks nicer when you don't pass it a label
Because of web differences, you have to test this one in the app (job forms or requests have examples of this use case)
Changes can be
---
> fix(components-native): Do not render Select's label element when no label is provided [JOB-125934]

- packages/components/src/Combobox/Combobox.test.tsx
- packages/components/src/Combobox/Combobox.types.ts
- packages/components/src/Combobox/components/ComboboxContent/ComboboxContent.tsx
- packages/components/src/Combobox/index.ts
- packages/site/src/content/Combobox/Combobox.props.json
We deliberately chose to create a new ComboboxSelection type in this [PR](https://github.com/GetJobber/atlantis/pull/2615#discussion_r2205377698) in order to better reflect the combobox options being passed back to the consumers via callbacks (only `id` and `label` of ComboboxOption). However, digging deeper I found these callbacks (onSelect) to be passed through layers of hooks and internal components. Going through each usage and changing the type quickly becomes messy, although all CI jobs are passing. We will have to come back and tackle a full cleanup in a separate ticket. This PR will undo the addition of ComboboxSelection type and also only return `id` and `label` in each option of `onSelectAll`
- 
- Undo the addition of ComboboxSelection and revert `onSelect` and `onSelectAll` …
> fix(components): Undo ComboboxSelection type for callback props

- packages/components/src/Autocomplete/Autocomplete.module.css
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/Autocomplete/Autocomplete.types.ts
- packages/components/src/Autocomplete/Menu/DefaultMenu.tsx
- packages/components/src/Autocomplete/Menu/Menu.tsx
- packages/components/src/Autocomplete/Menu/MenuWrapper.tsx
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/components/src/Autocomplete/constants.ts
- packages/components/src/Autocomplete/useRepositionMenu.ts
React-popper is deprecated, and we've chosen FloatingUI as its successor.
new `size` behavior both prevents the Autocomplete menu from being inaccessible and also avoids "pushing" the limits of its container (the document body) beyond, resulting in a broken layout. instead it will shrink to the available size, and allow scrolling.
Replaced the Popper code responsible for positioning the Autocomplete's dropdown menu with FloatingUI.
Replaced the `react-dom` `createPortal` with `FloatingPortal` which handles a bunch of stuff for us and solves the same problem that `createPortal` does
https://floating-ui.com/docs/floatingportal#floatingportal
Removed the workaround with Modal because I believe the FloatingPortal solves the problem.
- 
- 
- 
- 
This change should be completely imperceptible. …
> feat(components): Replace Popper with FloatingUI in Autocomplete

- packages/components/src/Chip/components/ChipSuffix/Chip.Suffix.tsx
There was icon allowed list check in `Chip.Suffix` that only allowed some action-type icons to be used. This limited consumer flexibility in choosing the icon that fits their workflow the best. We also did not have any indication of why an icon would not render, nor documentation on the allowed list. A consumer had to debug into Atlantis code to find out and submit [contribution PR](https://github.com/GetJobber/atlantis/pull/2618) to get the edit icon added .
With this change, we want to provide consumers more flexibility in picking their icon, so they don't have to depend on us releasing a new code change every time a new icon needs to be used. 
- 
- `Chip.Suffix` now allows any icon to be used.
- 
- 
- 
- 
- Confirm any icon that was not on the allowed list can render in Chip.Suffix …
> feat(components): Remove Chip.Suffix icon allowed list check

- docs/components/Banner/Banner.stories.mdx
The component design guidance varies in structure wildly from component to component. Based on feedback gathered by designers, there is not enough clarity around the usage of components. These changes are being made to bulk out the guidance and provide practical examples of what to do and what not to do on a component by component basis.
No guidance removed, in some cases altered to make overall guidance clearer. Several additions including:
Added content guidance, applied a template for future component design guidance. Added dos and don'ts to bring more in line with designer feedback. Added content examples. Made improvements to the summary, made improvements to guidance around banner variants to avoid confusion around which banner style to use in certain situations.
---
[In Atlantis we …
> docs(components): Update Banner.stories.mdx to improve design guidance

- packages/components/src/Tooltip/Tooltip.test.tsx
- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/useTooltipPositioning.ts
Popper is deprecated. replaced by FloatingUI.
shift middleware allows it to sort of follow you along as you scroll for example
this will be impossible to do with the hover trigger but focusing can happen. also added the shiftLimiter to prevent it from showing up off screen.
- replaced usePopper with useFloating
- renamed anything referencing popper
- swapped the ReactDOM portal for FloatingPortal
- 
- 
- 
- 
**shift + limitshift** 
since tooltips respond to focus, focus the activator element then scroll. the tooltip should shift along with the movement, and the arrow should move along with you BUT hit the edge at such a point that doesn't look bad with the rounded border radius.
furthermore the shift should not apply to things fully off screen. so if you have a tooltip on something, focus …
> feat(components): Use FloatingUI for Tooltip

- docs/components/Heading/Web.stories.tsx
- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
- packages/site/src/content/Heading/Heading.props.json
- Introduced numberOfLines prop to Heading component to control text truncation.
- Updated Heading stories to demonstrate single and multi-line truncation.
- Added test case for rendering Heading with numberOfLines prop
As discussed [here](https://github.com/GetJobber/jobber-frontend/pull/4169#discussion_r2257751592), Tanner was looking for a way to truncate text within our `Heading` component. This PR exposes the `numberOfLines` prop on `Typography` to the `Heading` component to allow for this truncation 
`numberOfLines` prop for Heading
You can take a look at the new story I added
Changes can be
--- …
> feat(components): Add numberOfLines prop to Heading [132044]

- packages/site/src/content/DataTable/DataTableNotes.mdx
Used `getStorybookUrl` in a `<a>` but it formats the `mdx` file with extra space and therefore, also created space in the Implement tab. This PR goes back to Markdown linking format.
Clicking the link opens a new window to the correct spot and formatting isn't borked!
Changes can be
---
> docs: Revert Link formatting in DataTableNotes

- packages/components/src/Flex/Flex.module.css
- packages/components/src/Flex/Flex.module.css.d.ts
- packages/components/src/Flex/Flex.types.ts
- packages/site/src/content/Flex/Flex.props.json
Adds all of our spacing sizes as gap options for `Flex` in response to a request for `largest` to be made an option. If it is a spacing that we document and make available for gaps on other layout components I can't think of any reason why it shouldn't be available for Flex. 
Take a look in Storybook. I slotted the new gaps in, in order of their sizes but they don't display in Storybook in exactly that order. This doesn't seem to be anything new because some were out of order before but if anyone knows how to change this I am happy to fix it.
Changes can be
---
> feat(components): Add additional gap spacings to Flex [JOB-133026]

- docs/hooks/useStepper.stories.mdx
- packages/site/src/hooksList.ts
- packages/site/src/maps/hooksContent.tsx
Add `useStepper` to new docs site
- `useStepper` docs are in new docs site
Make sure `useStepper` page is viewable via sidenav, main hooks page and via search modal
Changes can be
---
> docs: Add useStepper to Docs Site

- docs/components/Popover/Popover.stories.mdx
- package-lock.json
- packages/components/__mocks__/@popperjs/core.js
- packages/components/package.json
- packages/components/rollup.config.mjs
getting rid of the dependency of popper
This PR is a revert of the revert that was done due to an issue in migrating to floating-ui for Chips. Now that Chips with floating-ui with the proper z-index fix has been merged, we can go ahead and remove popper from the dependency list.
- 
fixed a typo that said "popper" that was showing up in my search results
- 
removed the packages from our direct dependencies
though the package will continue to be included  due to `react-datepicker` still using `@popperjs/core` and `react-popper`
that's also the only remaining real reference to `popper` is react datepicker props, css rules and tests. can't get rid of these until we upgrade, and presumably they've gotten off popper too.
removed a mock for popper in tests
removed the rollupconfig entry for …
> chore(components): Remove Popper Library

- docs/components/Datepicker/Datepicker.stories.mdx
- docs/components/InputDate/InputDate.stories.mdx
URL to DatePicker docs is broken, generates 404
- casing of Datepicker -> DatePicker in link, no longer 404s
Run InputDate docs locally / CF
---
> fix(docx): fix typo on DatePicker url in InputDate docs

- docs/components/Autocomplete/WebV2.stories.tsx
- packages/components/src/Autocomplete/Autocomplete.rebuilt.test.tsx
- packages/components/src/Autocomplete/Autocomplete.types.ts
- packages/components/src/Autocomplete/index.tsx
- packages/components/src/Autocomplete/utils/menuModel.ts
- packages/site/generateDocs.mjs
- packages/site/src/componentList.ts
- packages/site/src/content/AutocompleteV2/AutocompleteV2.props.json
- packages/site/src/content/AutocompleteV2/AutocompleteV2.stories.mdx
- packages/site/src/content/AutocompleteV2/AutocompleteV2Notes.mdx
- packages/site/src/content/AutocompleteV2/index.tsx
- packages/site/src/content/index.ts
- packages/site/src/preview/useAtlantisPreviewSkeleton.tsx
Autocomplete v2 has quite a few notable differences from v1 and how to build with it. we should have this documented, with examples
added a separate docs site entry for v2 including all tab content
added some better webstory examples showing how to build various combinations
- 
- 
- 
while building an example I found a bug with empty section logic. fixed it and added a test. happy to move this to its own PR if we'd prefer since it's not related to the docs at all, I just happened to come across it.
- 
Changes can be
---
> docs(components): Add AutocompleteV2 Docs

- .storybook/assets/css/preview.css
- docs/components/Modal/Web.stories.tsx
- packages/components/src/Modal/Modal.rebuilt.module.css
- packages/components/src/Modal/Modal.rebuilt.test.tsx
- packages/components/src/Modal/Modal.rebuilt.tsx
- packages/components/src/Modal/useModal.ts
the catalyst for this was the fact that when dismissing nested modals, we were seeing an outline around the modal.
this is intentional, for accessibility purposes. however what is not intentional is that the focus was persisting after the element had visually been removed, resulting in an odd outline shape of where the modal used to be
the reason for this gets pretty complicated, but essentially we are half using floating to manage focus and half doing it ourselves, and we have a layout that floating really doesn't expect.
https://www.codeguage.com/blog/focus-vs-focus-visible-vs-focus-within
- 
**useClick**
this is used to open/close the floating element when the reference is clicked
https://floating-ui.com/docs/useClick
however our reference is a button or some other interactive element. …
> fix(components): Reorganize Composed Modal to Solve Focus Management

- packages/components/src/Heading/Heading.test.tsx
- packages/components/src/Heading/Heading.tsx
- packages/site/src/content/Heading/Heading.props.json
- packages/site/src/content/Heading/HeadingNotes.mdx
Surface `id` prop from `Typography` to `Heading`
- optional `id` prop to `Heading`
- simple test for new `id` prop
- go to `Heading` story
- in `docs/components/Heading/Web.stories.tsx` put an `id` in one of the Headings in the story
- verify it shows up in the dom
Changes can be
---
> feat(components): Surface id prop to Heading

- packages/components/src/InputFile/InputFile.test.tsx
- packages/components/src/InputFile/InputFile.tsx
- packages/site/src/content/InputFile/InputFile.props.json
This PR adds a `name` prop to the `InputFile` component that allows setting the name attribute on the underlying HTML input element. 
- Added optional name?: string prop to InputFileProps interface
- Updated InputFile component to accept and apply the name prop to the input element
- Added test coverage to verify the name attribute is properly set
- Updated component documentation with prop description
Usage:
```
<InputFile 
name="file-upload" 
getUploadParams={fetchUploadParams} 
/>
```
- go to any `InputFile` storybook example
- enter a `name` via Controls and inspect the `InputFile` to see the `name` on the `input` element
Changes can be
--- …
> feat(components): Add name to InputFile
